# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "alsa-utils"
PE = "0"
PV = "1.2.13"
PR = "1.el10"
PACKAGES = "alsa-ucm-utils alsa-utils alsa-topology-utils alsa-utils-alsabat"
PROVIDES = "rpm/alsa-ucm-utils rpm/alsa-utils rpm/alsa-topology-utils rpm/alsa-utils-alsabat"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/alsa-utils-1.2.13-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7bf5e2bfcb84a9eb5c60077a641db20be46bd275038c507b7fa96cdefb9160ba"

URI_alsa-ucm-utils = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/alsa-ucm-utils-1.2.13-1.el10.x86_64_v2.rpm;name=alsa-ucm-utils;unpack=0"
SRC_URI += "${URI_alsa-ucm-utils}"
SRC_URI[alsa-ucm-utils.sha256sum] = "6d9ef83ccc73db76ef0c4e9596d5b04f95de19b99280331c0d42a77bbdef16be"
RDEPENDS:alsa-ucm-utils = " \
 glibc \
 alsa-lib \
"

URI_alsa-utils = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/alsa-utils-1.2.13-1.el10.x86_64_v2.rpm;name=alsa-utils;unpack=0"
SRC_URI += "${URI_alsa-utils}"
SRC_URI[alsa-utils.sha256sum] = "756c7054a7d5d91487e98149de82ee946b47dc40e612ace76f3ae7a9320f4562"
RDEPENDS:alsa-utils = " \
 alsa-lib \
 systemd \
 libsamplerate \
 alsa-ucm \
 bash \
 ncurses-libs \
 glibc \
"

URI_alsa-topology-utils = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/alsa-topology-utils-1.2.13-1.el10.x86_64_v2.rpm;name=alsa-topology-utils;unpack=0"
SRC_URI += "${URI_alsa-topology-utils}"
SRC_URI[alsa-topology-utils.sha256sum] = "9b962411467e95da00b2f86856aaf6e083664dac9f7083c22f116fab8cd71515"
RDEPENDS:alsa-topology-utils = " \
 glibc \
 alsa-lib \
 alsa-topology \
"

URI_alsa-utils-alsabat = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/alsa-utils-alsabat-1.2.13-1.el10.x86_64_v2.rpm;name=alsa-utils-alsabat;unpack=0"
SRC_URI += "${URI_alsa-utils-alsabat}"
SRC_URI[alsa-utils-alsabat.sha256sum] = "2945524a455200d275d063c9b0567a3e62829a48f8e742faa5f28cd186a187ec"
RDEPENDS:alsa-utils-alsabat = " \
 fftw-libs-single \
 alsa-lib \
 libgcc \
 bash \
 glibc \
"
