# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ant"
PE = "0"
PV = "1.10.15"
PR = "1.el10"
PACKAGES = "ant ant-antlr ant-apache-bcel ant-apache-bsf ant-apache-oro ant-apache-regexp ant-apache-resolver ant-apache-xalan2 ant-commons-logging ant-commons-net ant-jakartamail ant-jdepend ant-jmf ant-jsch ant-junit ant-junit5 ant-lib ant-swing ant-testutil ant-unbound ant-xz ant-imageio ant-javadoc ant-manual ant-openjdk21"
PROVIDES = "rpm/ant rpm/ant-antlr rpm/ant-apache-bcel rpm/ant-apache-bsf rpm/ant-apache-oro rpm/ant-apache-regexp rpm/ant-apache-resolver rpm/ant-apache-xalan2 rpm/ant-commons-logging rpm/ant-commons-net rpm/ant-jakartamail rpm/ant-jdepend rpm/ant-jmf rpm/ant-jsch rpm/ant-junit rpm/ant-junit5 rpm/ant-lib rpm/ant-swing rpm/ant-testutil rpm/ant-unbound rpm/ant-xz rpm/ant-imageio rpm/ant-javadoc rpm/ant-manual rpm/ant-openjdk21"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/ant-1.10.15-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a2237c77279aead8b0af6e84357463668013aab248489bc0f5fdcd72e5ee9ff2"

URI_ant = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-1.10.15-1.el10.noarch.rpm;name=ant;unpack=0"
SRC_URI += "${URI_ant}"
SRC_URI[ant.sha256sum] = "6ed82f177576605468ab0bb7cb2d6dcd8db41fc93a272b448169f781b91bfa6d"
RDEPENDS:ant = " \
 ant-lib \
 ant-unbound \
"

URI_ant-antlr = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-antlr-1.10.15-1.el10.noarch.rpm;name=ant-antlr;unpack=0"
SRC_URI += "${URI_ant-antlr}"
SRC_URI[ant-antlr.sha256sum] = "de1d9c2dbcc8228ba7cce95d337366ac79de90f8e9f981a0a8a88565e1b42c92"
RDEPENDS:ant-antlr = " \
 ant-lib \
 ant \
 javapackages-filesystem \
 antlr-tool \
"

URI_ant-apache-bcel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-apache-bcel-1.10.15-1.el10.noarch.rpm;name=ant-apache-bcel;unpack=0"
SRC_URI += "${URI_ant-apache-bcel}"
SRC_URI[ant-apache-bcel.sha256sum] = "7064408add04128a7a45ac48f41e89ee93a6be13ba47472875c0e7aa6d2ffa8c"
RDEPENDS:ant-apache-bcel = " \
 bcel \
 ant \
 javapackages-filesystem \
 ant-lib \
"

URI_ant-apache-bsf = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-apache-bsf-1.10.15-1.el10.noarch.rpm;name=ant-apache-bsf;unpack=0"
SRC_URI += "${URI_ant-apache-bsf}"
SRC_URI[ant-apache-bsf.sha256sum] = "6e516e6b90274ebb0c6dcaf7707912b5780a38d63e009a9f7581368a4f97a450"
RDEPENDS:ant-apache-bsf = " \
 ant-lib \
 ant \
 javapackages-filesystem \
 bsf \
"

URI_ant-apache-oro = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-apache-oro-1.10.15-1.el10.noarch.rpm;name=ant-apache-oro;unpack=0"
SRC_URI += "${URI_ant-apache-oro}"
SRC_URI[ant-apache-oro.sha256sum] = "bc8d48099e5ef6082ac128f23ba32a8c29d3d01b3df8451246938ccf7c497ca7"
RDEPENDS:ant-apache-oro = " \
 ant-lib \
 ant \
 javapackages-filesystem \
 jakarta-oro \
"

URI_ant-apache-regexp = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-apache-regexp-1.10.15-1.el10.noarch.rpm;name=ant-apache-regexp;unpack=0"
SRC_URI += "${URI_ant-apache-regexp}"
SRC_URI[ant-apache-regexp.sha256sum] = "eddbea9cc3921781487d01b5e5d2f457348665ab7bd0dae5b83beeb7eb1e271b"
RDEPENDS:ant-apache-regexp = " \
 ant-lib \
 ant \
 regexp \
 javapackages-filesystem \
"

URI_ant-apache-resolver = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-apache-resolver-1.10.15-1.el10.noarch.rpm;name=ant-apache-resolver;unpack=0"
SRC_URI += "${URI_ant-apache-resolver}"
SRC_URI[ant-apache-resolver.sha256sum] = "6100aa69c470912557cda99d04b31e3b9a32084910d303534919daf0c148345b"
RDEPENDS:ant-apache-resolver = " \
 ant \
 xml-commons-resolver \
 javapackages-filesystem \
 ant-lib \
"

URI_ant-apache-xalan2 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-apache-xalan2-1.10.15-1.el10.noarch.rpm;name=ant-apache-xalan2;unpack=0"
SRC_URI += "${URI_ant-apache-xalan2}"
SRC_URI[ant-apache-xalan2.sha256sum] = "7d77a937f1de8ff13b3e07c58d597ca9a73d7de00a59a96260d4624769706d6b"
RDEPENDS:ant-apache-xalan2 = " \
 ant-lib \
 ant \
 javapackages-filesystem \
 xalan-j2 \
"

URI_ant-commons-logging = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-commons-logging-1.10.15-1.el10.noarch.rpm;name=ant-commons-logging;unpack=0"
SRC_URI += "${URI_ant-commons-logging}"
SRC_URI[ant-commons-logging.sha256sum] = "6a1915d0524e42f7f6284d77fb69a99d10fd245ab9d2060fa3e06e545393c55e"
RDEPENDS:ant-commons-logging = " \
 ant-lib \
 ant \
 javapackages-filesystem \
"

URI_ant-commons-net = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-commons-net-1.10.15-1.el10.noarch.rpm;name=ant-commons-net;unpack=0"
SRC_URI += "${URI_ant-commons-net}"
SRC_URI[ant-commons-net.sha256sum] = "e9a2466f9f292342c04c0f4e4df2e27c8a51f094185dc93072cdf2d956d1ec78"
RDEPENDS:ant-commons-net = " \
 ant-lib \
 ant \
 javapackages-filesystem \
 apache-commons-net \
"

URI_ant-jakartamail = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-jakartamail-1.10.15-1.el10.noarch.rpm;name=ant-jakartamail;unpack=0"
SRC_URI += "${URI_ant-jakartamail}"
SRC_URI[ant-jakartamail.sha256sum] = "aeb7952467ec601b56459046b67e5ad8f3f220bccdeb9628286d125ebc804ba1"
RDEPENDS:ant-jakartamail = " \
 ant-lib \
 ant \
 jakarta-mail \
 javapackages-filesystem \
"

URI_ant-jdepend = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-jdepend-1.10.15-1.el10.noarch.rpm;name=ant-jdepend;unpack=0"
SRC_URI += "${URI_ant-jdepend}"
SRC_URI[ant-jdepend.sha256sum] = "b11fd7fdb1af1a3e3f09f9b07412bfae89b29fc18effd72c8e94ebf258f6cfbe"
RDEPENDS:ant-jdepend = " \
 jdepend \
 ant \
 javapackages-filesystem \
 ant-lib \
"

URI_ant-jmf = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-jmf-1.10.15-1.el10.noarch.rpm;name=ant-jmf;unpack=0"
SRC_URI += "${URI_ant-jmf}"
SRC_URI[ant-jmf.sha256sum] = "a3359195c9edf7639e1abce9df2cef1cc45301a3307400186290f3a0487c7b24"
RDEPENDS:ant-jmf = " \
 ant-lib \
 ant \
 javapackages-filesystem \
"

URI_ant-jsch = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-jsch-1.10.15-1.el10.noarch.rpm;name=ant-jsch;unpack=0"
SRC_URI += "${URI_ant-jsch}"
SRC_URI[ant-jsch.sha256sum] = "d6407c7ca2000292c27eac7f12c2681b8b822616d3e2669ad093ab69bd0dcc32"
RDEPENDS:ant-jsch = " \
 ant-lib \
 ant \
 javapackages-filesystem \
 jsch \
"

URI_ant-junit = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-junit-1.10.15-1.el10.noarch.rpm;name=ant-junit;unpack=0"
SRC_URI += "${URI_ant-junit}"
SRC_URI[ant-junit.sha256sum] = "c33b571af5834a05f6faa05d22f3ac68319a1107ff9bced7142902356547573a"
RDEPENDS:ant-junit = " \
 ant-lib \
 ant \
 junit \
 javapackages-filesystem \
"

URI_ant-junit5 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-junit5-1.10.15-1.el10.noarch.rpm;name=ant-junit5;unpack=0"
SRC_URI += "${URI_ant-junit5}"
SRC_URI[ant-junit5.sha256sum] = "b0f013a56757d73e7e2af05f24c3f76db3b5d2cde499bb15a586b351109e25b9"
RDEPENDS:ant-junit5 = " \
 junit5 \
 ant \
 javapackages-filesystem \
 ant-lib \
"

URI_ant-lib = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-lib-1.10.15-1.el10.noarch.rpm;name=ant-lib;unpack=0"
SRC_URI += "${URI_ant-lib}"
SRC_URI[ant-lib.sha256sum] = "109b3aaaf7bf0dd198e7476f1ea9b13d0b1d82e029b03029eaf0b37a17e3714a"
RDEPENDS:ant-lib = " \
 javapackages-filesystem \
"

URI_ant-swing = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-swing-1.10.15-1.el10.noarch.rpm;name=ant-swing;unpack=0"
SRC_URI += "${URI_ant-swing}"
SRC_URI[ant-swing.sha256sum] = "d3fa20198bba13c68807dc487a89e5fcfbe222996730efed076abb3c3c42bf15"
RDEPENDS:ant-swing = " \
 ant-lib \
 ant \
 javapackages-filesystem \
"

URI_ant-testutil = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-testutil-1.10.15-1.el10.noarch.rpm;name=ant-testutil;unpack=0"
SRC_URI += "${URI_ant-testutil}"
SRC_URI[ant-testutil.sha256sum] = "ad15ff6bb4e9bc83b82d41f862c2785c30061ba9cba3f24a55f0221e310a9b9b"
RDEPENDS:ant-testutil = " \
 ant-lib \
 ant \
 junit \
 javapackages-filesystem \
"

URI_ant-unbound = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-unbound-1.10.15-1.el10.noarch.rpm;name=ant-unbound;unpack=0"
SRC_URI += "${URI_ant-unbound}"
SRC_URI[ant-unbound.sha256sum] = "b0432d7c68e4d65606a5bb4377a31889d748051f9560e369aae1240971ccf9a9"
RDEPENDS:ant-unbound = " \
 ant \
 javapackages-tools \
"

URI_ant-xz = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ant-xz-1.10.15-1.el10.noarch.rpm;name=ant-xz;unpack=0"
SRC_URI += "${URI_ant-xz}"
SRC_URI[ant-xz.sha256sum] = "5bc5258bc4f5ac4debed6abc063728a8c3f1a42e51fa74227cb3ff3cb3e09b09"
RDEPENDS:ant-xz = " \
 ant \
 xz-java \
 javapackages-filesystem \
 ant-lib \
"

URI_ant-imageio = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ant-imageio-1.10.15-1.el10.noarch.rpm;name=ant-imageio;unpack=0"
SRC_URI += "${URI_ant-imageio}"
SRC_URI[ant-imageio.sha256sum] = "4e5f71f8c879a2e3824f5b0f6bf261e7fb95579946597cbd33b416713dfcc1e3"
RDEPENDS:ant-imageio = " \
 ant-lib \
 ant \
 javapackages-filesystem \
"

URI_ant-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ant-javadoc-1.10.15-1.el10.noarch.rpm;name=ant-javadoc;unpack=0"
SRC_URI += "${URI_ant-javadoc}"
SRC_URI[ant-javadoc.sha256sum] = "e4f0ea43448ab4e496d0f038b61ec55cfff8aba52d587b72fd118a749f19e23a"
RDEPENDS:ant-javadoc = " \
 javapackages-filesystem \
"

URI_ant-manual = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ant-manual-1.10.15-1.el10.noarch.rpm;name=ant-manual;unpack=0"
SRC_URI += "${URI_ant-manual}"
SRC_URI[ant-manual.sha256sum] = "51d4bfa98f52726d315ecc57d9aaca528af207f4d949f775510da1e7e238cddc"
RDEPENDS:ant-manual = ""

URI_ant-openjdk21 = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ant-openjdk21-1.10.15-1.el10.noarch.rpm;name=ant-openjdk21;unpack=0"
SRC_URI += "${URI_ant-openjdk21}"
SRC_URI[ant-openjdk21.sha256sum] = "00551f332862d854c7773f56cda47ec453d8fa615ae4ecd71ce9895533caa750"
RDEPENDS:ant-openjdk21 = " \
 ant \
 java-21-openjdk-headless \
 javapackages-tools \
"
