# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "aopalliance"
PE = "0"
PV = "1.0"
PR = "40.el10"
PACKAGES = "aopalliance aopalliance-javadoc"
PROVIDES = "rpm/aopalliance rpm/aopalliance-javadoc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/aopalliance-1.0-40.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "59c46fb61df547c817ddac7b9d3c7f440e284ce760819216be3ccc94cfb7ce22"

URI_aopalliance = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/aopalliance-1.0-40.el10.noarch.rpm;name=aopalliance;unpack=0"
SRC_URI += "${URI_aopalliance}"
SRC_URI[aopalliance.sha256sum] = "177bc31121b9d2f5398b6d38603b5d3862bcc59cb3ae472766e673cc3e8413d7"
RDEPENDS:aopalliance = " \
 javapackages-filesystem \
"

URI_aopalliance-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/aopalliance-javadoc-1.0-40.el10.noarch.rpm;name=aopalliance-javadoc;unpack=0"
SRC_URI += "${URI_aopalliance-javadoc}"
SRC_URI[aopalliance-javadoc.sha256sum] = "43ae39091df5a20f784c402f719d13c6818ca7770a47addd2bd5671740b7c219"
RDEPENDS:aopalliance-javadoc = " \
 javapackages-filesystem \
"
