# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "apache-commons-compress"
PE = "0"
PV = "1.27.1"
PR = "1.el10"
PACKAGES = "apache-commons-compress apache-commons-compress-javadoc"
PROVIDES = "rpm/apache-commons-compress rpm/apache-commons-compress-javadoc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/apache-commons-compress-1.27.1-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5d84add1f99633598d83ae7942b2b00679df7efd69f8fa7574403c8aa71fc334"

URI_apache-commons-compress = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/apache-commons-compress-1.27.1-1.el10.noarch.rpm;name=apache-commons-compress;unpack=0"
SRC_URI += "${URI_apache-commons-compress}"
SRC_URI[apache-commons-compress.sha256sum] = "f579d5db87d7ae548b1ee77701f0ff38b17a5bf062543ed9b5e0abf8f4d8e5fb"
RDEPENDS:apache-commons-compress = " \
 apache-commons-codec \
 apache-commons-io \
 javapackages-filesystem \
 apache-commons-lang3 \
"

URI_apache-commons-compress-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/apache-commons-compress-javadoc-1.27.1-1.el10.noarch.rpm;name=apache-commons-compress-javadoc;unpack=0"
SRC_URI += "${URI_apache-commons-compress-javadoc}"
SRC_URI[apache-commons-compress-javadoc.sha256sum] = "bdabe3405810eb9eecae31d2ed2dafb6324bec8b12c5f238a6b0c62fe9c34d8d"
RDEPENDS:apache-commons-compress-javadoc = " \
 javapackages-filesystem \
"
