# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "apache-resource-bundles"
PE = "1"
PV = "1.5"
PR = "8.el10"
PACKAGES = "apache-resource-bundles"
PROVIDES = "rpm/apache-resource-bundles"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/apache-resource-bundles-1.5-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "3044486921e6282ebeb20ee68652cdebcf8eab68ceb878c7f162415f5aeab1c6"

URI_apache-resource-bundles = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/apache-resource-bundles-1.5-8.el10.noarch.rpm;name=apache-resource-bundles;unpack=0"
SRC_URI += "${URI_apache-resource-bundles}"
SRC_URI[apache-resource-bundles.sha256sum] = "0d62245c9cfd85f80aeb4d53ab7f27756d5756fbb85fe2b8bd250584aa7fb7a1"
RDEPENDS:apache-resource-bundles = " \
 javapackages-filesystem \
"
