# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "assertj-core"
PE = "0"
PV = "3.24.2"
PR = "9.el10"
PACKAGES = "assertj-core assertj-core-javadoc"
PROVIDES = "rpm/assertj-core rpm/assertj-core-javadoc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/assertj-core-3.24.2-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "33a8f5b93117ab5e0510ebfa556cc9147fd429984e774fae7ea8f1d7e3284688"

URI_assertj-core = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/assertj-core-3.24.2-9.el10.noarch.rpm;name=assertj-core;unpack=0"
SRC_URI += "${URI_assertj-core}"
SRC_URI[assertj-core.sha256sum] = "8d0114190600606d543033e371abb15e4214be8d54af855cc2bf2752cc5cd068"
RDEPENDS:assertj-core = " \
 javapackages-filesystem \
 byte-buddy \
"

URI_assertj-core-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/assertj-core-javadoc-3.24.2-9.el10.noarch.rpm;name=assertj-core-javadoc;unpack=0"
SRC_URI += "${URI_assertj-core-javadoc}"
SRC_URI[assertj-core-javadoc.sha256sum] = "430cccadcf5535dde21e705726adc51c2f9038c201a007bfef8dbcb1b94bf73d"
RDEPENDS:assertj-core-javadoc = " \
 javapackages-filesystem \
"
