# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "autoconf"
PE = "0"
PV = "2.71"
PR = "12.el10"
PACKAGES = "autoconf"
PROVIDES = "rpm/autoconf"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/autoconf-2.71-12.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c1729f4f5912142f135df82e9429613886e316656498d852a633e15f2558e1dc"

URI_autoconf = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/autoconf-2.71-12.el10.noarch.rpm;name=autoconf;unpack=0"
SRC_URI += "${URI_autoconf}"
SRC_URI[autoconf.sha256sum] = "e5c2aaa1797d84dbddbe548d1371722ec6b0071e9bff9900774c5179841f3879"
RDEPENDS:autoconf = " \
 perl-File-stat \
 perl-libs \
 perl-Getopt-Long \
 m4 \
 emacs-filesystem \
 perl-Carp \
 perl-IO \
 perl-Class-Struct \
 perl-Text-ParseWords \
 perl-Data-Dumper \
 bash \
 perl-Errno \
 perl-Exporter \
 perl-constant \
 perl-POSIX \
 perl-File-Basename \
 perl-File-Compare \
 perl-File-Copy \
 perl-PathTools \
 perl-File-Find \
 perl-interpreter \
 perl-File-Temp \
"
