# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "autoconf-archive"
PE = "0"
PV = "2023.02.20"
PR = "8.el10"
PACKAGES = "autoconf-archive"
PROVIDES = "rpm/autoconf-archive"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/autoconf-archive-2023.02.20-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d63c19b45670b3f20c0607311841e1d9918380b002b0c7b05d1b5363cab4f051"

URI_autoconf-archive = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/autoconf-archive-2023.02.20-8.el10.noarch.rpm;name=autoconf-archive;unpack=0"
SRC_URI += "${URI_autoconf-archive}"
SRC_URI[autoconf-archive.sha256sum] = "1ba12d0315140800c0b07b419f3322dbeb78313faf6875a4957bede453e423b4"
RDEPENDS:autoconf-archive = " \
 autoconf \
"
