# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "babel"
PE = "0"
PV = "2.13.1"
PR = "5.el10"
PACKAGES = "babel babel-doc python3-babel"
PROVIDES = "rpm/babel rpm/babel-doc rpm/python3-babel"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/babel-2.13.1-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "40c4619ff9fc270dd64230a4ed9dd06ed90ced4580c3f95104f8a3cde54d5896"

URI_babel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/babel-2.13.1-5.el10.noarch.rpm;name=babel;unpack=0"
SRC_URI += "${URI_babel}"
SRC_URI[babel.sha256sum] = "7f2d19d6202c13bfbe71fa9dd37a4319ae0bf7d1ac6b4d719d2a778de490ee2d"
RDEPENDS:babel = " \
 python3 \
 python3-babel \
"

URI_babel-doc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/babel-doc-2.13.1-5.el10.noarch.rpm;name=babel-doc;unpack=0"
SRC_URI += "${URI_babel-doc}"
SRC_URI[babel-doc.sha256sum] = "8fb0792fc907b1e163973ec5701d28fa1f860525aede70bf126c73d9f8251159"
RDEPENDS:babel-doc = ""

URI_python3-babel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/python3-babel-2.13.1-5.el10.noarch.rpm;name=python3-babel;unpack=0"
SRC_URI += "${URI_python3-babel}"
SRC_URI[python3-babel.sha256sum] = "29a00f11f4860646d98d838e0740902d8e9a81a7eb25c729f3cc7f0bf39e2077"
RDEPENDS:python3-babel = " \
 python3-setuptools \
 python3 \
"
