# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "biosdevname"
PE = "0"
PV = "0.7.3"
PR = "19.el10"
PACKAGES = "biosdevname"
PROVIDES = "rpm/biosdevname"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/biosdevname-0.7.3-19.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "8f8aa99149f5a61681102b3ed886b92fde150f83bb65dc078bddb678331fd73d"

URI_biosdevname = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/biosdevname-0.7.3-19.el10.x86_64_v2.rpm;name=biosdevname;unpack=0"
SRC_URI += "${URI_biosdevname}"
SRC_URI[biosdevname.sha256sum] = "4d2bbeae673546076b2d40a290b9a54b609bed91e6db2f096cff55ae7dd05740"
RDEPENDS:biosdevname = " \
 glibc \
 pciutils-libs \
"
