# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "bison"
PE = "0"
PV = "3.8.2"
PR = "9.el10"
PACKAGES = "bison bison-runtime bison-devel"
PROVIDES = "rpm/bison rpm/bison-runtime rpm/bison-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/bison-3.8.2-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c1dfd02ae10f43f94d3f68a450d24029ca61224a6dbb8dea76dbfd723c5ff052"

URI_bison = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/bison-3.8.2-9.el10.x86_64_v2.rpm;name=bison;unpack=0"
SRC_URI += "${URI_bison}"
SRC_URI[bison.sha256sum] = "1d610a685d92b791824c6c2432920ae65f100ea8b558467c3b2323bcf95cfec5"
RDEPENDS:bison = " \
 glibc \
 m4 \
"

URI_bison-runtime = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/bison-runtime-3.8.2-9.el10.x86_64_v2.rpm;name=bison-runtime;unpack=0"
SRC_URI += "${URI_bison-runtime}"
SRC_URI[bison-runtime.sha256sum] = "53d97d9ed3179fb9d3ca89812651b6548e09d78bd4551bc9139600d7f2b17b12"
RDEPENDS:bison-runtime = ""

URI_bison-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/bison-devel-3.8.2-9.el10.x86_64_v2.rpm;name=bison-devel;unpack=0"
SRC_URI += "${URI_bison-devel}"
SRC_URI[bison-devel.sha256sum] = "2c96db11e49b29ab0dd3e2d7ff1aea55aea6528c254dd5b278826b3d50115a4d"
RDEPENDS:bison-devel = ""
