# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "bpftool"
PE = "0"
PV = "7.5.0"
PR = "800.el10"
PACKAGES = "bpftool"
PROVIDES = "rpm/bpftool"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/bpftool-7.5.0-800.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "fd6cd239240b3eb6e4a9d26c1073277ab09bdfef284603a0f90ece046356ae13"

URI_bpftool = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/bpftool-7.5.0-800.el10.x86_64_v2.rpm;name=bpftool;unpack=0"
SRC_URI += "${URI_bpftool}"
SRC_URI[bpftool.sha256sum] = "ddcb6b7ad2ce12dd010fb5c12564aae802ab87b5d915dcadc864b5f29d46b361"
RDEPENDS:bpftool = " \
 glibc \
 libcap \
 zlib-ng-compat \
 elfutils-libelf \
"
