# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "brasero"
PE = "0"
PV = "3.12.3"
PR = "11.el10"
PACKAGES = "brasero brasero-libs brasero-devel"
PROVIDES = "rpm/brasero rpm/brasero-libs rpm/brasero-devel"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/brasero-3.12.3-11.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "abb5d1b60abc99e1f7f33e5092e117c9eba73beae0ac7e1489ca361bc197fe96"

URI_brasero = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/brasero-3.12.3-11.el10.x86_64_v2.rpm;name=brasero;unpack=0"
SRC_URI += "${URI_brasero}"
SRC_URI[brasero.sha256sum] = "7a41448f32b97a26ea3502a570971868a45c4fd1ce09e7abe9a59e0ef8012811"
RDEPENDS:brasero = " \
 libburn \
 gstreamer1 \
 libtracker-sparql \
 libxml2 \
 pango \
 gdk-pixbuf2 \
 gstreamer1-plugins-base \
 libisofs \
 cairo \
 glib2 \
 gtk3 \
 glibc \
 brasero-libs \
"

URI_brasero-libs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/brasero-libs-3.12.3-11.el10.x86_64_v2.rpm;name=brasero-libs;unpack=0"
SRC_URI += "${URI_brasero-libs}"
SRC_URI[brasero-libs.sha256sum] = "48c926214cc9d5b6779f47921b116775f00891034d92a0ba76d7382bed6a4b2d"
RDEPENDS:brasero-libs = " \
 gstreamer1 \
 gstreamer1-plugins-base \
 pango \
 gdk-pixbuf2 \
 libcanberra-gtk3 \
 cairo \
 glib2 \
 gtk3 \
 glibc \
 libnotify \
"

URI_brasero-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/brasero-devel-3.12.3-11.el10.x86_64_v2.rpm;name=brasero-devel;unpack=0"
SRC_URI += "${URI_brasero-devel}"
SRC_URI[brasero-devel.sha256sum] = "04af4b4f32fd064fd62e2a53df2f83224ae8c29b301e8b0ccf5df145cfef2779"
RDEPENDS:brasero-devel = " \
 brasero-libs \
 glib2-devel \
 pkgconf-pkg-config \
 gtk3-devel \
"
