# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "butane"
PE = "0"
PV = "0.23.0"
PR = "1.el10"
PACKAGES = "butane butane-redistributable"
PROVIDES = "rpm/butane rpm/butane-redistributable"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/butane-0.23.0-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5752c1f0d4d113de11708de993b08b5b3518ad3d40fb01500b0b37459c08e4f3"

URI_butane = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/butane-0.23.0-1.el10.x86_64_v2.rpm;name=butane;unpack=0"
SRC_URI += "${URI_butane}"
SRC_URI[butane.sha256sum] = "542dd15da703aaeaebb5c94ae1561ebfc2c38628f622a04b0aecdce46c84533e"
RDEPENDS:butane = " \
 glibc \
"

URI_butane-redistributable = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/butane-redistributable-0.23.0-1.el10.noarch.rpm;name=butane-redistributable;unpack=0"
SRC_URI += "${URI_butane-redistributable}"
SRC_URI[butane-redistributable.sha256sum] = "b5fdac59e26b9d718af5bd74752efd941581ad65e1b98e607ef4a7d1373a614c"
RDEPENDS:butane-redistributable = ""
