# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "byacc"
PE = "0"
PV = "2.0.20230521"
PR = "7.el10"
PACKAGES = "byacc"
PROVIDES = "rpm/byacc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/byacc-2.0.20230521-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d27a846c0067d952eea2a196f8fccc439acb40d52655c086bafdb2f9ad1841d7"

URI_byacc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/byacc-2.0.20230521-7.el10.x86_64_v2.rpm;name=byacc;unpack=0"
SRC_URI += "${URI_byacc}"
SRC_URI[byacc.sha256sum] = "1a6026e3c4f372efe71e66e82498f36faf3b884067c82a1601c53e8a709932e9"
RDEPENDS:byacc = " \
 glibc \
"
