# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "cairomm"
PE = "0"
PV = "1.14.5"
PR = "5.el10"
PACKAGES = "cairomm cairomm-devel cairomm-doc"
PROVIDES = "rpm/cairomm rpm/cairomm-devel rpm/cairomm-doc"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/cairomm-1.14.5-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a799e5889105f1077456eb10903a0f0200ee9cbc1b0e835404c73e2cc13390c0"

URI_cairomm = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/cairomm-1.14.5-5.el10.x86_64_v2.rpm;name=cairomm;unpack=0"
SRC_URI += "${URI_cairomm}"
SRC_URI[cairomm.sha256sum] = "f2af42f738e867222cd8bb0559b3d0147f85f462681ac6703fb1eaf9d80dc8e3"
RDEPENDS:cairomm = " \
 libgcc \
 libsigc++20 \
 libstdc++ \
 cairo \
 glibc \
"

URI_cairomm-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/cairomm-devel-1.14.5-5.el10.x86_64_v2.rpm;name=cairomm-devel;unpack=0"
SRC_URI += "${URI_cairomm-devel}"
SRC_URI[cairomm-devel.sha256sum] = "8256df0d1541f27134f3bc5f5532a7320e0de74ca3b3c29573cf410cee0afffc"
RDEPENDS:cairomm-devel = " \
 cairomm \
 cairomm-devel \
 pkgconf-pkg-config \
 libsigc++20-devel \
 cairo-devel \
"

URI_cairomm-doc = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/cairomm-doc-1.14.5-5.el10.noarch.rpm;name=cairomm-doc;unpack=0"
SRC_URI += "${URI_cairomm-doc}"
SRC_URI[cairomm-doc.sha256sum] = "01b5368911098fb3707aca74851a437e3ac1e17d04d41b2bc879d75acd17df80"
RDEPENDS:cairomm-doc = ""
