# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "classloader-leak-test-framework"
PE = "0"
PV = "2.7.0"
PR = "10.el10"
PACKAGES = "classloader-leak-test-framework classloader-leak-test-framework-javadoc"
PROVIDES = "rpm/classloader-leak-test-framework rpm/classloader-leak-test-framework-javadoc"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/classloader-leak-test-framework-2.7.0-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ae5d9ffc34b67da72acc44cceb8c9b220b03a2b6d22e4b680cf587e522541fc0"

URI_classloader-leak-test-framework = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/classloader-leak-test-framework-2.7.0-10.el10.noarch.rpm;name=classloader-leak-test-framework;unpack=0"
SRC_URI += "${URI_classloader-leak-test-framework}"
SRC_URI[classloader-leak-test-framework.sha256sum] = "9f752d09f62ff44d850b19dd6b4cace25b0306f84a2f4a4fb34f8bdb603c7fbf"
RDEPENDS:classloader-leak-test-framework = " \
 bcel \
 junit \
 javapackages-filesystem \
"

URI_classloader-leak-test-framework-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/classloader-leak-test-framework-javadoc-2.7.0-10.el10.noarch.rpm;name=classloader-leak-test-framework-javadoc;unpack=0"
SRC_URI += "${URI_classloader-leak-test-framework-javadoc}"
SRC_URI[classloader-leak-test-framework-javadoc.sha256sum] = "667d73373dca44a8f0bfaf2152c02e21cecff62b800b1623b8505fab91315c52"
RDEPENDS:classloader-leak-test-framework-javadoc = " \
 javapackages-filesystem \
"
