# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "clevis"
PE = "0"
PV = "21"
PR = "8.el10"
PACKAGES = "clevis clevis-dracut clevis-luks clevis-pin-pkcs11 clevis-systemd clevis-udisks2"
PROVIDES = "rpm/clevis rpm/clevis-dracut rpm/clevis-luks rpm/clevis-pin-pkcs11 rpm/clevis-systemd rpm/clevis-udisks2"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/clevis-21-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "83d9df58fb4d54f5031806921e8c43231e6658980ffa3649d66eb64e3c2ae220"

URI_clevis = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/clevis-21-8.el10.x86_64_v2.rpm;name=clevis;unpack=0"
SRC_URI += "${URI_clevis}"
SRC_URI[clevis.sha256sum] = "341fb00837a41044a076962bbea979feee86405cf28075f8a4b59da8b4c5be84"
RDEPENDS:clevis = " \
 shadow-utils \
 systemd \
 jansson \
 libgcc \
 openssl-libs \
 curl \
 jq \
 bash \
 clevis-pin-tpm2 \
 tpm2-tools \
 glibc \
 coreutils \
 libjose \
 jose \
"

URI_clevis-dracut = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/clevis-dracut-21-8.el10.x86_64_v2.rpm;name=clevis-dracut;unpack=0"
SRC_URI += "${URI_clevis-dracut}"
SRC_URI[clevis-dracut.sha256sum] = "9a685d50253c823012e0f02558464a1d6b511d393d69f419caeeebe9385061e2"
RDEPENDS:clevis-dracut = " \
 dracut-network \
 bash \
 clevis-systemd \
"

URI_clevis-luks = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/clevis-luks-21-8.el10.x86_64_v2.rpm;name=clevis-luks;unpack=0"
SRC_URI += "${URI_clevis-luks}"
SRC_URI[clevis-luks.sha256sum] = "632ca86d85857289c35080222334270587cabdd11ac6b5a9e5ae52433704f7bb"
RDEPENDS:clevis-luks = " \
 luksmeta \
 clevis \
 bash \
 cryptsetup \
"

URI_clevis-pin-pkcs11 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/clevis-pin-pkcs11-21-8.el10.x86_64_v2.rpm;name=clevis-pin-pkcs11;unpack=0"
SRC_URI += "${URI_clevis-pin-pkcs11}"
SRC_URI[clevis-pin-pkcs11.sha256sum] = "b972f96ca4c92040f325405117a2b1ad30f0c8da130000daa62b84bf6ffeb8a6"
RDEPENDS:clevis-pin-pkcs11 = " \
 opensc \
 openssl \
 clevis-dracut \
 bash \
 clevis-luks \
 pcsc-lite \
 clevis-systemd \
 glibc \
 socat \
"

URI_clevis-systemd = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/clevis-systemd-21-8.el10.x86_64_v2.rpm;name=clevis-systemd;unpack=0"
SRC_URI += "${URI_clevis-systemd}"
SRC_URI[clevis-systemd.sha256sum] = "a5ff56db3d240e82381f78353d78532995beaeb6d36477989eb1e42f7730a6d9"
RDEPENDS:clevis-systemd = " \
 systemd \
 bash \
 clevis-luks \
"

URI_clevis-udisks2 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/clevis-udisks2-21-8.el10.x86_64_v2.rpm;name=clevis-udisks2;unpack=0"
SRC_URI += "${URI_clevis-udisks2}"
SRC_URI[clevis-udisks2.sha256sum] = "52366f65609091d73c88919d6908f32c10a8e2e5a07db3b971cde312fbad7b08"
RDEPENDS:clevis-udisks2 = " \
 jansson \
 cryptsetup-libs \
 audit-libs \
 libgcc \
 libluksmeta \
 libudisks2 \
 clevis-luks \
 glib2 \
 glibc \
"
