# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "cloud-utils"
PE = "0"
PV = "0.33"
PR = "11.el10"
PACKAGES = "cloud-utils-growpart cloud-utils cloud-utils-cloud-localds cloud-utils-ec2metadata cloud-utils-mount-image-callback cloud-utils-resize-part-image cloud-utils-vcs-run cloud-utils-write-mime-multipart"
PROVIDES = "rpm/cloud-utils-growpart rpm/cloud-utils rpm/cloud-utils-cloud-localds rpm/cloud-utils-ec2metadata rpm/cloud-utils-mount-image-callback rpm/cloud-utils-resize-part-image rpm/cloud-utils-vcs-run rpm/cloud-utils-write-mime-multipart"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/cloud-utils-0.33-11.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "470967a86958c3348264646a117ee29982432d795426c6f48ab5ea3ecab808c3"

URI_cloud-utils-growpart = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/cloud-utils-growpart-0.33-11.el10.noarch.rpm;name=cloud-utils-growpart;unpack=0"
SRC_URI += "${URI_cloud-utils-growpart}"
SRC_URI[cloud-utils-growpart.sha256sum] = "15e588602306bef1e6f1fc41faec76d2c1f6c801f4228c90d5e5095cb394dfe9"
RDEPENDS:cloud-utils-growpart = " \
 util-linux \
 gawk \
 bash \
"

URI_cloud-utils = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/cloud-utils-0.33-11.el10.noarch.rpm;name=cloud-utils;unpack=0"
SRC_URI += "${URI_cloud-utils}"
SRC_URI[cloud-utils.sha256sum] = "610ec4e13d5fef35c0e8791e972228ac6cb8ed12fecda7709ef4b7f81efeec41"
RDEPENDS:cloud-utils = " \
 cloud-utils-cloud-localds \
 cloud-utils-ec2metadata \
 cloud-utils-mount-image-callback \
 cloud-utils-resize-part-image \
 cloud-utils-vcs-run \
 cloud-utils-write-mime-multipart \
 cloud-utils-growpart \
"

URI_cloud-utils-cloud-localds = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/cloud-utils-cloud-localds-0.33-11.el10.noarch.rpm;name=cloud-utils-cloud-localds;unpack=0"
SRC_URI += "${URI_cloud-utils-cloud-localds}"
SRC_URI[cloud-utils-cloud-localds.sha256sum] = "960678d38fd08e4283b375cff77eebbe5854c9705cc9227bd5129d0cd46870e5"
RDEPENDS:cloud-utils-cloud-localds = " \
 bash \
"

URI_cloud-utils-ec2metadata = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/cloud-utils-ec2metadata-0.33-11.el10.noarch.rpm;name=cloud-utils-ec2metadata;unpack=0"
SRC_URI += "${URI_cloud-utils-ec2metadata}"
SRC_URI[cloud-utils-ec2metadata.sha256sum] = "3e9a46b95d0f3e1d06ed8e32a8396bff0a29501ca8d6bce32f6dae156ffb822c"
RDEPENDS:cloud-utils-ec2metadata = " \
 python3 \
"

URI_cloud-utils-mount-image-callback = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/cloud-utils-mount-image-callback-0.33-11.el10.noarch.rpm;name=cloud-utils-mount-image-callback;unpack=0"
SRC_URI += "${URI_cloud-utils-mount-image-callback}"
SRC_URI[cloud-utils-mount-image-callback.sha256sum] = "356e32afdf1c0941e5223d1e2c1961fd0c7036ac915b110c52eaeb7756f9ce47"
RDEPENDS:cloud-utils-mount-image-callback = " \
 util-linux \
 gawk \
 bash \
"

URI_cloud-utils-resize-part-image = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/cloud-utils-resize-part-image-0.33-11.el10.noarch.rpm;name=cloud-utils-resize-part-image;unpack=0"
SRC_URI += "${URI_cloud-utils-resize-part-image}"
SRC_URI[cloud-utils-resize-part-image.sha256sum] = "991206ef5b5f1994edfcf6293dcb7729c7e449425f8e36cb01ccf6400f8ef5e3"
RDEPENDS:cloud-utils-resize-part-image = " \
 e2fsprogs \
 gzip \
 gawk \
 tar \
 bash \
 file \
"

URI_cloud-utils-vcs-run = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/cloud-utils-vcs-run-0.33-11.el10.noarch.rpm;name=cloud-utils-vcs-run;unpack=0"
SRC_URI += "${URI_cloud-utils-vcs-run}"
SRC_URI[cloud-utils-vcs-run.sha256sum] = "1cbe3365ad5ebbd5397e502026898080ff5d691d3cd4542ab657f414c951bc7d"
RDEPENDS:cloud-utils-vcs-run = " \
 bash \
"

URI_cloud-utils-write-mime-multipart = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/cloud-utils-write-mime-multipart-0.33-11.el10.noarch.rpm;name=cloud-utils-write-mime-multipart;unpack=0"
SRC_URI += "${URI_cloud-utils-write-mime-multipart}"
SRC_URI[cloud-utils-write-mime-multipart.sha256sum] = "ca004c9348c3e8e442c21a7b450d1d2144a31d6860ce1aa033275019a48a5892"
RDEPENDS:cloud-utils-write-mime-multipart = " \
 python3 \
"
