# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "colord-gtk"
PE = "0"
PV = "0.3.1"
PR = "4.el10"
PACKAGES = "colord-gtk colord-gtk4 colord-gtk-devel colord-gtk4-devel"
PROVIDES = "rpm/colord-gtk rpm/colord-gtk4 rpm/colord-gtk-devel rpm/colord-gtk4-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/colord-gtk-0.3.1-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "70d4b3ed84c4dd7d5299594be297ff8962a7930c91ed271d5b504dc9b9816a29"

URI_colord-gtk = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/colord-gtk-0.3.1-4.el10.x86_64_v2.rpm;name=colord-gtk;unpack=0"
SRC_URI += "${URI_colord-gtk}"
SRC_URI[colord-gtk.sha256sum] = "d788d328288706fe0bb51a514447132852e36a3e1cb52da5349c9ff3222845a9"
RDEPENDS:colord-gtk = " \
 cairo \
 colord-libs \
 glib2 \
 glibc \
 gtk3 \
"

URI_colord-gtk4 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/colord-gtk4-0.3.1-4.el10.x86_64_v2.rpm;name=colord-gtk4;unpack=0"
SRC_URI += "${URI_colord-gtk4}"
SRC_URI[colord-gtk4.sha256sum] = "38df37ff593312ada691b30a1b318ee679fcefc873ad4755c70e7722531fd262"
RDEPENDS:colord-gtk4 = " \
 cairo \
 glib2 \
 colord-libs \
 glibc \
 gtk4 \
"

URI_colord-gtk-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/colord-gtk-devel-0.3.1-4.el10.x86_64_v2.rpm;name=colord-gtk-devel;unpack=0"
SRC_URI += "${URI_colord-gtk-devel}"
SRC_URI[colord-gtk-devel.sha256sum] = "2d659b5c681bb912c5138d1bb4b461c5732713d385945cc45402f43ebd0e835a"
RDEPENDS:colord-gtk-devel = " \
 colord-devel \
 colord-gtk \
 pkgconf-pkg-config \
 gtk3-devel \
"

URI_colord-gtk4-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/colord-gtk4-devel-0.3.1-4.el10.x86_64_v2.rpm;name=colord-gtk4-devel;unpack=0"
SRC_URI += "${URI_colord-gtk4-devel}"
SRC_URI[colord-gtk4-devel.sha256sum] = "7f2a9515829c531ceba54bf84364a4179c6a8f81c1adbdea6631e6cc79bded42"
RDEPENDS:colord-gtk4-devel = " \
 colord-devel \
 colord-gtk-devel \
 pkgconf-pkg-config \
 colord-gtk4 \
 gtk4-devel \
"
