# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "conntrack-tools"
PE = "0"
PV = "1.4.8"
PR = "3.el10"
PACKAGES = "conntrack-tools"
PROVIDES = "rpm/conntrack-tools"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/conntrack-tools-1.4.8-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0dfc610338c65d17408a3fdfef4dcdd3b4dda4d1f318186fbeddf336c211f00d"

URI_conntrack-tools = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/conntrack-tools-1.4.8-3.el10.x86_64_v2.rpm;name=conntrack-tools;unpack=0"
SRC_URI += "${URI_conntrack-tools}"
SRC_URI[conntrack-tools.sha256sum] = "b0b18c6d84e1b05b1d8bcbe868893f3fffc42f7d3c4234305720f832e08e4a2b"
RDEPENDS:conntrack-tools = " \
 systemd \
 systemd-libs \
 libmnl \
 libnetfilter_conntrack \
 bash \
 libnfnetlink \
 libnetfilter_cthelper \
 glibc \
 libnetfilter_cttimeout \
 libnetfilter_queue \
"
