# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "crontabs"
PE = "0"
PV = "1.11^20190603git9e74f2d"
PR = "6.el10"
PACKAGES = "crontabs"
PROVIDES = "rpm/crontabs"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/crontabs-1.11^20190603git9e74f2d-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4367b6060030d80c1171141a48ebb6fb3f44b91b1eb0875a32b7a580395c875b"

URI_crontabs = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/crontabs-1.11^20190603git9e74f2d-6.el10.noarch.rpm;name=crontabs;unpack=0"
SRC_URI += "${URI_crontabs}"
SRC_URI[crontabs.sha256sum] = "879f1342347b6802f274b970f093d44aae46a05c3b3694c96cfec3fc83181b41"
RDEPENDS:crontabs = " \
 sed \
 bash \
 cronie \
"
