# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "dmidecode"
PE = "1"
PV = "3.6"
PR = "3.el10"
PACKAGES = "dmidecode"
PROVIDES = "rpm/dmidecode"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/dmidecode-3.6-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a4ef477130ca6716af8e715ebf51bd560135b78d225648a2dac60321c8e505a5"

URI_dmidecode = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/dmidecode-3.6-3.el10.x86_64_v2.rpm;name=dmidecode;unpack=0"
SRC_URI += "${URI_dmidecode}"
SRC_URI[dmidecode.sha256sum] = "b990ba5a720efd12acea0b76a0853a61c91ea10a52e6f2eb6fa349d37a869d32"
RDEPENDS:dmidecode = " \
 glibc \
"
