# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "docbook2X"
PE = "0"
PV = "0.8.8"
PR = "50.el10"
PACKAGES = "docbook2X"
PROVIDES = "rpm/docbook2X"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/docbook2X-0.8.8-50.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2baed6ea762b44080e6dfe2cce6cdebb5fe8b54e64201726b7ab9a5756bd483e"

URI_docbook2X = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/docbook2X-0.8.8-50.el10.x86_64_v2.rpm;name=docbook2X;unpack=0"
SRC_URI += "${URI_docbook2X}"
SRC_URI[docbook2X.sha256sum] = "1696b6012bcf6567b60487c80ba9252e34879d1f8de06e3430ace9175fcdcf24"
RDEPENDS:docbook2X = " \
 perl-libs \
 libxslt \
 perl-interpreter \
 perl-vars \
 perl-IO \
 texinfo \
 perl-Text-Tabs+Wrap \
 perl-Getopt-Long \
 openjade \
 perl-XML-SAX \
 opensp \
 glibc \
 perl-Exporter \
"
