# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "dpdk"
PE = "2"
PV = "24.11.1"
PR = "2.el10"
PACKAGES = "dpdk dpdk-devel dpdk-doc dpdk-tools"
PROVIDES = "rpm/dpdk rpm/dpdk-devel rpm/dpdk-doc rpm/dpdk-tools"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/dpdk-24.11.1-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5027fafd5ab0cf46867a58d62be1d5a4b41171e566462edca8b32c2abf86419e"

URI_dpdk = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/dpdk-24.11.1-2.el10.x86_64_v2.rpm;name=dpdk;unpack=0"
SRC_URI += "${URI_dpdk}"
SRC_URI[dpdk.sha256sum] = "1c9af2893505f7a07459a1696b2396f0f2db0ad940618057605c0741830bfaca"
RDEPENDS:dpdk = " \
 glibc \
 libarchive \
 libibverbs \
 numactl-libs \
"

URI_dpdk-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/dpdk-devel-24.11.1-2.el10.x86_64_v2.rpm;name=dpdk-devel;unpack=0"
SRC_URI += "${URI_dpdk-devel}"
SRC_URI[dpdk-devel.sha256sum] = "d2b717f596b9340b649e56f8e5802929245dc42f3ce57e1f3e76d72019914481"
RDEPENDS:dpdk-devel = " \
 python3 \
 libarchive-devel \
 dpdk \
 dpdk-devel \
 pkgconf-pkg-config \
 bash \
 rdma-core-devel \
"

URI_dpdk-doc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/dpdk-doc-24.11.1-2.el10.noarch.rpm;name=dpdk-doc;unpack=0"
SRC_URI += "${URI_dpdk-doc}"
SRC_URI[dpdk-doc.sha256sum] = "0a6523b6c0c901d7e16b29ab6192b6ffa5c4bed0da6bb0f4e44dc75bc29681fc"
RDEPENDS:dpdk-doc = ""

URI_dpdk-tools = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/dpdk-tools-24.11.1-2.el10.x86_64_v2.rpm;name=dpdk-tools;unpack=0"
SRC_URI += "${URI_dpdk-tools}"
SRC_URI[dpdk-tools.sha256sum] = "fce313c786aa0c2d14ebf5ad7849bdecb919f466d7e14f146612d59a45a9ef3c"
RDEPENDS:dpdk-tools = " \
 python3 \
 dpdk \
 iproute \
 kmod \
 pciutils \
 findutils \
"
