# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "efibootmgr"
PE = "0"
PV = "18"
PR = "8.el10"
PACKAGES = "efibootmgr"
PROVIDES = "rpm/efibootmgr"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/efibootmgr-18-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "750701488a7da37e18909c1f4bd37fa97d9e515f6293b403406eeca5aa089ccb"

URI_efibootmgr = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/efibootmgr-18-8.el10.x86_64_v2.rpm;name=efibootmgr;unpack=0"
SRC_URI += "${URI_efibootmgr}"
SRC_URI[efibootmgr.sha256sum] = "f37c6bb9822a1c8d1e30a63f66b904a281bb19758b3c3ab13946bafba850d799"
RDEPENDS:efibootmgr = " \
 glibc \
 efi-filesystem \
 popt \
 efivar-libs \
"
