# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "enchant2"
PE = "0"
PV = "2.6.7"
PR = "3.el10"
PACKAGES = "enchant2 enchant2-voikko enchant2-devel"
PROVIDES = "rpm/enchant2 rpm/enchant2-voikko rpm/enchant2-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/enchant2-2.6.7-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4bdd03d7238da06c1959c0ba968c2708095490eb5be10714cea32557ee50d7b9"

URI_enchant2 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/enchant2-2.6.7-3.el10.x86_64_v2.rpm;name=enchant2;unpack=0"
SRC_URI += "${URI_enchant2}"
SRC_URI[enchant2.sha256sum] = "837256609e4c02fce5b50572d94806f2227458da767b425f17e9e39a0c13976c"
RDEPENDS:enchant2 = " \
 libgcc \
 hunspell \
 libstdc++ \
 glib2 \
 glibc \
"

URI_enchant2-voikko = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/enchant2-voikko-2.6.7-3.el10.x86_64_v2.rpm;name=enchant2-voikko;unpack=0"
SRC_URI += "${URI_enchant2-voikko}"
SRC_URI[enchant2-voikko.sha256sum] = "a2fcfb64adb8e6d15d113427cdf471cb6d82332b92776914baf5357cdaf50441"
RDEPENDS:enchant2-voikko = " \
 glibc \
 glib2 \
 enchant2 \
 libvoikko \
"

URI_enchant2-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/enchant2-devel-2.6.7-3.el10.x86_64_v2.rpm;name=enchant2-devel;unpack=0"
SRC_URI += "${URI_enchant2-devel}"
SRC_URI[enchant2-devel.sha256sum] = "427ee60e89587daf29fb330635944fea6940cfad0abc7a5b9a5ff4c7d1137ed7"
RDEPENDS:enchant2-devel = " \
 glib2-devel \
 pkgconf-pkg-config \
 enchant2 \
"
