# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "environment-modules"
PE = "0"
PV = "5.3.1"
PR = "8.el10"
PACKAGES = "environment-modules"
PROVIDES = "rpm/environment-modules"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/environment-modules-5.3.1-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "65fdf81a206fa2e37677fd2504b04745ed7de6cd962fb0e7ec560b7c404b7364"

URI_environment-modules = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/environment-modules-5.3.1-8.el10.x86_64_v2.rpm;name=environment-modules;unpack=0"
SRC_URI += "${URI_environment-modules}"
SRC_URI[environment-modules.sha256sum] = "6b9865c6a8f4d94b7d9624ef16c0147619514bf50d1bb57ffad7e588410a98ca"
RDEPENDS:environment-modules = " \
 less \
 tcl \
 man-db \
 vim-filesystem \
 bash \
 procps-ng \
 glibc \
 coreutils \
 sed \
 alternatives \
"
