# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "expat"
PE = "0"
PV = "2.7.1"
PR = "1.el10_0.3"
PACKAGES = "expat expat-devel expat-static"
PROVIDES = "rpm/expat rpm/expat-devel rpm/expat-static"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/expat-2.7.1-1.el10_0.3.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a48902b84f12074b32490a1bf641c4fb9619d01a6a03f1d5ebc479af0eb3b7e1"

URI_expat = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/expat-2.7.1-1.el10_0.3.x86_64_v2.rpm;name=expat;unpack=0"
SRC_URI += "${URI_expat}"
SRC_URI[expat.sha256sum] = "c2968d798f9c2d2ed4b6c77c1e97a7901087e82808d614e76ed0a419219cb5cb"
RDEPENDS:expat = " \
 glibc \
"

URI_expat-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/expat-devel-2.7.1-1.el10_0.3.x86_64_v2.rpm;name=expat-devel;unpack=0"
SRC_URI += "${URI_expat-devel}"
SRC_URI[expat-devel.sha256sum] = "5ec1b1938dfb0522705195224b40ea998ef1d2cc8e4efe74f7c714c53242ac89"
RDEPENDS:expat-devel = " \
 pkgconf-pkg-config \
 expat \
"

URI_expat-static = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/expat-static-2.7.1-1.el10_0.3.x86_64_v2.rpm;name=expat-static;unpack=0"
SRC_URI += "${URI_expat-static}"
SRC_URI[expat-static.sha256sum] = "cd5f0ed862c6edcfd628c7e470e32e04dff75f8b76e2e56ac2fb1c5c095ac496"
RDEPENDS:expat-static = " \
 expat-devel \
"
