# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "fabtests"
PE = "0"
PV = "1.22.0"
PR = "1.el10"
PACKAGES = "fabtests"
PROVIDES = "rpm/fabtests"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/fabtests-1.22.0-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1aa217017b99ebc25d53415c35181b4746eee59d54731a4681a9f1f424989c10"

URI_fabtests = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/fabtests-1.22.0-1.el10.x86_64_v2.rpm;name=fabtests;unpack=0"
SRC_URI += "${URI_fabtests}"
SRC_URI[fabtests.sha256sum] = "4e51674f1adce1438ddf72a16de8cbabc748bb7cc91feb4d2cd36b344b39bab9"
RDEPENDS:fabtests = " \
 python3 \
 ruby \
 libfabric \
 python3-pytest \
 bash \
 glibc \
"
