# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "fasterxml-oss-parent"
PE = "0"
PV = "57"
PR = "2.el10"
PACKAGES = "fasterxml-oss-parent"
PROVIDES = "rpm/fasterxml-oss-parent"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/fasterxml-oss-parent-57-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "cc6710cdfc3f836365385825ebc3f2f16439cc95b5d6bf6c1e6c828bc1212e5a"

URI_fasterxml-oss-parent = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/fasterxml-oss-parent-57-2.el10.noarch.rpm;name=fasterxml-oss-parent;unpack=0"
SRC_URI += "${URI_fasterxml-oss-parent}"
SRC_URI[fasterxml-oss-parent.sha256sum] = "9635729b25ada3a8690f4996e12f13cd6d5bd7416918f83805e4d80fe2a8ef52"
RDEPENDS:fasterxml-oss-parent = " \
 maven-surefire-plugin \
 maven-jar-plugin \
 javapackages-filesystem \
 maven-bundle-plugin \
 maven-compiler-plugin \
 build-helper-maven-plugin \
 java-21-openjdk-headless \
"
