# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "fetchmail"
PE = "0"
PV = "6.4.38"
PR = "3.el10"
PACKAGES = "fetchmail"
PROVIDES = "rpm/fetchmail"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/fetchmail-6.4.38-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "63e7cf0c2cff8fa871ede7086984f11f6ae3f69a251e37c8019351ba88fd0ce8"

URI_fetchmail = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/fetchmail-6.4.38-3.el10.x86_64_v2.rpm;name=fetchmail;unpack=0"
SRC_URI += "${URI_fetchmail}"
SRC_URI[fetchmail.sha256sum] = "d1182771e4d5cc181048f7ce9bcaa144580c46f45e737f911fb14fe42dde9b3b"
RDEPENDS:fetchmail = " \
 glibc \
 krb5-libs \
 openssl-libs \
 libcom_err \
"
