# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "firewalld"
PE = "0"
PV = "2.3.1"
PR = "1.el10_0"
PACKAGES = "firewalld firewalld-filesystem python3-firewall firewall-applet firewall-config firewalld-test"
PROVIDES = "rpm/firewalld rpm/firewalld-filesystem rpm/python3-firewall rpm/firewall-applet rpm/firewall-config rpm/firewalld-test"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/firewalld-2.3.1-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e22a96eb793edc71fcec29ed479017ffd15a269c88c2e4f9d81e60ed86e3792d"

URI_firewalld = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/firewalld-2.3.1-1.el10_0.noarch.rpm;name=firewalld;unpack=0"
SRC_URI += "${URI_firewalld}"
SRC_URI[firewalld.sha256sum] = "b718b6d0bc55d2380df622add90b904fd16fb9d75e1a15febcdd382a7c6c68ef"
RDEPENDS:firewalld = " \
 python3 \
 firewalld-filesystem \
 systemd \
 bash \
 python3-firewall \
"

URI_firewalld-filesystem = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/firewalld-filesystem-2.3.1-1.el10_0.noarch.rpm;name=firewalld-filesystem;unpack=0"
SRC_URI += "${URI_firewalld-filesystem}"
SRC_URI[firewalld-filesystem.sha256sum] = "1a4b095762c880e0ef503b7b5e6a312c9d8204769d22975f77a904e5f8dde077"
RDEPENDS:firewalld-filesystem = ""

URI_python3-firewall = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-firewall-2.3.1-1.el10_0.noarch.rpm;name=python3-firewall;unpack=0"
SRC_URI += "${URI_python3-firewall}"
SRC_URI[python3-firewall.sha256sum] = "5b1ae9202f26c38d11e675ff8861879c837dd9d1e201e9fa67a259b6d99daece"
RDEPENDS:python3-firewall = " \
 python3-nftables \
 python3-dbus \
 python3 \
 python3-gobject-base \
"

URI_firewall-applet = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/firewall-applet-2.3.1-1.el10_0.noarch.rpm;name=firewall-applet;unpack=0"
SRC_URI += "${URI_firewall-applet}"
SRC_URI[firewall-applet.sha256sum] = "15dc00283281bd2cf0fbfa5b9e6b7086185c3c2daeee61dcb8d907350e679b6f"
RDEPENDS:firewall-applet = " \
 python3 \
 python3-gobject \
 firewalld \
 python3-pyqt6-base \
 dbus-x11 \
 python3-firewall \
 hicolor-icon-theme \
 firewall-config \
 NetworkManager-libnm \
 libnotify \
"

URI_firewall-config = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/firewall-config-2.3.1-1.el10_0.noarch.rpm;name=firewall-config;unpack=0"
SRC_URI += "${URI_firewall-config}"
SRC_URI[firewall-config.sha256sum] = "c684feb92c30d60d9fe51663037638b419f626ff7f9b1b2aa308bbf70f446380"
RDEPENDS:firewall-config = " \
 python3 \
 python3-gobject \
 dbus-x11 \
 python3-firewall \
 gtk3 \
 hicolor-icon-theme \
 NetworkManager-libnm \
 firewalld \
"

URI_firewalld-test = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/firewalld-test-2.3.1-1.el10_0.noarch.rpm;name=firewalld-test;unpack=0"
SRC_URI += "${URI_firewalld-test}"
SRC_URI[firewalld-test.sha256sum] = "b28913be085131700b106b0b8e231720c56d1887e55cd141682de7a39c1b0746"
RDEPENDS:firewalld-test = " \
 bash \
"
