# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "flac"
PE = "0"
PV = "1.4.3"
PR = "6.el10"
PACKAGES = "flac-libs flac flac-devel"
PROVIDES = "rpm/flac-libs rpm/flac rpm/flac-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/flac-1.4.3-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "876a7acbce3a90a0307aac3053fc38a0aee3adecaccefbc69b2015f3c742ea3a"

URI_flac-libs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/flac-libs-1.4.3-6.el10.x86_64_v2.rpm;name=flac-libs;unpack=0"
SRC_URI += "${URI_flac-libs}"
SRC_URI[flac-libs.sha256sum] = "95d6c72d43327f99423011ca52b05021f2e19f5da35b876d2c7dc4d91814625f"
RDEPENDS:flac-libs = " \
 glibc \
 libogg \
 libgcc \
 libstdc++ \
"

URI_flac = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/flac-1.4.3-6.el10.x86_64_v2.rpm;name=flac;unpack=0"
SRC_URI += "${URI_flac}"
SRC_URI[flac.sha256sum] = "db2cf1a4a147acb0924c7aef6fd4df148e988855cfd301f6506229ce93383fde"
RDEPENDS:flac = " \
 glibc \
 flac-libs \
"

URI_flac-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/flac-devel-1.4.3-6.el10.x86_64_v2.rpm;name=flac-devel;unpack=0"
SRC_URI += "${URI_flac-devel}"
SRC_URI[flac-devel.sha256sum] = "27241d0083aa8c05fe83c21bf921edb9237e06c35cb338a166c7a8c72d513ffb"
RDEPENDS:flac-devel = " \
 flac-devel \
 libogg-devel \
 flac-libs \
 pkgconf-pkg-config \
"
