# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "flatpak-builder"
PE = "0"
PV = "1.4.4"
PR = "1.el10"
PACKAGES = "flatpak-builder flatpak-builder-tests"
PROVIDES = "rpm/flatpak-builder rpm/flatpak-builder-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/flatpak-builder-1.4.4-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a79784feb10caf13a434f6125a253541334ee52a23301f9169f887e1c29ddfc6"

URI_flatpak-builder = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/flatpak-builder-1.4.4-1.el10.x86_64_v2.rpm;name=flatpak-builder;unpack=0"
SRC_URI += "${URI_flatpak-builder}"
SRC_URI[flatpak-builder.sha256sum] = "57d6e800e64be1e951194e66f9f02983bff6f152f705dbca31bf29e9a32c2629"
RDEPENDS:flatpak-builder = " \
 ostree-libs \
 appstream-compose \
 libgcc \
 libxml2 \
 elfutils-libelf \
 json-glib \
 libyaml \
 glib2 \
 libcurl \
 glibc \
 debugedit \
 ostree \
 flatpak \
"

URI_flatpak-builder-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/flatpak-builder-tests-1.4.4-1.el10.x86_64_v2.rpm;name=flatpak-builder-tests;unpack=0"
SRC_URI += "${URI_flatpak-builder-tests}"
SRC_URI[flatpak-builder-tests.sha256sum] = "74c6965cdbd708a38719e4958ea31a2d6341de26193ce945ee4f12bef80a6eb8"
RDEPENDS:flatpak-builder-tests = " \
 bash \
 flatpak-builder \
"
