# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "fontawesome4-fonts"
PE = "1"
PV = "4.7.0"
PR = "23.el10"
PACKAGES = "fontawesome4-fonts fontawesome4-fonts-web"
PROVIDES = "rpm/fontawesome4-fonts rpm/fontawesome4-fonts-web"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/fontawesome4-fonts-4.7.0-23.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "bb1e72ef73b6df540b24db762a0f0c49ab90447ae58cd23fa1a99ff7b4c452f7"

URI_fontawesome4-fonts = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/fontawesome4-fonts-4.7.0-23.el10.noarch.rpm;name=fontawesome4-fonts;unpack=0"
SRC_URI += "${URI_fontawesome4-fonts}"
SRC_URI[fontawesome4-fonts.sha256sum] = "34ea039087b9a50279e8a8ba52a1add7d061794db74aa71e9520954294cba468"
RDEPENDS:fontawesome4-fonts = " \
 fonts-filesystem \
"

URI_fontawesome4-fonts-web = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/fontawesome4-fonts-web-4.7.0-23.el10.noarch.rpm;name=fontawesome4-fonts-web;unpack=0"
SRC_URI += "${URI_fontawesome4-fonts-web}"
SRC_URI[fontawesome4-fonts-web.sha256sum] = "a92626f7894bac12285ff567708be7d99f224672453ea5cf4d2daba9d952b499"
RDEPENDS:fontawesome4-fonts-web = " \
 fontawesome4-fonts \
"
