# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "fonts-rpm-macros"
PE = "1"
PV = "2.0.5"
PR = "18.el10"
PACKAGES = "fonts-filesystem fonts-srpm-macros fonts-rpm-macros fonts-rpm-templates"
PROVIDES = "rpm/fonts-filesystem rpm/fonts-srpm-macros rpm/fonts-rpm-macros rpm/fonts-rpm-templates"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/fonts-rpm-macros-2.0.5-18.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "9959b7a3dd3b9a7a57f3a69d5208bb44c42b29f60a7937395a3155111de17d58"

URI_fonts-filesystem = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/fonts-filesystem-2.0.5-18.el10.noarch.rpm;name=fonts-filesystem;unpack=0"
SRC_URI += "${URI_fonts-filesystem}"
SRC_URI[fonts-filesystem.sha256sum] = "da1d69f35d4fcc937ac3c1ac56ed083c5f067a6344fc6316fff580771ab42b83"
RDEPENDS:fonts-filesystem = ""

URI_fonts-srpm-macros = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/fonts-srpm-macros-2.0.5-18.el10.noarch.rpm;name=fonts-srpm-macros;unpack=0"
SRC_URI += "${URI_fonts-srpm-macros}"
SRC_URI[fonts-srpm-macros.sha256sum] = "1c4eda423634a984d4976c2e9b4ef071aee2a3e60a16f148f1b83fcd64e05e96"
RDEPENDS:fonts-srpm-macros = " \
 redhat-rpm-config \
 forge-srpm-macros \
"

URI_fonts-rpm-macros = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/fonts-rpm-macros-2.0.5-18.el10.noarch.rpm;name=fonts-rpm-macros;unpack=0"
SRC_URI += "${URI_fonts-rpm-macros}"
SRC_URI[fonts-rpm-macros.sha256sum] = "3017c2138718ed3453e14d5ab41e137d9458c1502aa12549176592cf9b93697d"
RDEPENDS:fonts-rpm-macros = " \
 python3 \
 fonts-filesystem \
 fontconfig \
 fonts-srpm-macros \
 python3-lxml \
 uchardet \
 libappstream-glib \
"

URI_fonts-rpm-templates = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/fonts-rpm-templates-2.0.5-18.el10.noarch.rpm;name=fonts-rpm-templates;unpack=0"
SRC_URI += "${URI_fonts-rpm-templates}"
SRC_URI[fonts-rpm-templates.sha256sum] = "6d01589320787207e34e1f37abadf6af4a82a2371e39a4218a554b9d959cf87c"
RDEPENDS:fonts-rpm-templates = " \
 fonts-rpm-macros \
"
