# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "forge-srpm-macros"
PE = "0"
PV = "0.4.0"
PR = "6.el10"
PACKAGES = "forge-srpm-macros"
PROVIDES = "rpm/forge-srpm-macros"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/forge-srpm-macros-0.4.0-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1dda3d6d6f4b25140aba3f4303d40b9d4d4a3a5156e071d07de7fe12922a042c"

URI_forge-srpm-macros = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/forge-srpm-macros-0.4.0-6.el10.noarch.rpm;name=forge-srpm-macros;unpack=0"
SRC_URI += "${URI_forge-srpm-macros}"
SRC_URI[forge-srpm-macros.sha256sum] = "c07ce83b6542f27f1f781c12dc1deee72e422c2ec8df742882e8cec9e4467471"
RDEPENDS:forge-srpm-macros = " \
 redhat-rpm-config \
"
