# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "fribidi"
PE = "0"
PV = "1.0.14"
PR = "4.el10"
PACKAGES = "fribidi fribidi-devel"
PROVIDES = "rpm/fribidi rpm/fribidi-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/fribidi-1.0.14-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c7dd06a678eb0582b91ad07a128ed90e8d165999a1239be270d21d09041ae88b"

URI_fribidi = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/fribidi-1.0.14-4.el10.x86_64_v2.rpm;name=fribidi;unpack=0"
SRC_URI += "${URI_fribidi}"
SRC_URI[fribidi.sha256sum] = "196aff68e354cc2cf981fab8bb54c411dfb68373eb80c63fd7a5295aa188615a"
RDEPENDS:fribidi = " \
 glibc \
"

URI_fribidi-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/fribidi-devel-1.0.14-4.el10.x86_64_v2.rpm;name=fribidi-devel;unpack=0"
SRC_URI += "${URI_fribidi-devel}"
SRC_URI[fribidi-devel.sha256sum] = "b24d571e3a8978ad892d2862a036a5de83b9987b887325f064d957876bdca11e"
RDEPENDS:fribidi-devel = " \
 fribidi \
 pkgconf-pkg-config \
"
