# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "fuse-overlayfs"
PE = "0"
PV = "1.14"
PR = "2.el10"
PACKAGES = "fuse-overlayfs"
PROVIDES = "rpm/fuse-overlayfs"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/fuse-overlayfs-1.14-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b6d2aed76c1b5a42bc8fb65d4e467464143417ed860e72911e3169c4138f7a16"

URI_fuse-overlayfs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/fuse-overlayfs-1.14-2.el10.x86_64_v2.rpm;name=fuse-overlayfs;unpack=0"
SRC_URI += "${URI_fuse-overlayfs}"
SRC_URI[fuse-overlayfs.sha256sum] = "7dfec70e8df428d8442b9939f2616f0877b68eeee2f8ac8f89fd107da0b8e2ea"
RDEPENDS:fuse-overlayfs = " \
 fuse3 \
 fuse3-libs \
 kmod \
 libgcc \
 bash \
 glibc \
"
