# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gawk"
PE = "0"
PV = "5.3.0"
PR = "6.el10"
PACKAGES = "gawk gawk-all-langpacks gawk-devel gawk-doc"
PROVIDES = "rpm/gawk rpm/gawk-all-langpacks rpm/gawk-devel rpm/gawk-doc"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/gawk-5.3.0-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2840ea03dd8930a0757566844c5667b7f93b55eef287e778890a8cc913b9179b"

URI_gawk = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/gawk-5.3.0-6.el10.x86_64_v2.rpm;name=gawk;unpack=0"
SRC_URI += "${URI_gawk}"
SRC_URI[gawk.sha256sum] = "0f756b200b7168070305891cfd7624cdfe965919a167bade078a28a93b64d001"
RDEPENDS:gawk = " \
 gmp \
 mpfr \
 readline \
 bash \
 glibc \
 filesystem \
"

URI_gawk-all-langpacks = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gawk-all-langpacks-5.3.0-6.el10.x86_64_v2.rpm;name=gawk-all-langpacks;unpack=0"
SRC_URI += "${URI_gawk-all-langpacks}"
SRC_URI[gawk-all-langpacks.sha256sum] = "5e28bc4be45e0454c3f34b9be37a0cae5f2457448c3421eb7e4559aa06a0df44"
RDEPENDS:gawk-all-langpacks = ""

URI_gawk-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/gawk-devel-5.3.0-6.el10.x86_64_v2.rpm;name=gawk-devel;unpack=0"
SRC_URI += "${URI_gawk-devel}"
SRC_URI[gawk-devel.sha256sum] = "e8e2d0d3d93fe70489ec5d9c7677715fd31d11885f405193328560e02e7eec21"
RDEPENDS:gawk-devel = " \
 gawk \
"

URI_gawk-doc = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/gawk-doc-5.3.0-6.el10.noarch.rpm;name=gawk-doc;unpack=0"
SRC_URI += "${URI_gawk-doc}"
SRC_URI[gawk-doc.sha256sum] = "a24fc914473059459d12031f28895455668222ef146af682257b32eb7faeb7f4"
RDEPENDS:gawk-doc = " \
 gawk \
"
