# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gdisk"
PE = "0"
PV = "1.0.9"
PR = "10.el10"
PACKAGES = "gdisk"
PROVIDES = "rpm/gdisk"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/gdisk-1.0.9-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a2e996bd189e8f38badb3c92adea3e9c490e2cd3925245b7eab58174decdeefd"

URI_gdisk = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/gdisk-1.0.9-10.el10.x86_64_v2.rpm;name=gdisk;unpack=0"
SRC_URI += "${URI_gdisk}"
SRC_URI[gdisk.sha256sum] = "8b0cfd3bca615596e165083be506386074693cc42e44d7c7bb7f78bae42de749"
RDEPENDS:gdisk = " \
 libuuid \
 libgcc \
 libstdc++ \
 ncurses-libs \
 popt \
 glibc \
"
