# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gfs2-utils"
PE = "0"
PV = "3.5.1"
PR = "5.el10"
PACKAGES = "gfs2-utils"
PROVIDES = "rpm/gfs2-utils"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/gfs2-utils-3.5.1-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "6800df58f2424fae8f11d40814563acca626944a9beaf6a13e5bd38a90c84570"

URI_gfs2-utils = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/gfs2-utils-3.5.1-5.el10.x86_64_v2.rpm;name=gfs2-utils;unpack=0"
SRC_URI += "${URI_gfs2-utils}"
SRC_URI[gfs2-utils.sha256sum] = "eb76255f33da3a40d44e694ad478934515606ead9ae17f883c809858ef09ee9a"
RDEPENDS:gfs2-utils = " \
 libuuid \
 zlib-ng-compat \
 bzip2-libs \
 libblkid \
 bash \
 ncurses-libs \
 glibc \
"
