# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gmp"
PE = "1"
PV = "6.2.1"
PR = "10.el10"
PACKAGES = "gmp gmp-c++ gmp-devel gmp-static"
PROVIDES = "rpm/gmp rpm/gmp-c++ rpm/gmp-devel rpm/gmp-static"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/gmp-6.2.1-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "defc1fdb7a7e03208e61329f6dab3e2828b95cb7114e655628630fafbf1477b1"

URI_gmp = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/gmp-6.2.1-10.el10.x86_64_v2.rpm;name=gmp;unpack=0"
SRC_URI += "${URI_gmp}"
SRC_URI[gmp.sha256sum] = "9fcb66297dac3b2ee396858f111ac44298dcf8121b06edd9ca83f35aae15b294"
RDEPENDS:gmp = " \
 glibc \
"

URI_gmp-c++ = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gmp-c++-6.2.1-10.el10.x86_64_v2.rpm;name=gmp-c++;unpack=0"
SRC_URI += "${URI_gmp-c++}"
SRC_URI[gmp-c++.sha256sum] = "b8f99e1bb42d63ef5f3e34eaba3ee735da41a238875d24b5680b74d43213e663"
RDEPENDS:gmp-c++ = " \
 glibc \
 gmp \
 libgcc \
 libstdc++ \
"

URI_gmp-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gmp-devel-6.2.1-10.el10.x86_64_v2.rpm;name=gmp-devel;unpack=0"
SRC_URI += "${URI_gmp-devel}"
SRC_URI[gmp-devel.sha256sum] = "91c30307f722134e68500a10d51472e0b73065bc980e484a6e34a9a53747c5c4"
RDEPENDS:gmp-devel = " \
 gmp \
 gmp-c++ \
 pkgconf-pkg-config \
 gmp-devel \
"

URI_gmp-static = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/gmp-static-6.2.1-10.el10.x86_64_v2.rpm;name=gmp-static;unpack=0"
SRC_URI += "${URI_gmp-static}"
SRC_URI[gmp-static.sha256sum] = "0ea0035f37a34b1a13cf99e4d4bc6a04f8ed027b469a189f7bed76b3c11e685a"
RDEPENDS:gmp-static = " \
 gmp-devel \
"
