# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gnome-desktop-testing"
PE = "0"
PV = "2018.1"
PR = "21.el10"
PACKAGES = "gnome-desktop-testing"
PROVIDES = "rpm/gnome-desktop-testing"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/gnome-desktop-testing-2018.1-21.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "474ca172029ebf8b6e2a7e77908a55e3fbeefd9643ca0da0651302a47dc9fb46"

URI_gnome-desktop-testing = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/gnome-desktop-testing-2018.1-21.el10.x86_64_v2.rpm;name=gnome-desktop-testing;unpack=0"
SRC_URI += "${URI_gnome-desktop-testing}"
SRC_URI[gnome-desktop-testing.sha256sum] = "67c8a35ca32e2eddbd7115265bd8c28b55fd5894525ebfe4ab2288138cea6af6"
RDEPENDS:gnome-desktop-testing = " \
 glibc \
 libgcc \
 glib2 \
 systemd-libs \
"
