# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gnome-kiosk"
PE = "0"
PV = "47.0"
PR = "9.el10_0"
PACKAGES = "gnome-kiosk gnome-kiosk-script-session gnome-kiosk-search-appliance"
PROVIDES = "rpm/gnome-kiosk rpm/gnome-kiosk-script-session rpm/gnome-kiosk-search-appliance"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/gnome-kiosk-47.0-9.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2da48428741b2c40c5ad30c37da5a976d218586f96c56493d1343ad73c71885c"

URI_gnome-kiosk = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gnome-kiosk-47.0-9.el10_0.x86_64_v2.rpm;name=gnome-kiosk;unpack=0"
SRC_URI += "${URI_gnome-kiosk}"
SRC_URI[gnome-kiosk.sha256sum] = "e5f8bb185ff353a32ad57dd86da3b9335b2eb759cf78d62312616661b2574c58"
RDEPENDS:gnome-kiosk = " \
 systemd-libs \
 libglvnd-gles \
 gsettings-desktop-schemas \
 libgcc \
 gnome-desktop4 \
 gdk-pixbuf2 \
 libX11 \
 mutter \
 glib2 \
 cairo \
 ibus-libs \
 glibc \
 gnome-settings-daemon \
"

URI_gnome-kiosk-script-session = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gnome-kiosk-script-session-47.0-9.el10_0.noarch.rpm;name=gnome-kiosk-script-session;unpack=0"
SRC_URI += "${URI_gnome-kiosk-script-session}"
SRC_URI[gnome-kiosk-script-session.sha256sum] = "cb32e94cd908cf0323354fc0687fda881ddc5e2793e6e64c9040c6bfdbb4fb3f"
RDEPENDS:gnome-kiosk-script-session = " \
 gnome-kiosk \
 gnome-session \
 bash \
"

URI_gnome-kiosk-search-appliance = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gnome-kiosk-search-appliance-47.0-9.el10_0.noarch.rpm;name=gnome-kiosk-search-appliance;unpack=0"
SRC_URI += "${URI_gnome-kiosk-search-appliance}"
SRC_URI[gnome-kiosk-search-appliance.sha256sum] = "11dcec200b647eb58c5a7699434f78ca71296e2b888020eddac8c755b5f778e0"
RDEPENDS:gnome-kiosk-search-appliance = " \
 gnome-kiosk \
 gnome-session \
 flatpak \
"
