# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gnome-devel-docs"
PE = "0"
PV = "40.3"
PR = "12.el10"
PACKAGES = "gnome-devel-docs"
PROVIDES = "rpm/gnome-devel-docs"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/gnome-devel-docs-40.3-12.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "977b5d79ac84666118e99024838d6954f0abd195c7f1a48501f21d2cbdedf1cd"

URI_gnome-devel-docs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gnome-devel-docs-40.3-12.el10.noarch.rpm;name=gnome-devel-docs;unpack=0"
SRC_URI += "${URI_gnome-devel-docs}"
SRC_URI[gnome-devel-docs.sha256sum] = "d29c3b537194a9b982a3971e034548e52f8df1da6cc902b5265635f5122dffd9"
RDEPENDS:gnome-devel-docs = ""
