# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gnome-browser-connector"
PE = "0"
PV = "42.1"
PR = "9.el10"
PACKAGES = "gnome-browser-connector"
PROVIDES = "rpm/gnome-browser-connector"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/gnome-browser-connector-42.1-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "9b4afbb2b4a93b45b50f0d879c153db2802489af67cbb19aa815b22aafd9127c"

URI_gnome-browser-connector = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gnome-browser-connector-42.1-9.el10.x86_64_v2.rpm;name=gnome-browser-connector;unpack=0"
SRC_URI += "${URI_gnome-browser-connector}"
SRC_URI[gnome-browser-connector.sha256sum] = "0d64fdfaad05bac97b8347100a6deac5c73f136f31afccbe9dbe6810a2baf973"
RDEPENDS:gnome-browser-connector = " \
 python3 \
 gnome-shell \
 mozilla-filesystem \
 dbus \
 python3-gobject-base \
 hicolor-icon-theme \
"
