# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gnome-font-viewer"
PE = "0"
PV = "46.0"
PR = "1.el10"
PACKAGES = "gnome-font-viewer"
PROVIDES = "rpm/gnome-font-viewer"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/gnome-font-viewer-46.0-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d15935757534b48ec3d2cf6d0b2ba660339c84e4c84940fab042085cc6b33630"

URI_gnome-font-viewer = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gnome-font-viewer-46.0-1.el10.x86_64_v2.rpm;name=gnome-font-viewer;unpack=0"
SRC_URI += "${URI_gnome-font-viewer}"
SRC_URI[gnome-font-viewer.sha256sum] = "a6f463855ddca680b2da35ac51a2111bf4150eb579587dcbb13cb8fdb5c527a5"
RDEPENDS:gnome-font-viewer = " \
 freetype \
 libgcc \
 harfbuzz \
 fribidi \
 pango \
 fontconfig \
 cairo \
 glib2 \
 graphene \
 glibc \
 gtk4 \
 libadwaita \
"
