# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gnome-shell-extension-dash-to-panel"
PE = "0"
PV = "64"
PR = "1.el10"
PACKAGES = "gnome-shell-extension-dash-to-panel"
PROVIDES = "rpm/gnome-shell-extension-dash-to-panel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/gnome-shell-extension-dash-to-panel-64-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0225ef3c38f14b05e31a42b6aa0bb354654f61e57131a7193dc6d8fd6ed1ea3d"

URI_gnome-shell-extension-dash-to-panel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gnome-shell-extension-dash-to-panel-64-1.el10.noarch.rpm;name=gnome-shell-extension-dash-to-panel;unpack=0"
SRC_URI += "${URI_gnome-shell-extension-dash-to-panel}"
SRC_URI[gnome-shell-extension-dash-to-panel.sha256sum] = "238fb1c88a828ef3556e31cdfe6def4f90963397ee90accf6b94799bcd84a84f"
RDEPENDS:gnome-shell-extension-dash-to-panel = " \
 gnome-shell \
"
