# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "golang-github-openprinting-ipp-usb"
PE = "0"
PV = "0.9.27"
PR = "3.el10_0"
PACKAGES = "ipp-usb golang-github-openprinting-ipp-usb-devel"
PROVIDES = "rpm/ipp-usb rpm/golang-github-openprinting-ipp-usb-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/golang-github-openprinting-ipp-usb-0.9.27-3.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "dc2a7e6e1ae4918afb2a68e34bf1c4c1965a35e6e31455e40c44ae78aaa0fffe"

URI_ipp-usb = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ipp-usb-0.9.27-3.el10_0.x86_64_v2.rpm;name=ipp-usb;unpack=0"
SRC_URI += "${URI_ipp-usb}"
SRC_URI[ipp-usb.sha256sum] = "7af654e7b17f135e83b87519ddf465aef616559bbc83368b961e43c09b3aa6c1"
RDEPENDS:ipp-usb = " \
 systemd \
 systemd-udev \
 avahi-libs \
 bash \
 glibc \
 libusb1 \
"

URI_golang-github-openprinting-ipp-usb-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/golang-github-openprinting-ipp-usb-devel-0.9.27-3.el10_0.noarch.rpm;name=golang-github-openprinting-ipp-usb-devel;unpack=0"
SRC_URI += "${URI_golang-github-openprinting-ipp-usb-devel}"
SRC_URI[golang-github-openprinting-ipp-usb-devel.sha256sum] = "58b9dfd1534ae568223c5b3bc6656331175cfb41acacbba83472495ce7d2615f"
RDEPENDS:golang-github-openprinting-ipp-usb-devel = " \
 libusb1-devel \
 golang-github-openprinting-goipp-devel \
 avahi-devel \
 go-filesystem \
"
