# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gstreamer1-plugins-bad-free"
PE = "0"
PV = "1.24.11"
PR = "2.el10_0"
PACKAGES = "gstreamer1-plugins-bad-free gstreamer1-plugins-bad-free-libs gstreamer1-plugins-bad-free-devel"
PROVIDES = "rpm/gstreamer1-plugins-bad-free rpm/gstreamer1-plugins-bad-free-libs rpm/gstreamer1-plugins-bad-free-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/gstreamer1-plugins-bad-free-1.24.11-2.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d21f04258f5772483895e79a1ac542859374bfed755e9e300ec125750a10cb55"

URI_gstreamer1-plugins-bad-free = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gstreamer1-plugins-bad-free-1.24.11-2.el10_0.x86_64_v2.rpm;name=gstreamer1-plugins-bad-free;unpack=0"
SRC_URI += "${URI_gstreamer1-plugins-bad-free}"
SRC_URI[gstreamer1-plugins-bad-free.sha256sum] = "2b1520ccb8b04914ab28a26e1fb2cd58179ad1cad61628d0f5bc1655c957e5ef"
RDEPENDS:gstreamer1-plugins-bad-free = " \
 liblc3 \
 lcms2 \
 pango \
 libva \
 libdrm \
 libdvdnav \
 libdvdread \
 json-glib \
 libstdc++ \
 cairo \
 fdk-aac-free \
 libusb1 \
 soundtouch \
 libwayland-client \
 librsvg2 \
 openssl-libs \
 libgcc \
 libxml2 \
 libwebp \
 libgudev \
 vulkan-loader \
 opus \
 libsndfile \
 orc \
 bzip2-libs \
 gsm \
 gstreamer1 \
 webrtc-audio-processing \
 gstreamer1-plugins-bad-free-libs \
 gstreamer1-plugins-base \
 libsrtp \
 glib2 \
 gtk3 \
 glibc \
"

URI_gstreamer1-plugins-bad-free-libs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gstreamer1-plugins-bad-free-libs-1.24.11-2.el10_0.x86_64_v2.rpm;name=gstreamer1-plugins-bad-free-libs;unpack=0"
SRC_URI += "${URI_gstreamer1-plugins-bad-free-libs}"
SRC_URI[gstreamer1-plugins-bad-free-libs.sha256sum] = "64d956e158237037209fd0e2b28f048069bde1e49a59b3c3f5d279ff9593f4ba"
RDEPENDS:gstreamer1-plugins-bad-free-libs = " \
 libwayland-client \
 gstreamer1 \
 libgcc \
 gstreamer1-plugins-base \
 libstdc++ \
 glib2 \
 glibc \
 libva \
 vulkan-loader \
 libdrm \
"

URI_gstreamer1-plugins-bad-free-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/gstreamer1-plugins-bad-free-devel-1.24.11-2.el10_0.x86_64_v2.rpm;name=gstreamer1-plugins-bad-free-devel;unpack=0"
SRC_URI += "${URI_gstreamer1-plugins-bad-free-devel}"
SRC_URI[gstreamer1-plugins-bad-free-devel.sha256sum] = "44f166912884e21d554958be772fd54120a2c5fe042be1a34c05c67891a6b531"
RDEPENDS:gstreamer1-plugins-bad-free-devel = " \
 wayland-devel \
 glib2-devel \
 gstreamer1-plugins-bad-free-devel \
 gstreamer1-devel \
 gstreamer1-plugins-bad-free \
 gstreamer1-plugins-bad-free-libs \
 pkgconf-pkg-config \
 gstreamer1-plugins-base-devel \
 libva-devel \
 vulkan-loader-devel \
 libdrm-devel \
"
