# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gstreamer1-plugins-base"
PE = "0"
PV = "1.24.11"
PR = "1.el10"
PACKAGES = "gstreamer1-plugins-base gstreamer1-plugins-base-devel gstreamer1-plugins-base-tools"
PROVIDES = "rpm/gstreamer1-plugins-base rpm/gstreamer1-plugins-base-devel rpm/gstreamer1-plugins-base-tools"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/gstreamer1-plugins-base-1.24.11-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f99e44a7de941cee74565990e6343579f42996746e0b74313966aa95ebb0914f"

URI_gstreamer1-plugins-base = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gstreamer1-plugins-base-1.24.11-1.el10.x86_64_v2.rpm;name=gstreamer1-plugins-base;unpack=0"
SRC_URI += "${URI_gstreamer1-plugins-base}"
SRC_URI[gstreamer1-plugins-base.sha256sum] = "8e8e9a0ecf6fe722b1bc3cb65f87110bcaf0c479a6e57a5cdc1d4692c757ff31"
RDEPENDS:gstreamer1-plugins-base = " \
 libpng \
 pango \
 libX11 \
 libX11-xcb \
 libtheora \
 libdrm \
 libXext \
 libogg \
 libXi \
 cairo \
 libXv \
 alsa-lib \
 libvorbis \
 zlib-ng-compat \
 libwayland-client \
 libglvnd-egl \
 libwayland-cursor \
 libwayland-egl \
 libglvnd-glx \
 libgudev \
 libxcb \
 mesa-libgbm \
 graphene \
 opus \
 orc \
 gstreamer1 \
 glib2 \
 glibc \
 libjpeg-turbo \
 iso-codes \
"

URI_gstreamer1-plugins-base-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gstreamer1-plugins-base-devel-1.24.11-1.el10.x86_64_v2.rpm;name=gstreamer1-plugins-base-devel;unpack=0"
SRC_URI += "${URI_gstreamer1-plugins-base-devel}"
SRC_URI[gstreamer1-plugins-base-devel.sha256sum] = "5a531cbee08c7afe1e3e8ffe09a5bbaf740946e3965e8eb473e94c08e68ff627"
RDEPENDS:gstreamer1-plugins-base-devel = " \
 orc-devel \
 wayland-devel \
 glib2-devel \
 libglvnd-devel \
 gstreamer1-devel \
 zlib-ng-compat-devel \
 gstreamer1-plugins-base \
 pkgconf-pkg-config \
 gstreamer1-plugins-base-devel \
 libX11-devel \
 libgudev-devel \
 mesa-libgbm-devel \
 libdrm-devel \
"

URI_gstreamer1-plugins-base-tools = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/gstreamer1-plugins-base-tools-1.24.11-1.el10.x86_64_v2.rpm;name=gstreamer1-plugins-base-tools;unpack=0"
SRC_URI += "${URI_gstreamer1-plugins-base-tools}"
SRC_URI[gstreamer1-plugins-base-tools.sha256sum] = "0dd76e05926303e979f9ddc598b081530ab1bc0f0e943a0a4f555b42e750ba1b"
RDEPENDS:gstreamer1-plugins-base-tools = " \
 glibc \
 gstreamer1-plugins-base \
 glib2 \
 gstreamer1 \
"
