# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "guava"
PE = "0"
PV = "32.1.3"
PR = "6.el10"
PACKAGES = "guava guava-javadoc guava-testlib"
PROVIDES = "rpm/guava rpm/guava-javadoc rpm/guava-testlib"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/guava-32.1.3-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "badbb3a87bfc66e87d77c9afbb8bd306a8e72917b295b91aae1f70cc4ba16e02"

URI_guava = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/guava-32.1.3-6.el10.noarch.rpm;name=guava;unpack=0"
SRC_URI += "${URI_guava}"
SRC_URI[guava.sha256sum] = "4aa6bb46a70481359aba12ff75d715210d9affed6082c9aa765c4ce5936c887d"
RDEPENDS:guava = " \
 jsr-305 \
 javapackages-filesystem \
"

URI_guava-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/guava-javadoc-32.1.3-6.el10.noarch.rpm;name=guava-javadoc;unpack=0"
SRC_URI += "${URI_guava-javadoc}"
SRC_URI[guava-javadoc.sha256sum] = "5a8bd58d84b2181863608024203c9d875d80fd6817668753a56a556cbb0df9de"
RDEPENDS:guava-javadoc = " \
 javapackages-filesystem \
"

URI_guava-testlib = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/guava-testlib-32.1.3-6.el10.noarch.rpm;name=guava-testlib;unpack=0"
SRC_URI += "${URI_guava-testlib}"
SRC_URI[guava-testlib.sha256sum] = "400d5c041b22b6353cbbde7990126eacae8c5dba2f68d4295171a955c2769c91"
RDEPENDS:guava-testlib = " \
 jsr-305 \
 junit \
 javapackages-filesystem \
 guava \
"
