# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "guestfs-tools"
PE = "0"
PV = "1.52.2"
PR = "2.el10.alma.1"
PACKAGES = "guestfs-tools virt-win-reg guestfs-tools-bash-completion guestfs-tools-man-pages-ja guestfs-tools-man-pages-uk"
PROVIDES = "rpm/guestfs-tools rpm/virt-win-reg rpm/guestfs-tools-bash-completion rpm/guestfs-tools-man-pages-ja rpm/guestfs-tools-man-pages-uk"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/guestfs-tools-1.52.2-2.el10.alma.1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "df2c13a73e27afe3deb770d64910d416e66650adb93dd106714cf1698c895f13"

URI_guestfs-tools = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/guestfs-tools-1.52.2-2.el10.alma.1.x86_64_v2.rpm;name=guestfs-tools;unpack=0"
SRC_URI += "${URI_guestfs-tools}"
SRC_URI[guestfs-tools.sha256sum] = "19f39719058d4c6a507c7736f6e43e99dae6fd8eb59abda864b09d79996ae037"
RDEPENDS:guestfs-tools = " \
 gnupg2 \
 libxcrypt \
 libosinfo \
 libgcc \
 json-c \
 libxml2 \
 curl \
 qemu-img \
 ncurses-libs \
 glib2 \
 pcre2 \
 libguestfs \
 glibc \
 libvirt-libs \
 xz \
 xz-libs \
"

URI_virt-win-reg = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/virt-win-reg-1.52.2-2.el10.alma.1.noarch.rpm;name=virt-win-reg;unpack=0"
SRC_URI += "${URI_virt-win-reg}"
SRC_URI[virt-win-reg.sha256sum] = "e2a4a6ea6d495048ed8cd7853ca67b9aea097e5d8126f9f03e57fc154348b5e1"
RDEPENDS:virt-win-reg = " \
 perl-libintl-perl \
 perl-libs \
 perl-Getopt-Long \
 perl-File-Basename \
 perl-Sys-Guestfs \
 perl-hivex \
 perl-interpreter \
 perl-File-Temp \
 perl-Pod-Usage \
"

URI_guestfs-tools-bash-completion = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/guestfs-tools-bash-completion-1.52.2-2.el10.alma.1.noarch.rpm;name=guestfs-tools-bash-completion;unpack=0"
SRC_URI += "${URI_guestfs-tools-bash-completion}"
SRC_URI[guestfs-tools-bash-completion.sha256sum] = "b2482c25eea1a432de18f961f8b05bf25f998f4c19058df5230670b57f1a8584"
RDEPENDS:guestfs-tools-bash-completion = " \
 bash-completion \
 guestfs-tools \
"

URI_guestfs-tools-man-pages-ja = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/guestfs-tools-man-pages-ja-1.52.2-2.el10.alma.1.noarch.rpm;name=guestfs-tools-man-pages-ja;unpack=0"
SRC_URI += "${URI_guestfs-tools-man-pages-ja}"
SRC_URI[guestfs-tools-man-pages-ja.sha256sum] = "aac7632bc1b21bee17cd8271bba538e7495224356fa901786a02ab5fcbf8ad98"
RDEPENDS:guestfs-tools-man-pages-ja = " \
 guestfs-tools \
"

URI_guestfs-tools-man-pages-uk = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/guestfs-tools-man-pages-uk-1.52.2-2.el10.alma.1.noarch.rpm;name=guestfs-tools-man-pages-uk;unpack=0"
SRC_URI += "${URI_guestfs-tools-man-pages-uk}"
SRC_URI[guestfs-tools-man-pages-uk.sha256sum] = "37b3a9b852fd875d54e019c64f92c56fd872098cf46a6d86dcb1524ba88a1c54"
RDEPENDS:guestfs-tools-man-pages-uk = " \
 guestfs-tools \
"
