# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "gzip"
PE = "0"
PV = "1.13"
PR = "3.el10"
PACKAGES = "gzip"
PROVIDES = "rpm/gzip"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/gzip-1.13-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "04823d5405544406fae47cb6baa5f42cfb44b94767c6ab706df36d77725de7f1"

URI_gzip = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/gzip-1.13-3.el10.x86_64_v2.rpm;name=gzip;unpack=0"
SRC_URI += "${URI_gzip}"
SRC_URI[gzip.sha256sum] = "08586d4af627dbb3fc8aaad15e192be3f8a9eb677c3cb7f51a56a204f4822e07"
RDEPENDS:gzip = " \
 glibc \
 coreutils \
 bash \
"
