# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "haproxy"
PE = "0"
PV = "3.0.5"
PR = "4.el10"
PACKAGES = "haproxy"
PROVIDES = "rpm/haproxy"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/haproxy-3.0.5-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a257d02f6cf2fa571e81f6ca0c0d43feea26d507ef593c08e6d72bb9dbc9d737"

URI_haproxy = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/haproxy-3.0.5-4.el10.x86_64_v2.rpm;name=haproxy;unpack=0"
SRC_URI += "${URI_haproxy}"
SRC_URI[haproxy.sha256sum] = "8a6e279236989eb74496998db1560662b228610418a757d03e077c60dcc604b3"
RDEPENDS:haproxy = " \
 shadow-utils \
 systemd \
 lua-libs \
 libxcrypt \
 openssl-libs \
 bash \
 pcre2 \
 glibc \
"
