# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "help2man"
PE = "0"
PV = "1.49.3"
PR = "7.el10"
PACKAGES = "help2man"
PROVIDES = "rpm/help2man"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/help2man-1.49.3-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "3337be1d4e91af105a8485490b360802b435d45b55f47c03ed81a38b68ad1ec9"

URI_help2man = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/help2man-1.49.3-7.el10.noarch.rpm;name=help2man;unpack=0"
SRC_URI += "${URI_help2man}"
SRC_URI[help2man.sha256sum] = "710c2c5f4fcb96d6e29d182e2eaf9edf341e31c5f683ab406d0614be502337b3"
RDEPENDS:help2man = " \
 perl-libs \
 perl-Text-ParseWords \
 perl-Text-Tabs+Wrap \
 perl-Getopt-Long \
 perl-POSIX \
 perl-interpreter \
"
