# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "highlight"
PE = "0"
PV = "4.8"
PR = "4.el10"
PACKAGES = "highlight"
PROVIDES = "rpm/highlight"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/highlight-4.8-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "de4659798d479b9a70e7ab5e482311a83da5f819cf8f745293726ca9362447ee"

URI_highlight = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/highlight-4.8-4.el10.x86_64_v2.rpm;name=highlight;unpack=0"
SRC_URI += "${URI_highlight}"
SRC_URI[highlight.sha256sum] = "b8c07e99504b9a82cd8341a8d0cb629a04ac9fe52600fb4459181e744823167c"
RDEPENDS:highlight = " \
 lua-libs \
 libgcc \
 libstdc++ \
 bash \
 glibc \
"
