# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hostapd"
PE = "0"
PV = "2.11"
PR = "2.el10"
PACKAGES = "hostapd hostapd-logwatch"
PROVIDES = "rpm/hostapd rpm/hostapd-logwatch"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hostapd-2.11-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f452754062ab54acf58a65bab753390c01c4eec2cd1cde6c05c1b9c11014b4e6"

URI_hostapd = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hostapd-2.11-2.el10.x86_64_v2.rpm;name=hostapd;unpack=0"
SRC_URI += "${URI_hostapd}"
SRC_URI[hostapd.sha256sum] = "8d3c715826cff17fb700e9c2d2e76bcf5b096326e1a044a86ed2f2d0691f66f9"
RDEPENDS:hostapd = " \
 systemd \
 openssl-libs \
 libnl3 \
 bash \
 glibc \
"

URI_hostapd-logwatch = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/hostapd-logwatch-2.11-2.el10.x86_64_v2.rpm;name=hostapd-logwatch;unpack=0"
SRC_URI += "${URI_hostapd-logwatch}"
SRC_URI[hostapd-logwatch.sha256sum] = "6a7cacf843de3422adfe93a7ab4b8da11bbf80ea51d0aea31a62559261d850d0"
RDEPENDS:hostapd-logwatch = " \
 perl-interpreter \
 perl-libs \
 hostapd \
 logwatch \
"
