# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hspell"
PE = "0"
PV = "1.4"
PR = "23.el10"
PACKAGES = "hunspell-he hspell hspell-devel"
PROVIDES = "rpm/hunspell-he rpm/hspell rpm/hspell-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hspell-1.4-23.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5daf14c6e1cf74ff6846e4a54a5f68e7f673a8d5c7a7bdd309f82bfe7abade26"

URI_hunspell-he = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-he-1.4-23.el10.x86_64_v2.rpm;name=hunspell-he;unpack=0"
SRC_URI += "${URI_hunspell-he}"
SRC_URI[hunspell-he.sha256sum] = "4e646d7fd7a5b6cacaf8115ea413dad8d295e978f025feeda674947d1db6ae50"
RDEPENDS:hunspell-he = " \
 hunspell \
"

URI_hspell = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/hspell-1.4-23.el10.x86_64_v2.rpm;name=hspell;unpack=0"
SRC_URI += "${URI_hspell}"
SRC_URI[hspell.sha256sum] = "d5e4c4fb2229b34d21dae8ca99892f25917011194bf212c5a9aaddaa0906fd96"
RDEPENDS:hspell = " \
 zlib-ng-compat \
 perl-libs \
 perl-IO \
 perl-Getopt-Long \
 perl-IPC-Open3 \
 glibc \
 perl-interpreter \
"

URI_hspell-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/hspell-devel-1.4-23.el10.x86_64_v2.rpm;name=hspell-devel;unpack=0"
SRC_URI += "${URI_hspell-devel}"
SRC_URI[hspell-devel.sha256sum] = "72cb1edc2b43444627d8ae54b9a9a196829000666fe308439ca2ae323e3d4b42"
RDEPENDS:hspell-devel = " \
 hspell \
"
