# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "httpd"
PE = "0"
PV = "2.4.63"
PR = "1.el10_0.2"
PACKAGES = "httpd httpd-core httpd-devel httpd-filesystem httpd-manual httpd-tools mod_ldap mod_lua mod_proxy_html mod_session mod_ssl"
PROVIDES = "rpm/httpd rpm/httpd-core rpm/httpd-devel rpm/httpd-filesystem rpm/httpd-manual rpm/httpd-tools rpm/mod_ldap rpm/mod_lua rpm/mod_proxy_html rpm/mod_session rpm/mod_ssl"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/httpd-2.4.63-1.el10_0.2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5395bdb87639831eb3b4ba3aa9eb7c9ace1013d19b56ae0c2da8bc20181302f5"

URI_httpd = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/httpd-2.4.63-1.el10_0.2.x86_64_v2.rpm;name=httpd;unpack=0"
SRC_URI += "${URI_httpd}"
SRC_URI[httpd.sha256sum] = "dc12bb10aff17309b71f303fdd686417315a3f41806312074af95aad8cf33c3d"
RDEPENDS:httpd = " \
 systemd \
 systemd-libs \
 httpd-core \
 libbrotli \
 bash \
 glibc \
 libselinux \
 almalinux-logos-httpd \
"

URI_httpd-core = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/httpd-core-2.4.63-1.el10_0.2.x86_64_v2.rpm;name=httpd-core;unpack=0"
SRC_URI += "${URI_httpd-core}"
SRC_URI[httpd-core.sha256sum] = "ae66ad09ac97832fb402c9b8c1c261e6d32ee3cd798161e3233365fd77324a05"
RDEPENDS:httpd-core = " \
 zlib-ng-compat \
 httpd-filesystem \
 apr \
 mailcap \
 apr-util \
 httpd-tools \
 apr-util-lmdb \
 bash \
 pcre2 \
 glibc \
"

URI_httpd-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/httpd-devel-2.4.63-1.el10_0.2.x86_64_v2.rpm;name=httpd-devel;unpack=0"
SRC_URI += "${URI_httpd-devel}"
SRC_URI[httpd-devel.sha256sum] = "5c5e7f3c32d039d34b0c18e5266036e5063b9d24deccaccec6bc5e4a7390d176"
RDEPENDS:httpd-devel = " \
 libtool \
 perl-libs \
 httpd-core \
 pkgconf-pkg-config \
 apr-devel \
 apr-util-devel \
 bash \
 perl-interpreter \
"

URI_httpd-filesystem = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/httpd-filesystem-2.4.63-1.el10_0.2.noarch.rpm;name=httpd-filesystem;unpack=0"
SRC_URI += "${URI_httpd-filesystem}"
SRC_URI[httpd-filesystem.sha256sum] = "23f6f8235a3f05108a4d571c2d97070cde904bc10c499c19721e36118a0b3cb5"
RDEPENDS:httpd-filesystem = " \
 shadow-utils \
 bash \
"

URI_httpd-manual = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/httpd-manual-2.4.63-1.el10_0.2.noarch.rpm;name=httpd-manual;unpack=0"
SRC_URI += "${URI_httpd-manual}"
SRC_URI[httpd-manual.sha256sum] = "fa129998bfad24b227f00316175e1a55119eb8a181278169fd59b9353fd8be7f"
RDEPENDS:httpd-manual = " \
 httpd-core \
"

URI_httpd-tools = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/httpd-tools-2.4.63-1.el10_0.2.x86_64_v2.rpm;name=httpd-tools;unpack=0"
SRC_URI += "${URI_httpd-tools}"
SRC_URI[httpd-tools.sha256sum] = "8c2b55d889838265ffd42fe66a3dc3927c6d6e7d5be9277621cf7d0644270ae6"
RDEPENDS:httpd-tools = " \
 libxcrypt \
 openssl-libs \
 apr \
 apr-util \
 glibc \
"

URI_mod_ldap = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/mod_ldap-2.4.63-1.el10_0.2.x86_64_v2.rpm;name=mod_ldap;unpack=0"
SRC_URI += "${URI_mod_ldap}"
SRC_URI[mod_ldap.sha256sum] = "edc7ecbc4a98d41fd1a78992c6ba73777031de6a12b9b0d36468b8e1c29bd54e"
RDEPENDS:mod_ldap = " \
 glibc \
 apr-util-ldap \
 openldap \
 httpd-core \
"

URI_mod_lua = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/mod_lua-2.4.63-1.el10_0.2.x86_64_v2.rpm;name=mod_lua;unpack=0"
SRC_URI += "${URI_mod_lua}"
SRC_URI[mod_lua.sha256sum] = "5b1b17953b65404dbc77591967c0b058af5f153cefe3c3c56c6bcc7177cc89a2"
RDEPENDS:mod_lua = " \
 glibc \
 libxcrypt \
 lua-libs \
 httpd-core \
"

URI_mod_proxy_html = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/mod_proxy_html-2.4.63-1.el10_0.2.x86_64_v2.rpm;name=mod_proxy_html;unpack=0"
SRC_URI += "${URI_mod_proxy_html}"
SRC_URI[mod_proxy_html.sha256sum] = "21bf95fdbd9f660382be50edc4658a74d8c148de6f0d61df8905e577bd159c7e"
RDEPENDS:mod_proxy_html = " \
 glibc \
 libxml2 \
 httpd-core \
"

URI_mod_session = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/mod_session-2.4.63-1.el10_0.2.x86_64_v2.rpm;name=mod_session;unpack=0"
SRC_URI += "${URI_mod_session}"
SRC_URI[mod_session.sha256sum] = "e753f9dece405168f7e570a5d3576a8f5fffdf4e7d594539d6c727718c07a215"
RDEPENDS:mod_session = " \
 glibc \
 httpd-core \
"

URI_mod_ssl = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/mod_ssl-2.4.63-1.el10_0.2.x86_64_v2.rpm;name=mod_ssl;unpack=0"
SRC_URI += "${URI_mod_ssl}"
SRC_URI[mod_ssl.sha256sum] = "502de857d78e7178f768091e9b489bf3f736fe01ec107f2facae9106191475a9"
RDEPENDS:mod_ssl = " \
 sscg \
 httpd-core \
 httpd-filesystem \
 openssl-libs \
 hostname \
 bash \
 glibc \
"
