# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-sk"
PE = "1"
PV = "0.20110228"
PR = "30.el10"
PACKAGES = "hunspell-sk"
PROVIDES = "rpm/hunspell-sk"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-sk-0.20110228-30.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "49d98716a0f885cf69ffd4cf15599e746bd82c3944789769b14d92c376d3bde4"

URI_hunspell-sk = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-sk-0.20110228-30.el10.noarch.rpm;name=hunspell-sk;unpack=0"
SRC_URI += "${URI_hunspell-sk}"
SRC_URI[hunspell-sk.sha256sum] = "2f19dbe20865d29144f44dac7c54655988fe572eadbb35c9b66a98c3f82374fb"
RDEPENDS:hunspell-sk = " \
 hunspell \
"
