# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-eu"
PE = "0"
PV = "5.1"
PR = "13.el10"
PACKAGES = "hunspell-eu"
PROVIDES = "rpm/hunspell-eu"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-eu-5.1-13.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a807e95218496c8ecbee92ca6c33516d235b79f5af764e1304ccaa81f9973408"

URI_hunspell-eu = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-eu-5.1-13.el10.noarch.rpm;name=hunspell-eu;unpack=0"
SRC_URI += "${URI_hunspell-eu}"
SRC_URI[hunspell-eu.sha256sum] = "18b0845e067ec7efa97ab1798b8150ff82ab68b2d509d6a5890194e7d9380334"
RDEPENDS:hunspell-eu = " \
 hunspell-filesystem \
"
