# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-de"
PE = "0"
PV = "20240224"
PR = "1.el10"
PACKAGES = "hunspell-de"
PROVIDES = "rpm/hunspell-de"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-de-20240224-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f0317f2cc8a23ba9c54c2f14d2820895153afd508347fed649826b3837da0b00"

URI_hunspell-de = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-de-20240224-1.el10.noarch.rpm;name=hunspell-de;unpack=0"
SRC_URI += "${URI_hunspell-de}"
SRC_URI[hunspell-de.sha256sum] = "46233ae8e1ccee7430d79b21da9b4c7967ab0f0f7a352faba46ab94071ba7b28"
RDEPENDS:hunspell-de = " \
 hunspell-filesystem \
"
