# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-haw"
PE = "0"
PV = "0.03"
PR = "18.el10"
PACKAGES = "hunspell-haw"
PROVIDES = "rpm/hunspell-haw"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-haw-0.03-18.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "bd65f43226356e4c749cc71fe47f523438a9213e30dc78324db6a40c332a31b7"

URI_hunspell-haw = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-haw-0.03-18.el10.noarch.rpm;name=hunspell-haw;unpack=0"
SRC_URI += "${URI_hunspell-haw}"
SRC_URI[hunspell-haw.sha256sum] = "285b14eea852c9cc186eef3fb757292deb56e0b7d9de1a20d202b9e9b9e7c819"
RDEPENDS:hunspell-haw = " \
 hunspell-filesystem \
"
