# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-fy"
PE = "0"
PV = "3.0.0"
PR = "19.el10"
PACKAGES = "hunspell-fy"
PROVIDES = "rpm/hunspell-fy"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-fy-3.0.0-19.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "20ab13a8afb178d7a6f1e01379ef6d0176d54ed8dbc495d845623a5104bff05e"

URI_hunspell-fy = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-fy-3.0.0-19.el10.noarch.rpm;name=hunspell-fy;unpack=0"
SRC_URI += "${URI_hunspell-fy}"
SRC_URI[hunspell-fy.sha256sum] = "8f57143dd92ce03874d8dd53359c39b631be849ee3fcdc985ceade0e959790db"
RDEPENDS:hunspell-fy = " \
 hunspell-filesystem \
"
