# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-gv"
PE = "0"
PV = "0.20040505"
PR = "35.el10"
PACKAGES = "hunspell-gv"
PROVIDES = "rpm/hunspell-gv"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-gv-0.20040505-35.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "3bce0ef9ac5b9cdbbeb46c25d951c4a273473b86633b45e8b136579652d38f2c"

URI_hunspell-gv = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-gv-0.20040505-35.el10.noarch.rpm;name=hunspell-gv;unpack=0"
SRC_URI += "${URI_hunspell-gv}"
SRC_URI[hunspell-gv.sha256sum] = "e7dbe2f77596d9af01f52f2d8bddbc17678e0017130e33568dbe1874532f3b74"
RDEPENDS:hunspell-gv = " \
 hunspell-filesystem \
"
