# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-hu"
PE = "0"
PV = "1.6.1"
PR = "30.el10"
PACKAGES = "hunspell-hu"
PROVIDES = "rpm/hunspell-hu"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-hu-1.6.1-30.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2cd7cae858c2ba8aefa2acfd4851a5b35ea19f144067276a4199af01dac53249"

URI_hunspell-hu = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-hu-1.6.1-30.el10.noarch.rpm;name=hunspell-hu;unpack=0"
SRC_URI += "${URI_hunspell-hu}"
SRC_URI[hunspell-hu.sha256sum] = "1b1a9808c539068ea5ddacacc3feef63fb573ca80b3f02ac2e4dd86bfd7ee789"
RDEPENDS:hunspell-hu = " \
 hunspell-filesystem \
"
