# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-fo"
PE = "0"
PV = "0.4.2"
PR = "25.el10"
PACKAGES = "hunspell-fo"
PROVIDES = "rpm/hunspell-fo"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-fo-0.4.2-25.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "015282b75045a127ffedea75a02095edf237bcd4555187bba2ecf239842048c1"

URI_hunspell-fo = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-fo-0.4.2-25.el10.noarch.rpm;name=hunspell-fo;unpack=0"
SRC_URI += "${URI_hunspell-fo}"
SRC_URI[hunspell-fo.sha256sum] = "06056f5843d73f1d3c3ec58300f9268cbfc2ab6222b823bc7b70e36018ae257f"
RDEPENDS:hunspell-fo = " \
 hunspell-filesystem \
"
