# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-fj"
PE = "0"
PV = "1.2"
PR = "32.el10"
PACKAGES = "hunspell-fj"
PROVIDES = "rpm/hunspell-fj"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-fj-1.2-32.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "455b3e3bfcba20d4d077bd281c1036189dc2cc0494448ec3c5376670e998971f"

URI_hunspell-fj = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-fj-1.2-32.el10.noarch.rpm;name=hunspell-fj;unpack=0"
SRC_URI += "${URI_hunspell-fj}"
SRC_URI[hunspell-fj.sha256sum] = "19ec2c3c74f45738ed8ca2912d38e5090512f30134e59d9a456da48c9a5bb560"
RDEPENDS:hunspell-fj = " \
 hunspell-filesystem \
"
