# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-te"
PE = "1"
PV = "1.0.0"
PR = "26.el10"
PACKAGES = "hunspell-te"
PROVIDES = "rpm/hunspell-te"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-te-1.0.0-26.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "8cb5b6d7fb0bec728f053327c93bbd94165aba317f143f47982b0fb3ef4d2cd2"

URI_hunspell-te = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-te-1.0.0-26.el10.noarch.rpm;name=hunspell-te;unpack=0"
SRC_URI += "${URI_hunspell-te}"
SRC_URI[hunspell-te.sha256sum] = "93dac4474e5323cb69bb8827e4f08e7d4110c8d139c5762a158922ef1273b9a5"
RDEPENDS:hunspell-te = " \
 hunspell \
"
