# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-tr"
PE = "0"
PV = "1.1.0"
PR = "9.el10"
PACKAGES = "hunspell-tr"
PROVIDES = "rpm/hunspell-tr"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-tr-1.1.0-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "66be106f33be59988872fdc48e98ff12d1e7eb5cecb46ad3c00855fc5ba56247"

URI_hunspell-tr = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-tr-1.1.0-9.el10.noarch.rpm;name=hunspell-tr;unpack=0"
SRC_URI += "${URI_hunspell-tr}"
SRC_URI[hunspell-tr.sha256sum] = "23c08db707525ccc369fe0a08a8a0a46fb6f53a75480cf5f504edb170239a8c1"
RDEPENDS:hunspell-tr = " \
 hunspell-filesystem \
"
