# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-ln"
PE = "0"
PV = "0.02"
PR = "31.el10"
PACKAGES = "hunspell-ln"
PROVIDES = "rpm/hunspell-ln"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-ln-0.02-31.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "3d5df97519af7185ffe8c1d1558051cef7386be23f5489f4dae6a65e6e17d1dd"

URI_hunspell-ln = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-ln-0.02-31.el10.noarch.rpm;name=hunspell-ln;unpack=0"
SRC_URI += "${URI_hunspell-ln}"
SRC_URI[hunspell-ln.sha256sum] = "9b2f3d425068793a023185526a3230891a1d04a9c2536a7a3f6b8dd3af6af4a2"
RDEPENDS:hunspell-ln = " \
 hunspell-filesystem \
"
