# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-pt"
PE = "0"
PV = "0.20131030"
PR = "15.el10"
PACKAGES = "hunspell-pt hunspell-pt-BR"
PROVIDES = "rpm/hunspell-pt rpm/hunspell-pt-BR"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-pt-0.20131030-15.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e85306bd74d47a50eec07beda4016d4cd14ae4623a8f3136a7ceb495da2d3af3"

URI_hunspell-pt = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-pt-0.20131030-15.el10.noarch.rpm;name=hunspell-pt;unpack=0"
SRC_URI += "${URI_hunspell-pt}"
SRC_URI[hunspell-pt.sha256sum] = "15df3329b073e9a6656f41fb51aeab20dd5df092537c69661cce95e619a52381"
RDEPENDS:hunspell-pt = " \
 hunspell \
"

URI_hunspell-pt-BR = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-pt-BR-0.20131030-15.el10.noarch.rpm;name=hunspell-pt-BR;unpack=0"
SRC_URI += "${URI_hunspell-pt-BR}"
SRC_URI[hunspell-pt-BR.sha256sum] = "ed3920e4ecf667aa8ede27c708413194f348d665b24078db90ddb157a02996aa"
RDEPENDS:hunspell-pt-BR = " \
 hunspell \
"
