# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-tn"
PE = "0"
PV = "0.20150904"
PR = "18.el10"
PACKAGES = "hunspell-tn"
PROVIDES = "rpm/hunspell-tn"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-tn-0.20150904-18.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b3bbc24ee3e961011103c563c1e1e3bef3d147b107063d6623acd2ab779f11dd"

URI_hunspell-tn = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-tn-0.20150904-18.el10.noarch.rpm;name=hunspell-tn;unpack=0"
SRC_URI += "${URI_hunspell-tn}"
SRC_URI[hunspell-tn.sha256sum] = "3c91c07f764cab8d4e8b83b5294d1da4a310dd07e9040ac09492c4d133d7c23b"
RDEPENDS:hunspell-tn = " \
 hunspell-filesystem \
"
