# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-be"
PE = "0"
PV = "1.1"
PR = "32.el10"
PACKAGES = "hunspell-be hyphen-be"
PROVIDES = "rpm/hunspell-be rpm/hyphen-be"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-be-1.1-32.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "69ed0f902f1a70235d6d85d94e76d78cf34de0d71aca7b86bbd38a8d6847e53f"

URI_hunspell-be = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-be-1.1-32.el10.noarch.rpm;name=hunspell-be;unpack=0"
SRC_URI += "${URI_hunspell-be}"
SRC_URI[hunspell-be.sha256sum] = "be844094539ffd39ca192cd9beb6d1e35de5103fb0b37173320fabb6196b52ad"
RDEPENDS:hunspell-be = " \
 hunspell-filesystem \
"

URI_hyphen-be = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-be-1.1-32.el10.noarch.rpm;name=hyphen-be;unpack=0"
SRC_URI += "${URI_hyphen-be}"
SRC_URI[hyphen-be.sha256sum] = "597381f368919cad13e4d8f17f1636f002e60885479e8c13cc839b0666617c4d"
RDEPENDS:hyphen-be = " \
 hyphen \
"
