# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-th"
PE = "0"
PV = "0.20061212"
PR = "34.el10"
PACKAGES = "hunspell-th"
PROVIDES = "rpm/hunspell-th"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-th-0.20061212-34.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "55a67cef6e78505f6b9454c86aa21e382d63bebf7c4ad76d11c20a89c802ab39"

URI_hunspell-th = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-th-0.20061212-34.el10.noarch.rpm;name=hunspell-th;unpack=0"
SRC_URI += "${URI_hunspell-th}"
SRC_URI[hunspell-th.sha256sum] = "5b56d4dd6a795f337425003e40d63c5ce3316628ccdd9e818d26f52631414f2e"
RDEPENDS:hunspell-th = " \
 hunspell-filesystem \
"
