# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-ber"
PE = "0"
PV = "0.20080210"
PR = "32.el10"
PACKAGES = "hunspell-ber"
PROVIDES = "rpm/hunspell-ber"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-ber-0.20080210-32.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "96f72b49ea0f54ae15c7f4aae9855a9241eed7a4ef90e9e27167a63ec0d8681d"

URI_hunspell-ber = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-ber-0.20080210-32.el10.noarch.rpm;name=hunspell-ber;unpack=0"
SRC_URI += "${URI_hunspell-ber}"
SRC_URI[hunspell-ber.sha256sum] = "882c9ae648b08366d7995303e26722b80ff185e9c1bb3615226c77c036f2097f"
RDEPENDS:hunspell-ber = " \
 hunspell-filesystem \
"
