# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hunspell-smj"
PE = "0"
PV = "1.0"
PR = "0.32.beta7.el10"
PACKAGES = "hunspell-smj"
PROVIDES = "rpm/hunspell-smj"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hunspell-smj-1.0-0.32.beta7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c35e0085bcb2f7cf80e90ef4612b87f5d627b46ee4a8874b03b9b6becd527044"

URI_hunspell-smj = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hunspell-smj-1.0-0.32.beta7.el10.noarch.rpm;name=hunspell-smj;unpack=0"
SRC_URI += "${URI_hunspell-smj}"
SRC_URI[hunspell-smj.sha256sum] = "00a56f1946c38ff7132849686cf48ee6f9616eb259381050ab892a6be56682c1"
RDEPENDS:hunspell-smj = " \
 hunspell \
"
