# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-fa"
PE = "0"
PV = "0.20130404"
PR = "25.el10"
PACKAGES = "hyphen-fa"
PROVIDES = "rpm/hyphen-fa"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-fa-0.20130404-25.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c8f374f64cc90bedeff8a8549474152f2ee6569ad72f87fceb481168afd60c21"

URI_hyphen-fa = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-fa-0.20130404-25.el10.noarch.rpm;name=hyphen-fa;unpack=0"
SRC_URI += "${URI_hyphen-fa}"
SRC_URI[hyphen-fa.sha256sum] = "8a33e3f5b8d028298ea8df697978413a940f442b64bb78d10e0e404c8409d825"
RDEPENDS:hyphen-fa = " \
 hyphen \
"
