# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-pa"
PE = "1"
PV = "0.7.0"
PR = "27.el10"
PACKAGES = "hyphen-pa"
PROVIDES = "rpm/hyphen-pa"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-pa-0.7.0-27.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e61406d0a453950fff946873eab0e6dfc322dac63e550d1bd8b8f9ca9a16a616"

URI_hyphen-pa = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-pa-0.7.0-27.el10.noarch.rpm;name=hyphen-pa;unpack=0"
SRC_URI += "${URI_hyphen-pa}"
SRC_URI[hyphen-pa.sha256sum] = "7d3d3500df2499740c57889b30904109067a24e537cf011cbc58deedf8b19b61"
RDEPENDS:hyphen-pa = " \
 hyphen \
"
