# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-bn"
PE = "1"
PV = "0.7.0"
PR = "27.el10"
PACKAGES = "hyphen-bn"
PROVIDES = "rpm/hyphen-bn"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-bn-0.7.0-27.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "83cea01ddb524fe79b603aeecd75a1b05183abc4ac8457a53dba49473305e90b"

URI_hyphen-bn = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-bn-0.7.0-27.el10.noarch.rpm;name=hyphen-bn;unpack=0"
SRC_URI += "${URI_hyphen-bn}"
SRC_URI[hyphen-bn.sha256sum] = "d4ba35e3bc5a6db4dea032d683c4ac1ad3b55e6c467bcf0242daf005a60e0cc2"
RDEPENDS:hyphen-bn = " \
 hyphen \
"
