# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-ml"
PE = "1"
PV = "0.7.0"
PR = "27.el10"
PACKAGES = "hyphen-ml"
PROVIDES = "rpm/hyphen-ml"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-ml-0.7.0-27.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "90bae923ad4860a9240b9b4f17270f7bafbef9bdf7446da2d1fea813062a075a"

URI_hyphen-ml = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-ml-0.7.0-27.el10.noarch.rpm;name=hyphen-ml;unpack=0"
SRC_URI += "${URI_hyphen-ml}"
SRC_URI[hyphen-ml.sha256sum] = "09ac58a0b4426871a1657df8cd185ba4eaa091d130e31d049b916ae1901afff2"
RDEPENDS:hyphen-ml = " \
 hyphen \
"
