# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-ta"
PE = "1"
PV = "0.7.0"
PR = "27.el10"
PACKAGES = "hyphen-ta"
PROVIDES = "rpm/hyphen-ta"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-ta-0.7.0-27.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "dae600d9588122578a655c00d21e1dd3f86a7ac3f33b77e6a26ccb1bf386f863"

URI_hyphen-ta = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-ta-0.7.0-27.el10.noarch.rpm;name=hyphen-ta;unpack=0"
SRC_URI += "${URI_hyphen-ta}"
SRC_URI[hyphen-ta.sha256sum] = "c69cf85dc70b4cfd0387547f715d8b2c259827bc42afa59b85ae7aaab0372d42"
RDEPENDS:hyphen-ta = " \
 hyphen \
"
