# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-ku"
PE = "0"
PV = "1.71.2"
PR = "31.el10"
PACKAGES = "hyphen-ku"
PROVIDES = "rpm/hyphen-ku"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-ku-1.71.2-31.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c1ade04c8f78233871a8e946bf545ede32a1fa71932c48f00bdbba33874dd981"

URI_hyphen-ku = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-ku-1.71.2-31.el10.noarch.rpm;name=hyphen-ku;unpack=0"
SRC_URI += "${URI_hyphen-ku}"
SRC_URI[hyphen-ku.sha256sum] = "9ca2c72b15dc0aaef0c2c15f3c98ab135e3de070a5769434627633e4c06e352a"
RDEPENDS:hyphen-ku = " \
 hyphen \
"
