# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-sv"
PE = "0"
PV = "1.00.1"
PR = "36.el10"
PACKAGES = "hyphen-sv"
PROVIDES = "rpm/hyphen-sv"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-sv-1.00.1-36.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c8e7d3456695f79fdfb7d23976d5834527be9037813ca5b07ef721ba44857ae4"

URI_hyphen-sv = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-sv-1.00.1-36.el10.noarch.rpm;name=hyphen-sv;unpack=0"
SRC_URI += "${URI_hyphen-sv}"
SRC_URI[hyphen-sv.sha256sum] = "3dc2d60ec073cad592a478905f69b235e109b0ce3377774639e6587f73ded5f0"
RDEPENDS:hyphen-sv = " \
 hyphen \
"
