# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-bg"
PE = "0"
PV = "4.3"
PR = "248.el10"
PACKAGES = "hyphen-bg"
PROVIDES = "rpm/hyphen-bg"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-bg-4.3-248.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1508ebd54e47ee94b48ed529b881b8c4e22afbdbc2a7edde26ce5bb5b2ce393b"

URI_hyphen-bg = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-bg-4.3-248.el10.noarch.rpm;name=hyphen-bg;unpack=0"
SRC_URI += "${URI_hyphen-bg}"
SRC_URI[hyphen-bg.sha256sum] = "6d4f4e28dd899f237de88cdbefac624895bf3ff5bd064c1a36d014c9d908233c"
RDEPENDS:hyphen-bg = " \
 hyphen \
"
