# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-te"
PE = "1"
PV = "0.7.0"
PR = "27.el10"
PACKAGES = "hyphen-te"
PROVIDES = "rpm/hyphen-te"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-te-0.7.0-27.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c9e52d136fb1a6c98240dad6352fa83ea22b7e498b82c1d6ca7b485cd87e5067"

URI_hyphen-te = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-te-0.7.0-27.el10.noarch.rpm;name=hyphen-te;unpack=0"
SRC_URI += "${URI_hyphen-te}"
SRC_URI[hyphen-te.sha256sum] = "aace9f6c37f29c52e59be260d60ad8c87ff353ed16171a0b0d0183947a765718"
RDEPENDS:hyphen-te = " \
 hyphen \
"
