# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-grc"
PE = "0"
PV = "0.20110913"
PR = "29.el10"
PACKAGES = "hyphen-grc"
PROVIDES = "rpm/hyphen-grc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-grc-0.20110913-29.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "61d21432dbf072440e2e51b068307d18b61cc92033347785aaa66b4f1a5b486d"

URI_hyphen-grc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-grc-0.20110913-29.el10.noarch.rpm;name=hyphen-grc;unpack=0"
SRC_URI += "${URI_hyphen-grc}"
SRC_URI[hyphen-grc.sha256sum] = "25c12c518973c5da211e4591359818fea7b2eee56e1982e97a752173506fa55a"
RDEPENDS:hyphen-grc = " \
 hyphen \
"
