# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-is"
PE = "0"
PV = "0.20030920"
PR = "35.el10"
PACKAGES = "hyphen-is"
PROVIDES = "rpm/hyphen-is"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-is-0.20030920-35.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4380ee648957542ca8130c814a8c152ff2a11a14e34a87c85cffb5f19ebd01b8"

URI_hyphen-is = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-is-0.20030920-35.el10.noarch.rpm;name=hyphen-is;unpack=0"
SRC_URI += "${URI_hyphen-is}"
SRC_URI[hyphen-is.sha256sum] = "8244a2216f354478de16f952af87312a99b5ece2ca03b30dd407924b1d7faa05"
RDEPENDS:hyphen-is = " \
 hyphen \
"
