# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "hyphen-uk"
PE = "0"
PV = "0.20030903"
PR = "32.el10"
PACKAGES = "hyphen-uk"
PROVIDES = "rpm/hyphen-uk"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/hyphen-uk-0.20030903-32.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2cac49068980d393af0a12237bb4822cecd4dd3ba99c5408157adb728b5a2f35"

URI_hyphen-uk = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/hyphen-uk-0.20030903-32.el10.noarch.rpm;name=hyphen-uk;unpack=0"
SRC_URI += "${URI_hyphen-uk}"
SRC_URI[hyphen-uk.sha256sum] = "8be5d8a873527abc8489bd4c6f33332ade47dd40dc49ec5aeb10ac448c9cb42b"
RDEPENDS:hyphen-uk = " \
 hyphen \
"
