# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ibus-table-others"
PE = "0"
PV = "1.3.17"
PR = "5.el10"
PACKAGES = "ibus-table-code ibus-table-cyrillic ibus-table-latin ibus-table-mathwriter ibus-table-mongol ibus-table-others ibus-table-translit ibus-table-tv"
PROVIDES = "rpm/ibus-table-code rpm/ibus-table-cyrillic rpm/ibus-table-latin rpm/ibus-table-mathwriter rpm/ibus-table-mongol rpm/ibus-table-others rpm/ibus-table-translit rpm/ibus-table-tv"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/ibus-table-others-1.3.17-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1acf9be9a20e6fd87732b9da5d54fda585399c785019786fbf8b6fb455fdd122"

URI_ibus-table-code = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ibus-table-code-1.3.17-5.el10.noarch.rpm;name=ibus-table-code;unpack=0"
SRC_URI += "${URI_ibus-table-code}"
SRC_URI[ibus-table-code.sha256sum] = "444a2f93e4754715ac6566ff503aa3cdf9a7cdd27111834bc520f0cdf4265d99"
RDEPENDS:ibus-table-code = " \
 ibus-table \
"

URI_ibus-table-cyrillic = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ibus-table-cyrillic-1.3.17-5.el10.noarch.rpm;name=ibus-table-cyrillic;unpack=0"
SRC_URI += "${URI_ibus-table-cyrillic}"
SRC_URI[ibus-table-cyrillic.sha256sum] = "9a2fb67c4b50a2922e65da7de7e94d6ef5874c9c1cd72ab7989a80b9d692b363"
RDEPENDS:ibus-table-cyrillic = " \
 ibus-table \
"

URI_ibus-table-latin = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ibus-table-latin-1.3.17-5.el10.noarch.rpm;name=ibus-table-latin;unpack=0"
SRC_URI += "${URI_ibus-table-latin}"
SRC_URI[ibus-table-latin.sha256sum] = "0c89d8306700461c6ca2e7edfa8f4b27114f538cfb91b4a44c78ab75bcf5bf02"
RDEPENDS:ibus-table-latin = " \
 ibus-table \
"

URI_ibus-table-mathwriter = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ibus-table-mathwriter-1.3.17-5.el10.noarch.rpm;name=ibus-table-mathwriter;unpack=0"
SRC_URI += "${URI_ibus-table-mathwriter}"
SRC_URI[ibus-table-mathwriter.sha256sum] = "75ef16285b4a0fe8dfa9250b1a39a443e52f62c52e78050041d350e44a6270b9"
RDEPENDS:ibus-table-mathwriter = " \
 ibus-table \
"

URI_ibus-table-mongol = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ibus-table-mongol-1.3.17-5.el10.noarch.rpm;name=ibus-table-mongol;unpack=0"
SRC_URI += "${URI_ibus-table-mongol}"
SRC_URI[ibus-table-mongol.sha256sum] = "0174b0a60dd6df961fa89627e7ab8f0b95f32049054cae7cd13bf0f508c76332"
RDEPENDS:ibus-table-mongol = " \
 ibus-table \
"

URI_ibus-table-others = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ibus-table-others-1.3.17-5.el10.noarch.rpm;name=ibus-table-others;unpack=0"
SRC_URI += "${URI_ibus-table-others}"
SRC_URI[ibus-table-others.sha256sum] = "43c24bc3a119aa44d94535dc1d29e38aa31281f0b1858d1f09c66dfbf218d4a0"
RDEPENDS:ibus-table-others = " \
 ibus-table \
"

URI_ibus-table-translit = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ibus-table-translit-1.3.17-5.el10.noarch.rpm;name=ibus-table-translit;unpack=0"
SRC_URI += "${URI_ibus-table-translit}"
SRC_URI[ibus-table-translit.sha256sum] = "917a7c2a991dfb8c37f6740c96e483715a7c2206a14c2f0c4c9b05450aa2b465"
RDEPENDS:ibus-table-translit = " \
 ibus-table \
"

URI_ibus-table-tv = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ibus-table-tv-1.3.17-5.el10.noarch.rpm;name=ibus-table-tv;unpack=0"
SRC_URI += "${URI_ibus-table-tv}"
SRC_URI[ibus-table-tv.sha256sum] = "de866ab5439f783da40de5ebb3bb7485bd0ec6c28151110a8d68c11a5a81b876"
RDEPENDS:ibus-table-tv = " \
 ibus-table \
"
