# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ibus-typing-booster"
PE = "0"
PV = "2.25.13"
PR = "2.el10"
PACKAGES = "ibus-typing-booster emoji-picker ibus-typing-booster-tests"
PROVIDES = "rpm/ibus-typing-booster rpm/emoji-picker rpm/ibus-typing-booster-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/ibus-typing-booster-2.25.13-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "56371ab0a8aef4fcf0331a4abcfe345e4551c1ea5b738a054a0cb6ba8b6b65d1"

URI_ibus-typing-booster = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ibus-typing-booster-2.25.13-2.el10.noarch.rpm;name=ibus-typing-booster;unpack=0"
SRC_URI += "${URI_ibus-typing-booster}"
SRC_URI[ibus-typing-booster.sha256sum] = "deea0e9b6c211f742d228df801416de3ca75c55f6affd44e86905db44c804c7b"
RDEPENDS:ibus-typing-booster = " \
 python3 \
 python3-distro \
 python3-dbus \
 cldr-emoji-annotation \
 ibus \
 unicode-ucd \
 bash \
 python3-pyxdg \
 python3-packaging \
 python3-enchant \
 m17n-lib \
"

URI_emoji-picker = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/emoji-picker-2.25.13-2.el10.noarch.rpm;name=emoji-picker;unpack=0"
SRC_URI += "${URI_emoji-picker}"
SRC_URI[emoji-picker.sha256sum] = "d8ddef93b912dfd8a846ffef3958788e63ef8f392d40fc27c25aa0dec2b39ec6"
RDEPENDS:emoji-picker = " \
 ibus-typing-booster \
 bash \
"

URI_ibus-typing-booster-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ibus-typing-booster-tests-2.25.13-2.el10.noarch.rpm;name=ibus-typing-booster-tests;unpack=0"
SRC_URI += "${URI_ibus-typing-booster-tests}"
SRC_URI[ibus-typing-booster-tests.sha256sum] = "724f3856f3106388c2d59577344351b4efe39d71980cdb4ed3dd3b2582b25c55"
RDEPENDS:ibus-typing-booster-tests = " \
 python3 \
 ibus-typing-booster \
"
