# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ibus-hangul"
PE = "0"
PV = "1.5.5"
PR = "9.el10"
PACKAGES = "ibus-hangul ibus-hangul-tests"
PROVIDES = "rpm/ibus-hangul rpm/ibus-hangul-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/ibus-hangul-1.5.5-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0ec0bcdac11c9f5b274dedcb22ca21a013a2ae378ed4b54d126ee6fdb3d540ff"

URI_ibus-hangul = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ibus-hangul-1.5.5-9.el10.x86_64_v2.rpm;name=ibus-hangul;unpack=0"
SRC_URI += "${URI_ibus-hangul}"
SRC_URI[ibus-hangul.sha256sum] = "71e81f395b7806f86bc1fa69d6d969af3f9b2b2d1346b415de2df3777155d3f4"
RDEPENDS:ibus-hangul = " \
 python3 \
 python3-gobject \
 libhangul \
 ibus \
 bash \
 glib2 \
 ibus-libs \
 glibc \
"

URI_ibus-hangul-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ibus-hangul-tests-1.5.5-9.el10.x86_64_v2.rpm;name=ibus-hangul-tests;unpack=0"
SRC_URI += "${URI_ibus-hangul-tests}"
SRC_URI[ibus-hangul-tests.sha256sum] = "9d3cd89274baf5f10f0aef0c9b95bd9a56db26cd13ad5338c7e9570c26fa728f"
RDEPENDS:ibus-hangul-tests = " \
 libhangul \
 glib2 \
 gtk3 \
 ibus-libs \
 glibc \
 ibus-hangul \
"
