# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ibus-libpinyin"
PE = "0"
PV = "1.15.7"
PR = "3.el10"
PACKAGES = "ibus-libpinyin"
PROVIDES = "rpm/ibus-libpinyin"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/ibus-libpinyin-1.15.7-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4d647abcba9b4ebc0e1350cc7b194b19822bd6ff33987b2ea236a0b6f9b84b30"

URI_ibus-libpinyin = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ibus-libpinyin-1.15.7-3.el10.x86_64_v2.rpm;name=ibus-libpinyin;unpack=0"
SRC_URI += "${URI_ibus-libpinyin}"
SRC_URI[ibus-libpinyin.sha256sum] = "9151a9e579e32daecd7f5ef6c29964e9139e8729813e2335bc8744dd7f0e6fb3"
RDEPENDS:ibus-libpinyin = " \
 python3-gobject \
 lua-libs \
 libgcc \
 ibus \
 sqlite-libs \
 libstdc++ \
 bash \
 glib2 \
 libpinyin \
 ibus-libs \
 glibc \
 libpinyin-data \
"
