# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "icoutils"
PE = "0"
PV = "0.32.3"
PR = "18.el10"
PACKAGES = "icoutils"
PROVIDES = "rpm/icoutils"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/icoutils-0.32.3-18.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "627f031df0a7c8ac4d1e85df5d022fba8037be70ca150e08eb68057beaaff603"

URI_icoutils = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/icoutils-0.32.3-18.el10.x86_64_v2.rpm;name=icoutils;unpack=0"
SRC_URI += "${URI_icoutils}"
SRC_URI[icoutils.sha256sum] = "7bb7bec6ae13bfc2aaa80b6a76449aef060917ebfab604f24574bbc05b093254"
RDEPENDS:icoutils = " \
 libpng \
 perl-libwww-perl \
 perl-Getopt-Long \
 perl-File-Basename \
 perl-PathTools \
 glibc \
 perl-HTTP-Message \
 perl-interpreter \
 perl-Term-ReadLine \
"
