# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ignition"
PE = "0"
PV = "2.21.0"
PR = "2.el10_0"
PACKAGES = "ignition ignition-edge ignition-grub ignition-validate"
PROVIDES = "rpm/ignition rpm/ignition-edge rpm/ignition-grub rpm/ignition-validate"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/ignition-2.21.0-2.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "14fcb3958a217eff1ba18267843af036a6284d867f8495372a7f5d1e387ddc57"

URI_ignition = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ignition-2.21.0-2.el10_0.x86_64_v2.rpm;name=ignition;unpack=0"
SRC_URI += "${URI_ignition}"
SRC_URI[ignition.sha256sum] = "2d18440e7de1520f9c9b26fb250c37accbacd4171111da6b733a225bbd31386e"
RDEPENDS:ignition = " \
 libuuid \
 libgcc \
 libblkid \
 libstdc++ \
 bash \
 popt \
 dracut \
 dosfstools \
 glibc \
 dracut-network \
"

URI_ignition-edge = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ignition-edge-2.21.0-2.el10_0.x86_64_v2.rpm;name=ignition-edge;unpack=0"
SRC_URI += "${URI_ignition-edge}"
SRC_URI[ignition-edge.sha256sum] = "337b43880a91e67fb1f407b00b57fff2dbc1175ae6b7d0ee9922a6961b9cd760"
RDEPENDS:ignition-edge = " \
 bash \
"

URI_ignition-grub = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ignition-grub-2.21.0-2.el10_0.x86_64_v2.rpm;name=ignition-grub;unpack=0"
SRC_URI += "${URI_ignition-grub}"
SRC_URI[ignition-grub.sha256sum] = "c8d793545c570112900c8873b058cc82b0a640a59792154043d0c55c6e49da11"
RDEPENDS:ignition-grub = ""

URI_ignition-validate = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ignition-validate-2.21.0-2.el10_0.x86_64_v2.rpm;name=ignition-validate;unpack=0"
SRC_URI += "${URI_ignition-validate}"
SRC_URI[ignition-validate.sha256sum] = "bcb05442ea2a6d857a75e85154a95277844f6e0d79e693fd36344a246e7c8f99"
RDEPENDS:ignition-validate = " \
 glibc \
"
