# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "inih"
PE = "0"
PV = "58"
PR = "3.el10"
PACKAGES = "inih inih-cpp inih-devel"
PROVIDES = "rpm/inih rpm/inih-cpp rpm/inih-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/inih-58-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ac8c3c57ee29fa85f6960e7d55eba94020e9da86ece563bade0a7d07afe30ef6"

URI_inih = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/inih-58-3.el10.x86_64_v2.rpm;name=inih;unpack=0"
SRC_URI += "${URI_inih}"
SRC_URI[inih.sha256sum] = "3610dddeac847924b93d9ddc38b65f30604b569c5cd5ad8f6780d4b593d7ae94"
RDEPENDS:inih = " \
 glibc \
"

URI_inih-cpp = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/inih-cpp-58-3.el10.x86_64_v2.rpm;name=inih-cpp;unpack=0"
SRC_URI += "${URI_inih-cpp}"
SRC_URI[inih-cpp.sha256sum] = "3c522134b8259b5092514f232f6fa8107dfba83ddf106f867ac5b8ff62bcbbf4"
RDEPENDS:inih-cpp = " \
 glibc \
 inih \
 libgcc \
 libstdc++ \
"

URI_inih-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/inih-devel-58-3.el10.x86_64_v2.rpm;name=inih-devel;unpack=0"
SRC_URI += "${URI_inih-devel}"
SRC_URI[inih-devel.sha256sum] = "4f95aaf76b0f0b6546135f74fe829fadd20f6c5cf74e3ffcef085c10492cfa11"
RDEPENDS:inih-devel = " \
 inih \
 inih-cpp \
 pkgconf-pkg-config \
 inih-devel \
"
