# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "intel-cmt-cat"
PE = "0"
PV = "23.11"
PR = "6.el10"
PACKAGES = "intel-cmt-cat intel-cmt-cat-devel"
PROVIDES = "rpm/intel-cmt-cat rpm/intel-cmt-cat-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/intel-cmt-cat-23.11-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d240d7df0f072d4ece40ce50a7cf53a21cd756eb77dc6181b409e2d01a6afd3e"

URI_intel-cmt-cat = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/intel-cmt-cat-23.11-6.el10.x86_64_v2.rpm;name=intel-cmt-cat;unpack=0"
SRC_URI += "${URI_intel-cmt-cat}"
SRC_URI[intel-cmt-cat.sha256sum] = "a916257b74ff7039a938f062cf1b5eccd051759f7746441b51e9456db0a34f6e"
RDEPENDS:intel-cmt-cat = " \
 glibc \
 bash \
"

URI_intel-cmt-cat-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/intel-cmt-cat-devel-23.11-6.el10.x86_64_v2.rpm;name=intel-cmt-cat-devel;unpack=0"
SRC_URI += "${URI_intel-cmt-cat-devel}"
SRC_URI[intel-cmt-cat-devel.sha256sum] = "463ed6249e773c00ba3efa70c26bcb7f8f38492c22a88df9c268bd8691bf17df"
RDEPENDS:intel-cmt-cat-devel = " \
 intel-cmt-cat \
"
