# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "iperf3"
PE = "0"
PV = "3.17.1"
PR = "4.el10"
PACKAGES = "iperf3 iperf3-devel"
PROVIDES = "rpm/iperf3 rpm/iperf3-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/iperf3-3.17.1-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c8d557a354b63c17851879d0d1e96baf888dd0b7b7e149f06112027607f187dc"

URI_iperf3 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/iperf3-3.17.1-4.el10.x86_64_v2.rpm;name=iperf3;unpack=0"
SRC_URI += "${URI_iperf3}"
SRC_URI[iperf3.sha256sum] = "3666dc9e41e959e774acb672c0e41a142b128124343db0083b95303536fa254a"
RDEPENDS:iperf3 = " \
 glibc \
 openssl-libs \
 lksctp-tools \
"

URI_iperf3-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/iperf3-devel-3.17.1-4.el10.x86_64_v2.rpm;name=iperf3-devel;unpack=0"
SRC_URI += "${URI_iperf3-devel}"
SRC_URI[iperf3-devel.sha256sum] = "3dedffd1e1e7694b6fefaa1c344a534f8eceaedf60013359398b37839b1fee37"
RDEPENDS:iperf3-devel = " \
 iperf3 \
"
