# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ipmitool"
PE = "0"
PV = "1.8.19"
PR = "9.el10"
PACKAGES = "bmc-snmp-proxy exchange-bmc-os-info ipmievd ipmitool"
PROVIDES = "rpm/bmc-snmp-proxy rpm/exchange-bmc-os-info rpm/ipmievd rpm/ipmitool"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/ipmitool-1.8.19-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "abbfb88001390d89401a16dd8420aef23bd947b57ceb00ee798ecf83e791c928"

URI_bmc-snmp-proxy = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/bmc-snmp-proxy-1.8.19-9.el10.noarch.rpm;name=bmc-snmp-proxy;unpack=0"
SRC_URI += "${URI_bmc-snmp-proxy}"
SRC_URI[bmc-snmp-proxy.sha256sum] = "869dfbe458519302abd94a313028ad02afac53060d71a5fcbe7930ba87ca29e4"
RDEPENDS:bmc-snmp-proxy = " \
 net-snmp \
 bash \
 exchange-bmc-os-info \
"

URI_exchange-bmc-os-info = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/exchange-bmc-os-info-1.8.19-9.el10.noarch.rpm;name=exchange-bmc-os-info;unpack=0"
SRC_URI += "${URI_exchange-bmc-os-info}"
SRC_URI[exchange-bmc-os-info.sha256sum] = "1354c2e759f1be3e1428978ec02a6236bb1796070291bfd899bbc1819e4ade64"
RDEPENDS:exchange-bmc-os-info = " \
 systemd \
 bash \
 hostname \
 ipmitool \
"

URI_ipmievd = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ipmievd-1.8.19-9.el10.x86_64_v2.rpm;name=ipmievd;unpack=0"
SRC_URI += "${URI_ipmievd}"
SRC_URI[ipmievd.sha256sum] = "2729532a4ec5dc841779697acd8ab6ee4fd5a6162b5dd96f876a0d6a4ee5aca5"
RDEPENDS:ipmievd = " \
 systemd \
 openssl-libs \
 ipmitool \
 bash \
 glibc \
"

URI_ipmitool = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ipmitool-1.8.19-9.el10.x86_64_v2.rpm;name=ipmitool;unpack=0"
SRC_URI += "${URI_ipmitool}"
SRC_URI[ipmitool.sha256sum] = "1d8bbb3c49465718af3b05f5f7a6e610f2cc5f9838aa0d0acde4bfa78bc8721c"
RDEPENDS:ipmitool = " \
 systemd \
 openssl-libs \
 readline \
 bash \
 glibc \
"
