# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "iproute"
PE = "0"
PV = "6.11.0"
PR = "1.el10"
PACKAGES = "iproute iproute-tc iproute-devel iproute-doc"
PROVIDES = "rpm/iproute rpm/iproute-tc rpm/iproute-devel rpm/iproute-doc"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/iproute-6.11.0-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "59dd4604e23d62d78b3b8e62ac8a8a22cfa4de2f56c1a3aff931ed465557a659"

URI_iproute = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/iproute-6.11.0-1.el10.x86_64_v2.rpm;name=iproute;unpack=0"
SRC_URI += "${URI_iproute}"
SRC_URI[iproute.sha256sum] = "e9966c7117592e82e3bb6b347873f0fd67fc49cd953307b88e6cfaaa4ff7eed1"
RDEPENDS:iproute = " \
 libmnl \
 libbpf \
 elfutils-libelf \
 libcap \
 glibc \
 libselinux \
 psmisc \
"

URI_iproute-tc = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/iproute-tc-6.11.0-1.el10.x86_64_v2.rpm;name=iproute-tc;unpack=0"
SRC_URI += "${URI_iproute-tc}"
SRC_URI[iproute-tc.sha256sum] = "431d1f5ad7f6296f28142bf708fb396c4a2feba56f3520543c9bf8043b1fff65"
RDEPENDS:iproute-tc = " \
 iproute \
 libmnl \
 libbpf \
 iptables-libs \
 elfutils-libelf \
 libcap \
 glibc \
"

URI_iproute-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/iproute-devel-6.11.0-1.el10.x86_64_v2.rpm;name=iproute-devel;unpack=0"
SRC_URI += "${URI_iproute-devel}"
SRC_URI[iproute-devel.sha256sum] = "e98ad5b23f604d22e75bfc50b09c3471d9acfac18703aa765e22c7d0cda7051a"
RDEPENDS:iproute-devel = " \
 iproute \
"

URI_iproute-doc = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/iproute-doc-6.11.0-1.el10.x86_64_v2.rpm;name=iproute-doc;unpack=0"
SRC_URI += "${URI_iproute-doc}"
SRC_URI[iproute-doc.sha256sum] = "746f25dc90c71f07455eaccc885fbb2c98e4b1aaee84c4c8e2f65925af065f44"
RDEPENDS:iproute-doc = " \
 iproute \
"
