# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "iprutils"
PE = "0"
PV = "2.4.19"
PR = "14.el10"
PACKAGES = ""
PROVIDES = ""


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/iprutils-2.4.19-14.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "32bd835b0922b319dc316970ded93fbf743d4dbdb0e9d10098aba3616ff3b049"
