# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "irqbalance"
PE = "2"
PV = "1.9.4"
PR = "2.el10"
PACKAGES = "irqbalance"
PROVIDES = "rpm/irqbalance"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/irqbalance-1.9.4-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ac0ba6969a0c047f2ce17b8295aeb34b49e56793a1af4427dd8e6b81de9d375f"

URI_irqbalance = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/irqbalance-1.9.4-2.el10.x86_64_v2.rpm;name=irqbalance;unpack=0"
SRC_URI += "${URI_irqbalance}"
SRC_URI[irqbalance.sha256sum] = "db3a5fcbf5a3a65974a812df4a5772450981d81ef08e905eb504b6aa50a0d0eb"
RDEPENDS:irqbalance = " \
 systemd-libs \
 numactl-libs \
 libcap-ng \
 bash \
 glib2 \
 ncurses-libs \
 glibc \
"
