# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "iscsi-initiator-utils"
PE = "0"
PV = "6.2.1.9"
PR = "22.gita65a472.el10"
PACKAGES = "iscsi-initiator-utils iscsi-initiator-utils-iscsiuio python3-iscsi-initiator-utils iscsi-initiator-utils-devel"
PROVIDES = "rpm/iscsi-initiator-utils rpm/iscsi-initiator-utils-iscsiuio rpm/python3-iscsi-initiator-utils rpm/iscsi-initiator-utils-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/iscsi-initiator-utils-6.2.1.9-22.gita65a472.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d0d212adc9cdafd156cb5328c28c62a1336376a07442626c64e92a1ee1b4bbf1"

URI_iscsi-initiator-utils = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/iscsi-initiator-utils-6.2.1.9-22.gita65a472.el10.x86_64_v2.rpm;name=iscsi-initiator-utils;unpack=0"
SRC_URI += "${URI_iscsi-initiator-utils}"
SRC_URI[iscsi-initiator-utils.sha256sum] = "a45ccfa717bc2b0dce2677227ba3208751d35bdb54e30c84f8d7cc1adb6b4682"
RDEPENDS:iscsi-initiator-utils = " \
 systemd \
 systemd-libs \
 openssl-libs \
 kmod-libs \
 libmount \
 iscsi-initiator-utils-iscsiuio \
 bash \
 isns-utils-libs \
 glibc \
"

URI_iscsi-initiator-utils-iscsiuio = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/iscsi-initiator-utils-iscsiuio-6.2.1.9-22.gita65a472.el10.x86_64_v2.rpm;name=iscsi-initiator-utils-iscsiuio;unpack=0"
SRC_URI += "${URI_iscsi-initiator-utils-iscsiuio}"
SRC_URI[iscsi-initiator-utils-iscsiuio.sha256sum] = "68db0c69df1481f0ea52bd01ca5011f0b41b4e880963e7d3a9a8160e3b09c13e"
RDEPENDS:iscsi-initiator-utils-iscsiuio = " \
 systemd-libs \
 libgcc \
 iscsi-initiator-utils \
 bash \
 glibc \
"

URI_python3-iscsi-initiator-utils = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/python3-iscsi-initiator-utils-6.2.1.9-22.gita65a472.el10.x86_64_v2.rpm;name=python3-iscsi-initiator-utils;unpack=0"
SRC_URI += "${URI_python3-iscsi-initiator-utils}"
SRC_URI[python3-iscsi-initiator-utils.sha256sum] = "e7a6cdfd31c8c14443c02cc6be3a75ab7f884b5b361d28635816950cc49f6ef1"
RDEPENDS:python3-iscsi-initiator-utils = " \
 glibc \
 iscsi-initiator-utils \
 python3 \
"

URI_iscsi-initiator-utils-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/iscsi-initiator-utils-devel-6.2.1.9-22.gita65a472.el10.x86_64_v2.rpm;name=iscsi-initiator-utils-devel;unpack=0"
SRC_URI += "${URI_iscsi-initiator-utils-devel}"
SRC_URI[iscsi-initiator-utils-devel.sha256sum] = "ff610a7b974f3516d0749b11a10b62d5455a1ded22ce8ee86f1911aa34148044"
RDEPENDS:iscsi-initiator-utils-devel = " \
 iscsi-initiator-utils \
 pkgconf-pkg-config \
"
