# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "jackson-bom"
PE = "0"
PV = "2.16.1"
PR = "3.el10"
PACKAGES = "jackson-bom"
PROVIDES = "rpm/jackson-bom"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/jackson-bom-2.16.1-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "896b69b11ec34778e7916b4b81f919d3b899f7756acb1004ae22f673cfb953ce"

URI_jackson-bom = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/jackson-bom-2.16.1-3.el10.noarch.rpm;name=jackson-bom;unpack=0"
SRC_URI += "${URI_jackson-bom}"
SRC_URI[jackson-bom.sha256sum] = "259dbdbd1e05c6aa7ea7ecf15e68972cf316d9e50511d8abc06a772b3359da37"
RDEPENDS:jackson-bom = " \
 jackson-parent \
 javapackages-filesystem \
 java-21-openjdk-headless \
"
