# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "jackson-parent"
PE = "0"
PV = "2.16"
PR = "4.el10"
PACKAGES = "jackson-parent"
PROVIDES = "rpm/jackson-parent"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/jackson-parent-2.16-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b18750cb636c8786fde3825a51f3e965f550a11ba131f111e442576dc34f7554"

URI_jackson-parent = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/jackson-parent-2.16-4.el10.noarch.rpm;name=jackson-parent;unpack=0"
SRC_URI += "${URI_jackson-parent}"
SRC_URI[jackson-parent.sha256sum] = "db6c536dfc20905c4fe6f956e8115cff8886c1915f6aa2c5f553eaa4bca3764a"
RDEPENDS:jackson-parent = " \
 fasterxml-oss-parent \
 javapackages-filesystem \
 java-21-openjdk-headless \
"
