# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "jackson-jaxrs-providers"
PE = "0"
PV = "2.14.2"
PR = "1.el10"
PACKAGES = "jackson-jaxrs-json-provider jackson-jaxrs-providers jackson-jaxrs-providers-datatypes jackson-jaxrs-providers-parent"
PROVIDES = "rpm/jackson-jaxrs-json-provider rpm/jackson-jaxrs-providers rpm/jackson-jaxrs-providers-datatypes rpm/jackson-jaxrs-providers-parent"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/jackson-jaxrs-providers-2.14.2-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b253a76ca53021f693f8f9a2c1f268ddeeb092cca0a693e5e442f324b123ab16"

URI_jackson-jaxrs-json-provider = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/jackson-jaxrs-json-provider-2.14.2-1.el10.noarch.rpm;name=jackson-jaxrs-json-provider;unpack=0"
SRC_URI += "${URI_jackson-jaxrs-json-provider}"
SRC_URI[jackson-jaxrs-json-provider.sha256sum] = "37f3c37b924cb53abc674cb46e7bb7e413d69351f40c88b7783e910f15dceee5"
RDEPENDS:jackson-jaxrs-json-provider = " \
 jackson-jaxrs-providers \
 javapackages-filesystem \
 java-21-openjdk-headless \
 jackson-module-jaxb-annotations \
"

URI_jackson-jaxrs-providers = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/jackson-jaxrs-providers-2.14.2-1.el10.noarch.rpm;name=jackson-jaxrs-providers;unpack=0"
SRC_URI += "${URI_jackson-jaxrs-providers}"
SRC_URI[jackson-jaxrs-providers.sha256sum] = "99e380f9ccebfa275d70826d2b721daf57078e8781962052ec16530559434a43"
RDEPENDS:jackson-jaxrs-providers = " \
 jackson-core \
 jackson-databind \
 javapackages-filesystem \
 java-21-openjdk-headless \
"

URI_jackson-jaxrs-providers-datatypes = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/jackson-jaxrs-providers-datatypes-2.14.2-1.el10.noarch.rpm;name=jackson-jaxrs-providers-datatypes;unpack=0"
SRC_URI += "${URI_jackson-jaxrs-providers-datatypes}"
SRC_URI[jackson-jaxrs-providers-datatypes.sha256sum] = "78fd2308920359f815450b001b7abd481f047b6d23c3fba061525247dc6c2763"
RDEPENDS:jackson-jaxrs-providers-datatypes = " \
 jackson-core \
 jackson-databind \
 javapackages-filesystem \
 java-21-openjdk-headless \
"

URI_jackson-jaxrs-providers-parent = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/jackson-jaxrs-providers-parent-2.14.2-1.el10.noarch.rpm;name=jackson-jaxrs-providers-parent;unpack=0"
SRC_URI += "${URI_jackson-jaxrs-providers-parent}"
SRC_URI[jackson-jaxrs-providers-parent.sha256sum] = "a3fe7b0a031526e8f123e7aec029a77e066bd68febc7b259b76f215833826146"
RDEPENDS:jackson-jaxrs-providers-parent = " \
 jackson-bom \
 javapackages-filesystem \
 java-21-openjdk-headless \
"
