# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "jakarta-annotations"
PE = "0"
PV = "1.3.5"
PR = "23.el10"
PACKAGES = "jakarta-annotations jakarta-annotations-javadoc"
PROVIDES = "rpm/jakarta-annotations rpm/jakarta-annotations-javadoc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/jakarta-annotations-1.3.5-23.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b1051c2a2710b531d2fd137f86c5981cf3f4c66764efac335dfe418ff5e388f1"

URI_jakarta-annotations = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/jakarta-annotations-1.3.5-23.el10.noarch.rpm;name=jakarta-annotations;unpack=0"
SRC_URI += "${URI_jakarta-annotations}"
SRC_URI[jakarta-annotations.sha256sum] = "bd734a52c9daa265b3bded05b6216a39fc014348ed19a8adc8f2d7de7f2520af"
RDEPENDS:jakarta-annotations = " \
 javapackages-filesystem \
"

URI_jakarta-annotations-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/jakarta-annotations-javadoc-1.3.5-23.el10.noarch.rpm;name=jakarta-annotations-javadoc;unpack=0"
SRC_URI += "${URI_jakarta-annotations-javadoc}"
SRC_URI[jakarta-annotations-javadoc.sha256sum] = "4b2ff4787b13ba2ae119d1ba1099be9a45903e08e6f61e975663c8ed7b14af5b"
RDEPENDS:jakarta-annotations-javadoc = " \
 javapackages-filesystem \
"
