# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "jakarta-servlet"
PE = "0"
PV = "5.0.0"
PR = "19.el10"
PACKAGES = "jakarta-servlet jakarta-servlet-javadoc"
PROVIDES = "rpm/jakarta-servlet rpm/jakarta-servlet-javadoc"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/jakarta-servlet-5.0.0-19.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "204195b28303cee1ac51070f166d9fe78429b4aa714bba1764a8c5b761f4fdb8"

URI_jakarta-servlet = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/jakarta-servlet-5.0.0-19.el10.noarch.rpm;name=jakarta-servlet;unpack=0"
SRC_URI += "${URI_jakarta-servlet}"
SRC_URI[jakarta-servlet.sha256sum] = "ac30effe0d8047a7a59bc71f4be49a615affb432b63c2a01a6e42b02af3d4413"
RDEPENDS:jakarta-servlet = " \
 javapackages-filesystem \
"

URI_jakarta-servlet-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/jakarta-servlet-javadoc-5.0.0-19.el10.noarch.rpm;name=jakarta-servlet-javadoc;unpack=0"
SRC_URI += "${URI_jakarta-servlet-javadoc}"
SRC_URI[jakarta-servlet-javadoc.sha256sum] = "8d40740314a1c9239a2cf4bdbdd418bea56d247dee8c694a5ae8a1999ec33410"
RDEPENDS:jakarta-servlet-javadoc = " \
 javapackages-filesystem \
"
