# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "jansson"
PE = "0"
PV = "2.14"
PR = "3.el10"
PACKAGES = "jansson jansson-devel jansson-devel-doc"
PROVIDES = "rpm/jansson rpm/jansson-devel rpm/jansson-devel-doc"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/jansson-2.14-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "133ffcba890aca09004bf521eff4e6bfea5685654c9b7cca080e40f676c6157a"

URI_jansson = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/jansson-2.14-3.el10.x86_64_v2.rpm;name=jansson;unpack=0"
SRC_URI += "${URI_jansson}"
SRC_URI[jansson.sha256sum] = "4d09bfe8a603488dd6943dd9936cd5fd16e3f9f5068516c4a982a6ff61280fa2"
RDEPENDS:jansson = " \
 glibc \
"

URI_jansson-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/jansson-devel-2.14-3.el10.x86_64_v2.rpm;name=jansson-devel;unpack=0"
SRC_URI += "${URI_jansson-devel}"
SRC_URI[jansson-devel.sha256sum] = "d11d8a2684570228716e3931cb7545fde3cba39702a7081ceae5268e82578388"
RDEPENDS:jansson-devel = " \
 jansson \
 pkgconf-pkg-config \
"

URI_jansson-devel-doc = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/jansson-devel-doc-2.14-3.el10.noarch.rpm;name=jansson-devel-doc;unpack=0"
SRC_URI += "${URI_jansson-devel-doc}"
SRC_URI[jansson-devel-doc.sha256sum] = "64747504a5374144456497b0ebf76e2b50a1aece713ff7b0575eac5fb4d93b6f"
RDEPENDS:jansson-devel-doc = ""
