# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "jaxb-api"
PE = "0"
PV = "4.0.1"
PR = "6.el10"
PACKAGES = "jaxb-api jaxb-api-javadoc"
PROVIDES = "rpm/jaxb-api rpm/jaxb-api-javadoc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/jaxb-api-4.0.1-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "bf7155b953aeb1c052bbe5c0e91783a85222ead07122f6a025603bf4aa4be654"

URI_jaxb-api = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/jaxb-api-4.0.1-6.el10.noarch.rpm;name=jaxb-api;unpack=0"
SRC_URI += "${URI_jaxb-api}"
SRC_URI[jaxb-api.sha256sum] = "4bdeedd62fe6009c063ca75560a54a69031a9b6451fd04fa7c97965b1d066fe0"
RDEPENDS:jaxb-api = " \
 jakarta-activation \
 javapackages-filesystem \
"

URI_jaxb-api-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/jaxb-api-javadoc-4.0.1-6.el10.noarch.rpm;name=jaxb-api-javadoc;unpack=0"
SRC_URI += "${URI_jaxb-api-javadoc}"
SRC_URI[jaxb-api-javadoc.sha256sum] = "4075aafa8e44daaa600a69a117400c61449a22d7bb0410adbfd64506550cefa8"
RDEPENDS:jaxb-api-javadoc = " \
 javapackages-filesystem \
"
