# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "jaxb-dtd-parser"
PE = "0"
PV = "1.5.1"
PR = "6.el10"
PACKAGES = "jaxb-dtd-parser jaxb-dtd-parser-javadoc"
PROVIDES = "rpm/jaxb-dtd-parser rpm/jaxb-dtd-parser-javadoc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/jaxb-dtd-parser-1.5.1-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a027826abdbefe71484137926c717e30b71e81f51b9416dedb635d4d4c878d8a"

URI_jaxb-dtd-parser = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/jaxb-dtd-parser-1.5.1-6.el10.noarch.rpm;name=jaxb-dtd-parser;unpack=0"
SRC_URI += "${URI_jaxb-dtd-parser}"
SRC_URI[jaxb-dtd-parser.sha256sum] = "40d901a33a9be99010c5d25f0389986078625e0eb92ab278de9bb561cc539099"
RDEPENDS:jaxb-dtd-parser = " \
 javapackages-filesystem \
"

URI_jaxb-dtd-parser-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/jaxb-dtd-parser-javadoc-1.5.1-6.el10.noarch.rpm;name=jaxb-dtd-parser-javadoc;unpack=0"
SRC_URI += "${URI_jaxb-dtd-parser-javadoc}"
SRC_URI[jaxb-dtd-parser-javadoc.sha256sum] = "49201b150bdbc7da5686eedac5d7292b70b6713c2b38efce08a42682c02ec555"
RDEPENDS:jaxb-dtd-parser-javadoc = " \
 javapackages-filesystem \
"
