# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "jbigkit"
PE = "0"
PV = "2.1"
PR = "31.el10"
PACKAGES = "jbigkit jbigkit-libs jbigkit-devel"
PROVIDES = "rpm/jbigkit rpm/jbigkit-libs rpm/jbigkit-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/jbigkit-2.1-31.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1d963c42b56d9b6115161317988d560b450e7f4ebe46e74fd6c7c95e5a2eb69a"

URI_jbigkit = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/jbigkit-2.1-31.el10.x86_64_v2.rpm;name=jbigkit;unpack=0"
SRC_URI += "${URI_jbigkit}"
SRC_URI[jbigkit.sha256sum] = "8dab98ac1bb815b5d36421cef4aa9d8537096cadcf7787cca4b0a81c90decbe7"
RDEPENDS:jbigkit = " \
 glibc \
 jbigkit-libs \
"

URI_jbigkit-libs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/jbigkit-libs-2.1-31.el10.x86_64_v2.rpm;name=jbigkit-libs;unpack=0"
SRC_URI += "${URI_jbigkit-libs}"
SRC_URI[jbigkit-libs.sha256sum] = "fdec2d6e1688a59aea26026b39e70bffc84bc9e81f91ffdff80107ba7a49acaa"
RDEPENDS:jbigkit-libs = " \
 glibc \
"

URI_jbigkit-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/jbigkit-devel-2.1-31.el10.x86_64_v2.rpm;name=jbigkit-devel;unpack=0"
SRC_URI += "${URI_jbigkit-devel}"
SRC_URI[jbigkit-devel.sha256sum] = "684f269a6cd5c6103d362c56afd1a97a6484f1b920d77b054c1569b14b7ac328"
RDEPENDS:jbigkit-devel = " \
 jbigkit-libs \
"
