# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "jdepend"
PE = "0"
PV = "2.10"
PR = "12.el10"
PACKAGES = "jdepend jdepend-javadoc"
PROVIDES = "rpm/jdepend rpm/jdepend-javadoc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/jdepend-2.10-12.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "10c4fbfd373f0335248a97be371e7117a483fecf8b3cc40d4b50dc1108e76f1c"

URI_jdepend = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/jdepend-2.10-12.el10.noarch.rpm;name=jdepend;unpack=0"
SRC_URI += "${URI_jdepend}"
SRC_URI[jdepend.sha256sum] = "6f2b7cad50387e61d87b10ab60f663a789c2c0b139bc1dae11dbba4514e0e52e"
RDEPENDS:jdepend = " \
 javapackages-filesystem \
"

URI_jdepend-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/jdepend-javadoc-2.10-12.el10.noarch.rpm;name=jdepend-javadoc;unpack=0"
SRC_URI += "${URI_jdepend-javadoc}"
SRC_URI[jdepend-javadoc.sha256sum] = "830ad7482b508b773947632f3c890ca859e9d4282f5ac200e52e440ed18fd856"
RDEPENDS:jdepend-javadoc = " \
 javapackages-filesystem \
"
