# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "jsch"
PE = "0"
PV = "0.1.55"
PR = "16.el10"
PACKAGES = "jsch jsch-javadoc"
PROVIDES = "rpm/jsch rpm/jsch-javadoc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/jsch-0.1.55-16.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ebc02bd70dfba1cc4faf9e66ce9294402d79735935bee768076efb6e3b7c6b3f"

URI_jsch = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/jsch-0.1.55-16.el10.noarch.rpm;name=jsch;unpack=0"
SRC_URI += "${URI_jsch}"
SRC_URI[jsch.sha256sum] = "3f588112f1e875f1564764869647a4e0901b4ce36dc5737e4ab6711c613b5963"
RDEPENDS:jsch = " \
 javapackages-filesystem \
 jzlib \
"

URI_jsch-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/jsch-javadoc-0.1.55-16.el10.noarch.rpm;name=jsch-javadoc;unpack=0"
SRC_URI += "${URI_jsch-javadoc}"
SRC_URI[jsch-javadoc.sha256sum] = "4a347bd10e3b1e2a0cf7c46872c81a4ac706bfadab2fc12fcf19d68a3ba93ec8"
RDEPENDS:jsch-javadoc = " \
 javapackages-filesystem \
"
