# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "junit"
PE = "1"
PV = "4.13.2"
PR = "7.el10"
PACKAGES = "junit junit-javadoc junit-manual"
PROVIDES = "rpm/junit rpm/junit-javadoc rpm/junit-manual"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/junit-4.13.2-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "aa56364f8f713df653755bc8f8a23b2a23f9a9236a3a1cbe984417db4da2e746"

URI_junit = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/junit-4.13.2-7.el10.noarch.rpm;name=junit;unpack=0"
SRC_URI += "${URI_junit}"
SRC_URI[junit.sha256sum] = "da832a56cbe2ea52389d5566c38a792b49acb51f61417ab92ab8e1b1d2af2970"
RDEPENDS:junit = " \
 hamcrest \
 javapackages-filesystem \
"

URI_junit-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/junit-javadoc-4.13.2-7.el10.noarch.rpm;name=junit-javadoc;unpack=0"
SRC_URI += "${URI_junit-javadoc}"
SRC_URI[junit-javadoc.sha256sum] = "55b4b25391b8298f4fb5b0875e98af410609f9e7e2716c592c2d3045a52769f8"
RDEPENDS:junit-javadoc = " \
 javapackages-filesystem \
"

URI_junit-manual = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/junit-manual-4.13.2-7.el10.noarch.rpm;name=junit-manual;unpack=0"
SRC_URI += "${URI_junit-manual}"
SRC_URI[junit-manual.sha256sum] = "e97f1d38f919a59904141ced427606c73608a488c2e8ddcba25001303a9f26fc"
RDEPENDS:junit-manual = ""
