# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "kdump-anaconda-addon"
PE = "0"
PV = "006"
PR = "17.20220714git7ca2d3e.el10"
PACKAGES = "kdump-anaconda-addon"
PROVIDES = "rpm/kdump-anaconda-addon"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/kdump-anaconda-addon-006-17.20220714git7ca2d3e.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b823340007d357b9d3db8db313a9c76cfc6f0883d2063a5e83d37d8be68d3211"

URI_kdump-anaconda-addon = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/kdump-anaconda-addon-006-17.20220714git7ca2d3e.el10.noarch.rpm;name=kdump-anaconda-addon;unpack=0"
SRC_URI += "${URI_kdump-anaconda-addon}"
SRC_URI[kdump-anaconda-addon.sha256sum] = "36fd216e3371eac3b31da723c217914fc3d5ceaaddb008cd0a9793ebae0e4586"
RDEPENDS:kdump-anaconda-addon = " \
 hicolor-icon-theme \
 anaconda \
"
