# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "kmod"
PE = "0"
PV = "31"
PR = "11.el10"
PACKAGES = "kmod kmod-libs kmod-devel"
PROVIDES = "rpm/kmod rpm/kmod-libs rpm/kmod-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/kmod-31-11.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "cc4376fb5de9c88f4f6e61853b5fb34520e4461c69c4e829335d6cef96926604"

URI_kmod = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/kmod-31-11.el10.x86_64_v2.rpm;name=kmod;unpack=0"
SRC_URI += "${URI_kmod}"
SRC_URI[kmod.sha256sum] = "c03e5a76d7e3d24210924f6b8483e3800a8d8e4e103056fc036725933c6810dc"
RDEPENDS:kmod = " \
 zlib-ng-compat \
 openssl-libs \
 libgcc \
 libzstd \
 bash \
 glibc \
 xz-libs \
"

URI_kmod-libs = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/kmod-libs-31-11.el10.x86_64_v2.rpm;name=kmod-libs;unpack=0"
SRC_URI += "${URI_kmod-libs}"
SRC_URI[kmod-libs.sha256sum] = "4bf145ec0165f1b88dd73f032d5d8fbaa1ac89160a500684b229b410412c9699"
RDEPENDS:kmod-libs = " \
 zlib-ng-compat \
 openssl-libs \
 libgcc \
 libzstd \
 glibc \
 xz-libs \
"

URI_kmod-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/kmod-devel-31-11.el10.x86_64_v2.rpm;name=kmod-devel;unpack=0"
SRC_URI += "${URI_kmod-devel}"
SRC_URI[kmod-devel.sha256sum] = "b7d8d901410f26125ab4414f03a17cb8d69397e838047e143901cbe4c77a4d98"
RDEPENDS:kmod-devel = " \
 kmod-libs \
 pkgconf-pkg-config \
"
