# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ldns"
PE = "0"
PV = "1.8.3"
PR = "18.el10"
PACKAGES = "ldns ldns-devel ldns-doc ldns-utils perl-ldns python3-ldns"
PROVIDES = "rpm/ldns rpm/ldns-devel rpm/ldns-doc rpm/ldns-utils rpm/perl-ldns rpm/python3-ldns"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/ldns-1.8.3-18.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7ba06ef6bbf6647053953d03c4ab5b7f867505bd03f153baa4778c5b448b1e66"

URI_ldns = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ldns-1.8.3-18.el10.x86_64_v2.rpm;name=ldns;unpack=0"
SRC_URI += "${URI_ldns}"
SRC_URI[ldns.sha256sum] = "b3a535a7dbd787bb36b5de450c577708cfc2e1597dc4cee33938a418ee4fcb16"
RDEPENDS:ldns = " \
 glibc \
 openssl-libs \
 ca-certificates \
"

URI_ldns-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ldns-devel-1.8.3-18.el10.x86_64_v2.rpm;name=ldns-devel;unpack=0"
SRC_URI += "${URI_ldns-devel}"
SRC_URI[ldns-devel.sha256sum] = "f4bc0e9979dd94d35d712c7c6aeb5b5788846234a002ca63b1f6bc3dd9307c0b"
RDEPENDS:ldns-devel = " \
 openssl-devel \
 bash \
 pkgconf-pkg-config \
 ldns \
"

URI_ldns-doc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ldns-doc-1.8.3-18.el10.noarch.rpm;name=ldns-doc;unpack=0"
SRC_URI += "${URI_ldns-doc}"
SRC_URI[ldns-doc.sha256sum] = "e2b614646106982b624b16dc496580749c9368ed073ba5e0ac58ce8858667647"
RDEPENDS:ldns-doc = ""

URI_ldns-utils = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ldns-utils-1.8.3-18.el10.x86_64_v2.rpm;name=ldns-utils;unpack=0"
SRC_URI += "${URI_ldns-utils}"
SRC_URI[ldns-utils.sha256sum] = "93d866a3bb8f8bab2988475236d56748c2523abb4a703bead81cbb1ff3bb029b"
RDEPENDS:ldns-utils = " \
 glibc \
 openssl-libs \
 libpcap \
 ldns \
"

URI_perl-ldns = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/perl-ldns-1.8.3-18.el10.x86_64_v2.rpm;name=perl-ldns;unpack=0"
SRC_URI += "${URI_perl-ldns}"
SRC_URI[perl-ldns.sha256sum] = "e0cb6891c63c0f07806d1154ea668753d71a5e23e342e67084232c43099d1900"
RDEPENDS:perl-ldns = " \
 perl-libs \
 perl-Carp \
 ldns \
 perl-ldns \
 perl-AutoLoader \
 glibc \
 perl-Exporter \
"

URI_python3-ldns = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/python3-ldns-1.8.3-18.el10.x86_64_v2.rpm;name=python3-ldns;unpack=0"
SRC_URI += "${URI_python3-ldns}"
SRC_URI[python3-ldns.sha256sum] = "f9c2ff603504527d69b6a377b23438aae0cd0097d031d793882be06e9d8a4438"
RDEPENDS:python3-ldns = " \
 python3 \
 ldns \
 openssl-libs \
 python3-libs \
 glibc \
"
