# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libaio"
PE = "0"
PV = "0.3.111"
PR = "22.el10"
PACKAGES = "libaio libaio-devel"
PROVIDES = "rpm/libaio rpm/libaio-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/libaio-0.3.111-22.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "892fcbc315c718ff3d9bd5c2a0df021253c02886136a4a81cec531ba2fed893b"

URI_libaio = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libaio-0.3.111-22.el10.x86_64_v2.rpm;name=libaio;unpack=0"
SRC_URI += "${URI_libaio}"
SRC_URI[libaio.sha256sum] = "0f28f8d1b4db56ff3dad35aba14fa7648faf3ba5cea3b0f9d4a40f0ede15d782"
RDEPENDS:libaio = " \
 glibc \
"

URI_libaio-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libaio-devel-0.3.111-22.el10.x86_64_v2.rpm;name=libaio-devel;unpack=0"
SRC_URI += "${URI_libaio-devel}"
SRC_URI[libaio-devel.sha256sum] = "e4ab03f413a634cc8ca1a1dcdf720943d8aaa10598c30da8599225cd0f9ac42e"
RDEPENDS:libaio-devel = " \
 libaio \
"
