# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libatomic_ops"
PE = "0"
PV = "7.8.2"
PR = "5.el10"
PACKAGES = "libatomic_ops libatomic_ops-devel libatomic_ops-static"
PROVIDES = "rpm/libatomic_ops rpm/libatomic_ops-devel rpm/libatomic_ops-static"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/libatomic_ops-7.8.2-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7a3e374bd5aa3debfca1081cbb064323d1637088f6d6c273d9221971cc45c63f"

URI_libatomic_ops = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libatomic_ops-7.8.2-5.el10.x86_64_v2.rpm;name=libatomic_ops;unpack=0"
SRC_URI += "${URI_libatomic_ops}"
SRC_URI[libatomic_ops.sha256sum] = "74bd16fc0425bbb680de6a3ed9d5ac78d2cfb290a956fbc2cac8063a5f488dc9"
RDEPENDS:libatomic_ops = " \
 glibc \
"

URI_libatomic_ops-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libatomic_ops-devel-7.8.2-5.el10.x86_64_v2.rpm;name=libatomic_ops-devel;unpack=0"
SRC_URI += "${URI_libatomic_ops-devel}"
SRC_URI[libatomic_ops-devel.sha256sum] = "4fc55f973d53bb8e94f8fc428647842bed452a291b8b0c455187c4201233855c"
RDEPENDS:libatomic_ops-devel = " \
 libatomic_ops \
 pkgconf-pkg-config \
"

URI_libatomic_ops-static = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libatomic_ops-static-7.8.2-5.el10.x86_64_v2.rpm;name=libatomic_ops-static;unpack=0"
SRC_URI += "${URI_libatomic_ops-static}"
SRC_URI[libatomic_ops-static.sha256sum] = "68d770a4184ee43ca77dfe99246ea7fb20a1c39bfe469ec947f40c89d7bceb6a"
RDEPENDS:libatomic_ops-static = " \
 libatomic_ops-devel \
"
