# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libbpf"
PE = "2"
PV = "1.5.0"
PR = "4.el10"
PACKAGES = "libbpf libbpf-devel libbpf-static"
PROVIDES = "rpm/libbpf rpm/libbpf-devel rpm/libbpf-static"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/libbpf-1.5.0-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4524d4653929cf0ae3f66f5d19f4050dd30ac7db2b07ed1a97d72ab750bca573"

URI_libbpf = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libbpf-1.5.0-4.el10.x86_64_v2.rpm;name=libbpf;unpack=0"
SRC_URI += "${URI_libbpf}"
SRC_URI[libbpf.sha256sum] = "6cca1a44206ad1d63a707728aa82ca9b11aa467f7b9fb7e922bcf05024bd379c"
RDEPENDS:libbpf = " \
 glibc \
 zlib-ng-compat \
 elfutils-libelf \
"

URI_libbpf-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libbpf-devel-1.5.0-4.el10.x86_64_v2.rpm;name=libbpf-devel;unpack=0"
SRC_URI += "${URI_libbpf-devel}"
SRC_URI[libbpf-devel.sha256sum] = "f86c7e76d59436b2a8d850584444e333014b5304d76c980af7300dd8bdc4298c"
RDEPENDS:libbpf-devel = " \
 zlib-ng-compat \
 zlib-ng-compat-devel \
 libbpf \
 pkgconf-pkg-config \
 kernel-headers \
 elfutils-libelf-devel \
"

URI_libbpf-static = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libbpf-static-1.5.0-4.el10.x86_64_v2.rpm;name=libbpf-static;unpack=0"
SRC_URI += "${URI_libbpf-static}"
SRC_URI[libbpf-static.sha256sum] = "2d8ecb386780081fe5d5076da9c953de4c493ea177c628bdbc4eea3bc347685b"
RDEPENDS:libbpf-static = " \
 libbpf-devel \
"
