# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libcupsfilters"
PE = "1"
PV = "2.0.0"
PR = "10.el10"
PACKAGES = "libcupsfilters libcupsfilters-devel"
PROVIDES = "rpm/libcupsfilters rpm/libcupsfilters-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libcupsfilters-2.0.0-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b6f09eb62e505d6f01c6639ff08138020a5e623c23562d13dc8d40257f5892f2"

URI_libcupsfilters = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libcupsfilters-2.0.0-10.el10.x86_64_v2.rpm;name=libcupsfilters;unpack=0"
SRC_URI += "${URI_libcupsfilters}"
SRC_URI[libcupsfilters.sha256sum] = "46d6b6bca3c81cc3f68288fcefcfe224b82b46a7de0851630dccf82e794554d9"
RDEPENDS:libcupsfilters = " \
 qpdf-libs \
 lcms2 \
 libpng \
 cups-filesystem \
 libgcc \
 cups-libs \
 ghostscript \
 fontconfig \
 poppler-cpp \
 libstdc++ \
 colord \
 libexif \
 glibc \
 libjpeg-turbo \
 dbus-libs \
 libtiff \
"

URI_libcupsfilters-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libcupsfilters-devel-2.0.0-10.el10.x86_64_v2.rpm;name=libcupsfilters-devel;unpack=0"
SRC_URI += "${URI_libcupsfilters-devel}"
SRC_URI[libcupsfilters-devel.sha256sum] = "6b761f5a88a6ca08c78eaa5e537ab6755962947fe87c53bae14a4631dc79bf75"
RDEPENDS:libcupsfilters-devel = " \
 pkgconf-pkg-config \
 libcupsfilters \
"
