# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libdnf"
PE = "0"
PV = "0.73.1"
PR = "9.el10_0.alma.1"
PACKAGES = "libdnf python3-hawkey python3-libdnf libdnf-devel"
PROVIDES = "rpm/libdnf rpm/python3-hawkey rpm/python3-libdnf rpm/libdnf-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/libdnf-0.73.1-9.el10_0.alma.1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "49ff76e950a2fef7167cafcfb99431ed780fddb6292e5846d5548f58f6d25cab"

URI_libdnf = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libdnf-0.73.1-9.el10_0.alma.1.x86_64_v2.rpm;name=libdnf;unpack=0"
SRC_URI += "${URI_libdnf}"
SRC_URI[libdnf.sha256sum] = "6891d6fb87a237e37dd26727aad7df14a67fe7a9dd98299e1d65d463355e7800"
RDEPENDS:libdnf = " \
 libsolv \
 libgcc \
 json-c \
 libmodulemd \
 sqlite-libs \
 libstdc++ \
 glib2 \
 librepo \
 glibc \
 rpm-libs \
 libsmartcols \
"

URI_python3-hawkey = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-hawkey-0.73.1-9.el10_0.alma.1.x86_64_v2.rpm;name=python3-hawkey;unpack=0"
SRC_URI += "${URI_python3-hawkey}"
SRC_URI[python3-hawkey.sha256sum] = "de84af8adf2be1179f8ddaee63f4994a75500ee1a7482b5dc439500ca7f3b683"
RDEPENDS:python3-hawkey = " \
 python3 \
 libsolv \
 python3-libdnf \
 libgcc \
 python3-libs \
 libstdc++ \
 glib2 \
 glibc \
 libdnf \
"

URI_python3-libdnf = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-libdnf-0.73.1-9.el10_0.alma.1.x86_64_v2.rpm;name=python3-libdnf;unpack=0"
SRC_URI += "${URI_python3-libdnf}"
SRC_URI[python3-libdnf.sha256sum] = "835708a3c0ff9fd41ab15a1be0a3ece979f935e4a07d0f94311be9040987e3a4"
RDEPENDS:python3-libdnf = " \
 python3 \
 libgcc \
 python3-libs \
 libstdc++ \
 glibc \
 libdnf \
 libsmartcols \
"

URI_libdnf-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libdnf-devel-0.73.1-9.el10_0.alma.1.x86_64_v2.rpm;name=libdnf-devel;unpack=0"
SRC_URI += "${URI_libdnf-devel}"
SRC_URI[libdnf-devel.sha256sum] = "64cc24911ab60ea01d04985a15822b226733c070cef3f89b5b2c1c2a67e21bbc"
RDEPENDS:libdnf-devel = " \
 glib2-devel \
 pkgconf-pkg-config \
 libsolv-devel \
 rpm-devel \
 libdnf \
 librepo-devel \
 sqlite-devel \
"
