# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libedit"
PE = "0"
PV = "3.1"
PR = "52.20230828cvs.el10"
PACKAGES = "libedit libedit-devel"
PROVIDES = "rpm/libedit rpm/libedit-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/libedit-3.1-52.20230828cvs.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4857400a31fafab98df013b27cf36e5655b5a1cdeabb1f04d3811fc7f0e02c52"

URI_libedit = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libedit-3.1-52.20230828cvs.el10.x86_64_v2.rpm;name=libedit;unpack=0"
SRC_URI += "${URI_libedit}"
SRC_URI[libedit.sha256sum] = "42721020101064bd8106878264cf1b547128ea705f3f8bf13434d53ded854072"
RDEPENDS:libedit = " \
 glibc \
 ncurses-libs \
"

URI_libedit-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libedit-devel-3.1-52.20230828cvs.el10.x86_64_v2.rpm;name=libedit-devel;unpack=0"
SRC_URI += "${URI_libedit-devel}"
SRC_URI[libedit-devel.sha256sum] = "d14f5adcb23a303f0828e7f4c5b11bf1abc42a92c4aca5705f9cb89eb56be0a6"
RDEPENDS:libedit-devel = " \
 ncurses-devel \
 pkgconf-pkg-config \
 libedit \
"
