# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libexif"
PE = "0"
PV = "0.6.24"
PR = "9.el10"
PACKAGES = "libexif libexif-devel libexif-doc"
PROVIDES = "rpm/libexif rpm/libexif-devel rpm/libexif-doc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libexif-0.6.24-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0dc5f0386308d477580fa43b77e4835ebe76b21acc7f3cf2a0a5400a54474f7c"

URI_libexif = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libexif-0.6.24-9.el10.x86_64_v2.rpm;name=libexif;unpack=0"
SRC_URI += "${URI_libexif}"
SRC_URI[libexif.sha256sum] = "433ee71fac7b984f6044f364ca8def4d2b547eedcccbd7d299ba427d49c35fad"
RDEPENDS:libexif = " \
 glibc \
"

URI_libexif-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libexif-devel-0.6.24-9.el10.x86_64_v2.rpm;name=libexif-devel;unpack=0"
SRC_URI += "${URI_libexif-devel}"
SRC_URI[libexif-devel.sha256sum] = "c65fcf83d520977043c6459fafdd62bee9c98be7a3b2867fe78d4ba77c841e26"
RDEPENDS:libexif-devel = " \
 pkgconf-pkg-config \
 libexif \
"

URI_libexif-doc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libexif-doc-0.6.24-9.el10.x86_64_v2.rpm;name=libexif-doc;unpack=0"
SRC_URI += "${URI_libexif-doc}"
SRC_URI[libexif-doc.sha256sum] = "7031ff0e32f17bfb87dfbeb009575ed672ea7233b2f8ca40cdac2f1983c75e28"
RDEPENDS:libexif-doc = " \
 libexif \
"
