# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libei"
PE = "0"
PV = "1.3.0"
PR = "1.el10"
PACKAGES = "libei libeis liboeffis libei-devel libeis-devel liboeffis-devel libei-utils"
PROVIDES = "rpm/libei rpm/libeis rpm/liboeffis rpm/libei-devel rpm/libeis-devel rpm/liboeffis-devel rpm/libei-utils"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libei-1.3.0-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "62b2302a452eded16da606d1eeb212bb70257232e83b266f883fe07945f21ca5"

URI_libei = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libei-1.3.0-1.el10.x86_64_v2.rpm;name=libei;unpack=0"
SRC_URI += "${URI_libei}"
SRC_URI[libei.sha256sum] = "0c1657049e027887abf44c36aabb0ae47309c37c4774eb907f051f3a9b19ddce"
RDEPENDS:libei = " \
 glibc \
 libgcc \
"

URI_libeis = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libeis-1.3.0-1.el10.x86_64_v2.rpm;name=libeis;unpack=0"
SRC_URI += "${URI_libeis}"
SRC_URI[libeis.sha256sum] = "29829309f7d09fa39b9f4d381807695340fb9236f5fcd7564a5663632af51723"
RDEPENDS:libeis = " \
 glibc \
 libgcc \
"

URI_liboeffis = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/liboeffis-1.3.0-1.el10.x86_64_v2.rpm;name=liboeffis;unpack=0"
SRC_URI += "${URI_liboeffis}"
SRC_URI[liboeffis.sha256sum] = "f55312c2c7000da89c6f5b97c9cf6fb22cdc439159a0e72a9df1d046573daf69"
RDEPENDS:liboeffis = " \
 glibc \
 libgcc \
 systemd-libs \
"

URI_libei-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libei-devel-1.3.0-1.el10.x86_64_v2.rpm;name=libei-devel;unpack=0"
SRC_URI += "${URI_libei-devel}"
SRC_URI[libei-devel.sha256sum] = "ca24de50a0f3e0c95db90c0c182158600d375e17d8890dde7866077860e65f71"
RDEPENDS:libei-devel = " \
 pkgconf-pkg-config \
 libei \
"

URI_libeis-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libeis-devel-1.3.0-1.el10.x86_64_v2.rpm;name=libeis-devel;unpack=0"
SRC_URI += "${URI_libeis-devel}"
SRC_URI[libeis-devel.sha256sum] = "c42edb5dffba652410a2fcdfa4d242c18265c11b6577b6e324facc37f166e72f"
RDEPENDS:libeis-devel = " \
 libeis \
 pkgconf-pkg-config \
"

URI_liboeffis-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/liboeffis-devel-1.3.0-1.el10.x86_64_v2.rpm;name=liboeffis-devel;unpack=0"
SRC_URI += "${URI_liboeffis-devel}"
SRC_URI[liboeffis-devel.sha256sum] = "2875aaa7ed8f8037748508856a3e9c5966ba7b8c0fabbc1f415fa64690067e94"
RDEPENDS:liboeffis-devel = " \
 systemd-devel \
 liboeffis \
 pkgconf-pkg-config \
"

URI_libei-utils = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libei-utils-1.3.0-1.el10.x86_64_v2.rpm;name=libei-utils;unpack=0"
SRC_URI += "${URI_libei-utils}"
SRC_URI[libei-utils.sha256sum] = "aa75e9f4bd76a7a1cff593e9c25588dc7da50f9893f9740c138da4dafadd830c"
RDEPENDS:libei-utils = " \
 glibc \
 libgcc \
 libei \
"
