# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libfprint"
PE = "0"
PV = "1.94.9"
PR = "1.el10_0"
PACKAGES = "libfprint libfprint-devel"
PROVIDES = "rpm/libfprint rpm/libfprint-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libfprint-1.94.9-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "94f744c1b6fce44f0cb5ca4dd0c1cb331a1021c6024cac634ac6ac6c592a3027"

URI_libfprint = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libfprint-1.94.9-1.el10_0.x86_64_v2.rpm;name=libfprint;unpack=0"
SRC_URI += "${URI_libfprint}"
SRC_URI[libfprint.sha256sum] = "5dbc53bc82577511a6396bc2fe3df2caeaf88b43ff8cff043b771a6a5ab1960a"
RDEPENDS:libfprint = " \
 openssl-libs \
 libgcc \
 libgudev \
 libgusb \
 glib2 \
 glibc \
 pixman \
"

URI_libfprint-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libfprint-devel-1.94.9-1.el10_0.x86_64_v2.rpm;name=libfprint-devel;unpack=0"
SRC_URI += "${URI_libfprint-devel}"
SRC_URI[libfprint-devel.sha256sum] = "1742c7b42acd5229b87994c8a6f0c202a4880d18f3f01ab43a7de04ea84a442b"
RDEPENDS:libfprint-devel = " \
 glib2-devel \
 pkgconf-pkg-config \
 libfprint \
"
