# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libgphoto2"
PE = "0"
PV = "2.5.30"
PR = "9.el10"
PACKAGES = "libgphoto2 libgphoto2-devel"
PROVIDES = "rpm/libgphoto2 rpm/libgphoto2-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libgphoto2-2.5.30-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "6233367f3d425c637dc90f478f705e3113f5ed1a76af31e0b3ed33e9bfe99729"

URI_libgphoto2 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libgphoto2-2.5.30-9.el10.x86_64_v2.rpm;name=libgphoto2;unpack=0"
SRC_URI += "${URI_libgphoto2}"
SRC_URI[libgphoto2.sha256sum] = "d50f9a7b7ce7fbc0b854a71147b57ddb84699314bd323866ea98937da8cad880"
RDEPENDS:libgphoto2 = " \
 gd \
 libtool-ltdl \
 libxml2 \
 libexif \
 bash \
 libcurl \
 glibc \
 libjpeg-turbo \
 lockdev \
 libusb1 \
"

URI_libgphoto2-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libgphoto2-devel-2.5.30-9.el10.x86_64_v2.rpm;name=libgphoto2-devel;unpack=0"
SRC_URI += "${URI_libgphoto2-devel}"
SRC_URI[libgphoto2-devel.sha256sum] = "3d5858c9755c9a85e1adaac7197c76d3d98655b4c430f66c10d2f5f3f029eed7"
RDEPENDS:libgphoto2-devel = " \
 libgphoto2-devel \
 pkgconf-pkg-config \
 libgphoto2 \
 bash \
 libexif-devel \
"
