# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libglvnd"
PE = "1"
PV = "1.7.0"
PR = "7.el10"
PACKAGES = "libglvnd libglvnd-core-devel libglvnd-devel libglvnd-egl libglvnd-gles libglvnd-glx libglvnd-opengl"
PROVIDES = "rpm/libglvnd rpm/libglvnd-core-devel rpm/libglvnd-devel rpm/libglvnd-egl rpm/libglvnd-gles rpm/libglvnd-glx rpm/libglvnd-opengl"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libglvnd-1.7.0-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e82cab48d5d1bec9d04ae22dc2fdcad31ad2faec68357b7cc74f1722c9601716"

URI_libglvnd = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libglvnd-1.7.0-7.el10.x86_64_v2.rpm;name=libglvnd;unpack=0"
SRC_URI += "${URI_libglvnd}"
SRC_URI[libglvnd.sha256sum] = "8dc7bed1a65cd165b77dd07138296adae26b7ffdcf48e5cef999e225908965ea"
RDEPENDS:libglvnd = " \
 glibc \
"

URI_libglvnd-core-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libglvnd-core-devel-1.7.0-7.el10.x86_64_v2.rpm;name=libglvnd-core-devel;unpack=0"
SRC_URI += "${URI_libglvnd-core-devel}"
SRC_URI[libglvnd-core-devel.sha256sum] = "7a9c87259266099736cd4f47d2c4dbf0069cbbb05dbc7e2ba85654353cb1463b"
RDEPENDS:libglvnd-core-devel = " \
 pkgconf-pkg-config \
"

URI_libglvnd-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libglvnd-devel-1.7.0-7.el10.x86_64_v2.rpm;name=libglvnd-devel;unpack=0"
SRC_URI += "${URI_libglvnd-devel}"
SRC_URI[libglvnd-devel.sha256sum] = "30d9b6ca17a41c460aa0c2814213179e275b1618aa8e129a8b4ea43b1099cb28"
RDEPENDS:libglvnd-devel = " \
 libglvnd \
 libglvnd-core-devel \
 libglvnd-egl \
 libglvnd-gles \
 libglvnd-glx \
 libglvnd-opengl \
 pkgconf-pkg-config \
 libX11-devel \
"

URI_libglvnd-egl = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libglvnd-egl-1.7.0-7.el10.x86_64_v2.rpm;name=libglvnd-egl;unpack=0"
SRC_URI += "${URI_libglvnd-egl}"
SRC_URI[libglvnd-egl.sha256sum] = "6920fb6db70aa9d5de54cfef295a44960bb9b59c330a6049e4191deb02663fbb"
RDEPENDS:libglvnd-egl = " \
 glibc \
 mesa-libEGL \
 libglvnd \
"

URI_libglvnd-gles = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libglvnd-gles-1.7.0-7.el10.x86_64_v2.rpm;name=libglvnd-gles;unpack=0"
SRC_URI += "${URI_libglvnd-gles}"
SRC_URI[libglvnd-gles.sha256sum] = "3cfa90c2ccd60998ac9a11e85516bd76c5542beb1a3d35d9806a87b00d9987b2"
RDEPENDS:libglvnd-gles = " \
 glibc \
 mesa-libEGL \
 libglvnd \
"

URI_libglvnd-glx = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libglvnd-glx-1.7.0-7.el10.x86_64_v2.rpm;name=libglvnd-glx;unpack=0"
SRC_URI += "${URI_libglvnd-glx}"
SRC_URI[libglvnd-glx.sha256sum] = "64d7275eb7b3cda8925d2099b7fccbd52a7eff5be09e6ab105a2fe9880bde9c5"
RDEPENDS:libglvnd-glx = " \
 libglvnd \
 mesa-libGL \
 libX11 \
 glibc \
 libXext \
"

URI_libglvnd-opengl = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libglvnd-opengl-1.7.0-7.el10.x86_64_v2.rpm;name=libglvnd-opengl;unpack=0"
SRC_URI += "${URI_libglvnd-opengl}"
SRC_URI[libglvnd-opengl.sha256sum] = "c1aaf40895bca81144cfd268c1265b4ddcef2e17e6e79ec4c1155460f82c3475"
RDEPENDS:libglvnd-opengl = " \
 glibc \
 libglvnd \
"
