# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libldac"
PE = "0"
PV = "2.0.2.3"
PR = "17.el10"
PACKAGES = "libldac libldac-devel"
PROVIDES = "rpm/libldac rpm/libldac-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libldac-2.0.2.3-17.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "c94db0c90282c841eecc31a40502091672f279f01d47c92727e408872129b03d"

URI_libldac = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libldac-2.0.2.3-17.el10.x86_64_v2.rpm;name=libldac;unpack=0"
SRC_URI += "${URI_libldac}"
SRC_URI[libldac.sha256sum] = "219662b2291bfec8326b8115a91b542a279e23037b7462aeba0e85b8dc33bf22"
RDEPENDS:libldac = " \
 glibc \
"

URI_libldac-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libldac-devel-2.0.2.3-17.el10.x86_64_v2.rpm;name=libldac-devel;unpack=0"
SRC_URI += "${URI_libldac-devel}"
SRC_URI[libldac-devel.sha256sum] = "a122dee121de885f33113509929ef0fae7a5d842dcbf8a73bac1a10c97f9e23d"
RDEPENDS:libldac-devel = " \
 libldac \
 pkgconf-pkg-config \
"
