# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "liblognorm"
PE = "0"
PV = "2.0.6"
PR = "15.el10"
PACKAGES = "liblognorm liblognorm-doc liblognorm-devel liblognorm-utils"
PROVIDES = "rpm/liblognorm rpm/liblognorm-doc rpm/liblognorm-devel rpm/liblognorm-utils"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/liblognorm-2.0.6-15.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2547f6141400ec4b2243d833d3b4afcd82ccdb475133037050a0995bde358707"

URI_liblognorm = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/liblognorm-2.0.6-15.el10.x86_64_v2.rpm;name=liblognorm;unpack=0"
SRC_URI += "${URI_liblognorm}"
SRC_URI[liblognorm.sha256sum] = "c4862fd6a5584a3942b0106d3e0ab25a58eb486c5153358905f82889c370ca6a"
RDEPENDS:liblognorm = " \
 glibc \
 libfastjson \
 libestr \
 pcre2 \
"

URI_liblognorm-doc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/liblognorm-doc-2.0.6-15.el10.x86_64_v2.rpm;name=liblognorm-doc;unpack=0"
SRC_URI += "${URI_liblognorm-doc}"
SRC_URI[liblognorm-doc.sha256sum] = "f718330b1c66f7df98b64339db373dcd8ea85f591e254d70e5abc1872f6bcd2f"
RDEPENDS:liblognorm-doc = ""

URI_liblognorm-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/liblognorm-devel-2.0.6-15.el10.x86_64_v2.rpm;name=liblognorm-devel;unpack=0"
SRC_URI += "${URI_liblognorm-devel}"
SRC_URI[liblognorm-devel.sha256sum] = "e3665baa410eb58b4b6d335a0b402cc4a91fdfa8cd0c30c1a45fab6645e6ed43"
RDEPENDS:liblognorm-devel = " \
 json-c-devel \
 liblognorm \
 pkgconf-pkg-config \
 libestr-devel \
 libfastjson-devel \
"

URI_liblognorm-utils = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/liblognorm-utils-2.0.6-15.el10.x86_64_v2.rpm;name=liblognorm-utils;unpack=0"
SRC_URI += "${URI_liblognorm-utils}"
SRC_URI[liblognorm-utils.sha256sum] = "820429ee18cb81b093f5d3879b1e92606824a786f9f92b4abcaf50b391b6c5d3"
RDEPENDS:liblognorm-utils = " \
 glibc \
 libfastjson \
 libestr \
 liblognorm \
"
