# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libmtp"
PE = "0"
PV = "1.1.19"
PR = "9.el10"
PACKAGES = "libmtp libmtp-devel libmtp-examples"
PROVIDES = "rpm/libmtp rpm/libmtp-devel rpm/libmtp-examples"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libmtp-1.1.19-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "258b6515100a99eac63790cb7078d90602b7d45534da99ae274be473b4efb39c"

URI_libmtp = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libmtp-1.1.19-9.el10.x86_64_v2.rpm;name=libmtp;unpack=0"
SRC_URI += "${URI_libmtp}"
SRC_URI[libmtp.sha256sum] = "6f84ef864b38f0df976b6809aca7756fc11c9c7e7f31f29071105edd493766e6"
RDEPENDS:libmtp = " \
 glibc \
 libusb1 \
"

URI_libmtp-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libmtp-devel-1.1.19-9.el10.x86_64_v2.rpm;name=libmtp-devel;unpack=0"
SRC_URI += "${URI_libmtp-devel}"
SRC_URI[libmtp-devel.sha256sum] = "662debdf02202e0250aff436cb75910b9840128dbf22b7cada1dbc278f26e357"
RDEPENDS:libmtp-devel = " \
 libusb1-devel \
 libmtp \
 pkgconf-pkg-config \
"

URI_libmtp-examples = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libmtp-examples-1.1.19-9.el10.x86_64_v2.rpm;name=libmtp-examples;unpack=0"
SRC_URI += "${URI_libmtp-examples}"
SRC_URI[libmtp-examples.sha256sum] = "387858c199bdf742afd01033fb2d251f6d23122f469139b66e0deb36bda76e56"
RDEPENDS:libmtp-examples = " \
 glibc \
 libmtp \
"
