# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libnsl2"
PE = "0"
PV = "2.0.1"
PR = "2.el10"
PACKAGES = "libnsl2 libnsl2-devel"
PROVIDES = "rpm/libnsl2 rpm/libnsl2-devel"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/libnsl2-2.0.1-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "71bb27d664fbc9c0b5c7f5e5d387f894d547ac565bec6da5d4110d8b18b4507e"

URI_libnsl2 = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libnsl2-2.0.1-2.el10.x86_64_v2.rpm;name=libnsl2;unpack=0"
SRC_URI += "${URI_libnsl2}"
SRC_URI[libnsl2.sha256sum] = "afca425e0f533d59a6fc1eb7addd0c37734410909f2dc6a749002d8893307fd0"
RDEPENDS:libnsl2 = " \
 glibc \
 libtirpc \
"

URI_libnsl2-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libnsl2-devel-2.0.1-2.el10.x86_64_v2.rpm;name=libnsl2-devel;unpack=0"
SRC_URI += "${URI_libnsl2-devel}"
SRC_URI[libnsl2-devel.sha256sum] = "851629dfd3df47330671976cd6f52961143ccd34e56afd7ef0879570584d70d7"
RDEPENDS:libnsl2-devel = " \
 libtirpc-devel \
 pkgconf-pkg-config \
 libnsl2 \
"
