# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libnvme"
PE = "0"
PV = "1.11.1"
PR = "1.el10"
PACKAGES = "libnvme python3-libnvme libnvme-devel libnvme-doc"
PROVIDES = "rpm/libnvme rpm/python3-libnvme rpm/libnvme-devel rpm/libnvme-doc"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/libnvme-1.11.1-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "82236c2222c6b7b027279708f08399c67de071e2fb090854772b8cd40d3b90e6"

URI_libnvme = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libnvme-1.11.1-1.el10.x86_64_v2.rpm;name=libnvme;unpack=0"
SRC_URI += "${URI_libnvme}"
SRC_URI[libnvme.sha256sum] = "fa1fa9be60cf39703fc3ba8550ade09e52b8e4690843c504e85ffdf9706ab6b9"
RDEPENDS:libnvme = " \
 keyutils-libs \
 openssl-libs \
 libgcc \
 json-c \
 glibc \
 dbus-libs \
"

URI_python3-libnvme = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/python3-libnvme-1.11.1-1.el10.x86_64_v2.rpm;name=python3-libnvme;unpack=0"
SRC_URI += "${URI_python3-libnvme}"
SRC_URI[python3-libnvme.sha256sum] = "1f527ee6d1e67b8e05480f94a7f9ea4de9e23bc4121c9f31b8604319be4f691a"
RDEPENDS:python3-libnvme = " \
 glibc \
 python3 \
 libnvme \
"

URI_libnvme-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libnvme-devel-1.11.1-1.el10.x86_64_v2.rpm;name=libnvme-devel;unpack=0"
SRC_URI += "${URI_libnvme-devel}"
SRC_URI[libnvme-devel.sha256sum] = "8fafd335305cce2d219706879b2f1c5d249cfeda8a41d27e1f8406583bfefcb3"
RDEPENDS:libnvme-devel = " \
 pkgconf-pkg-config \
 openssl-devel \
 dbus-devel \
 keyutils-libs-devel \
 libnvme \
 json-c-devel \
"

URI_libnvme-doc = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libnvme-doc-1.11.1-1.el10.noarch.rpm;name=libnvme-doc;unpack=0"
SRC_URI += "${URI_libnvme-doc}"
SRC_URI[libnvme-doc.sha256sum] = "3c420dc798939fed4d99ee84dec1b314dd9a974127ac80ca799636c55cab6d82"
RDEPENDS:libnvme-doc = ""
