# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libopenraw"
PE = "0"
PV = "0.1.3"
PR = "19.el10"
PACKAGES = "libopenraw libopenraw-devel libopenraw-gnome libopenraw-gnome-devel libopenraw-pixbuf-loader"
PROVIDES = "rpm/libopenraw rpm/libopenraw-devel rpm/libopenraw-gnome rpm/libopenraw-gnome-devel rpm/libopenraw-pixbuf-loader"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libopenraw-0.1.3-19.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f345a0ab2e7adfd4e9d099a50fd38dc759ae9ab23700122478e6aa4c59792c25"

URI_libopenraw = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libopenraw-0.1.3-19.el10.x86_64_v2.rpm;name=libopenraw;unpack=0"
SRC_URI += "${URI_libopenraw}"
SRC_URI[libopenraw.sha256sum] = "6aed0be1771efa20e54684179862906ec52bc072124b875bda4d0ac1af8500e6"
RDEPENDS:libopenraw = " \
 glibc \
 libgcc \
 libjpeg-turbo \
 libstdc++ \
"

URI_libopenraw-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libopenraw-devel-0.1.3-19.el10.x86_64_v2.rpm;name=libopenraw-devel;unpack=0"
SRC_URI += "${URI_libopenraw-devel}"
SRC_URI[libopenraw-devel.sha256sum] = "fc1aa9103332ec27feb495ce7c88271cd96384ec6f535e8966882a11721aa826"
RDEPENDS:libopenraw-devel = " \
 pkgconf-pkg-config \
 libopenraw \
"

URI_libopenraw-gnome = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libopenraw-gnome-0.1.3-19.el10.x86_64_v2.rpm;name=libopenraw-gnome;unpack=0"
SRC_URI += "${URI_libopenraw-gnome}"
SRC_URI[libopenraw-gnome.sha256sum] = "009693141927f791f9c49c88b99648cb7f6a81b4f1d12e4c145a38f742594f03"
RDEPENDS:libopenraw-gnome = " \
 glibc \
 glib2 \
 libopenraw \
 gdk-pixbuf2 \
"

URI_libopenraw-gnome-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libopenraw-gnome-devel-0.1.3-19.el10.x86_64_v2.rpm;name=libopenraw-gnome-devel;unpack=0"
SRC_URI += "${URI_libopenraw-gnome-devel}"
SRC_URI[libopenraw-gnome-devel.sha256sum] = "7a5011cb242bee9e48aab5e292c26f5839cc3f4250022ebb9aa3f49ab9a0affb"
RDEPENDS:libopenraw-gnome-devel = " \
 libopenraw-devel \
 pkgconf-pkg-config \
 libopenraw-gnome \
"

URI_libopenraw-pixbuf-loader = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libopenraw-pixbuf-loader-0.1.3-19.el10.x86_64_v2.rpm;name=libopenraw-pixbuf-loader;unpack=0"
SRC_URI += "${URI_libopenraw-pixbuf-loader}"
SRC_URI[libopenraw-pixbuf-loader.sha256sum] = "b03d9e73b02a8898e080fb1fe991af81164ac95033a6e99ecf25e0a0df59a596"
RDEPENDS:libopenraw-pixbuf-loader = " \
 glibc \
 glib2 \
 libopenraw \
 gdk-pixbuf2 \
"
