# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libpng"
PE = "2"
PV = "1.6.40"
PR = "8.el10"
PACKAGES = "libpng libpng-devel libpng-static libpng-tools"
PROVIDES = "rpm/libpng rpm/libpng-devel rpm/libpng-static rpm/libpng-tools"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libpng-1.6.40-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "8d2fa66106e40785268ffeff5e0bb09bf955980f852a5d9c09ddc6e3e04a7476"

URI_libpng = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libpng-1.6.40-8.el10.x86_64_v2.rpm;name=libpng;unpack=0"
SRC_URI += "${URI_libpng}"
SRC_URI[libpng.sha256sum] = "88bcd03a42c41eea8536b133cc4772e4f658e05e1344534e4b0457be1d2f7d65"
RDEPENDS:libpng = " \
 glibc \
 zlib-ng-compat \
"

URI_libpng-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libpng-devel-1.6.40-8.el10.x86_64_v2.rpm;name=libpng-devel;unpack=0"
SRC_URI += "${URI_libpng-devel}"
SRC_URI[libpng-devel.sha256sum] = "15557092543e32a4ea30aa97b3d10af642482eb66efe87d02be1055fdde7a215"
RDEPENDS:libpng-devel = " \
 zlib-ng-compat \
 libpng \
 zlib-ng-compat-devel \
 pkgconf-pkg-config \
 bash \
 glibc \
"

URI_libpng-static = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libpng-static-1.6.40-8.el10.x86_64_v2.rpm;name=libpng-static;unpack=0"
SRC_URI += "${URI_libpng-static}"
SRC_URI[libpng-static.sha256sum] = "6f9593c4ad4e897d9153442e07263be70e0c8f880720955f5758107fc7d6bc84"
RDEPENDS:libpng-static = " \
 libpng-devel \
"

URI_libpng-tools = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libpng-tools-1.6.40-8.el10.x86_64_v2.rpm;name=libpng-tools;unpack=0"
SRC_URI += "${URI_libpng-tools}"
SRC_URI[libpng-tools.sha256sum] = "679739e09df45e1010c5390bbdf4f9b19f2a4be5656fd54103927a393ed512e8"
RDEPENDS:libpng-tools = " \
 glibc \
 zlib-ng-compat \
 libpng \
"
