# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libppd"
PE = "1"
PV = "2.0.0"
PR = "10.el10"
PACKAGES = "libppd libppd-devel"
PROVIDES = "rpm/libppd rpm/libppd-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libppd-2.0.0-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "cf6d899d25e3e0a2e5a4b01442ae4dea68d6849cb0b6c2a9d343ee6b1b957788"

URI_libppd = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libppd-2.0.0-10.el10.x86_64_v2.rpm;name=libppd;unpack=0"
SRC_URI += "${URI_libppd}"
SRC_URI[libppd.sha256sum] = "4c4a581c4085bdf9d8e3f422b213fee92bf9ff109cf0e2d32b81ead58c460abf"
RDEPENDS:libppd = " \
 libgcc \
 cups-libs \
 cups \
 libstdc++ \
 poppler-utils \
 libcupsfilters \
 glibc \
 ghostscript \
"

URI_libppd-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libppd-devel-2.0.0-10.el10.x86_64_v2.rpm;name=libppd-devel;unpack=0"
SRC_URI += "${URI_libppd-devel}"
SRC_URI[libppd-devel.sha256sum] = "8b8ad62963505e9b830b532d02f70fd94068fba16cae26c16a909072dd6fd100"
RDEPENDS:libppd-devel = " \
 cups-devel \
 libppd \
 pkgconf-pkg-config \
 libcupsfilters-devel \
"
