# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libpaper"
PE = "1"
PV = "2.1.1"
PR = "7.el10"
PACKAGES = "libpaper libpaper-devel paper"
PROVIDES = "rpm/libpaper rpm/libpaper-devel rpm/paper"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libpaper-2.1.1-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "3329b7ba2af90920fcab5b3a1749adb08196bff3611063669bc8b87312ba0a0e"

URI_libpaper = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libpaper-2.1.1-7.el10.x86_64_v2.rpm;name=libpaper;unpack=0"
SRC_URI += "${URI_libpaper}"
SRC_URI[libpaper.sha256sum] = "e7036ef9879114ee94e94a475326043d8dee05066cf7b77d77f63a476beac5d2"
RDEPENDS:libpaper = " \
 glibc \
"

URI_libpaper-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libpaper-devel-2.1.1-7.el10.x86_64_v2.rpm;name=libpaper-devel;unpack=0"
SRC_URI += "${URI_libpaper-devel}"
SRC_URI[libpaper-devel.sha256sum] = "ac000109c10ddd3b69d5dcea6c9ab3729f37fb9d9c0615a8b34cf3390835794a"
RDEPENDS:libpaper-devel = " \
 libpaper \
"

URI_paper = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/paper-2.1.1-7.el10.x86_64_v2.rpm;name=paper;unpack=0"
SRC_URI += "${URI_paper}"
SRC_URI[paper.sha256sum] = "e5f4e1078606654388aa39e4a505696f407f53403c0abdd1edfce76f82fa3a72"
RDEPENDS:paper = " \
 glibc \
 libpaper \
"
