# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "librdkafka"
PE = "0"
PV = "2.1.1"
PR = "7.el10"
PACKAGES = "librdkafka librdkafka-devel"
PROVIDES = "rpm/librdkafka rpm/librdkafka-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/librdkafka-2.1.1-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "676b009c695146634b2e9610ddf920631b9a96d66aba3780bbdb979e6094f569"

URI_librdkafka = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/librdkafka-2.1.1-7.el10.x86_64_v2.rpm;name=librdkafka;unpack=0"
SRC_URI += "${URI_librdkafka}"
SRC_URI[librdkafka.sha256sum] = "1961c965630a04687b7eb561c6aee605438b37e0b593dfce50a36237fc05c132"
RDEPENDS:librdkafka = " \
 zlib-ng-compat \
 lz4-libs \
 openssl-libs \
 libgcc \
 libzstd \
 cyrus-sasl-lib \
 libstdc++ \
 glibc \
"

URI_librdkafka-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/librdkafka-devel-2.1.1-7.el10.x86_64_v2.rpm;name=librdkafka-devel;unpack=0"
SRC_URI += "${URI_librdkafka-devel}"
SRC_URI[librdkafka-devel.sha256sum] = "c6360f4b0a6f53b0269dc85f310490fe46f4606b00aeaccc03ae3319eb3fa516"
RDEPENDS:librdkafka-devel = " \
 librdkafka \
 zlib-ng-compat-devel \
 libzstd-devel \
 cyrus-sasl-devel \
 pkgconf-pkg-config \
 openssl-devel \
 librdkafka-devel \
 lz4-devel \
"
