# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libseccomp"
PE = "0"
PV = "2.5.3"
PR = "10.el10"
PACKAGES = "libseccomp libseccomp-devel libseccomp-static"
PROVIDES = "rpm/libseccomp rpm/libseccomp-devel rpm/libseccomp-static"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/libseccomp-2.5.3-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "3764401413327ba5a4f24bca82d553798476e731df39dad1ba96c53a28f8f6ec"

URI_libseccomp = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libseccomp-2.5.3-10.el10.x86_64_v2.rpm;name=libseccomp;unpack=0"
SRC_URI += "${URI_libseccomp}"
SRC_URI[libseccomp.sha256sum] = "36539f11ec9d00b07d7c23bfe94c5462ee4b465c4e4a2a77eeb64f438c0c7d18"
RDEPENDS:libseccomp = " \
 glibc \
"

URI_libseccomp-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libseccomp-devel-2.5.3-10.el10.x86_64_v2.rpm;name=libseccomp-devel;unpack=0"
SRC_URI += "${URI_libseccomp-devel}"
SRC_URI[libseccomp-devel.sha256sum] = "b871d84cf5fdef8768c96af199109dfa1930e9b7244cd6cbeee722992b2a1598"
RDEPENDS:libseccomp-devel = " \
 glibc \
 pkgconf-pkg-config \
 libseccomp \
"

URI_libseccomp-static = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libseccomp-static-2.5.3-10.el10.x86_64_v2.rpm;name=libseccomp-static;unpack=0"
SRC_URI += "${URI_libseccomp-static}"
SRC_URI[libseccomp-static.sha256sum] = "c65ddbe09f155d0bd88eed0641446d733447f4041f15b257ffb36a883f135bba"
RDEPENDS:libseccomp-static = " \
 libseccomp-devel \
"
