# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libsamplerate"
PE = "0"
PV = "0.2.2"
PR = "10.el10"
PACKAGES = "libsamplerate libsamplerate-devel"
PROVIDES = "rpm/libsamplerate rpm/libsamplerate-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libsamplerate-0.2.2-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "013f214931150457d5f7883030432a7c6d468a4dae5a8f1170c1af5414dc36fc"

URI_libsamplerate = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libsamplerate-0.2.2-10.el10.x86_64_v2.rpm;name=libsamplerate;unpack=0"
SRC_URI += "${URI_libsamplerate}"
SRC_URI[libsamplerate.sha256sum] = "b082b74654f803bee7737052c444f3aae8e3a7df96c24942b1e7344a6f6f297b"
RDEPENDS:libsamplerate = " \
 glibc \
"

URI_libsamplerate-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libsamplerate-devel-0.2.2-10.el10.x86_64_v2.rpm;name=libsamplerate-devel;unpack=0"
SRC_URI += "${URI_libsamplerate-devel}"
SRC_URI[libsamplerate-devel.sha256sum] = "102ea12bf2b709af6063d42e04c019cb1545c1c4679751b55379416a9f8d550b"
RDEPENDS:libsamplerate-devel = " \
 libsamplerate \
 pkgconf-pkg-config \
"
