# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libsndfile"
PE = "0"
PV = "1.2.2"
PR = "5.el10"
PACKAGES = "libsndfile libsndfile-utils libsndfile-devel"
PROVIDES = "rpm/libsndfile rpm/libsndfile-utils rpm/libsndfile-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libsndfile-1.2.2-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "cce57c459f18fbb6371f590f7f96f1c0ddf7fe5339efe83294229099f98c4809"

URI_libsndfile = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libsndfile-1.2.2-5.el10.x86_64_v2.rpm;name=libsndfile;unpack=0"
SRC_URI += "${URI_libsndfile}"
SRC_URI[libsndfile.sha256sum] = "75a596e2630a6c671e507d6461f44f294f2b3ed237c07a03c18ad69b685aa735"
RDEPENDS:libsndfile = " \
 libvorbis \
 libogg \
 lame-libs \
 gsm \
 flac-libs \
 glibc \
 opus \
 mpg123-libs \
"

URI_libsndfile-utils = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libsndfile-utils-1.2.2-5.el10.x86_64_v2.rpm;name=libsndfile-utils;unpack=0"
SRC_URI += "${URI_libsndfile-utils}"
SRC_URI[libsndfile-utils.sha256sum] = "dc3b4c0e5cae40a2dc36f7416013519960288268dd69d06b478b20416948f073"
RDEPENDS:libsndfile-utils = " \
 glibc \
 alsa-lib \
 libsndfile \
"

URI_libsndfile-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libsndfile-devel-1.2.2-5.el10.x86_64_v2.rpm;name=libsndfile-devel;unpack=0"
SRC_URI += "${URI_libsndfile-devel}"
SRC_URI[libsndfile-devel.sha256sum] = "bc1b5373e3196bd5ab32093a404056d708d20f47c5ddc6130bf08dfc7470f335"
RDEPENDS:libsndfile-devel = " \
 libogg-devel \
 pkgconf-pkg-config \
 mpg123-devel \
 libvorbis-devel \
 flac-devel \
 opus-devel \
 libsndfile \
"
