# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libserf"
PE = "0"
PV = "1.3.10"
PR = "7.el10"
PACKAGES = "libserf libserf-devel"
PROVIDES = "rpm/libserf rpm/libserf-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libserf-1.3.10-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1bac70d704d12ac586dae80c64cf2cc8bd5390e9468df48a6904041f563fb336"

URI_libserf = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libserf-1.3.10-7.el10.x86_64_v2.rpm;name=libserf;unpack=0"
SRC_URI += "${URI_libserf}"
SRC_URI[libserf.sha256sum] = "19f23e6558b0018e600e5729ee8eab2846ca385504d3db26b3262150e0eaff0e"
RDEPENDS:libserf = " \
 zlib-ng-compat \
 openssl-libs \
 apr \
 apr-util \
 krb5-libs \
 glibc \
"

URI_libserf-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libserf-devel-1.3.10-7.el10.x86_64_v2.rpm;name=libserf-devel;unpack=0"
SRC_URI += "${URI_libserf-devel}"
SRC_URI[libserf-devel.sha256sum] = "83e5636baadc1b4d5977b7909733ca51018213d86ba3fcee3df25adb78fbee0f"
RDEPENDS:libserf-devel = " \
 libserf \
 openssl-devel \
 pkgconf-pkg-config \
 apr-devel \
"
