# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libsrtp"
PE = "0"
PV = "2.3.0"
PR = "16.el10"
PACKAGES = "libsrtp libsrtp-devel libsrtp-tools"
PROVIDES = "rpm/libsrtp rpm/libsrtp-devel rpm/libsrtp-tools"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libsrtp-2.3.0-16.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f13aa71884e1889e9b370b00810448ee6d259a42633c926e8e39a29583bd5b57"

URI_libsrtp = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libsrtp-2.3.0-16.el10.x86_64_v2.rpm;name=libsrtp;unpack=0"
SRC_URI += "${URI_libsrtp}"
SRC_URI[libsrtp.sha256sum] = "aa1546a1753578f63a2b38b4c90919a972bc2ba7f48689504518af0b3f519e3c"
RDEPENDS:libsrtp = " \
 glibc \
 nss \
 nspr \
"

URI_libsrtp-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libsrtp-devel-2.3.0-16.el10.x86_64_v2.rpm;name=libsrtp-devel;unpack=0"
SRC_URI += "${URI_libsrtp-devel}"
SRC_URI[libsrtp-devel.sha256sum] = "dae3d9c9dcf5b7d1053dc28aac1261ed3bdba5cb00b126cce2783976bc0ead33"
RDEPENDS:libsrtp-devel = " \
 libsrtp \
 pkgconf-pkg-config \
"

URI_libsrtp-tools = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libsrtp-tools-2.3.0-16.el10.x86_64_v2.rpm;name=libsrtp-tools;unpack=0"
SRC_URI += "${URI_libsrtp-tools}"
SRC_URI[libsrtp-tools.sha256sum] = "8fdca9ca3878b09775cc7e20ba4c5d0bf315246a77cf0a061ef23fe0ef61c751"
RDEPENDS:libsrtp-tools = " \
 glibc \
 libsrtp \
 libpcap \
"
