# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libtracefs"
PE = "0"
PV = "1.8.0"
PR = "6.el10"
PACKAGES = "libtracefs libtracefs-devel"
PROVIDES = "rpm/libtracefs rpm/libtracefs-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/libtracefs-1.8.0-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a2d3a2b1af65611282795e1f638d9f155084793582a990aeebe182f502575689"

URI_libtracefs = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libtracefs-1.8.0-6.el10.x86_64_v2.rpm;name=libtracefs;unpack=0"
SRC_URI += "${URI_libtracefs}"
SRC_URI[libtracefs.sha256sum] = "40958664f7b1b62896aabd3582ea0c309076bc9d2d67ce96e51835763dccf95f"
RDEPENDS:libtracefs = " \
 glibc \
 libtraceevent \
"

URI_libtracefs-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libtracefs-devel-1.8.0-6.el10.x86_64_v2.rpm;name=libtracefs-devel;unpack=0"
SRC_URI += "${URI_libtracefs-devel}"
SRC_URI[libtracefs-devel.sha256sum] = "74669190b29ab9101aeb5f5528a8466f07b4bf25b239517d85103fcbbea6fce9"
RDEPENDS:libtracefs-devel = " \
 libtraceevent-devel \
 libtracefs \
 pkgconf-pkg-config \
"
