# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libverto"
PE = "0"
PV = "0.3.2"
PR = "10.el10"
PACKAGES = "libverto libverto-libev libverto-devel libverto-glib libverto-glib-devel libverto-libev-devel libverto-libevent libverto-libevent-devel"
PROVIDES = "rpm/libverto rpm/libverto-libev rpm/libverto-devel rpm/libverto-glib rpm/libverto-glib-devel rpm/libverto-libev-devel rpm/libverto-libevent rpm/libverto-libevent-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/libverto-0.3.2-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "78e2969f504cdaab132394988dc677d4f4c1507996e08a73117105703dda664c"

URI_libverto = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libverto-0.3.2-10.el10.x86_64_v2.rpm;name=libverto;unpack=0"
SRC_URI += "${URI_libverto}"
SRC_URI[libverto.sha256sum] = "071bcc66289f7b21e58511149dd6b6304185206416bf57ece0944a2232264db5"
RDEPENDS:libverto = " \
 glibc \
"

URI_libverto-libev = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libverto-libev-0.3.2-10.el10.x86_64_v2.rpm;name=libverto-libev;unpack=0"
SRC_URI += "${URI_libverto-libev}"
SRC_URI[libverto-libev.sha256sum] = "92beadd09906b193c6a71a1246ddb6216a33938e6deeee113f8846b09ab6b8ea"
RDEPENDS:libverto-libev = " \
 glibc \
 libverto \
 libev \
"

URI_libverto-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libverto-devel-0.3.2-10.el10.x86_64_v2.rpm;name=libverto-devel;unpack=0"
SRC_URI += "${URI_libverto-devel}"
SRC_URI[libverto-devel.sha256sum] = "590819f10aae2415051ae48aebb5a5b40ba24ba5a84816afde58447a8efc267d"
RDEPENDS:libverto-devel = " \
 libverto \
 pkgconf-pkg-config \
"

URI_libverto-glib = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libverto-glib-0.3.2-10.el10.x86_64_v2.rpm;name=libverto-glib;unpack=0"
SRC_URI += "${URI_libverto-glib}"
SRC_URI[libverto-glib.sha256sum] = "5bc858f883651877e62dbd012d541bf7b8ff7d5444cee1b1864f6aebbdb9a0f9"
RDEPENDS:libverto-glib = " \
 glibc \
 libverto \
 glib2 \
"

URI_libverto-glib-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libverto-glib-devel-0.3.2-10.el10.x86_64_v2.rpm;name=libverto-glib-devel;unpack=0"
SRC_URI += "${URI_libverto-glib-devel}"
SRC_URI[libverto-glib-devel.sha256sum] = "d85415fc5650fd20b2fb9c8e3ba680a7b518935e79e1cf4487a33c99a8b4aead"
RDEPENDS:libverto-glib-devel = " \
 libverto-devel \
 pkgconf-pkg-config \
 libverto-glib \
"

URI_libverto-libev-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libverto-libev-devel-0.3.2-10.el10.x86_64_v2.rpm;name=libverto-libev-devel;unpack=0"
SRC_URI += "${URI_libverto-libev-devel}"
SRC_URI[libverto-libev-devel.sha256sum] = "95299ad5ef6ac2f95fe548347bcd2085948d04044441adf7bbdfc28a9512aca5"
RDEPENDS:libverto-libev-devel = " \
 libverto-devel \
 libverto-libev \
 pkgconf-pkg-config \
"

URI_libverto-libevent = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libverto-libevent-0.3.2-10.el10.x86_64_v2.rpm;name=libverto-libevent;unpack=0"
SRC_URI += "${URI_libverto-libevent}"
SRC_URI[libverto-libevent.sha256sum] = "cfa12636b8ba088a9e80dd53e811fa3c2e0496d7228e5469adc63990b46b4964"
RDEPENDS:libverto-libevent = " \
 glibc \
 libverto \
 libevent \
"

URI_libverto-libevent-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libverto-libevent-devel-0.3.2-10.el10.x86_64_v2.rpm;name=libverto-libevent-devel;unpack=0"
SRC_URI += "${URI_libverto-libevent-devel}"
SRC_URI[libverto-libevent-devel.sha256sum] = "b82ad6744999a2c25fbe792accd6545afc796bc96ef6e4669bad17fa6b6bbd04"
RDEPENDS:libverto-libevent-devel = " \
 libverto-libevent \
 libverto-devel \
 pkgconf-pkg-config \
"
