# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libXfont2"
PE = "0"
PV = "2.0.6"
PR = "5.el10"
PACKAGES = "libXfont2 libXfont2-devel"
PROVIDES = "rpm/libXfont2 rpm/libXfont2-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libXfont2-2.0.6-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5233158a86850308985910d7a0bcbe9d3de17c68438ea000aa334d1352be1328"

URI_libXfont2 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libXfont2-2.0.6-5.el10.x86_64_v2.rpm;name=libXfont2;unpack=0"
SRC_URI += "${URI_libXfont2}"
SRC_URI[libXfont2.sha256sum] = "4f265abdcfee3e6991d5467cabc46466d5e0b5c58ca3b3a7e75cf6d4f82565f2"
RDEPENDS:libXfont2 = " \
 glibc \
 zlib-ng-compat \
 libfontenc \
 freetype \
"

URI_libXfont2-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libXfont2-devel-2.0.6-5.el10.x86_64_v2.rpm;name=libXfont2-devel;unpack=0"
SRC_URI += "${URI_libXfont2-devel}"
SRC_URI[libXfont2-devel.sha256sum] = "dc518e7aba1604cdeec83bf82c008fb0ca746dee5f5dba850c850dec8b363687"
RDEPENDS:libXfont2-devel = " \
 libXfont2 \
 libfontenc-devel \
 zlib-ng-compat-devel \
 freetype-devel \
 pkgconf-pkg-config \
 xorg-x11-proto-devel \
"
