# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libxslt"
PE = "0"
PV = "1.1.39"
PR = "8.el10_0"
PACKAGES = "libxslt libxslt-devel"
PROVIDES = "rpm/libxslt rpm/libxslt-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libxslt-1.1.39-8.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2950a541961e1a6673e1b8dc59f510b277245cae73da26bd4574e7ce1fe9df56"

URI_libxslt = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libxslt-1.1.39-8.el10_0.x86_64_v2.rpm;name=libxslt;unpack=0"
SRC_URI += "${URI_libxslt}"
SRC_URI[libxslt.sha256sum] = "8e852558cc8407367c283e1d90fd83b66d167af09bf06d17485b8781d40c8d51"
RDEPENDS:libxslt = " \
 glibc \
 libxml2 \
"

URI_libxslt-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libxslt-devel-1.1.39-8.el10_0.x86_64_v2.rpm;name=libxslt-devel;unpack=0"
SRC_URI += "${URI_libxslt-devel}"
SRC_URI[libxslt-devel.sha256sum] = "d80459dc29a54572a611717d4c0c05d9717474b83a78117d7594b05bd80fbc1c"
RDEPENDS:libxslt-devel = " \
 libxml2-devel \
 libxslt \
 libxslt-devel \
 libgpg-error-devel \
 pkgconf-pkg-config \
 bash \
"
