# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libXmu"
PE = "0"
PV = "1.1.4"
PR = "8.el10"
PACKAGES = "libXmu libXmu-devel"
PROVIDES = "rpm/libXmu rpm/libXmu-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libXmu-1.1.4-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "82ada8036269a1b157c748997c59043651d87ef02bd2c2cb88a7c8105ff96be9"

URI_libXmu = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libXmu-1.1.4-8.el10.x86_64_v2.rpm;name=libXmu;unpack=0"
SRC_URI += "${URI_libXmu}"
SRC_URI[libXmu.sha256sum] = "2429ce9ce0979add7ceeba6664353a42632cae1a64fe64979fd6737126306394"
RDEPENDS:libXmu = " \
 glibc \
 libXt \
 libX11 \
 libXext \
"

URI_libXmu-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libXmu-devel-1.1.4-8.el10.x86_64_v2.rpm;name=libXmu-devel;unpack=0"
SRC_URI += "${URI_libXmu-devel}"
SRC_URI[libXmu-devel.sha256sum] = "f5a3f2f2970d134979f94f7f2308ee56d89bc3016f7965c02da204840f457a0b"
RDEPENDS:libXmu-devel = " \
 libXext-devel \
 libXmu \
 pkgconf-pkg-config \
 libX11-devel \
 xorg-x11-proto-devel \
 libXt-devel \
"
