# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libxshmfence"
PE = "0"
PV = "1.3.2"
PR = "5.el10"
PACKAGES = "libxshmfence libxshmfence-devel"
PROVIDES = "rpm/libxshmfence rpm/libxshmfence-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libxshmfence-1.3.2-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "670581bf10f7043772a252c4b73bfdbb039c488d8e5c204941ca1ce36572b49b"

URI_libxshmfence = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libxshmfence-1.3.2-5.el10.x86_64_v2.rpm;name=libxshmfence;unpack=0"
SRC_URI += "${URI_libxshmfence}"
SRC_URI[libxshmfence.sha256sum] = "a4e1da66f4497b4080cbefd0ac99b6049c14e810bbf234528b38e212b69b9d3f"
RDEPENDS:libxshmfence = " \
 glibc \
"

URI_libxshmfence-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libxshmfence-devel-1.3.2-5.el10.x86_64_v2.rpm;name=libxshmfence-devel;unpack=0"
SRC_URI += "${URI_libxshmfence-devel}"
SRC_URI[libxshmfence-devel.sha256sum] = "4aa1b8e649cfa3a31f1025746d7888aa029d81fd7ae6761c449bfe792a9ced70"
RDEPENDS:libxshmfence-devel = " \
 libxshmfence \
 pkgconf-pkg-config \
"
