# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "libXext"
PE = "0"
PV = "1.3.6"
PR = "3.el10"
PACKAGES = "libXext libXext-devel"
PROVIDES = "rpm/libXext rpm/libXext-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/libXext-1.3.6-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5c34a2dfe42ae5cc17b4f550029a8f2bca06d51e07796470c82ed34882c52f5e"

URI_libXext = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libXext-1.3.6-3.el10.x86_64_v2.rpm;name=libXext;unpack=0"
SRC_URI += "${URI_libXext}"
SRC_URI[libXext.sha256sum] = "304b9904a670f759834d13a67e5aa92e8db3d5649a36a04d1a8530a6c6a2a645"
RDEPENDS:libXext = " \
 glibc \
 libX11 \
"

URI_libXext-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/libXext-devel-1.3.6-3.el10.x86_64_v2.rpm;name=libXext-devel;unpack=0"
SRC_URI += "${URI_libXext-devel}"
SRC_URI[libXext-devel.sha256sum] = "10fc6e150be7faff5e33d4dd804bcec6b9b0b0f951d598b56800e87d71bf9753"
RDEPENDS:libXext-devel = " \
 libX11-devel \
 xorg-x11-proto-devel \
 pkgconf-pkg-config \
 libXext \
"
