# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "lldpd"
PE = "0"
PV = "1.0.19"
PR = "1.el10"
PACKAGES = "lldpd lldpd-devel"
PROVIDES = "rpm/lldpd rpm/lldpd-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/lldpd-1.0.19-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d99af15a4ff01393e09e1c9e24a3b0602e0a020c57ebaddc888f84d30bc0a478"

URI_lldpd = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/lldpd-1.0.19-1.el10.x86_64_v2.rpm;name=lldpd;unpack=0"
SRC_URI += "${URI_lldpd}"
SRC_URI[lldpd.sha256sum] = "c85447af070a47470eb7bdea7ddbb3335a92ceaceba4f04af0fc0a4552400db8"
RDEPENDS:lldpd = " \
 shadow-utils \
 systemd \
 net-snmp-agent-libs \
 net-snmp-libs \
 libevent \
 readline \
 libxml2 \
 bash \
 glibc \
"

URI_lldpd-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/lldpd-devel-1.0.19-1.el10.x86_64_v2.rpm;name=lldpd-devel;unpack=0"
SRC_URI += "${URI_lldpd-devel}"
SRC_URI[lldpd-devel.sha256sum] = "1050346093e0496db54adddfc73d18141295f343ff47f0cc872795f7fe11a089"
RDEPENDS:lldpd-devel = " \
 pkgconf-pkg-config \
 lldpd \
"
