# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "lmdb"
PE = "0"
PV = "0.9.32"
PR = "4.el10"
PACKAGES = "lmdb-libs lmdb lmdb-devel lmdb-doc"
PROVIDES = "rpm/lmdb-libs rpm/lmdb rpm/lmdb-devel rpm/lmdb-doc"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/lmdb-0.9.32-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "20b290ebc4399ab914df18925b9bbfcf438b87b9ce3486836df24c8edf69d1a6"

URI_lmdb-libs = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/lmdb-libs-0.9.32-4.el10.x86_64_v2.rpm;name=lmdb-libs;unpack=0"
SRC_URI += "${URI_lmdb-libs}"
SRC_URI[lmdb-libs.sha256sum] = "1c59e618962a1d5bd3e0a2c4e6719a9ca3325ced93f748436d14003bc042238c"
RDEPENDS:lmdb-libs = " \
 glibc \
"

URI_lmdb = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/lmdb-0.9.32-4.el10.x86_64_v2.rpm;name=lmdb;unpack=0"
SRC_URI += "${URI_lmdb}"
SRC_URI[lmdb.sha256sum] = "bb48e9d8160412db83fe9b9745794e030910649b3019a5889c85fcdf7431fa9a"
RDEPENDS:lmdb = " \
 glibc \
 lmdb-libs \
"

URI_lmdb-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/lmdb-devel-0.9.32-4.el10.x86_64_v2.rpm;name=lmdb-devel;unpack=0"
SRC_URI += "${URI_lmdb-devel}"
SRC_URI[lmdb-devel.sha256sum] = "1c06db62040fd0e26e3b12714a0cf96ce5050f70842952e7c7c5181ba3332005"
RDEPENDS:lmdb-devel = " \
 lmdb-libs \
 lmdb \
 pkgconf-pkg-config \
"

URI_lmdb-doc = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/lmdb-doc-0.9.32-4.el10.noarch.rpm;name=lmdb-doc;unpack=0"
SRC_URI += "${URI_lmdb-doc}"
SRC_URI[lmdb-doc.sha256sum] = "33689fd84ccc0013da187bbd4de63678071fbef7a09b918f2fa1ff343436bcfc"
RDEPENDS:lmdb-doc = ""
