# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "low-memory-monitor"
PE = "0"
PV = "2.1"
PR = "12.el10"
PACKAGES = "low-memory-monitor low-memory-monitor-doc"
PROVIDES = "rpm/low-memory-monitor rpm/low-memory-monitor-doc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/low-memory-monitor-2.1-12.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f2066cc8476909a5eec996f71347b2ad0ce2b01d3563916cb578c697b2c43dcd"

URI_low-memory-monitor = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/low-memory-monitor-2.1-12.el10.x86_64_v2.rpm;name=low-memory-monitor;unpack=0"
SRC_URI += "${URI_low-memory-monitor}"
SRC_URI[low-memory-monitor.sha256sum] = "b1b8a20f8fc9a95a26ee41edc569710855f34ccff7dbaaea53233e3b843be9a1"
RDEPENDS:low-memory-monitor = " \
 glibc \
 libgcc \
 bash \
 glib2 \
"

URI_low-memory-monitor-doc = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/low-memory-monitor-doc-2.1-12.el10.noarch.rpm;name=low-memory-monitor-doc;unpack=0"
SRC_URI += "${URI_low-memory-monitor-doc}"
SRC_URI[low-memory-monitor-doc.sha256sum] = "1d1dd357354d3fce74f8823ebbd0aa85e1e91c5339465722ae05bb36432ad7fa"
RDEPENDS:low-memory-monitor-doc = " \
 low-memory-monitor \
"
