# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "lprint"
PE = "0"
PV = "1.3.1"
PR = "8.el10"
PACKAGES = "lprint"
PROVIDES = "rpm/lprint"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/lprint-1.3.1-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e032eaae031e772e93f9e40eddf2a9ced5999c57b04d93c9196d8a0ca917d249"

URI_lprint = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/lprint-1.3.1-8.el10.x86_64_v2.rpm;name=lprint;unpack=0"
SRC_URI += "${URI_lprint}"
SRC_URI[lprint.sha256sum] = "5cf968982a6da97b0ab35b387e7596f055e066450e702c64936f01e89f408041"
RDEPENDS:lprint = " \
 cups-libs \
 avahi \
 bash \
 glibc \
 pappl \
 filesystem \
"
