# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "lshw"
PE = "0"
PV = "B.02.20"
PR = "6.el10"
PACKAGES = "lshw lshw-gui"
PROVIDES = "rpm/lshw rpm/lshw-gui"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/lshw-B.02.20-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "fda489245b65782927ec2bdef32f166e54a12d0bc689f9e371835fb2b82ec207"

URI_lshw = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/lshw-B.02.20-6.el10.x86_64_v2.rpm;name=lshw;unpack=0"
SRC_URI += "${URI_lshw}"
SRC_URI[lshw.sha256sum] = "220ebe05c3b3e4a33247ee3f8f745df1e04ad8bc02d088ceaf25a48297cf2afb"
RDEPENDS:lshw = " \
 libgcc \
 hwdata \
 sqlite-libs \
 libstdc++ \
 glibc \
"

URI_lshw-gui = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/lshw-gui-B.02.20-6.el10.x86_64_v2.rpm;name=lshw-gui;unpack=0"
SRC_URI += "${URI_lshw-gui}"
SRC_URI[lshw-gui.sha256sum] = "5db019bd8ed72003086d1340bead980e27631bde5013b5a35ac8f0d8e11a7ea8"
RDEPENDS:lshw-gui = " \
 lshw \
 libgcc \
 gdk-pixbuf2 \
 sqlite-libs \
 polkit \
 libstdc++ \
 bash \
 glib2 \
 gtk3 \
 glibc \
"
