# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "lua-posix"
PE = "0"
PV = "36.2.1"
PR = "8.el10"
PACKAGES = "lua-posix"
PROVIDES = "rpm/lua-posix"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/lua-posix-36.2.1-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4293231e26db0c2aa3380246900b187968b17702587415c123a556350edf2387"

URI_lua-posix = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/lua-posix-36.2.1-8.el10.x86_64_v2.rpm;name=lua-posix;unpack=0"
SRC_URI += "${URI_lua-posix}"
SRC_URI[lua-posix.sha256sum] = "85b223ef28e8a4adda2a3cedd97538856c80ab000c121cc847d0a2c3b7cf0b60"
RDEPENDS:lua-posix = " \
 glibc \
 libxcrypt \
 lua-libs \
"
