# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "lz4"
PE = "0"
PV = "1.9.4"
PR = "8.el10"
PACKAGES = "lz4 lz4-libs lz4-devel lz4-static"
PROVIDES = "rpm/lz4 rpm/lz4-libs rpm/lz4-devel rpm/lz4-static"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/lz4-1.9.4-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "857dad0eba0bd29adac43626551f10b4a4033389bd138469e40c9126756c9b22"

URI_lz4 = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/lz4-1.9.4-8.el10.x86_64_v2.rpm;name=lz4;unpack=0"
SRC_URI += "${URI_lz4}"
SRC_URI[lz4.sha256sum] = "a5bddf5e329546ad25cb73c3e1377da32ad2213e23344a105c33e589128df347"
RDEPENDS:lz4 = " \
 glibc \
"

URI_lz4-libs = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/lz4-libs-1.9.4-8.el10.x86_64_v2.rpm;name=lz4-libs;unpack=0"
SRC_URI += "${URI_lz4-libs}"
SRC_URI[lz4-libs.sha256sum] = "a0657ca2436584eb4457750517184b652ab4db63bf47a308cbc0a6893e48b0fd"
RDEPENDS:lz4-libs = " \
 glibc \
"

URI_lz4-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/lz4-devel-1.9.4-8.el10.x86_64_v2.rpm;name=lz4-devel;unpack=0"
SRC_URI += "${URI_lz4-devel}"
SRC_URI[lz4-devel.sha256sum] = "ed76352204f892bae207368e5bfe80ed8326d741f05c0f7adaa0055a0d1a60f0"
RDEPENDS:lz4-devel = " \
 lz4-libs \
 pkgconf-pkg-config \
"

URI_lz4-static = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/lz4-static-1.9.4-8.el10.x86_64_v2.rpm;name=lz4-static;unpack=0"
SRC_URI += "${URI_lz4-static}"
SRC_URI[lz4-static.sha256sum] = "a96a721f611f9f7d8a3af23e23945f5444be599bd45dbd1ace218e7453522548"
RDEPENDS:lz4-static = ""
