# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "makedumpfile"
PE = "0"
PV = "1.7.6"
PR = "4.el10"
PACKAGES = "makedumpfile"
PROVIDES = "rpm/makedumpfile"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/makedumpfile-1.7.6-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1f9b6185ca9d3e374076bf7eaeffcd401d9783fb4fc508aecf300b524c4e4ebb"

URI_makedumpfile = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/makedumpfile-1.7.6-4.el10.x86_64_v2.rpm;name=makedumpfile;unpack=0"
SRC_URI += "${URI_makedumpfile}"
SRC_URI[makedumpfile.sha256sum] = "5ac3d2a9cd82eddd77ff03874338b59c713f611366820c43ab1a671bdca2e728"
RDEPENDS:makedumpfile = " \
 zlib-ng-compat \
 lzo \
 libgcc \
 snappy \
 elfutils-libelf \
 libzstd \
 elfutils-libs \
 ncurses-libs \
 glibc \
"
