# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "mallard-rng"
PE = "0"
PV = "1.1.0"
PR = "14.el10"
PACKAGES = "mallard-rng"
PROVIDES = "rpm/mallard-rng"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/mallard-rng-1.1.0-14.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "15ffc5e6b965ad290cae1fe8ad5476a78bf08b8dd39f51148ff419fb087ec4b9"

URI_mallard-rng = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/mallard-rng-1.1.0-14.el10.noarch.rpm;name=mallard-rng;unpack=0"
SRC_URI += "${URI_mallard-rng}"
SRC_URI[mallard-rng.sha256sum] = "2e3afab086fd78bb16f33bc4ef86581771ec4142059e912449d197e275b01ad0"
RDEPENDS:mallard-rng = " \
 pkgconf-pkg-config \
 bash \
 libxml2 \
 xml-common \
"
