# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "mariadb-connector-odbc"
PE = "0"
PV = "3.2.4"
PR = "1.el10"
PACKAGES = "mariadb-connector-odbc"
PROVIDES = "rpm/mariadb-connector-odbc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/mariadb-connector-odbc-3.2.4-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "86e03ad8ff9da898d9fe000fe5e859b636f0e658f81c782b125e2e7ffdae4060"

URI_mariadb-connector-odbc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/mariadb-connector-odbc-3.2.4-1.el10.x86_64_v2.rpm;name=mariadb-connector-odbc;unpack=0"
SRC_URI += "${URI_mariadb-connector-odbc}"
SRC_URI[mariadb-connector-odbc.sha256sum] = "c7a45c40700878c1d9b14201468e5883c1cf5c217c3b7f2edb33fdda4d6e8023"
RDEPENDS:mariadb-connector-odbc = " \
 libgcc \
 pkgconf-pkg-config \
 libstdc++ \
 mariadb-connector-c \
 unixODBC \
 glibc \
"
