# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "maven-plugin-testing"
PE = "0"
PV = "3.3.0"
PR = "35.el10"
PACKAGES = "maven-plugin-testing maven-plugin-testing-harness maven-plugin-testing-javadoc"
PROVIDES = "rpm/maven-plugin-testing rpm/maven-plugin-testing-harness rpm/maven-plugin-testing-javadoc"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/maven-plugin-testing-3.3.0-35.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "9427a47d6e43eca7c0fa1f658a6af91db69775ce18eb12a31a637c4ece470c5a"

URI_maven-plugin-testing = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-plugin-testing-3.3.0-35.el10.noarch.rpm;name=maven-plugin-testing;unpack=0"
SRC_URI += "${URI_maven-plugin-testing}"
SRC_URI[maven-plugin-testing.sha256sum] = "085f7def9a8b7d0e0898324bf01dd66364e02698f41c09be931c5cf1bc645f9c"
RDEPENDS:maven-plugin-testing = " \
 javapackages-filesystem \
 maven-parent \
"

URI_maven-plugin-testing-harness = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-plugin-testing-harness-3.3.0-35.el10.noarch.rpm;name=maven-plugin-testing-harness;unpack=0"
SRC_URI += "${URI_maven-plugin-testing-harness}"
SRC_URI[maven-plugin-testing-harness.sha256sum] = "17a9e4f40c4bf602648c0af95f29d635813e659fc0ecfe1df519667d584317ca"
RDEPENDS:maven-plugin-testing-harness = " \
 plexus-archiver \
 apache-commons-io \
 javapackages-filesystem \
"

URI_maven-plugin-testing-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-plugin-testing-javadoc-3.3.0-35.el10.noarch.rpm;name=maven-plugin-testing-javadoc;unpack=0"
SRC_URI += "${URI_maven-plugin-testing-javadoc}"
SRC_URI[maven-plugin-testing-javadoc.sha256sum] = "e25f1c53fae745e7984714e9ac5f9ff103bf9ee08e8f3e6fc784195dfab431c7"
RDEPENDS:maven-plugin-testing-javadoc = " \
 javapackages-filesystem \
"
