# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "maven-shared-incremental"
PE = "0"
PV = "1.1"
PR = "34.el10"
PACKAGES = "maven-shared-incremental maven-shared-incremental-javadoc"
PROVIDES = "rpm/maven-shared-incremental rpm/maven-shared-incremental-javadoc"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/maven-shared-incremental-1.1-34.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "30f8a94383e627c540f56038f70b66e9c3c9db3c1d675514bb0f78d1fc80bf2e"

URI_maven-shared-incremental = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-shared-incremental-1.1-34.el10.noarch.rpm;name=maven-shared-incremental;unpack=0"
SRC_URI += "${URI_maven-shared-incremental}"
SRC_URI[maven-shared-incremental.sha256sum] = "ff1f3bcfe0b637aa17626d6e35e75abd29746b530077eba51b7763350c29f547"
RDEPENDS:maven-shared-incremental = " \
 plexus-containers-component-annotations \
 maven-shared-utils \
 javapackages-filesystem \
 maven-lib \
"

URI_maven-shared-incremental-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-shared-incremental-javadoc-1.1-34.el10.noarch.rpm;name=maven-shared-incremental-javadoc;unpack=0"
SRC_URI += "${URI_maven-shared-incremental-javadoc}"
SRC_URI[maven-shared-incremental-javadoc.sha256sum] = "d9c31499f9fbba38089952f3314c68b8c1c899bc3af951963b310fbdf21d2ee9"
RDEPENDS:maven-shared-incremental-javadoc = " \
 javapackages-filesystem \
"
