# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "maven-artifact-transfer"
PE = "1"
PV = "0.13.1"
PR = "16.el10"
PACKAGES = "maven-artifact-transfer maven-artifact-transfer-javadoc"
PROVIDES = "rpm/maven-artifact-transfer rpm/maven-artifact-transfer-javadoc"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/maven-artifact-transfer-0.13.1-16.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f37832bfcbd874e7887b2c699fe8be2f8ddc9491a1d53436e02cf8bd457add7d"

URI_maven-artifact-transfer = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-artifact-transfer-0.13.1-16.el10.noarch.rpm;name=maven-artifact-transfer;unpack=0"
SRC_URI += "${URI_maven-artifact-transfer}"
SRC_URI[maven-artifact-transfer.sha256sum] = "791e0f1d23b08da52d2dce7c8d62a1e2c6b1feb9d8993f4fc2300f18bbd9a87b"
RDEPENDS:maven-artifact-transfer = " \
 plexus-containers-component-annotations \
 plexus-utils \
 javapackages-filesystem \
 maven-common-artifact-filters \
 slf4j \
 maven-lib \
 maven-resolver \
"

URI_maven-artifact-transfer-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-artifact-transfer-javadoc-0.13.1-16.el10.noarch.rpm;name=maven-artifact-transfer-javadoc;unpack=0"
SRC_URI += "${URI_maven-artifact-transfer-javadoc}"
SRC_URI[maven-artifact-transfer-javadoc.sha256sum] = "8358177f10f357f2f0acafe1bae5d733ea8366280ab7f67109ed8dbc60170b89"
RDEPENDS:maven-artifact-transfer-javadoc = " \
 javapackages-filesystem \
"
