# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "maven-compiler-plugin"
PE = "0"
PV = "3.12.1"
PR = "4.el10"
PACKAGES = "maven-compiler-plugin maven-compiler-plugin-javadoc"
PROVIDES = "rpm/maven-compiler-plugin rpm/maven-compiler-plugin-javadoc"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/maven-compiler-plugin-3.12.1-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f13406565c39e9bc699d852ee66f4e8bb3fe107820f0a7898f2b26193a406631"

URI_maven-compiler-plugin = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-compiler-plugin-3.12.1-4.el10.noarch.rpm;name=maven-compiler-plugin;unpack=0"
SRC_URI += "${URI_maven-compiler-plugin}"
SRC_URI[maven-compiler-plugin.sha256sum] = "93501f1183d5dac172ad892c0eb71603e5ca15527dcf630591b15983018435a5"
RDEPENDS:maven-compiler-plugin = " \
 plexus-utils \
 javapackages-filesystem \
 plexus-compiler \
 maven-shared-incremental \
 maven-shared-utils \
 plexus-languages \
"

URI_maven-compiler-plugin-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-compiler-plugin-javadoc-3.12.1-4.el10.noarch.rpm;name=maven-compiler-plugin-javadoc;unpack=0"
SRC_URI += "${URI_maven-compiler-plugin-javadoc}"
SRC_URI[maven-compiler-plugin-javadoc.sha256sum] = "2a6152d99e793a6123d43f7a01e70ddd6d0e766a3ba92768b00e489530ccdd73"
RDEPENDS:maven-compiler-plugin-javadoc = " \
 javapackages-filesystem \
"
