# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "maven-remote-resources-plugin"
PE = "0"
PV = "3.1.0"
PR = "7.el10"
PACKAGES = "maven-remote-resources-plugin maven-remote-resources-plugin-javadoc"
PROVIDES = "rpm/maven-remote-resources-plugin rpm/maven-remote-resources-plugin-javadoc"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/maven-remote-resources-plugin-3.1.0-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7858286077371d9be01c42fc2001c300ee099f1ed92dfed5a9f27a8a0152ec20"

URI_maven-remote-resources-plugin = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-remote-resources-plugin-3.1.0-7.el10.noarch.rpm;name=maven-remote-resources-plugin;unpack=0"
SRC_URI += "${URI_maven-remote-resources-plugin}"
SRC_URI[maven-remote-resources-plugin.sha256sum] = "44b46ae15c8c35ff77a1c91a1c11e7427036eb49153721cc9de1079ba8f24899"
RDEPENDS:maven-remote-resources-plugin = " \
 maven-filtering \
 plexus-resources \
 apache-commons-io \
 plexus-utils \
 javapackages-filesystem \
 maven-archiver \
 maven-common-artifact-filters \
 velocity \
 maven-resolver \
"

URI_maven-remote-resources-plugin-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-remote-resources-plugin-javadoc-3.1.0-7.el10.noarch.rpm;name=maven-remote-resources-plugin-javadoc;unpack=0"
SRC_URI += "${URI_maven-remote-resources-plugin-javadoc}"
SRC_URI[maven-remote-resources-plugin-javadoc.sha256sum] = "03e3bd76cb708b253c3f348ce044922ff10fc94885fda52e310e4fc61fceadfc"
RDEPENDS:maven-remote-resources-plugin-javadoc = " \
 javapackages-filesystem \
"
