# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "maven-resources-plugin"
PE = "0"
PV = "3.3.1"
PR = "7.el10"
PACKAGES = "maven-resources-plugin maven-resources-plugin-javadoc"
PROVIDES = "rpm/maven-resources-plugin rpm/maven-resources-plugin-javadoc"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/maven-resources-plugin-3.3.1-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f4e03476382533c0dc4c1bf279a806ba4f80cb9548f4a4a5661e36a19582d20c"

URI_maven-resources-plugin = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-resources-plugin-3.3.1-7.el10.noarch.rpm;name=maven-resources-plugin;unpack=0"
SRC_URI += "${URI_maven-resources-plugin}"
SRC_URI[maven-resources-plugin.sha256sum] = "70a994b506f3bed266d427f1cc44b20d5d29bc468248aff945a56410e9ddb1cc"
RDEPENDS:maven-resources-plugin = " \
 maven-filtering \
 plexus-interpolation \
 apache-commons-io \
 plexus-utils \
 javapackages-filesystem \
 apache-commons-lang3 \
"

URI_maven-resources-plugin-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-resources-plugin-javadoc-3.3.1-7.el10.noarch.rpm;name=maven-resources-plugin-javadoc;unpack=0"
SRC_URI += "${URI_maven-resources-plugin-javadoc}"
SRC_URI[maven-resources-plugin-javadoc.sha256sum] = "e953f6aee4429ca3257bc2dd83d67408560d3930b516453c53c9f4709e6a2aed"
RDEPENDS:maven-resources-plugin-javadoc = " \
 javapackages-filesystem \
"
