# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "maven-common-artifact-filters"
PE = "0"
PV = "3.3.2"
PR = "7.el10"
PACKAGES = "maven-common-artifact-filters maven-common-artifact-filters-javadoc"
PROVIDES = "rpm/maven-common-artifact-filters rpm/maven-common-artifact-filters-javadoc"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/maven-common-artifact-filters-3.3.2-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7d80f0073504c54b3d064f856533dd65b0029978002d9db6ce6506d84eab40fd"

URI_maven-common-artifact-filters = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-common-artifact-filters-3.3.2-7.el10.noarch.rpm;name=maven-common-artifact-filters;unpack=0"
SRC_URI += "${URI_maven-common-artifact-filters}"
SRC_URI[maven-common-artifact-filters.sha256sum] = "bcaa1bc35cad6eee636c6407e02c58abbd5b8d510d4efa35cda6b537240fce7f"
RDEPENDS:maven-common-artifact-filters = " \
 javapackages-filesystem \
 slf4j \
"

URI_maven-common-artifact-filters-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/maven-common-artifact-filters-javadoc-3.3.2-7.el10.noarch.rpm;name=maven-common-artifact-filters-javadoc;unpack=0"
SRC_URI += "${URI_maven-common-artifact-filters-javadoc}"
SRC_URI[maven-common-artifact-filters-javadoc.sha256sum] = "6b10541aba3933de7a3878a5394918c6d9ce4155447f6a4ae05014a3ebd3dde1"
RDEPENDS:maven-common-artifact-filters-javadoc = " \
 javapackages-filesystem \
"
