# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "mc"
PE = "1"
PV = "4.8.31"
PR = "3.el10"
PACKAGES = "mc mc-python"
PROVIDES = "rpm/mc rpm/mc-python"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/mc-4.8.31-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a3dc0e5110b1dec69d9aba4364794dc103c3522e6c8541cd0f511ee8fcea0a2a"

URI_mc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/mc-4.8.31-3.el10.x86_64_v2.rpm;name=mc;unpack=0"
SRC_URI += "${URI_mc}"
SRC_URI[mc.sha256sum] = "94515aa9b364597d83742b048ff24dfc355bb6f678d2a25b9a417bab830d4f1a"
RDEPENDS:mc = " \
 e2fsprogs-libs \
 perl-libs \
 slang \
 perl-POSIX \
 perl-File-Basename \
 bash \
 glib2 \
 glibc \
 perl-interpreter \
 perl-File-Temp \
"

URI_mc-python = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/mc-python-4.8.31-3.el10.noarch.rpm;name=mc-python;unpack=0"
SRC_URI += "${URI_mc-python}"
SRC_URI[mc-python.sha256sum] = "245d80d523d1feaa18fc2a34dfd3fc2872d3c8660c5f87713257e2906749f7ee"
RDEPENDS:mc-python = " \
 python3 \
 mc \
"
