# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "mecab"
PE = "0"
PV = "0.996"
PR = "9.el10"
PACKAGES = "mecab mecab-devel"
PROVIDES = "rpm/mecab rpm/mecab-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/mecab-0.996-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "8fcb3383e9a9ca1a5bf7ecbf121575749e7b9902805237b64a0de3d4c40fa0f2"

URI_mecab = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/mecab-0.996-9.el10.x86_64_v2.rpm;name=mecab;unpack=0"
SRC_URI += "${URI_mecab}"
SRC_URI[mecab.sha256sum] = "9a42dab32fa5e9c19a19a78a87e7c1ac413c078d1332764d78e05da5a09724fa"
RDEPENDS:mecab = " \
 glibc \
 libgcc \
 libstdc++ \
"

URI_mecab-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/mecab-devel-0.996-9.el10.x86_64_v2.rpm;name=mecab-devel;unpack=0"
SRC_URI += "${URI_mecab-devel}"
SRC_URI[mecab-devel.sha256sum] = "667af5220f06e751817c1277dd59980430fee8f17c957ecbb3d0424e022221d8"
RDEPENDS:mecab-devel = " \
 bash \
 mecab \
"
