# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "mingw-filesystem"
PE = "0"
PV = "148"
PR = "7.el10"
PACKAGES = "mingw-filesystem-base mingw32-filesystem mingw64-filesystem ucrt64-filesystem"
PROVIDES = "rpm/mingw-filesystem-base rpm/mingw32-filesystem rpm/mingw64-filesystem rpm/ucrt64-filesystem"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/mingw-filesystem-148-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2e9d94e5e8d17bc4426d5d2ac419577a4ea2ad54936e5f25dc7e8f4f6e29314f"

URI_mingw-filesystem-base = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/mingw-filesystem-base-148-7.el10.noarch.rpm;name=mingw-filesystem-base;unpack=0"
SRC_URI += "${URI_mingw-filesystem-base}"
SRC_URI[mingw-filesystem-base.sha256sum] = "343e920f85b5348c13644bf9a70a0b9c1eb9b1128e7ad67a922ac26255f30f80"
RDEPENDS:mingw-filesystem-base = " \
 redhat-rpm-config \
 pkgconf \
 bash \
 cmake-rpm-macros \
"

URI_mingw32-filesystem = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/mingw32-filesystem-148-7.el10.noarch.rpm;name=mingw32-filesystem;unpack=0"
SRC_URI += "${URI_mingw32-filesystem}"
SRC_URI[mingw32-filesystem.sha256sum] = "42b6b053cb2206e97fecfa6e4909951908b0080153b2850a44e9e520248017c2"
RDEPENDS:mingw32-filesystem = " \
 mingw-binutils-generic \
 mingw-filesystem-base \
"

URI_mingw64-filesystem = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/mingw64-filesystem-148-7.el10.noarch.rpm;name=mingw64-filesystem;unpack=0"
SRC_URI += "${URI_mingw64-filesystem}"
SRC_URI[mingw64-filesystem.sha256sum] = "25eed24210748a2afff1d7c15958e62a7227dad2d7bc4054a21a688811caea48"
RDEPENDS:mingw64-filesystem = " \
 mingw-binutils-generic \
 mingw-filesystem-base \
"

URI_ucrt64-filesystem = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ucrt64-filesystem-148-7.el10.noarch.rpm;name=ucrt64-filesystem;unpack=0"
SRC_URI += "${URI_ucrt64-filesystem}"
SRC_URI[ucrt64-filesystem.sha256sum] = "5741ccf1f65e14e55466ed99aeb6ea1e1fe45f6bbda61b6cf2e7405dfc6deaad"
RDEPENDS:ucrt64-filesystem = " \
 mingw-binutils-generic \
 mingw-filesystem-base \
"
