# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "mingw-libffi"
PE = "0"
PV = "3.4.6"
PR = "2.el10"
PACKAGES = "mingw32-libffi mingw64-libffi mingw32-libffi-static mingw64-libffi-static"
PROVIDES = "rpm/mingw32-libffi rpm/mingw64-libffi rpm/mingw32-libffi-static rpm/mingw64-libffi-static"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/mingw-libffi-3.4.6-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "6cea077b9c272ba0bb78315b0c4e2e1d5c7f13f1025be92e567033d18ec45e36"

URI_mingw32-libffi = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/mingw32-libffi-3.4.6-2.el10.noarch.rpm;name=mingw32-libffi;unpack=0"
SRC_URI += "${URI_mingw32-libffi}"
SRC_URI[mingw32-libffi.sha256sum] = "fc75aaa064f5aefb398a2eb19e1efd1c8b004f470a54e5669ca165cd3dbfa65b"
RDEPENDS:mingw32-libffi = " \
 mingw32-crt \
 mingw32-filesystem \
"

URI_mingw64-libffi = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/mingw64-libffi-3.4.6-2.el10.noarch.rpm;name=mingw64-libffi;unpack=0"
SRC_URI += "${URI_mingw64-libffi}"
SRC_URI[mingw64-libffi.sha256sum] = "fc7b7cc5f8acc4a68d23eb18c4eb2b242953cf0beec47f15d9413dfa03e79845"
RDEPENDS:mingw64-libffi = " \
 mingw64-crt \
 mingw64-filesystem \
"

URI_mingw32-libffi-static = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/mingw32-libffi-static-3.4.6-2.el10.noarch.rpm;name=mingw32-libffi-static;unpack=0"
SRC_URI += "${URI_mingw32-libffi-static}"
SRC_URI[mingw32-libffi-static.sha256sum] = "6b5139c4caf25e150f09fb98bbde477289534dd193ba33bd63239fba38d333df"
RDEPENDS:mingw32-libffi-static = ""

URI_mingw64-libffi-static = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/mingw64-libffi-static-3.4.6-2.el10.noarch.rpm;name=mingw64-libffi-static;unpack=0"
SRC_URI += "${URI_mingw64-libffi-static}"
SRC_URI[mingw64-libffi-static.sha256sum] = "1952572dcbdd3b6758c8a22d988d70c61d800b0eb6316a9a1a0c0da69210ec6e"
RDEPENDS:mingw64-libffi-static = ""
