# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "minicom"
PE = "0"
PV = "2.9"
PR = "4.el10"
PACKAGES = "minicom"
PROVIDES = "rpm/minicom"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/minicom-2.9-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ec4dbf3c20b3f4f64f722309728c1226db082eea3d90b7abdbaef2686fffd625"

URI_minicom = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/minicom-2.9-4.el10.x86_64_v2.rpm;name=minicom;unpack=0"
SRC_URI += "${URI_minicom}"
SRC_URI[minicom.sha256sum] = "4bdced5f60f71a20075bc9b5aacb1bab35fffbe0acfbb4ec019a4ebe0a3114f9"
RDEPENDS:minicom = " \
 lrzsz \
 bash \
 ncurses-libs \
 glibc \
 lockdev \
"
