# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "mod_auth_openidc"
PE = "0"
PV = "2.4.15"
PR = "4.el10_0.1"
PACKAGES = "mod_auth_openidc"
PROVIDES = "rpm/mod_auth_openidc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/mod_auth_openidc-2.4.15-4.el10_0.1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b9ad755005303d9518244d3d686a0c54da7732864526ebf18c3c1e1cab39a55b"

URI_mod_auth_openidc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/mod_auth_openidc-2.4.15-4.el10_0.1.x86_64_v2.rpm;name=mod_auth_openidc;unpack=0"
SRC_URI += "${URI_mod_auth_openidc}"
SRC_URI[mod_auth_openidc.sha256sum] = "b8aaef7aabac54a2722198b44f701d54361e31c8cb0b1e6389f2db32306bad12"
RDEPENDS:mod_auth_openidc = " \
 zlib-ng-compat \
 httpd-core \
 jansson \
 libxcrypt \
 cjose \
 openssl-libs \
 apr \
 jq \
 apr-util \
 pcre2 \
 libcurl \
 glibc \
 expat \
 openldap \
"
