# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "msv"
PE = "0"
PV = "2022.7"
PR = "6.el10"
PACKAGES = "msv-javadoc msv-xsdlib"
PROVIDES = "rpm/msv-javadoc rpm/msv-xsdlib"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/msv-2022.7-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "85e0ca5639546fc34f4dbd39565a7c1c68a1e60f6c936d9e58cfa00ccf862431"

URI_msv-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/msv-javadoc-2022.7-6.el10.noarch.rpm;name=msv-javadoc;unpack=0"
SRC_URI += "${URI_msv-javadoc}"
SRC_URI[msv-javadoc.sha256sum] = "d2e0d1c1ba001af585a45d1d946bb406a47db8828eee3d25081f81011dca0f08"
RDEPENDS:msv-javadoc = " \
 javapackages-filesystem \
"

URI_msv-xsdlib = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/msv-xsdlib-2022.7-6.el10.noarch.rpm;name=msv-xsdlib;unpack=0"
SRC_URI += "${URI_msv-xsdlib}"
SRC_URI[msv-xsdlib.sha256sum] = "1919d9bfac1e3b758f76994c6aeee70e9a86f3bf8d8b6be700cc58affe70e76d"
RDEPENDS:msv-xsdlib = " \
 relaxng-datatype-java \
 javapackages-filesystem \
"
