# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "mtdev"
PE = "0"
PV = "1.1.6"
PR = "10.el10"
PACKAGES = "mtdev mtdev-devel"
PROVIDES = "rpm/mtdev rpm/mtdev-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/mtdev-1.1.6-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "57ff57457ac4cfcf14d876f74a065cf6b499beaf193b6e6ca6591c36fe767c13"

URI_mtdev = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/mtdev-1.1.6-10.el10.x86_64_v2.rpm;name=mtdev;unpack=0"
SRC_URI += "${URI_mtdev}"
SRC_URI[mtdev.sha256sum] = "9ad37eafbe57b8e2b0e225c3bc6b0fd8d62d854e4e6d04e03aea45684ac4708a"
RDEPENDS:mtdev = " \
 glibc \
"

URI_mtdev-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/mtdev-devel-1.1.6-10.el10.x86_64_v2.rpm;name=mtdev-devel;unpack=0"
SRC_URI += "${URI_mtdev-devel}"
SRC_URI[mtdev-devel.sha256sum] = "d91db64747d304649451dca0ac655cf957ce1cc5ae0d92051298f5f192ee37c7"
RDEPENDS:mtdev-devel = " \
 glibc \
 mtdev \
 pkgconf-pkg-config \
"
