# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "nasm"
PE = "0"
PV = "2.16.01"
PR = "9.el10"
PACKAGES = "nasm"
PROVIDES = "rpm/nasm"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/nasm-2.16.01-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d323044bd78c1a0ffd72a03cd3787d581ab5c7cda29cccf689fd8d1754e0372d"

URI_nasm = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/nasm-2.16.01-9.el10.x86_64_v2.rpm;name=nasm;unpack=0"
SRC_URI += "${URI_nasm}"
SRC_URI[nasm.sha256sum] = "c0210a8a92f8294a6133136575d5077a2be542879e7ac34cc9778f94ed5e2710"
RDEPENDS:nasm = " \
 glibc \
"
