# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "netavark"
PE = "2"
PV = "1.14.1"
PR = "1.el10_0"
PACKAGES = "netavark"
PROVIDES = "rpm/netavark"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/netavark-1.14.1-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "15e708cc00f18b390a6b176e33faf4b7845ca02e48089c2873c42320054a72ca"

URI_netavark = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/netavark-1.14.1-1.el10_0.x86_64_v2.rpm;name=netavark;unpack=0"
SRC_URI += "${URI_netavark}"
SRC_URI[netavark.sha256sum] = "aeddbcb32f8ab8acfb1966e2515a5a7518be6f6e8b441223fa7f4dfad966d974"
RDEPENDS:netavark = " \
 nftables \
 aardvark-dns \
 libgcc \
 bash \
 glibc \
"
