# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "nettle"
PE = "0"
PV = "3.10.1"
PR = "1.el10"
PACKAGES = "nettle nettle-devel"
PROVIDES = "rpm/nettle rpm/nettle-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/nettle-3.10.1-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "62eb9fe6a221aab60ea8b6c2991fab50e60d4dc0d2325ec12d1e81d72c9a7ebd"

URI_nettle = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/nettle-3.10.1-1.el10.x86_64_v2.rpm;name=nettle;unpack=0"
SRC_URI += "${URI_nettle}"
SRC_URI[nettle.sha256sum] = "04a7913d1348dfa5c83b97f8167b3f2c2ff377880c04b63ec44303ca928c5ae5"
RDEPENDS:nettle = " \
 glibc \
"

URI_nettle-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/nettle-devel-3.10.1-1.el10.x86_64_v2.rpm;name=nettle-devel;unpack=0"
SRC_URI += "${URI_nettle-devel}"
SRC_URI[nettle-devel.sha256sum] = "7b4bdd7b91b7ad9314fbf30828c327c4e01eef84069cf1e64d5846ca19be26fb"
RDEPENDS:nettle-devel = " \
 gmp-devel \
 nettle-devel \
 pkgconf-pkg-config \
 nettle \
"
