# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "nfs-utils"
PE = "1"
PV = "2.8.2"
PR = "3.el10"
PACKAGES = "libnfsidmap nfs-utils nfs-utils-coreos nfsv4-client-utils libnfsidmap-devel nfs-stats-utils"
PROVIDES = "rpm/libnfsidmap rpm/nfs-utils rpm/nfs-utils-coreos rpm/nfsv4-client-utils rpm/libnfsidmap-devel rpm/nfs-stats-utils"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/nfs-utils-2.8.2-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e0f7e7076b92a2a5acc343b1d1d04205e9b2e37271da887e703feb8a7e138106"

URI_libnfsidmap = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libnfsidmap-2.8.2-3.el10.x86_64_v2.rpm;name=libnfsidmap;unpack=0"
SRC_URI += "${URI_libnfsidmap}"
SRC_URI[libnfsidmap.sha256sum] = "30b7c1b79e23d5eda75a15465513a697d958e4040b0603afa9ca5ed314026444"
RDEPENDS:libnfsidmap = " \
 glibc \
 krb5-libs \
 openldap \
"

URI_nfs-utils = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/nfs-utils-2.8.2-3.el10.x86_64_v2.rpm;name=nfs-utils;unpack=0"
SRC_URI += "${URI_nfs-utils}"
SRC_URI[nfs-utils.sha256sum] = "89f0c889afb87524268549f7b4837d5c62a7f0a957dacfcbaec0524d1bc6cec1"
RDEPENDS:nfs-utils = " \
 python3 \
 systemd \
 keyutils \
 keyutils-libs \
 kmod \
 krb5-libs \
 device-mapper-libs \
 util-linux \
 libblkid \
 libcap \
 libcom_err \
 sed \
 libtirpc \
 libuuid \
 shadow-utils \
 libevent \
 libgcc \
 grep \
 libxml2 \
 sqlite-libs \
 bash \
 glibc \
 quota \
 gssproxy \
 gawk \
 readline \
 libmount \
 libnfsidmap \
 libnl3 \
 coreutils \
 rpcbind \
"

URI_nfs-utils-coreos = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/nfs-utils-coreos-2.8.2-3.el10.x86_64_v2.rpm;name=nfs-utils-coreos;unpack=0"
SRC_URI += "${URI_nfs-utils-coreos}"
SRC_URI[nfs-utils-coreos.sha256sum] = "6f1e55cfb4b380198854dda148455c44b8c00f220772af1182fa97349326090d"
RDEPENDS:nfs-utils-coreos = " \
 systemd \
 libevent \
 keyutils-libs \
 libgcc \
 libmount \
 libcap \
 krb5-libs \
 libcom_err \
 bash \
 libnfsidmap \
 glibc \
 libtirpc \
 rpcbind \
"

URI_nfsv4-client-utils = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/nfsv4-client-utils-2.8.2-3.el10.x86_64_v2.rpm;name=nfsv4-client-utils;unpack=0"
SRC_URI += "${URI_nfsv4-client-utils}"
SRC_URI[nfsv4-client-utils.sha256sum] = "7a477d4863cb0a4817024287f0a5fafe9556b43a56068f66c1f954d09922674a"
RDEPENDS:nfsv4-client-utils = " \
 libevent \
 keyutils-libs \
 gssproxy \
 libgcc \
 libmount \
 krb5-libs \
 libcom_err \
 libnfsidmap \
 glibc \
 libtirpc \
"

URI_libnfsidmap-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/libnfsidmap-devel-2.8.2-3.el10.x86_64_v2.rpm;name=libnfsidmap-devel;unpack=0"
SRC_URI += "${URI_libnfsidmap-devel}"
SRC_URI[libnfsidmap-devel.sha256sum] = "1430ddb19915334f5fda45f56dbcb4c580aa7e10b90be8e51abb12330a676e8c"
RDEPENDS:libnfsidmap-devel = " \
 libnfsidmap \
 pkgconf-pkg-config \
"

URI_nfs-stats-utils = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/nfs-stats-utils-2.8.2-3.el10.x86_64_v2.rpm;name=nfs-stats-utils;unpack=0"
SRC_URI += "${URI_nfs-stats-utils}"
SRC_URI[nfs-stats-utils.sha256sum] = "841223f48f57eed19c80afe95bc85f446881bd9ca6c347e24a5db4b39db43962"
RDEPENDS:nfs-stats-utils = " \
 python3 \
"
