# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "nodejs-packaging"
PE = "0"
PV = "2023.10"
PR = "9.el10_0"
PACKAGES = "nodejs-packaging nodejs-packaging-bundler"
PROVIDES = "rpm/nodejs-packaging rpm/nodejs-packaging-bundler"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/nodejs-packaging-2023.10-9.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "cfef7753f4cb8ef2adfc2c2583bf9e2b12be999b0976e3b131d0596c20b8d6b7"

URI_nodejs-packaging = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/nodejs-packaging-2023.10-9.el10_0.noarch.rpm;name=nodejs-packaging;unpack=0"
SRC_URI += "${URI_nodejs-packaging}"
SRC_URI[nodejs-packaging.sha256sum] = "77ed7d6846ba534d705102ef894a1b377814d5a9fb0cf9d9d3afe573ebeaa5c4"
RDEPENDS:nodejs-packaging = " \
 python3 \
 redhat-rpm-config \
"

URI_nodejs-packaging-bundler = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/nodejs-packaging-bundler-2023.10-9.el10_0.noarch.rpm;name=nodejs-packaging-bundler;unpack=0"
SRC_URI += "${URI_nodejs-packaging-bundler}"
SRC_URI[nodejs-packaging-bundler.sha256sum] = "bfa7c9980528499b32770fe4466240298f83f823789a798645a294794ba396e9"
RDEPENDS:nodejs-packaging-bundler = " \
 jq \
 bash \
 coreutils \
 nodejs-npm \
 findutils \
"
