# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "nvmetcli"
PE = "0"
PV = "0.8"
PR = "1.el10"
PACKAGES = "nvmetcli"
PROVIDES = "rpm/nvmetcli"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/nvmetcli-0.8-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "db5e68dbd8fa01fbf581d71a5f85efba80632ede4eb8da51296946aad36d8736"

URI_nvmetcli = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/nvmetcli-0.8-1.el10.noarch.rpm;name=nvmetcli;unpack=0"
SRC_URI += "${URI_nvmetcli}"
SRC_URI[nvmetcli.sha256sum] = "b7865f7b9e84d4c9344b61b6c0de05dc4f157e0c64b57704569f523b410f9da3"
RDEPENDS:nvmetcli = " \
 python3 \
 systemd \
 python3-configshell \
 bash \
 python3-kmod \
"
