# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ocaml-cppo"
PE = "0"
PV = "1.6.9"
PR = "12.el10"
PACKAGES = "ocaml-cppo ocaml-cppo-ocamlbuild"
PROVIDES = "rpm/ocaml-cppo rpm/ocaml-cppo-ocamlbuild"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/ocaml-cppo-1.6.9-12.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "45917d54066b4205bd6289bb3a3e3d2a75e1ece1bde49cd9b39b080a6889f200"

URI_ocaml-cppo = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ocaml-cppo-1.6.9-12.el10.x86_64_v2.rpm;name=ocaml-cppo;unpack=0"
SRC_URI += "${URI_ocaml-cppo}"
SRC_URI[ocaml-cppo.sha256sum] = "850d8780802b7f9c2fe6c7abeffcc3d9f25a1cb784c1de4199ee33471924eb6c"
RDEPENDS:ocaml-cppo = " \
 glibc \
"

URI_ocaml-cppo-ocamlbuild = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ocaml-cppo-ocamlbuild-1.6.9-12.el10.x86_64_v2.rpm;name=ocaml-cppo-ocamlbuild;unpack=0"
SRC_URI += "${URI_ocaml-cppo-ocamlbuild}"
SRC_URI[ocaml-cppo-ocamlbuild.sha256sum] = "70523a36f1e91d9f57bf3a727768ab446fafc38ff642d8b292e963b80fdae322"
RDEPENDS:ocaml-cppo-ocamlbuild = " \
 ocaml-runtime \
 ocaml \
 ocaml-cppo \
 glibc \
 ocaml-ocamlbuild \
"
