# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ocaml"
PE = "0"
PV = "5.2.0"
PR = "4.el10"
PACKAGES = "ocaml ocaml-compiler-libs ocaml-docs ocaml-ocamldoc ocaml-rpm-macros ocaml-runtime ocaml-source"
PROVIDES = "rpm/ocaml rpm/ocaml-compiler-libs rpm/ocaml-docs rpm/ocaml-ocamldoc rpm/ocaml-rpm-macros rpm/ocaml-runtime rpm/ocaml-source"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/ocaml-5.2.0-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d51d6e067a008898ed552b0d850679039b209b59735a5ffda5d29db906eef1d3"

URI_ocaml = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ocaml-5.2.0-4.el10.x86_64_v2.rpm;name=ocaml;unpack=0"
SRC_URI += "${URI_ocaml}"
SRC_URI[ocaml.sha256sum] = "92d691479baf83a79422418460799d8df52023de09d25ba7179c67cab1981dc1"
RDEPENDS:ocaml = " \
 ocaml-runtime \
 ocaml-srpm-macros \
 redhat-rpm-config \
 libzstd-devel \
 libzstd \
 gcc \
 glibc \
"

URI_ocaml-compiler-libs = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ocaml-compiler-libs-5.2.0-4.el10.x86_64_v2.rpm;name=ocaml-compiler-libs;unpack=0"
SRC_URI += "${URI_ocaml-compiler-libs}"
SRC_URI[ocaml-compiler-libs.sha256sum] = "e21085ecf3362e772c0fa6f804c4a435b106f16979e870c6ce695b0b472e4a6f"
RDEPENDS:ocaml-compiler-libs = " \
 ocaml-runtime \
 ocaml \
"

URI_ocaml-docs = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ocaml-docs-5.2.0-4.el10.noarch.rpm;name=ocaml-docs;unpack=0"
SRC_URI += "${URI_ocaml-docs}"
SRC_URI[ocaml-docs.sha256sum] = "c761daa626f3372336e336e49e5ef8ef7316762284a1d857ca7fa318460d67e4"
RDEPENDS:ocaml-docs = " \
 ocaml \
"

URI_ocaml-ocamldoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ocaml-ocamldoc-5.2.0-4.el10.x86_64_v2.rpm;name=ocaml-ocamldoc;unpack=0"
SRC_URI += "${URI_ocaml-ocamldoc}"
SRC_URI[ocaml-ocamldoc.sha256sum] = "dd8b6de62c5e2a3f3a6974cfc64b792a11b29e6adf296722784e0569916e11e5"
RDEPENDS:ocaml-ocamldoc = " \
 ocaml-runtime \
 ocaml \
 ocaml-compiler-libs \
 libzstd \
 glibc \
"

URI_ocaml-rpm-macros = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ocaml-rpm-macros-5.2.0-4.el10.noarch.rpm;name=ocaml-rpm-macros;unpack=0"
SRC_URI += "${URI_ocaml-rpm-macros}"
SRC_URI[ocaml-rpm-macros.sha256sum] = "c55d1466dfa5a06f75a24b12dcfa9edd6bb02dc477fff2afbf57b41c80253fd6"
RDEPENDS:ocaml-rpm-macros = " \
 python3 \
 ocaml \
"

URI_ocaml-runtime = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ocaml-runtime-5.2.0-4.el10.x86_64_v2.rpm;name=ocaml-runtime;unpack=0"
SRC_URI += "${URI_ocaml-runtime}"
SRC_URI[ocaml-runtime.sha256sum] = "8b549a6f439c6679627f6d1990c041138d4c1b30c0c59f6f7dd16ae4e55a73a3"
RDEPENDS:ocaml-runtime = " \
 glibc \
 libgcc \
 util-linux \
 libzstd \
"

URI_ocaml-source = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ocaml-source-5.2.0-4.el10.x86_64_v2.rpm;name=ocaml-source;unpack=0"
SRC_URI += "${URI_ocaml-source}"
SRC_URI[ocaml-source.sha256sum] = "dfbf29f11b603df4900be81b214ff684f92bd497a96aacec8481ff66b2f4312e"
RDEPENDS:ocaml-source = " \
 ocaml \
"
