# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ocaml-curses"
PE = "0"
PV = "1.0.11"
PR = "12.el10"
PACKAGES = "ocaml-curses ocaml-curses-devel"
PROVIDES = "rpm/ocaml-curses rpm/ocaml-curses-devel"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/ocaml-curses-1.0.11-12.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "8a6b0a792e34279180025bbfb66eb64bc366217021cdca828b67fc59c245fc90"

URI_ocaml-curses = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ocaml-curses-1.0.11-12.el10.x86_64_v2.rpm;name=ocaml-curses;unpack=0"
SRC_URI += "${URI_ocaml-curses}"
SRC_URI[ocaml-curses.sha256sum] = "794e3f7d1cda6ff0c6ae58aadf566ec070bfd84a0f76a6f83034210f0cc247d6"
RDEPENDS:ocaml-curses = " \
 glibc \
 ocaml-runtime \
 ncurses-libs \
"

URI_ocaml-curses-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ocaml-curses-devel-1.0.11-12.el10.x86_64_v2.rpm;name=ocaml-curses-devel;unpack=0"
SRC_URI += "${URI_ocaml-curses-devel}"
SRC_URI[ocaml-curses-devel.sha256sum] = "ab2434eb3d0adce7041ca9f7003894d73af098d628036dc50a37adf870650fa3"
RDEPENDS:ocaml-curses-devel = " \
 ncurses-devel \
 ocaml-runtime \
 ocaml \
 ocaml-curses \
"
