# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "oniguruma"
PE = "0"
PV = "6.9.9"
PR = "7.el10"
PACKAGES = "oniguruma oniguruma-devel"
PROVIDES = "rpm/oniguruma rpm/oniguruma-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/oniguruma-6.9.9-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "479bb902b2324247d5238611cf078979e4beccc3872c3d3803ecb6266e0ba740"

URI_oniguruma = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/oniguruma-6.9.9-7.el10.x86_64_v2.rpm;name=oniguruma;unpack=0"
SRC_URI += "${URI_oniguruma}"
SRC_URI[oniguruma.sha256sum] = "3631cdbd84800c12de026ec836470f2b3a91de380333e3e52165b6c9572b007a"
RDEPENDS:oniguruma = " \
 glibc \
"

URI_oniguruma-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/oniguruma-devel-6.9.9-7.el10.x86_64_v2.rpm;name=oniguruma-devel;unpack=0"
SRC_URI += "${URI_oniguruma-devel}"
SRC_URI[oniguruma-devel.sha256sum] = "c15522d80a9a44f07a98dafb381d1743d69f8209b11840272755607f02383c9d"
RDEPENDS:oniguruma-devel = " \
 oniguruma \
 bash \
 pkgconf-pkg-config \
"
