# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "opencsd"
PE = "0"
PV = "1.4.1"
PR = "4.el10"
PACKAGES = "opencsd opencsd-devel"
PROVIDES = "rpm/opencsd rpm/opencsd-devel"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/opencsd-1.4.1-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "bea9c58415be95b131e487d04b745788f057a2fc1c8bbd9dc3638cbb478e6c66"

URI_opencsd = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/opencsd-1.4.1-4.el10.x86_64_v2.rpm;name=opencsd;unpack=0"
SRC_URI += "${URI_opencsd}"
SRC_URI[opencsd.sha256sum] = "25516718ce2706fc0779a2e6fa009e1e2449fd79218b50afdad287e65f9f660c"
RDEPENDS:opencsd = " \
 glibc \
 libgcc \
 libstdc++ \
"

URI_opencsd-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/opencsd-devel-1.4.1-4.el10.x86_64_v2.rpm;name=opencsd-devel;unpack=0"
SRC_URI += "${URI_opencsd-devel}"
SRC_URI[opencsd-devel.sha256sum] = "c7609f38227d50c0dd335ab2ceb210e373712c3c6260812109b6a9001f9dd430"
RDEPENDS:opencsd-devel = " \
 opencsd \
"
