# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "openssl"
PE = "1"
PV = "3.2.2"
PR = "16.el10_0.4.alma.1"
PACKAGES = "openssl openssl-libs openssl-devel openssl-perl"
PROVIDES = "rpm/openssl rpm/openssl-libs rpm/openssl-devel rpm/openssl-perl"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/openssl-3.2.2-16.el10_0.4.alma.1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "6125da460ec83736af5ce6dbaf0593692175fed73ff40fd7e548bef33b390165"

URI_openssl = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/openssl-3.2.2-16.el10_0.4.alma.1.x86_64_v2.rpm;name=openssl;unpack=0"
SRC_URI += "${URI_openssl}"
SRC_URI[openssl.sha256sum] = "f9a00323dc0f3faada1e8b61ddf885c4118c63ed9c4df322229737ced6ec102f"
RDEPENDS:openssl = " \
 glibc \
 coreutils \
 openssl-libs \
 bash \
"

URI_openssl-libs = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/openssl-libs-3.2.2-16.el10_0.4.alma.1.x86_64_v2.rpm;name=openssl-libs;unpack=0"
SRC_URI += "${URI_openssl-libs}"
SRC_URI[openssl-libs.sha256sum] = "e5bc310f9691a35e77babba26c6309bc5529ac5371900a6150043cca9b6693c1"
RDEPENDS:openssl-libs = " \
 glibc \
 crypto-policies \
 zlib-ng-compat \
 ca-certificates \
"

URI_openssl-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/openssl-devel-3.2.2-16.el10_0.4.alma.1.x86_64_v2.rpm;name=openssl-devel;unpack=0"
SRC_URI += "${URI_openssl-devel}"
SRC_URI[openssl-devel.sha256sum] = "97f57f18ea3ff8ed1b0de6d8162f1dbee4198ef6a55cbefd7a70cd984241e686"
RDEPENDS:openssl-devel = " \
 openssl-devel \
 openssl-libs \
 pkgconf-pkg-config \
"

URI_openssl-perl = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/openssl-perl-3.2.2-16.el10_0.4.alma.1.x86_64_v2.rpm;name=openssl-perl;unpack=0"
SRC_URI += "${URI_openssl-perl}"
SRC_URI[openssl-perl.sha256sum] = "b4758606304d0ef233d12078edb6d272b0e5ee20966d9503d87cc9755faaeae6"
RDEPENDS:openssl-perl = " \
 openssl \
 perl-interpreter \
"
