# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "openexr"
PE = "0"
PV = "3.1.10"
PR = "8.el10"
PACKAGES = "openexr openexr-libs openexr-devel"
PROVIDES = "rpm/openexr rpm/openexr-libs rpm/openexr-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/openexr-3.1.10-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "be8fa7c1def1b67dc8c1b036a95431c7452caa1fbc289b2cfb8b39b717746cae"

URI_openexr = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/openexr-3.1.10-8.el10.x86_64_v2.rpm;name=openexr;unpack=0"
SRC_URI += "${URI_openexr}"
SRC_URI[openexr.sha256sum] = "3b2acb29de6ed44360e576eb627a2f00173344d4177978d9059eecf6132ad9c2"
RDEPENDS:openexr = " \
 imath \
 openexr-libs \
 libgcc \
 libstdc++ \
 glibc \
"

URI_openexr-libs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/openexr-libs-3.1.10-8.el10.x86_64_v2.rpm;name=openexr-libs;unpack=0"
SRC_URI += "${URI_openexr-libs}"
SRC_URI[openexr-libs.sha256sum] = "a800fc20cf9d8c6670b0801d84cfd685abf3f8deaf04dfc744e003f2844545d3"
RDEPENDS:openexr-libs = " \
 imath \
 zlib-ng-compat \
 libgcc \
 libstdc++ \
 glibc \
"

URI_openexr-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/openexr-devel-3.1.10-8.el10.x86_64_v2.rpm;name=openexr-devel;unpack=0"
SRC_URI += "${URI_openexr-devel}"
SRC_URI[openexr-devel.sha256sum] = "ecde25469e45e3fe5bbefbe8df57812563aa43afb1d8beba5612d7e56c034da0"
RDEPENDS:openexr-devel = " \
 openexr-libs \
 cmake-filesystem \
 pkgconf-pkg-config \
 imath-devel \
"
