# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "opendnssec"
PE = "0"
PV = "2.1.14"
PR = "1.el10"
PACKAGES = "opendnssec"
PROVIDES = "rpm/opendnssec"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/opendnssec-2.1.14-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f21bb0f21731ed4a1b2f64308ea67469677a4f6f2c6fedf1a3403eb48fa5ec25"

URI_opendnssec = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/opendnssec-2.1.14-1.el10.x86_64_v2.rpm;name=opendnssec;unpack=0"
SRC_URI += "${URI_opendnssec}"
SRC_URI[opendnssec.sha256sum] = "93dbd63edb967b418e40bb5ec6876d5c3d89cf31182d8b35a47b40695ad0f118"
RDEPENDS:opendnssec = " \
 softhsm \
 shadow-utils \
 zlib-ng-compat \
 systemd \
 libxslt \
 ldns \
 openssl-libs \
 libxml2 \
 sqlite-libs \
 bash \
 opencryptoki \
 glibc \
 sqlite \
 xz-libs \
"
