# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "openssl-ibmca"
PE = "0"
PV = "2.4.1"
PR = "6.el10"
PACKAGES = ""
PROVIDES = ""


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/openssl-ibmca-2.4.1-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ddd562be8693cdba7dd57ab250b4e4708ddda9e7bcd4bdd5fd0e47e08408c433"
