# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "opensc"
PE = "0"
PV = "0.26.1"
PR = "1.el10"
PACKAGES = "opensc opensc-libs"
PROVIDES = "rpm/opensc rpm/opensc-libs"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/opensc-0.26.1-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "75899b863fdf71d0d0129a62752d6e237b793f1354a0262ef0a95878eaf43b38"

URI_opensc = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/opensc-0.26.1-1.el10.x86_64_v2.rpm;name=opensc;unpack=0"
SRC_URI += "${URI_opensc}"
SRC_URI[opensc.sha256sum] = "f2eec6607645ccb7097de7844ad2b30c3212662b861a4dd0c0a40f0fd1895d3c"
RDEPENDS:opensc = " \
 opensc-libs \
 zlib-ng-compat \
 openssl-libs \
 readline \
 pcsc-lite \
 glibc \
"

URI_opensc-libs = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/opensc-libs-0.26.1-1.el10.x86_64_v2.rpm;name=opensc-libs;unpack=0"
SRC_URI += "${URI_opensc-libs}"
SRC_URI[opensc-libs.sha256sum] = "649faff20882fda247c27a4fe2cb968f3834949f0776e2cd472dee50a8ea9c17"
RDEPENDS:opensc-libs = " \
 glibc \
 pcsc-lite-libs \
 openssl-libs \
 zlib-ng-compat \
"
