# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "pam_wrapper"
PE = "0"
PV = "1.1.4"
PR = "14.el10"
PACKAGES = "pam_wrapper libpamtest libpamtest-devel libpamtest-doc python3-libpamtest"
PROVIDES = "rpm/pam_wrapper rpm/libpamtest rpm/libpamtest-devel rpm/libpamtest-doc rpm/python3-libpamtest"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/pam_wrapper-1.1.4-14.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "22ad0ead45bd66ffb1d4f8cd6e8ce1df42a517f72f0b1af7a005ef6adf745908"

URI_pam_wrapper = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/pam_wrapper-1.1.4-14.el10.x86_64_v2.rpm;name=pam_wrapper;unpack=0"
SRC_URI += "${URI_pam_wrapper}"
SRC_URI[pam_wrapper.sha256sum] = "7a7c06670972e4581336049b7e8958f94e13f0d805f374886f5c00d4010cff6c"
RDEPENDS:pam_wrapper = " \
 glibc \
 pam-libs \
 cmake-filesystem \
 pkgconf-pkg-config \
"

URI_libpamtest = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libpamtest-1.1.4-14.el10.x86_64_v2.rpm;name=libpamtest;unpack=0"
SRC_URI += "${URI_libpamtest}"
SRC_URI[libpamtest.sha256sum] = "a04f61b3e46f13f9879168466f750c15ff6499029e764bc2eccbb729b04c91f4"
RDEPENDS:libpamtest = " \
 glibc \
 pam-libs \
 pam_wrapper \
"

URI_libpamtest-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libpamtest-devel-1.1.4-14.el10.x86_64_v2.rpm;name=libpamtest-devel;unpack=0"
SRC_URI += "${URI_libpamtest-devel}"
SRC_URI[libpamtest-devel.sha256sum] = "d1a25348f34ba3fd5ccb29227d0796b155678909dc171c1fd84c183477cc930d"
RDEPENDS:libpamtest-devel = " \
 libpamtest \
 pam_wrapper \
 cmake-filesystem \
 pkgconf-pkg-config \
"

URI_libpamtest-doc = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libpamtest-doc-1.1.4-14.el10.x86_64_v2.rpm;name=libpamtest-doc;unpack=0"
SRC_URI += "${URI_libpamtest-doc}"
SRC_URI[libpamtest-doc.sha256sum] = "425aec2726f8cb11a6edd5f3e1c2f21a7028db294fab6402b49ff4bdc5ecb767"
RDEPENDS:libpamtest-doc = ""

URI_python3-libpamtest = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/python3-libpamtest-1.1.4-14.el10.x86_64_v2.rpm;name=python3-libpamtest;unpack=0"
SRC_URI += "${URI_python3-libpamtest}"
SRC_URI[python3-libpamtest.sha256sum] = "a50d127d74d6d6dcf57a1b2bf56b75fb5a8f7d8fdc36cbe9dfecd173f69f648b"
RDEPENDS:python3-libpamtest = " \
 python3 \
 pam_wrapper \
 python3-libs \
 libpamtest \
 glibc \
"
