# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "pappl"
PE = "0"
PV = "1.4.6"
PR = "5.el10"
PACKAGES = "pappl pappl-devel"
PROVIDES = "rpm/pappl rpm/pappl-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/pappl-1.4.6-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "051aa638e04efde03e7cdb3a23f1e91ce4b1eed83c53c0083314b87296365489"

URI_pappl = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/pappl-1.4.6-5.el10.x86_64_v2.rpm;name=pappl;unpack=0"
SRC_URI += "${URI_pappl}"
SRC_URI[pappl.sha256sum] = "519fd25c14e113ad21b05a3d3fd75a27580a6101d8d773198eff7ddef6ae305a"
RDEPENDS:pappl = " \
 gnutls \
 libpng \
 cups-libs \
 pam-libs \
 avahi-libs \
 glibc \
 libjpeg-turbo \
 libusb1 \
"

URI_pappl-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/pappl-devel-1.4.6-5.el10.x86_64_v2.rpm;name=pappl-devel;unpack=0"
SRC_URI += "${URI_pappl-devel}"
SRC_URI[pappl-devel.sha256sum] = "d486b0d459c3a2b20a55c1ef42bc7575975f7e19765ae608fc297aa525d5ffc7"
RDEPENDS:pappl-devel = " \
 gnutls-devel \
 zlib-ng-compat-devel \
 avahi-devel \
 pkgconf-pkg-config \
 libusb1-devel \
 bash \
 libpng-devel \
 pappl \
 libjpeg-turbo-devel \
"
