# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "pcaudiolib"
PE = "0"
PV = "1.1"
PR = "20.el10"
PACKAGES = "pcaudiolib pcaudiolib-devel"
PROVIDES = "rpm/pcaudiolib rpm/pcaudiolib-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/pcaudiolib-1.1-20.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "759bb0ccb30000ee13425e67b77f9838138a5e0525a40ffa8608292822ee099b"

URI_pcaudiolib = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/pcaudiolib-1.1-20.el10.x86_64_v2.rpm;name=pcaudiolib;unpack=0"
SRC_URI += "${URI_pcaudiolib}"
SRC_URI[pcaudiolib.sha256sum] = "2c54b2f7204c22e8c21e447ae0f5eb7dfbef246ede11a46d9b5ab4b144bbe839"
RDEPENDS:pcaudiolib = " \
 glibc \
 pulseaudio-libs \
 alsa-lib \
"

URI_pcaudiolib-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/pcaudiolib-devel-1.1-20.el10.x86_64_v2.rpm;name=pcaudiolib-devel;unpack=0"
SRC_URI += "${URI_pcaudiolib-devel}"
SRC_URI[pcaudiolib-devel.sha256sum] = "f2acf4f47fc6e0777f97f3e3b2d38e43cdcbcecb1c1b8a2683ae60bd869487ad"
RDEPENDS:pcaudiolib-devel = " \
 pcaudiolib \
"
