# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "pcsc-lite-ccid"
PE = "0"
PV = "1.6.0"
PR = "2.el10"
PACKAGES = "pcsc-lite-ccid"
PROVIDES = "rpm/pcsc-lite-ccid"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/pcsc-lite-ccid-1.6.0-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "6a3e331735ec8f6efd8ccbfc14d83d49ec9cae13a3107b21212b0550c4c48ded"

URI_pcsc-lite-ccid = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/pcsc-lite-ccid-1.6.0-2.el10.x86_64_v2.rpm;name=pcsc-lite-ccid;unpack=0"
SRC_URI += "${URI_pcsc-lite-ccid}"
SRC_URI[pcsc-lite-ccid.sha256sum] = "28ad3539ba221601cf2033306d9c8cf1ce69fea984cb4c22b807691c92b9eed5"
RDEPENDS:pcsc-lite-ccid = " \
 systemd \
 bash \
 pcsc-lite \
 glibc \
 libusb1 \
"
