# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-XML-Catalog"
PE = "0"
PV = "1.03"
PR = "32.el10"
PACKAGES = "perl-XML-Catalog perl-XML-Catalog-tests"
PROVIDES = "rpm/perl-XML-Catalog rpm/perl-XML-Catalog-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-XML-Catalog-1.03-32.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0dc48b251ebf5ada9672c19ca9335ac1f42afd8cac8ee8a92e436291460de454"

URI_perl-XML-Catalog = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-XML-Catalog-1.03-32.el10.noarch.rpm;name=perl-XML-Catalog;unpack=0"
SRC_URI += "${URI_perl-XML-Catalog}"
SRC_URI[perl-XML-Catalog.sha256sum] = "1f7271c2fbf4f48efddafbb5217044554b1ea598287dda53dc69573cbaf5605a"
RDEPENDS:perl-XML-Catalog = " \
 perl-libs \
 perl-libwww-perl \
 perl-vars \
 perl-URI \
 perl-Text-ParseWords \
 perl-XML-Parser \
"

URI_perl-XML-Catalog-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-XML-Catalog-tests-1.03-32.el10.noarch.rpm;name=perl-XML-Catalog-tests;unpack=0"
SRC_URI += "${URI_perl-XML-Catalog-tests}"
SRC_URI[perl-XML-Catalog-tests.sha256sum] = "e57dec81dfa4f15627e77f999a8d7be6f9475be635249d0bcee990f6f18df37c"
RDEPENDS:perl-XML-Catalog-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-XML-Catalog \
 bash \
 perl-PathTools \
 perl-interpreter \
"
