# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Devel-Size"
PE = "0"
PV = "0.84"
PR = "3.el10"
PACKAGES = "perl-Devel-Size perl-Devel-Size-tests"
PROVIDES = "rpm/perl-Devel-Size rpm/perl-Devel-Size-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Devel-Size-0.84-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "908ecee073d0aaea387674797373d763626781e62a91e4eda5afac99cbfa3a6b"

URI_perl-Devel-Size = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Devel-Size-0.84-3.el10.x86_64_v2.rpm;name=perl-Devel-Size;unpack=0"
SRC_URI += "${URI_perl-Devel-Size}"
SRC_URI[perl-Devel-Size.sha256sum] = "242cd59e19bee5b440ea293acd84b2455b8bb6e947e7f11327b2f3378bc63e62"
RDEPENDS:perl-Devel-Size = " \
 glibc \
 perl-Exporter \
 perl-libs \
 perl-vars \
"

URI_perl-Devel-Size-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Devel-Size-tests-0.84-3.el10.x86_64_v2.rpm;name=perl-Devel-Size-tests;unpack=0"
SRC_URI += "${URI_perl-Devel-Size-tests}"
SRC_URI[perl-Devel-Size-tests.sha256sum] = "1e440d943e07ca4ab0dd3adc738ec60fbf55f3aa46bb2c7dd3d28eb5dcfe8504"
RDEPENDS:perl-Devel-Size-tests = " \
 perl-constant \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-vars \
 perl-Scalar-List-Utils \
 perl-Devel-Size \
 bash \
 perl-Tie \
 perl-interpreter \
"
