# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-DBD-Pg"
PE = "0"
PV = "3.18.0"
PR = "6.el10"
PACKAGES = "perl-DBD-Pg perl-DBD-Pg-tests"
PROVIDES = "rpm/perl-DBD-Pg rpm/perl-DBD-Pg-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-DBD-Pg-3.18.0-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "681d3173f708e559bd1b605b5aaad72f2ea8f33d7868ec000046e5c2e6f63097"

URI_perl-DBD-Pg = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-DBD-Pg-3.18.0-6.el10.x86_64_v2.rpm;name=perl-DBD-Pg;unpack=0"
SRC_URI += "${URI_perl-DBD-Pg}"
SRC_URI[perl-DBD-Pg.sha256sum] = "973626c4c6a59fc2d40897c23bf741a24f2e30c6cb79e3878229c47147f524fb"
RDEPENDS:perl-DBD-Pg = " \
 perl-constant \
 perl-libs \
 libpq \
 perl-version \
 perl-DBI \
 glibc \
 perl-Exporter \
"

URI_perl-DBD-Pg-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-DBD-Pg-tests-3.18.0-6.el10.x86_64_v2.rpm;name=perl-DBD-Pg-tests;unpack=0"
SRC_URI += "${URI_perl-DBD-Pg-tests}"
SRC_URI[perl-DBD-Pg-tests.sha256sum] = "9b0d06599f27ade093a6359523b67501d2de94a88d69c971f6cf39b90680c5b4"
RDEPENDS:perl-DBD-Pg-tests = " \
 perl-libs \
 perl-open \
 perl-Test-Harness \
 perl-Test-Simple \
 perl-Carp \
 postgresql-server \
 perl-DBD-Pg \
 perl-lib \
 perl-Data-Dumper \
 perl-Time-HiRes \
 perl-Time-Piece \
 perl-Encode \
 bash \
 perl-constant \
 perl-Fcntl \
 perl-POSIX \
 perl-PathTools \
 perl-interpreter \
 perl-File-Temp \
"
