# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Test-Differences"
PE = "0"
PV = "0.7100"
PR = "7.el10"
PACKAGES = "perl-Test-Differences perl-Test-Differences-tests"
PROVIDES = "rpm/perl-Test-Differences rpm/perl-Test-Differences-tests"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/perl-Test-Differences-0.7100-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7c06ac1bd3e1e8f5dbf924f85cd0f1a5092be1df0a97b902a5431612b20ecd59"

URI_perl-Test-Differences = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/perl-Test-Differences-0.7100-7.el10.noarch.rpm;name=perl-Test-Differences;unpack=0"
SRC_URI += "${URI_perl-Test-Differences}"
SRC_URI[perl-Test-Differences.sha256sum] = "e16fb8b0fda2e53dfba5c48c54ca97ab6b7d11c7df0d5edb87fb8e98f3465910"
RDEPENDS:perl-Test-Differences = " \
 perl-constant \
 perl-libs \
 perl-Carp \
 perl-Text-Diff \
 perl-B \
 perl-Exporter \
 perl-Data-Dumper \
"

URI_perl-Test-Differences-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Test-Differences-tests-0.7100-7.el10.noarch.rpm;name=perl-Test-Differences-tests;unpack=0"
SRC_URI += "${URI_perl-Test-Differences-tests}"
SRC_URI[perl-Test-Differences-tests.sha256sum] = "aa68b5863fb6cfaafebefa3c39adc8e8ab349ad9947a1fe6428c0ce1868b59f4"
RDEPENDS:perl-Test-Differences-tests = " \
 perl-Test \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-Capture-Tiny \
 bash \
 perl-interpreter \
 perl-Test-Differences \
 perl-Data-Dumper \
 perl-Exporter \
 perl-lib \
"
