# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Module-Install-AutoLicense"
PE = "0"
PV = "0.10"
PR = "23.el10"
PACKAGES = "perl-Module-Install-AutoLicense"
PROVIDES = "rpm/perl-Module-Install-AutoLicense"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/perl-Module-Install-AutoLicense-0.10-23.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "fb8b5deb472fdf45a19afc996e2639cf4db5ee60e06aa70c1867d3fd52f4ab18"

URI_perl-Module-Install-AutoLicense = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Module-Install-AutoLicense-0.10-23.el10.noarch.rpm;name=perl-Module-Install-AutoLicense;unpack=0"
SRC_URI += "${URI_perl-Module-Install-AutoLicense}"
SRC_URI[perl-Module-Install-AutoLicense.sha256sum] = "8f6c0e47770fd2e2e6c5fcdcc8ca836b481d5672394b7bcac88fd82fe72e9b2a"
RDEPENDS:perl-Module-Install-AutoLicense = " \
 perl-libs \
 perl-vars \
 perl-Module-Install \
 perl-Software-License \
 perl-base \
"
