# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-File-pushd"
PE = "0"
PV = "1.016"
PR = "23.el10"
PACKAGES = "perl-File-pushd perl-File-pushd-tests"
PROVIDES = "rpm/perl-File-pushd rpm/perl-File-pushd-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-File-pushd-1.016-23.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "fc8453535d1daa395c9614a9c139be99062ef924708cd2b1d5ad6c967ddd795e"

URI_perl-File-pushd = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-File-pushd-1.016-23.el10.noarch.rpm;name=perl-File-pushd;unpack=0"
SRC_URI += "${URI_perl-File-pushd}"
SRC_URI[perl-File-pushd.sha256sum] = "a052e73d7b6a9c1738f7b31d94989823ebb9ae42c53039cd6b9ba32b6980d74c"
RDEPENDS:perl-File-pushd = " \
 perl-libs \
 perl-Carp \
 perl-overload \
 perl-PathTools \
 perl-Exporter \
 perl-File-Path \
 perl-File-Temp \
"

URI_perl-File-pushd-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-File-pushd-tests-1.016-23.el10.noarch.rpm;name=perl-File-pushd-tests;unpack=0"
SRC_URI += "${URI_perl-File-pushd-tests}"
SRC_URI[perl-File-pushd-tests.sha256sum] = "73d41f6d9fa73e9f8e49261c4cba1bed8f91b4b1409947aa771e76d9c7c35b58"
RDEPENDS:perl-File-pushd-tests = " \
 perl-File-pushd \
 perl-Test-Harness \
 perl-libs \
 perl-ExtUtils-MakeMaker \
 perl-Test-Simple \
 perl-File-Basename \
 perl-PathTools \
 bash \
 perl-interpreter \
 perl-File-Path \
 perl-File-Temp \
"
