# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Archive-Tar"
PE = "0"
PV = "3.02"
PR = "512.el10"
PACKAGES = "perl-Archive-Tar perl-Archive-Tar-tests"
PROVIDES = "rpm/perl-Archive-Tar rpm/perl-Archive-Tar-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Archive-Tar-3.02-512.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f5a1963c7c59cabcfdd46dab94b19126a2c2195bf371d17012b0db58c5857a28"

URI_perl-Archive-Tar = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Archive-Tar-3.02-512.el10.noarch.rpm;name=perl-Archive-Tar;unpack=0"
SRC_URI += "${URI_perl-Archive-Tar}"
SRC_URI[perl-Archive-Tar.sha256sum] = "2c202ddea65486e9c0153c77154a550f57cd172ab21bc75e863ce7e5e89f7420"
RDEPENDS:perl-Archive-Tar = " \
 perl-libs \
 perl-Getopt-Long \
 perl-Archive-Tar \
 perl-Getopt-Std \
 perl-Carp \
 perl-vars \
 perl-IO \
 perl-IO-Compress \
 perl-Text-Diff \
 perl-IO-Compress-Lzma \
 perl-IO-Zlib \
 perl-Data-Dumper \
 perl-Exporter \
 perl-constant \
 perl-File-Basename \
 perl-PathTools \
 perl-File-Find \
 perl-interpreter \
 perl-File-Path \
 perl-Pod-Usage \
"

URI_perl-Archive-Tar-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Archive-Tar-tests-3.02-512.el10.noarch.rpm;name=perl-Archive-Tar-tests;unpack=0"
SRC_URI += "${URI_perl-Archive-Tar-tests}"
SRC_URI[perl-Archive-Tar-tests.sha256sum] = "5c8fbd001e8414594d1b2150cb0a558a117ed24f64b63f66aa42b1aff20dabd9"
RDEPENDS:perl-Archive-Tar-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-ExtUtils-MakeMaker \
 perl-IO \
 perl-FindBin \
 perl-Archive-Tar \
 perl-File-Basename \
 perl-IPC-Cmd \
 perl-File-Temp \
 perl-File-Copy \
 bash \
 perl-PathTools \
 perl-interpreter \
 perl-File-Path \
 perl-Data-Dumper \
 perl-lib \
"
