# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Socket"
PE = "4"
PV = "2.038"
PR = "511.el10"
PACKAGES = "perl-Socket perl-Socket-tests"
PROVIDES = "rpm/perl-Socket rpm/perl-Socket-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Socket-2.038-511.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5a42d50e289d2f880629382c70f4d53f1f2e59a4e77fcac3912907348610066f"

URI_perl-Socket = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Socket-2.038-511.el10.x86_64_v2.rpm;name=perl-Socket;unpack=0"
SRC_URI += "${URI_perl-Socket}"
SRC_URI[perl-Socket.sha256sum] = "f270ad7067c1825220b57124754e51babba72f0c5860176ad646bdbd62c48b5a"
RDEPENDS:perl-Socket = " \
 glibc \
 perl-Exporter \
 perl-libs \
 perl-Carp \
"

URI_perl-Socket-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Socket-tests-2.038-511.el10.x86_64_v2.rpm;name=perl-Socket-tests;unpack=0"
SRC_URI += "${URI_perl-Socket-tests}"
SRC_URI[perl-Socket-tests.sha256sum] = "63029ba0ea29e0e04eec9a5cb27421ecf27f20b50679980cbdc89cba852557ed"
RDEPENDS:perl-Socket-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-Socket \
 bash \
 perl-Errno \
 perl-interpreter \
"
