# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Text-Balanced"
PE = "0"
PV = "2.06"
PR = "511.el10"
PACKAGES = "perl-Text-Balanced perl-Text-Balanced-tests"
PROVIDES = "rpm/perl-Text-Balanced rpm/perl-Text-Balanced-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Text-Balanced-2.06-511.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e8f95c2535909ead6ffd5ead732395eb8aaf9d97f88473a1df937f4d4b1995e7"

URI_perl-Text-Balanced = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Text-Balanced-2.06-511.el10.noarch.rpm;name=perl-Text-Balanced;unpack=0"
SRC_URI += "${URI_perl-Text-Balanced}"
SRC_URI[perl-Text-Balanced.sha256sum] = "e71870819c5c42fd438d7d953882ad7590f485fa203f6ffd126fa80ce23d5ad1"
RDEPENDS:perl-Text-Balanced = " \
 perl-libs \
 perl-Carp \
 perl-vars \
 perl-overload \
 perl-Exporter \
"

URI_perl-Text-Balanced-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Text-Balanced-tests-2.06-511.el10.noarch.rpm;name=perl-Text-Balanced-tests;unpack=0"
SRC_URI += "${URI_perl-Text-Balanced-tests}"
SRC_URI[perl-Text-Balanced-tests.sha256sum] = "c3a818a0b3fc016764c381a37b99e67d88b9bbb38a8cbf1bed0360a40896fb32"
RDEPENDS:perl-Text-Balanced-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-Text-Balanced \
 bash \
 perl-interpreter \
"
