# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-libnet"
PE = "0"
PV = "3.15"
PR = "512.el10"
PACKAGES = "perl-libnet perl-libnet-tests"
PROVIDES = "rpm/perl-libnet rpm/perl-libnet-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-libnet-3.15-512.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4aa48d583b12668e662dc64557d0566a493523fc41efa0115aa062ae2ffe8358"

URI_perl-libnet = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-libnet-3.15-512.el10.noarch.rpm;name=perl-libnet;unpack=0"
SRC_URI += "${URI_perl-libnet}"
SRC_URI[perl-libnet.sha256sum] = "1c7a64f05cf253c039ec909729408925c259d751fa764b47af823a4b5fac0ca1"
RDEPENDS:perl-libnet = " \
 perl-libnet \
 perl-constant \
 perl-libs \
 perl-Carp \
 perl-FileHandle \
 perl-IO \
 perl-Digest-MD5 \
 perl-Socket \
 perl-Fcntl \
 perl-IO-Socket-IP \
 perl-POSIX \
 perl-File-Basename \
 perl-Symbol \
 perl-Errno \
 perl-Exporter \
 perl-Time-Local \
"

URI_perl-libnet-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-libnet-tests-3.15-512.el10.noarch.rpm;name=perl-libnet-tests;unpack=0"
SRC_URI += "${URI_perl-libnet-tests}"
SRC_URI[perl-libnet-tests.sha256sum] = "f33a56400aefe95f53ae188d94d9f7f888b0eb984edb70ea5f3b5e52b3670056"
RDEPENDS:perl-libnet-tests = " \
 perl-libnet \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-IO \
 perl-IO-Socket-SSL \
 bash \
 perl-PathTools \
 perl-interpreter \
 perl-File-Temp \
"
