# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-String-ShellQuote"
PE = "0"
PV = "1.04"
PR = "45.el10"
PACKAGES = "perl-String-ShellQuote perl-String-ShellQuote-tests"
PROVIDES = "rpm/perl-String-ShellQuote rpm/perl-String-ShellQuote-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-String-ShellQuote-1.04-45.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a554af9b60df0eacc7d2300ce8bf09a8be48ea6fd6c02dfbc4c7289fc8f0a256"

URI_perl-String-ShellQuote = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-String-ShellQuote-1.04-45.el10.noarch.rpm;name=perl-String-ShellQuote;unpack=0"
SRC_URI += "${URI_perl-String-ShellQuote}"
SRC_URI[perl-String-ShellQuote.sha256sum] = "a36249964871707499b23f18470553379c202a867370124965250dd4baa8b9f4"
RDEPENDS:perl-String-ShellQuote = " \
 perl-libs \
 perl-Carp \
 perl-vars \
 perl-interpreter \
 perl-Getopt-Long \
 perl-String-ShellQuote \
 perl-Exporter \
"

URI_perl-String-ShellQuote-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-String-ShellQuote-tests-1.04-45.el10.noarch.rpm;name=perl-String-ShellQuote-tests;unpack=0"
SRC_URI += "${URI_perl-String-ShellQuote-tests}"
SRC_URI[perl-String-ShellQuote-tests.sha256sum] = "7e6c4cf09e5f8e5ecbf308183d2e860a06b4f9c0c18f58a906381519d2c45c73"
RDEPENDS:perl-String-ShellQuote-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-String-ShellQuote \
 bash \
 perl-interpreter \
"
