# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-NTLM"
PE = "0"
PV = "1.09"
PR = "41.el10"
PACKAGES = "perl-NTLM perl-NTLM-tests"
PROVIDES = "rpm/perl-NTLM rpm/perl-NTLM-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-NTLM-1.09-41.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "8ba41fcb4cc735a83009dcf60ab8b66e4a44e93093408409ccc24728bd8c3bbc"

URI_perl-NTLM = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-NTLM-1.09-41.el10.noarch.rpm;name=perl-NTLM;unpack=0"
SRC_URI += "${URI_perl-NTLM}"
SRC_URI[perl-NTLM.sha256sum] = "afd979172e04a8cc4caa742c118219f99702e3a7915fa4e7166e757aab240849"
RDEPENDS:perl-NTLM = " \
 perl-constant \
 perl-libs \
 perl-vars \
 perl-Digest-HMAC \
 perl-NTLM \
 perl-Exporter \
 perl-MIME-Base64 \
"

URI_perl-NTLM-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-NTLM-tests-1.09-41.el10.noarch.rpm;name=perl-NTLM-tests;unpack=0"
SRC_URI += "${URI_perl-NTLM-tests}"
SRC_URI[perl-NTLM-tests.sha256sum] = "19337a592aec9fa6e7ac77f6c930d9a83513c0ae8db9402f4409fab1230a90f9"
RDEPENDS:perl-NTLM-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 bash \
 perl-NTLM \
 perl-interpreter \
 perl-MIME-Base64 \
"
