# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Module-Install-AuthorRequires"
PE = "0"
PV = "0.02"
PR = "36.el10"
PACKAGES = "perl-Module-Install-AuthorRequires perl-Module-Install-AuthorRequires-tests"
PROVIDES = "rpm/perl-Module-Install-AuthorRequires rpm/perl-Module-Install-AuthorRequires-tests"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/perl-Module-Install-AuthorRequires-0.02-36.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "883244206c060f0a0ecf7de63de5e083321df046692142c267efad9df42d2aab"

URI_perl-Module-Install-AuthorRequires = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Module-Install-AuthorRequires-0.02-36.el10.noarch.rpm;name=perl-Module-Install-AuthorRequires;unpack=0"
SRC_URI += "${URI_perl-Module-Install-AuthorRequires}"
SRC_URI[perl-Module-Install-AuthorRequires.sha256sum] = "b3e37463272769fb84e377c9e680a041c7173e7cb9aa7afc42c49c52c083c14a"
RDEPENDS:perl-Module-Install-AuthorRequires = " \
 perl-Module-Install \
 perl-libs \
 perl-base \
"

URI_perl-Module-Install-AuthorRequires-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Module-Install-AuthorRequires-tests-0.02-36.el10.noarch.rpm;name=perl-Module-Install-AuthorRequires-tests;unpack=0"
SRC_URI += "${URI_perl-Module-Install-AuthorRequires-tests}"
SRC_URI[perl-Module-Install-AuthorRequires-tests.sha256sum] = "1c4ced151b7de8f3eaf0f86a643faed06f63e42cf9b18adfce99ad1412c7ddd1"
RDEPENDS:perl-Module-Install-AuthorRequires-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 bash \
 perl-interpreter \
 perl-Module-Install-AuthorRequires \
"
