# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Pod-Markdown"
PE = "0"
PV = "3.400"
PR = "6.el10"
PACKAGES = "perl-Pod-Markdown perl-Pod-Markdown-tests"
PROVIDES = "rpm/perl-Pod-Markdown rpm/perl-Pod-Markdown-tests"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/perl-Pod-Markdown-3.400-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "090bb8712e0f4fd4f67a7f95eb2f757385ac0ee9e4306e23e697838c62dba9fd"

URI_perl-Pod-Markdown = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/perl-Pod-Markdown-3.400-6.el10.noarch.rpm;name=perl-Pod-Markdown;unpack=0"
SRC_URI += "${URI_perl-Pod-Markdown}"
SRC_URI[perl-Pod-Markdown.sha256sum] = "07f4b7228e834675cf232713987b24a901cfb10f42e30e8c43256f337b3661fb"
RDEPENDS:perl-Pod-Markdown = " \
 perl-libs \
 perl-URI \
 perl-Getopt-Long \
 perl-Encode \
 perl-Pod-Markdown \
 perl-parent \
 perl-interpreter \
 perl-Pod-Simple \
 perl-Pod-Usage \
"

URI_perl-Pod-Markdown-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Pod-Markdown-tests-3.400-6.el10.noarch.rpm;name=perl-Pod-Markdown-tests;unpack=0"
SRC_URI += "${URI_perl-Pod-Markdown-tests}"
SRC_URI[perl-Pod-Markdown-tests.sha256sum] = "02314157e70a7a826d601a3a2c094de48dc22c1b611f84ea0d7f24033d77e3f2"
RDEPENDS:perl-Pod-Markdown-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-ExtUtils-MakeMaker \
 perl-Test-Simple \
 perl-IO \
 perl-Getopt-Long \
 perl-Pod-Markdown \
 perl-File-Temp \
 perl-Symbol \
 perl-PathTools \
 bash \
 perl-IPC-Open3 \
 perl-interpreter \
 perl-Test-Differences \
 perl-Exporter \
 perl-lib \
 perl-Pod-Usage \
"
