# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Text-Tabs+Wrap"
PE = "0"
PV = "2024.001"
PR = "511.el10"
PACKAGES = "perl-Text-Tabs+Wrap perl-Text-Tabs+Wrap-tests"
PROVIDES = "rpm/perl-Text-Tabs+Wrap rpm/perl-Text-Tabs+Wrap-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Text-Tabs+Wrap-2024.001-511.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ff44386dc429d84dffd7606972b960cb100808357e9b5e18df2ff14d2e3dacfd"

URI_perl-Text-Tabs+Wrap = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Text-Tabs+Wrap-2024.001-511.el10.noarch.rpm;name=perl-Text-Tabs+Wrap;unpack=0"
SRC_URI += "${URI_perl-Text-Tabs+Wrap}"
SRC_URI[perl-Text-Tabs+Wrap.sha256sum] = "f65456625bbdb4d7e02f8795ff00f2026f716382178d6a768f76dec7e6e638ca"
RDEPENDS:perl-Text-Tabs+Wrap = " \
 perl-Exporter \
 perl-libs \
 perl-Text-Tabs+Wrap \
"

URI_perl-Text-Tabs+Wrap-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Text-Tabs+Wrap-tests-2024.001-511.el10.noarch.rpm;name=perl-Text-Tabs+Wrap-tests;unpack=0"
SRC_URI += "${URI_perl-Text-Tabs+Wrap-tests}"
SRC_URI[perl-Text-Tabs+Wrap-tests.sha256sum] = "89818c1bbfffcb94e6e8fae7b0d23fb1e565f73a75cb52a7717750ade3528ba8"
RDEPENDS:perl-Text-Tabs+Wrap-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Text-Tabs+Wrap \
 bash \
 perl-interpreter \
"
