# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Pod-Perldoc"
PE = "0"
PV = "3.28.01"
PR = "512.el10"
PACKAGES = "perl-Pod-Perldoc perl-Pod-Perldoc-tests"
PROVIDES = "rpm/perl-Pod-Perldoc rpm/perl-Pod-Perldoc-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Pod-Perldoc-3.28.01-512.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a5f70e69a412cd3510a82c1478c9460270b67b7f8a197d5e0a98ed62b54f4da1"

URI_perl-Pod-Perldoc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Pod-Perldoc-3.28.01-512.el10.noarch.rpm;name=perl-Pod-Perldoc;unpack=0"
SRC_URI += "${URI_perl-Pod-Perldoc}"
SRC_URI[perl-Pod-Perldoc.sha256sum] = "260f92316899b869ad998cb9df861b26d2fb69da37ca4fdaceb77416b74cfb5e"
RDEPENDS:perl-Pod-Perldoc = " \
 perl-libs \
 perl-Symbol \
 perl-parent \
 perl-podlators \
 perl-HTTP-Tiny \
 perl-Carp \
 perl-vars \
 perl-IO \
 perl-Text-ParseWords \
 perl-IPC-Open3 \
 perl-Pod-Simple \
 groff-base \
 perl-Encode \
 perl-Fcntl \
 perl-File-Basename \
 perl-PathTools \
 perl-interpreter \
 perl-Pod-Perldoc \
 perl-File-Temp \
"

URI_perl-Pod-Perldoc-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Pod-Perldoc-tests-3.28.01-512.el10.noarch.rpm;name=perl-Pod-Perldoc-tests;unpack=0"
SRC_URI += "${URI_perl-Pod-Perldoc-tests}"
SRC_URI[perl-Pod-Perldoc-tests.sha256sum] = "20b057a8f15e09a673a744062ad8f8310a9bc77a347cdc05881dcf20d2b16d09"
RDEPENDS:perl-Pod-Perldoc-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-vars \
 bash \
 perl-parent \
 perl-interpreter \
 perl-Pod-Perldoc \
"
