# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-IO-Compress"
PE = "0"
PV = "2.212"
PR = "512.el10"
PACKAGES = "perl-IO-Compress perl-IO-Compress-tests"
PROVIDES = "rpm/perl-IO-Compress rpm/perl-IO-Compress-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-IO-Compress-2.212-512.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5c2e93d9e99b93db899ee026590777261a16f310bf272039ff5273dd5d4ec825"

URI_perl-IO-Compress = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-IO-Compress-2.212-512.el10.noarch.rpm;name=perl-IO-Compress;unpack=0"
SRC_URI += "${URI_perl-IO-Compress}"
SRC_URI[perl-IO-Compress.sha256sum] = "ea03f48d67511b393dbf19f0c04f7959e19ce2db1795b34e3cc5200563305c55"
RDEPENDS:perl-IO-Compress = " \
 perl-constant \
 perl-Scalar-List-Utils \
 perl-libs \
 perl-Carp \
 perl-interpreter \
 perl-IO \
 perl-IO-Compress \
 perl-Compress-Raw-Bzip2 \
 perl-Fcntl \
 perl-Compress-Raw-Zlib \
 perl-Getopt-Long \
 perl-Encode \
 perl-Symbol \
 perl-PathTools \
 perl-parent \
 perl-Exporter \
 perl-Data-Dumper \
 perl-Time-Local \
"

URI_perl-IO-Compress-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-IO-Compress-tests-2.212-512.el10.noarch.rpm;name=perl-IO-Compress-tests;unpack=0"
SRC_URI += "${URI_perl-IO-Compress-tests}"
SRC_URI[perl-IO-Compress-tests.sha256sum] = "f483b9d2a9523fa89c7726f7d3f109817808f60bff2ae88ad95b98785d100a77"
RDEPENDS:perl-IO-Compress-tests = " \
 perl-constant \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-Carp \
 perl-IO \
 perl-IO-Compress \
 perl-Compress-Raw-Zlib \
 perl-Symbol \
 bash \
 perl-PathTools \
 perl-interpreter \
 perl-File-Path \
 perl-Data-Dumper \
 perl-lib \
"
