# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-IO-HTML"
PE = "0"
PV = "1.004"
PR = "14.el10"
PACKAGES = "perl-IO-HTML perl-IO-HTML-tests"
PROVIDES = "rpm/perl-IO-HTML rpm/perl-IO-HTML-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-IO-HTML-1.004-14.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7fa807f47896223cb7d357f6488dfa61eeee4bb86a554b4ffe5aa6293a4ce24a"

URI_perl-IO-HTML = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-IO-HTML-1.004-14.el10.noarch.rpm;name=perl-IO-HTML;unpack=0"
SRC_URI += "${URI_perl-IO-HTML}"
SRC_URI[perl-IO-HTML.sha256sum] = "6e23241b69a11f5cbd6ce534def5dfe5492982991c61e77d105ca01a31d66448"
RDEPENDS:perl-IO-HTML = " \
 perl-Encode \
 perl-Exporter \
 perl-libs \
 perl-Carp \
"

URI_perl-IO-HTML-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-IO-HTML-tests-1.004-14.el10.noarch.rpm;name=perl-IO-HTML-tests;unpack=0"
SRC_URI += "${URI_perl-IO-HTML-tests}"
SRC_URI[perl-IO-HTML-tests.sha256sum] = "61751388c3e2480e9dcca498287cbd305f7cf7e28e0648e2d6b2eed0c1119fe8"
RDEPENDS:perl-IO-HTML-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Scalar-List-Utils \
 perl-Test-Simple \
 perl-IO-HTML \
 perl-Encode \
 bash \
 perl-interpreter \
 perl-File-Temp \
"
