# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Data-Dumper"
PE = "0"
PV = "2.189"
PR = "512.el10"
PACKAGES = "perl-Data-Dumper perl-Data-Dumper-tests"
PROVIDES = "rpm/perl-Data-Dumper rpm/perl-Data-Dumper-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Data-Dumper-2.189-512.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "93067fb531363048949c021ea8cbc9c58c201a242cea4c8c462c9929508911af"

URI_perl-Data-Dumper = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Data-Dumper-2.189-512.el10.x86_64_v2.rpm;name=perl-Data-Dumper;unpack=0"
SRC_URI += "${URI_perl-Data-Dumper}"
SRC_URI[perl-Data-Dumper.sha256sum] = "1606a885441b46aea682222c2a0c45f3ffc7e2ff1ff58d8425ca14426f135787"
RDEPENDS:perl-Data-Dumper = " \
 perl-constant \
 perl-Scalar-List-Utils \
 perl-libs \
 perl-Carp \
 perl-B \
 glibc \
 perl-Exporter \
"

URI_perl-Data-Dumper-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Data-Dumper-tests-2.189-512.el10.x86_64_v2.rpm;name=perl-Data-Dumper-tests;unpack=0"
SRC_URI += "${URI_perl-Data-Dumper-tests}"
SRC_URI[perl-Data-Dumper-tests.sha256sum] = "db5579367b3ab93a90e4ef4787fd9fc9bad7fcdfb092d39b48068eb65f4d7689"
RDEPENDS:perl-Data-Dumper-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Carp \
 perl-Test-Simple \
 perl-Encode \
 perl-overload \
 bash \
 perl-interpreter \
 perl-Data-Dumper \
 perl-Exporter \
 perl-lib \
"
