# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Scalar-List-Utils"
PE = "5"
PV = "1.63"
PR = "511.el10"
PACKAGES = "perl-Scalar-List-Utils perl-Scalar-List-Utils-tests"
PROVIDES = "rpm/perl-Scalar-List-Utils rpm/perl-Scalar-List-Utils-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Scalar-List-Utils-1.63-511.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "fddc7ceedcca0da74dfb25f133cca3cda91139842f9aafa9c45fdf866d144c67"

URI_perl-Scalar-List-Utils = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Scalar-List-Utils-1.63-511.el10.x86_64_v2.rpm;name=perl-Scalar-List-Utils;unpack=0"
SRC_URI += "${URI_perl-Scalar-List-Utils}"
SRC_URI[perl-Scalar-List-Utils.sha256sum] = "f570882d80e86a70a99163f34ccdf0c7120fff6359be9d74bcf47dac76717974"
RDEPENDS:perl-Scalar-List-Utils = " \
 perl-Scalar-List-Utils \
 perl-libs \
 perl-Carp \
 glibc \
 perl-Exporter \
"

URI_perl-Scalar-List-Utils-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Scalar-List-Utils-tests-1.63-511.el10.noarch.rpm;name=perl-Scalar-List-Utils-tests;unpack=0"
SRC_URI += "${URI_perl-Scalar-List-Utils-tests}"
SRC_URI[perl-Scalar-List-Utils-tests.sha256sum] = "e5f473860ab5373531b120ca6964f8958e8c54f6495d5ea093c3a1e525ac9f6b"
RDEPENDS:perl-Scalar-List-Utils-tests = " \
 perl-Scalar-List-Utils \
 perl-libs \
 perl-overload \
 perl-Symbol \
 perl-B \
 perl-threads \
 perl-threads-shared \
 perl-Test-Harness \
 perl-Test-Simple \
 perl-Carp \
 perl-vars \
 perl-IO \
 perl-Tie \
 perl-Math-BigInt \
 bash \
 perl-base \
 perl-constant \
 perl-if \
 perl-interpreter \
"
