# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-XML-Simple"
PE = "0"
PV = "2.25"
PR = "22.el10"
PACKAGES = "perl-XML-Simple perl-XML-Simple-tests"
PROVIDES = "rpm/perl-XML-Simple rpm/perl-XML-Simple-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-XML-Simple-2.25-22.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "082af027166ea6b37fedb06d55b863474f99deaefa6f8ad9657ac83c92e4f712"

URI_perl-XML-Simple = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-XML-Simple-2.25-22.el10.noarch.rpm;name=perl-XML-Simple;unpack=0"
SRC_URI += "${URI_perl-XML-Simple}"
SRC_URI[perl-XML-Simple.sha256sum] = "74ab4e61af54d73fc4bb18eee4fa573d5c9d59a68ee3a278918d006e607c8f8c"
RDEPENDS:perl-XML-Simple = " \
 perl-Scalar-List-Utils \
 perl-libs \
 perl-Carp \
 perl-vars \
 perl-IO \
 perl-Storable \
 perl-File-Basename \
 perl-XML-NamespaceSupport \
 perl-XML-Parser \
 perl-XML-SAX \
 perl-PathTools \
 perl-Exporter \
"

URI_perl-XML-Simple-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-XML-Simple-tests-2.25-22.el10.noarch.rpm;name=perl-XML-Simple-tests;unpack=0"
SRC_URI += "${URI_perl-XML-Simple-tests}"
SRC_URI[perl-XML-Simple-tests.sha256sum] = "72dbb2bae799f842cf22736e5d8975e9cb842714478f3101d9c4be479d88d522"
RDEPENDS:perl-XML-Simple-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-vars \
 perl-IO \
 perl-FileHandle \
 bash \
 perl-PathTools \
 perl-XML-SAX-Base \
 perl-XML-Simple \
 perl-interpreter \
 perl-base \
 perl-File-Temp \
"
