# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-JSON-XS"
PE = "1"
PV = "4.04"
PR = "1.el10_0"
PACKAGES = "perl-JSON-XS perl-JSON-XS-tests"
PROVIDES = "rpm/perl-JSON-XS rpm/perl-JSON-XS-tests"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/perl-JSON-XS-4.04-1.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "567733456f5bd93faa9c53b5bc4ede573437cffd9c07bc31fea7d59171a0f22e"

URI_perl-JSON-XS = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/perl-JSON-XS-4.04-1.el10_0.x86_64_v2.rpm;name=perl-JSON-XS;unpack=0"
SRC_URI += "${URI_perl-JSON-XS}"
SRC_URI[perl-JSON-XS.sha256sum] = "a683b9fb14454a31caf736b9cb56c894c2d6d7ffd29d1a6a2f968d3779fdc729"
RDEPENDS:perl-JSON-XS = " \
 perl-libs \
 perl-interpreter \
 perl-JSON-XS \
 perl-Types-Serialiser \
 perl-Storable \
 perl-Getopt-Long \
 perl-common-sense \
 perl-Encode \
 glibc \
 perl-Exporter \
"

URI_perl-JSON-XS-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-JSON-XS-tests-4.04-1.el10_0.noarch.rpm;name=perl-JSON-XS-tests;unpack=0"
SRC_URI += "${URI_perl-JSON-XS-tests}"
SRC_URI[perl-JSON-XS-tests.sha256sum] = "985f2a93a27aebbe22094e0c1bf285c6b446574b35dba0f6e96ca60692622aa2"
RDEPENDS:perl-JSON-XS-tests = " \
 perl-Test \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-JSON-XS \
 perl-Types-Serialiser \
 perl-Encode \
 bash \
 perl-Tie \
 perl-interpreter \
 perl-Data-Dumper \
"
