# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Time-HiRes"
PE = "4"
PV = "1.9777"
PR = "511.el10"
PACKAGES = "perl-Time-HiRes perl-Time-HiRes-tests"
PROVIDES = "rpm/perl-Time-HiRes rpm/perl-Time-HiRes-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Time-HiRes-1.9777-511.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "acf560edda9c5c71bc406417c785562c209b323c55a22bb1032e8819355185e3"

URI_perl-Time-HiRes = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Time-HiRes-1.9777-511.el10.x86_64_v2.rpm;name=perl-Time-HiRes;unpack=0"
SRC_URI += "${URI_perl-Time-HiRes}"
SRC_URI[perl-Time-HiRes.sha256sum] = "3455b85c9e797a4b5d52bca28472e18b989c80bf048fc6b155a6192633c5088d"
RDEPENDS:perl-Time-HiRes = " \
 glibc \
 perl-Exporter \
 perl-libs \
 perl-Carp \
"

URI_perl-Time-HiRes-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Time-HiRes-tests-1.9777-511.el10.x86_64_v2.rpm;name=perl-Time-HiRes-tests;unpack=0"
SRC_URI += "${URI_perl-Time-HiRes-tests}"
SRC_URI[perl-Time-HiRes-tests.sha256sum] = "3a36c168cd99df4599f6178f1ad0b4bef3da60a1c366c94be81de52e3ab281a8"
RDEPENDS:perl-Time-HiRes-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-File-Basename \
 bash \
 perl-Time-HiRes \
 perl-interpreter \
 perl-File-Temp \
"
