# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Compress-Raw-Bzip2"
PE = "0"
PV = "2.212"
PR = "512.el10"
PACKAGES = "perl-Compress-Raw-Bzip2 perl-Compress-Raw-Bzip2-tests"
PROVIDES = "rpm/perl-Compress-Raw-Bzip2 rpm/perl-Compress-Raw-Bzip2-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Compress-Raw-Bzip2-2.212-512.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2cfb5a7d35e403cf2e5a1b054c68110e903b1297ba4f0dc2e90e76f0320211b4"

URI_perl-Compress-Raw-Bzip2 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Compress-Raw-Bzip2-2.212-512.el10.x86_64_v2.rpm;name=perl-Compress-Raw-Bzip2;unpack=0"
SRC_URI += "${URI_perl-Compress-Raw-Bzip2}"
SRC_URI[perl-Compress-Raw-Bzip2.sha256sum] = "b7c35fd8ec2957fd0c3d20b19ae8584fa3423258284173bb153b32f9ab99a947"
RDEPENDS:perl-Compress-Raw-Bzip2 = " \
 perl-constant \
 perl-libs \
 perl-Carp \
 bzip2-libs \
 glibc \
 perl-Exporter \
"

URI_perl-Compress-Raw-Bzip2-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Compress-Raw-Bzip2-tests-2.212-512.el10.x86_64_v2.rpm;name=perl-Compress-Raw-Bzip2-tests;unpack=0"
SRC_URI += "${URI_perl-Compress-Raw-Bzip2-tests}"
SRC_URI[perl-Compress-Raw-Bzip2-tests.sha256sum] = "7725b75e82b240b3f2a6bac0c5fb9d84d68e151a757914c4e41d7713a0b079f3"
RDEPENDS:perl-Compress-Raw-Bzip2-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-Carp \
 perl-Compress-Raw-Bzip2 \
 bash \
 perl-interpreter \
 perl-File-Path \
 perl-lib \
"
