# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Text-ParseWords"
PE = "0"
PV = "3.31"
PR = "511.el10"
PACKAGES = "perl-Text-ParseWords perl-Text-ParseWords-tests"
PROVIDES = "rpm/perl-Text-ParseWords rpm/perl-Text-ParseWords-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Text-ParseWords-3.31-511.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1127f89f1cbfdb107eaeed6cb8f78ed996271609087eee95e9df52fa018fda1e"

URI_perl-Text-ParseWords = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Text-ParseWords-3.31-511.el10.noarch.rpm;name=perl-Text-ParseWords;unpack=0"
SRC_URI += "${URI_perl-Text-ParseWords}"
SRC_URI[perl-Text-ParseWords.sha256sum] = "371701469ff48ff7c2fd9fa1903bdf1d449513352f8e8e26fec7c7f9f8f2585c"
RDEPENDS:perl-Text-ParseWords = " \
 perl-Exporter \
 perl-libs \
 perl-Carp \
"

URI_perl-Text-ParseWords-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Text-ParseWords-tests-3.31-511.el10.noarch.rpm;name=perl-Text-ParseWords-tests;unpack=0"
SRC_URI += "${URI_perl-Text-ParseWords-tests}"
SRC_URI[perl-Text-ParseWords-tests.sha256sum] = "608e126db0c8a8be9cceb4c83b2c5ed9221f422130305db76451b4ad5fd8f166"
RDEPENDS:perl-Text-ParseWords-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-Scalar-List-Utils \
 perl-Text-ParseWords \
 bash \
 perl-interpreter \
"
