# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-HTML-Parser"
PE = "0"
PV = "3.82"
PR = "3.el10"
PACKAGES = "perl-HTML-Parser perl-HTML-Parser-tests"
PROVIDES = "rpm/perl-HTML-Parser rpm/perl-HTML-Parser-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-HTML-Parser-3.82-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "8b8ebd69e0bb7cdbdd7a42b8e9dcff6a239369aaa5259bdb725e3118b4788e8b"

URI_perl-HTML-Parser = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-HTML-Parser-3.82-3.el10.x86_64_v2.rpm;name=perl-HTML-Parser;unpack=0"
SRC_URI += "${URI_perl-HTML-Parser}"
SRC_URI[perl-HTML-Parser.sha256sum] = "088faafffa2c11b55980f6633365eee657f09547c0ff448d1498bacd053d1a71"
RDEPENDS:perl-HTML-Parser = " \
 perl-libs \
 perl-Carp \
 perl-URI \
 perl-IO \
 perl-HTML-Parser \
 perl-HTML-Tagset \
 glibc \
 perl-HTTP-Message \
 perl-Exporter \
"

URI_perl-HTML-Parser-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-HTML-Parser-tests-3.82-3.el10.x86_64_v2.rpm;name=perl-HTML-Parser-tests;unpack=0"
SRC_URI += "${URI_perl-HTML-Parser-tests}"
SRC_URI[perl-HTML-Parser-tests.sha256sum] = "780841730a293f6b00f7a472a5ac974cafcbb26d4b724488956f2bc90669ee7e"
RDEPENDS:perl-HTML-Parser-tests = " \
 perl-threads \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-ExtUtils-MakeMaker \
 perl-IO \
 perl-URI \
 perl-SelectSaver \
 bash \
 perl-PathTools \
 perl-HTML-Parser \
 perl-interpreter \
"
