# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Pod-Usage"
PE = "4"
PV = "2.03"
PR = "511.el10"
PACKAGES = "perl-Pod-Usage perl-Pod-Usage-tests"
PROVIDES = "rpm/perl-Pod-Usage rpm/perl-Pod-Usage-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Pod-Usage-2.03-511.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "8093f4fbf44cfd70cf20ac57d743ffb6cf6cc5d0517a9ba4e5d12384d8441111"

URI_perl-Pod-Usage = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Pod-Usage-2.03-511.el10.noarch.rpm;name=perl-Pod-Usage;unpack=0"
SRC_URI += "${URI_perl-Pod-Usage}"
SRC_URI[perl-Pod-Usage.sha256sum] = "b3aee0f405b0ac80a0967256eb3111cef6aa5c42023099692daa3d5eba819261"
RDEPENDS:perl-Pod-Usage = " \
 perl-libs \
 perl-Carp \
 perl-interpreter \
 perl-Getopt-Long \
 perl-PathTools \
 perl-podlators \
 perl-Exporter \
 perl-Pod-Perldoc \
 perl-Pod-Usage \
"

URI_perl-Pod-Usage-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Pod-Usage-tests-2.03-511.el10.noarch.rpm;name=perl-Pod-Usage-tests;unpack=0"
SRC_URI += "${URI_perl-Pod-Usage-tests}"
SRC_URI[perl-Pod-Usage-tests.sha256sum] = "9ae05d9bd4af44b4d972e56911c5bdeb914543cda0544c4292ca9871ec918a7d"
RDEPENDS:perl-Pod-Usage-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-Carp \
 perl-vars \
 perl-ExtUtils-MakeMaker \
 perl-FileHandle \
 perl-File-Basename \
 perl-Pod-Parser \
 bash \
 perl-PathTools \
 perl-interpreter \
 perl-Exporter \
 perl-Pod-Usage \
"
