# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Sub-Exporter"
PE = "0"
PV = "0.991"
PR = "7.el10"
PACKAGES = "perl-Sub-Exporter perl-Sub-Exporter-tests"
PROVIDES = "rpm/perl-Sub-Exporter rpm/perl-Sub-Exporter-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Sub-Exporter-0.991-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4227e9438479d2f45263d46d0017c54a61384725c4a94b054ba138c3306de730"

URI_perl-Sub-Exporter = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Sub-Exporter-0.991-7.el10.noarch.rpm;name=perl-Sub-Exporter;unpack=0"
SRC_URI += "${URI_perl-Sub-Exporter}"
SRC_URI[perl-Sub-Exporter.sha256sum] = "d72c51eca8d144757e48a55c76d1c9135ccc49e69d0f3079542f15949d2e10ba"
RDEPENDS:perl-Sub-Exporter = " \
 perl-libs \
 perl-Carp \
 perl-Sub-Exporter \
 perl-Package-Generator \
 perl-Sub-Install \
 perl-Params-Util \
 perl-Data-OptList \
"

URI_perl-Sub-Exporter-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Sub-Exporter-tests-0.991-7.el10.noarch.rpm;name=perl-Sub-Exporter-tests;unpack=0"
SRC_URI += "${URI_perl-Sub-Exporter-tests}"
SRC_URI[perl-Sub-Exporter-tests.sha256sum] = "d886c89a46a1c338489f884389fd7d9c5fbfa25152402396ef10df98e5950334"
RDEPENDS:perl-Sub-Exporter-tests = " \
 perl-subs \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-Carp \
 perl-ExtUtils-MakeMaker \
 perl-Data-OptList \
 perl-Sub-Exporter \
 perl-overload \
 bash \
 perl-PathTools \
 perl-base \
 perl-interpreter \
 perl-Exporter \
 perl-lib \
"
