# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-constant"
PE = "0"
PV = "1.33"
PR = "512.el10"
PACKAGES = "perl-constant perl-constant-tests"
PROVIDES = "rpm/perl-constant rpm/perl-constant-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-constant-1.33-512.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "956c0b458248c3fa53eaa2b0ddcc699601d80193afaefaf7fd72b6d158040d84"

URI_perl-constant = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-constant-1.33-512.el10.noarch.rpm;name=perl-constant;unpack=0"
SRC_URI += "${URI_perl-constant}"
SRC_URI[perl-constant.sha256sum] = "00221c59085f4a9ec4ebc5d547bcf5e3d9ec2ab3a057a0b351b4f0d029ecff74"
RDEPENDS:perl-constant = " \
 perl-libs \
 perl-Carp \
"

URI_perl-constant-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-constant-tests-1.33-512.el10.noarch.rpm;name=perl-constant-tests;unpack=0"
SRC_URI += "${URI_perl-constant-tests}"
SRC_URI[perl-constant-tests.sha256sum] = "e304bbcf23702bcc997a1c66f595b067dc93d746d5f6145950ab2912e3459496"
RDEPENDS:perl-constant-tests = " \
 perl-constant \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-vars \
 bash \
 perl-interpreter \
"
