# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-XML-TokeParser"
PE = "0"
PV = "0.05"
PR = "47.el10"
PACKAGES = "perl-XML-TokeParser perl-XML-TokeParser-tests"
PROVIDES = "rpm/perl-XML-TokeParser rpm/perl-XML-TokeParser-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-XML-TokeParser-0.05-47.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "fcbcf7291e6dd217bd1bc8a67aa3922a2e3db04991ab7f65ef9a603899afe292"

URI_perl-XML-TokeParser = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-XML-TokeParser-0.05-47.el10.noarch.rpm;name=perl-XML-TokeParser;unpack=0"
SRC_URI += "${URI_perl-XML-TokeParser}"
SRC_URI[perl-XML-TokeParser.sha256sum] = "7118023b224c4f7e927c6168c0350b8a79b4e95a115295356f6053935e15ca85"
RDEPENDS:perl-XML-TokeParser = " \
 perl-libs \
 perl-Carp \
 perl-vars \
 perl-IO \
 perl-XML-Catalog \
 perl-XML-Parser \
"

URI_perl-XML-TokeParser-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-XML-TokeParser-tests-0.05-47.el10.noarch.rpm;name=perl-XML-TokeParser-tests;unpack=0"
SRC_URI += "${URI_perl-XML-TokeParser-tests}"
SRC_URI[perl-XML-TokeParser-tests.sha256sum] = "a151bc99e71517654ca9b84f07f64eee60349844238610e7236c4a997fb1424a"
RDEPENDS:perl-XML-TokeParser-tests = " \
 perl-Test \
 perl-Test-Harness \
 bash \
 perl-XML-TokeParser \
 perl-interpreter \
"
