# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Test-Pod"
PE = "0"
PV = "1.52"
PR = "23.el10"
PACKAGES = "perl-Test-Pod perl-Test-Pod-tests"
PROVIDES = "rpm/perl-Test-Pod rpm/perl-Test-Pod-tests"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/perl-Test-Pod-1.52-23.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e781e641072876fd7f67c684a26d4d9a9cb820b3edc460be3661960d313b61c3"

URI_perl-Test-Pod = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/perl-Test-Pod-1.52-23.el10.noarch.rpm;name=perl-Test-Pod;unpack=0"
SRC_URI += "${URI_perl-Test-Pod}"
SRC_URI[perl-Test-Pod.sha256sum] = "a5a0c45dbdedc6d57d57057129b3ca2290d9253fb3133615edf49d32bc2c8e2b"
RDEPENDS:perl-Test-Pod = " \
 perl-File-Find \
 perl-libs \
 perl-Pod-Simple \
 perl-Test-Simple \
"

URI_perl-Test-Pod-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Test-Pod-tests-1.52-23.el10.noarch.rpm;name=perl-Test-Pod-tests;unpack=0"
SRC_URI += "${URI_perl-Test-Pod-tests}"
SRC_URI[perl-Test-Pod-tests.sha256sum] = "3d4bdab4a2d7f9b735d4b7a960c621ac8f7eb2884989383906a7f523a3b229cb"
RDEPENDS:perl-Test-Pod-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 bash \
 perl-interpreter \
 perl-Test-Pod \
"
