# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Locale-Maketext"
PE = "0"
PV = "1.33"
PR = "512.el10"
PACKAGES = "perl-Locale-Maketext perl-Locale-Maketext-tests"
PROVIDES = "rpm/perl-Locale-Maketext rpm/perl-Locale-Maketext-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Locale-Maketext-1.33-512.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a989af56d1ad92f9f248c117450811e6a7bc3369111ed40f634eb20853771e0e"

URI_perl-Locale-Maketext = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Locale-Maketext-1.33-512.el10.noarch.rpm;name=perl-Locale-Maketext;unpack=0"
SRC_URI += "${URI_perl-Locale-Maketext}"
SRC_URI[perl-Locale-Maketext.sha256sum] = "29ae938b0e5100d904d8762ef4fa21f3d6e1ee9c8afec19e01f9698fed8c9157"
RDEPENDS:perl-Locale-Maketext = " \
 perl-Locale-Maketext \
 perl-I18N-LangTags \
 perl-libs \
 perl-Carp \
"

URI_perl-Locale-Maketext-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Locale-Maketext-tests-1.33-512.el10.noarch.rpm;name=perl-Locale-Maketext-tests;unpack=0"
SRC_URI += "${URI_perl-Locale-Maketext-tests}"
SRC_URI[perl-Locale-Maketext-tests.sha256sum] = "31f7e7fc2e84a0d522d266764772ea0f95a2125743b93b0c752ae5b448046471"
RDEPENDS:perl-Locale-Maketext-tests = " \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-Scalar-List-Utils \
 bash \
 perl-parent \
 perl-interpreter \
 perl-Locale-Maketext \
"
