# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Parse-PMFile"
PE = "0"
PV = "0.45"
PR = "3.el10"
PACKAGES = "perl-Parse-PMFile perl-Parse-PMFile-tests"
PROVIDES = "rpm/perl-Parse-PMFile rpm/perl-Parse-PMFile-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Parse-PMFile-0.45-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7b423fb8b6c810434df2c71eae037a972a1f8f15fbf82270dcaea52c34d4014c"

URI_perl-Parse-PMFile = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Parse-PMFile-0.45-3.el10.noarch.rpm;name=perl-Parse-PMFile;unpack=0"
SRC_URI += "${URI_perl-Parse-PMFile}"
SRC_URI[perl-Parse-PMFile.sha256sum] = "6c3b2c6ea39e16137e23940fa8ae25181d3fbeb32f27a2f75b0a26a23a9c89af"
RDEPENDS:perl-Parse-PMFile = " \
 perl-Safe \
 perl-libs \
 perl-version \
 perl-Dumpvalue \
 perl-PathTools \
 perl-JSON-PP \
"

URI_perl-Parse-PMFile-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Parse-PMFile-tests-0.45-3.el10.noarch.rpm;name=perl-Parse-PMFile-tests;unpack=0"
SRC_URI += "${URI_perl-Parse-PMFile-tests}"
SRC_URI[perl-Parse-PMFile-tests.sha256sum] = "b249c4ed17881e9691b9123e240516546da484aeb18b561726ee52d5fa6dea20"
RDEPENDS:perl-Parse-PMFile-tests = " \
 perl-Safe \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-Opcode \
 perl-FindBin \
 perl-Parse-PMFile \
 bash \
 perl-interpreter \
 perl-File-Temp \
"
