# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "perl-Digest-MD5"
PE = "0"
PV = "2.59"
PR = "6.el10"
PACKAGES = "perl-Digest-MD5 perl-Digest-MD5-tests"
PROVIDES = "rpm/perl-Digest-MD5 rpm/perl-Digest-MD5-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/perl-Digest-MD5-2.59-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "8b31a977aa4f59f953eb9e5265379e3b60716f46342da47147ad451b25e0839e"

URI_perl-Digest-MD5 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Digest-MD5-2.59-6.el10.x86_64_v2.rpm;name=perl-Digest-MD5;unpack=0"
SRC_URI += "${URI_perl-Digest-MD5}"
SRC_URI[perl-Digest-MD5.sha256sum] = "3615b1689cb3274a2e938d68ff628c6ba67504a036a67221c4a59abafe769daa"
RDEPENDS:perl-Digest-MD5 = " \
 glibc \
 perl-Exporter \
 perl-libs \
 perl-Digest \
"

URI_perl-Digest-MD5-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Digest-MD5-tests-2.59-6.el10.x86_64_v2.rpm;name=perl-Digest-MD5-tests;unpack=0"
SRC_URI += "${URI_perl-Digest-MD5-tests}"
SRC_URI[perl-Digest-MD5-tests.sha256sum] = "407296ad0405a468e7756688094dde46d76f85f9cba5cc8d930d07cc1d2b985c"
RDEPENDS:perl-Digest-MD5-tests = " \
 perl-threads \
 perl-Test-Harness \
 perl-libs \
 perl-Test-Simple \
 perl-vars \
 perl-Digest-MD5 \
 perl-Encode \
 bash \
 perl-interpreter \
"
