# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "php-pear"
PE = "1"
PV = "1.10.14"
PR = "6.el10"
PACKAGES = "php-pear"
PROVIDES = "rpm/php-pear"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/php-pear-1.10.14-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1ce0c0e1d5b5444c299333c4bcc819d766adf749e736e9becba6eb11a8ab87ac"

URI_php-pear = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/php-pear-1.10.14-6.el10.noarch.rpm;name=php-pear;unpack=0"
SRC_URI += "${URI_php-pear}"
SRC_URI[php-pear.sha256sum] = "761cca1aea570919fed2b9b0aa6b292e68dbad671e80591de9fba90ae578ad03"
RDEPENDS:php-pear = " \
 httpd-filesystem \
 php-process \
 php-xml \
 php-cli \
 php-common \
 bash \
"
