# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "pkgconf"
PE = "0"
PV = "2.1.0"
PR = "3.el10"
PACKAGES = "libpkgconf pkgconf pkgconf-m4 pkgconf-pkg-config bomtool libpkgconf-devel"
PROVIDES = "rpm/libpkgconf rpm/pkgconf rpm/pkgconf-m4 rpm/pkgconf-pkg-config rpm/bomtool rpm/libpkgconf-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/pkgconf-2.1.0-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b9e27d557f93f409f936356969e9286df4008ec9c3209100c80c7652eae39a64"

URI_libpkgconf = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libpkgconf-2.1.0-3.el10.x86_64_v2.rpm;name=libpkgconf;unpack=0"
SRC_URI += "${URI_libpkgconf}"
SRC_URI[libpkgconf.sha256sum] = "6034b138cff02b148af4b1bbef757e88844abd5cd2a1c0bc6281516065a0c537"
RDEPENDS:libpkgconf = " \
 glibc \
"

URI_pkgconf = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/pkgconf-2.1.0-3.el10.x86_64_v2.rpm;name=pkgconf;unpack=0"
SRC_URI += "${URI_pkgconf}"
SRC_URI[pkgconf.sha256sum] = "b1a196ca310d5f594b844cc5dee70c2712a1a5277ef4807baa630a3200a476ae"
RDEPENDS:pkgconf = " \
 glibc \
 libpkgconf \
"

URI_pkgconf-m4 = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/pkgconf-m4-2.1.0-3.el10.noarch.rpm;name=pkgconf-m4;unpack=0"
SRC_URI += "${URI_pkgconf-m4}"
SRC_URI[pkgconf-m4.sha256sum] = "74cba7eb2aaa7c8bbc11f8125c01eb59b9be00fe60aa7f6b234ff448a7761824"
RDEPENDS:pkgconf-m4 = ""

URI_pkgconf-pkg-config = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/pkgconf-pkg-config-2.1.0-3.el10.x86_64_v2.rpm;name=pkgconf-pkg-config;unpack=0"
SRC_URI += "${URI_pkgconf-pkg-config}"
SRC_URI[pkgconf-pkg-config.sha256sum] = "01cc1bd2dded7e637887d55edad8f9f0a15b499e97fed50f021380117134ce96"
RDEPENDS:pkgconf-pkg-config = " \
 pkgconf-m4 \
 pkgconf \
 bash \
"

URI_bomtool = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/bomtool-2.1.0-3.el10.x86_64_v2.rpm;name=bomtool;unpack=0"
SRC_URI += "${URI_bomtool}"
SRC_URI[bomtool.sha256sum] = "47b00c8e96c2a16cb4b5e2bfbcb0b333a754b0357c5a2878b5e9ec112bd11fb5"
RDEPENDS:bomtool = " \
 glibc \
 libpkgconf \
"

URI_libpkgconf-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/libpkgconf-devel-2.1.0-3.el10.x86_64_v2.rpm;name=libpkgconf-devel;unpack=0"
SRC_URI += "${URI_libpkgconf-devel}"
SRC_URI[libpkgconf-devel.sha256sum] = "e0bc0904e1bb6ea86709409154e1607de3fedbd1b17fb0631c1255fa59eeb30d"
RDEPENDS:libpkgconf-devel = " \
 libpkgconf \
 pkgconf-pkg-config \
"
