# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "plymouth"
PE = "0"
PV = "24.004.60"
PR = "13.el10.alma.1"
PACKAGES = "plymouth plymouth-core-libs plymouth-devel plymouth-graphics-libs plymouth-plugin-fade-throbber plymouth-plugin-label plymouth-plugin-script plymouth-plugin-space-flares plymouth-plugin-two-step plymouth-scripts plymouth-system-theme plymouth-theme-fade-in plymouth-theme-script plymouth-theme-solar plymouth-theme-spinfinity plymouth-theme-spinner"
PROVIDES = "rpm/plymouth rpm/plymouth-core-libs rpm/plymouth-devel rpm/plymouth-graphics-libs rpm/plymouth-plugin-fade-throbber rpm/plymouth-plugin-label rpm/plymouth-plugin-script rpm/plymouth-plugin-space-flares rpm/plymouth-plugin-two-step rpm/plymouth-scripts rpm/plymouth-system-theme rpm/plymouth-theme-fade-in rpm/plymouth-theme-script rpm/plymouth-theme-solar rpm/plymouth-theme-spinfinity rpm/plymouth-theme-spinner"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/plymouth-24.004.60-13.el10.alma.1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a59be2c57064c11d23c747d82f5882b385db7d7610fa86112f75eb9f2e578866"

URI_plymouth = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth;unpack=0"
SRC_URI += "${URI_plymouth}"
SRC_URI[plymouth.sha256sum] = "e78cb47a93d16fccbbebad4de2715030e79ad33f7f9fa46ea1c4d499d3ba16d3"
RDEPENDS:plymouth = " \
 glibc \
 plymouth-scripts \
 xkeyboard-config \
 plymouth-core-libs \
"

URI_plymouth-core-libs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-core-libs-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-core-libs;unpack=0"
SRC_URI += "${URI_plymouth-core-libs}"
SRC_URI[plymouth-core-libs.sha256sum] = "f89441e78de478525b461d74c654078b64935b538911a064808eebc1e9c22214"
RDEPENDS:plymouth-core-libs = " \
 glibc \
 libxkbcommon \
 libevdev \
 systemd-libs \
"

URI_plymouth-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-devel-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-devel;unpack=0"
SRC_URI += "${URI_plymouth-devel}"
SRC_URI[plymouth-devel.sha256sum] = "bdc442eb22d14906a6a755f0c84c2f88c37f719568199e9ca1309ea70806e8bf"
RDEPENDS:plymouth-devel = " \
 plymouth \
 plymouth-core-libs \
 systemd-devel \
 plymouth-graphics-libs \
 plymouth-devel \
 pkgconf-pkg-config \
 libpng-devel \
 libevdev-devel \
 cairo \
 glib2 \
 gtk3 \
 glibc \
 xkeyboard-config-devel \
 libxkbcommon-devel \
"

URI_plymouth-graphics-libs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-graphics-libs-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-graphics-libs;unpack=0"
SRC_URI += "${URI_plymouth-graphics-libs}"
SRC_URI[plymouth-graphics-libs.sha256sum] = "650d378b9d952483ee87d531b8abdc7a84be103bebf1d56bfcdb3cc987e7ddc7"
RDEPENDS:plymouth-graphics-libs = " \
 almalinux-logos \
 libpng \
 plymouth-core-libs \
 glibc \
 libdrm \
"

URI_plymouth-plugin-fade-throbber = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-plugin-fade-throbber-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-plugin-fade-throbber;unpack=0"
SRC_URI += "${URI_plymouth-plugin-fade-throbber}"
SRC_URI[plymouth-plugin-fade-throbber.sha256sum] = "daa9fdf1203faab8d19b281ab12b41a96afb94e8b486303ec88a7b8317e4d6b6"
RDEPENDS:plymouth-plugin-fade-throbber = " \
 glibc \
 plymouth-graphics-libs \
 plymouth \
 plymouth-core-libs \
"

URI_plymouth-plugin-label = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-plugin-label-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-plugin-label;unpack=0"
SRC_URI += "${URI_plymouth-plugin-label}"
SRC_URI[plymouth-plugin-label.sha256sum] = "c9b1489ab1225a0f358a5a727e6cf4baba961b8db2f337324d10dc5ef083e8ec"
RDEPENDS:plymouth-plugin-label = " \
 freetype \
 plymouth \
 plymouth-core-libs \
 plymouth-graphics-libs \
 pango \
 cairo \
 glib2 \
 glibc \
"

URI_plymouth-plugin-script = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-plugin-script-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-plugin-script;unpack=0"
SRC_URI += "${URI_plymouth-plugin-script}"
SRC_URI[plymouth-plugin-script.sha256sum] = "97bf2c101b534d3103adc27a8c1967b5e36eaa73e313b29cf3ea4b9b0d53e8a1"
RDEPENDS:plymouth-plugin-script = " \
 glibc \
 plymouth-graphics-libs \
 plymouth \
 plymouth-core-libs \
"

URI_plymouth-plugin-space-flares = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-plugin-space-flares-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-plugin-space-flares;unpack=0"
SRC_URI += "${URI_plymouth-plugin-space-flares}"
SRC_URI[plymouth-plugin-space-flares.sha256sum] = "a5f5117ce7aa517d238255a343b6d941f861e2c102ba2689bde390d4e7667ae8"
RDEPENDS:plymouth-plugin-space-flares = " \
 plymouth \
 plymouth-core-libs \
 plymouth-graphics-libs \
 plymouth-plugin-label \
 glibc \
"

URI_plymouth-plugin-two-step = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-plugin-two-step-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-plugin-two-step;unpack=0"
SRC_URI += "${URI_plymouth-plugin-two-step}"
SRC_URI[plymouth-plugin-two-step.sha256sum] = "959428693cb55f1879bcf63ab58270384d6395d0043b1ea58ca0d22187bcea33"
RDEPENDS:plymouth-plugin-two-step = " \
 plymouth \
 plymouth-core-libs \
 plymouth-graphics-libs \
 plymouth-plugin-label \
 glibc \
"

URI_plymouth-scripts = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-scripts-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-scripts;unpack=0"
SRC_URI += "${URI_plymouth-scripts}"
SRC_URI[plymouth-scripts.sha256sum] = "3e31cea42f9f0019bd64505d0a96617d1234e6feb157c07666de5172f7829437"
RDEPENDS:plymouth-scripts = " \
 plymouth \
 gzip \
 bash \
 dracut \
 xkeyboard-config \
 coreutils \
 cpio \
 findutils \
"

URI_plymouth-system-theme = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-system-theme-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-system-theme;unpack=0"
SRC_URI += "${URI_plymouth-system-theme}"
SRC_URI[plymouth-system-theme.sha256sum] = "98038b0fb7732b7e2eee29115f4fc85feb9ac93a24bf4c4a1e345f1ca0a9b6b4"
RDEPENDS:plymouth-system-theme = " \
 plymouth-theme-spinner \
"

URI_plymouth-theme-fade-in = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-theme-fade-in-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-theme-fade-in;unpack=0"
SRC_URI += "${URI_plymouth-theme-fade-in}"
SRC_URI[plymouth-theme-fade-in.sha256sum] = "4feb7716873efb1cbba3a9e3dbdb9df1b9f56899c4f997f088ea39a6209d441b"
RDEPENDS:plymouth-theme-fade-in = " \
 plymouth-scripts \
 plymouth-plugin-fade-throbber \
 bash \
"

URI_plymouth-theme-script = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-theme-script-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-theme-script;unpack=0"
SRC_URI += "${URI_plymouth-theme-script}"
SRC_URI[plymouth-theme-script.sha256sum] = "59eb8102bb279db62f6b7d7dedfbb0c78d5910cd9793b3e9eb8bbd1c4da6f58d"
RDEPENDS:plymouth-theme-script = " \
 plymouth-scripts \
 plymouth-plugin-script \
"

URI_plymouth-theme-solar = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-theme-solar-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-theme-solar;unpack=0"
SRC_URI += "${URI_plymouth-theme-solar}"
SRC_URI[plymouth-theme-solar.sha256sum] = "f04577e4b509341f76acdfc052e33404a20b95e7d4b3bcdb81309c97569a4917"
RDEPENDS:plymouth-theme-solar = " \
 plymouth-scripts \
 bash \
 plymouth-plugin-space-flares \
"

URI_plymouth-theme-spinfinity = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-theme-spinfinity-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-theme-spinfinity;unpack=0"
SRC_URI += "${URI_plymouth-theme-spinfinity}"
SRC_URI[plymouth-theme-spinfinity.sha256sum] = "ed826a236e55c02a0dc5109ae3a955ab9e0d0cc697ea23f2ad74f642453cc46e"
RDEPENDS:plymouth-theme-spinfinity = " \
 plymouth-scripts \
 bash \
 plymouth-plugin-two-step \
"

URI_plymouth-theme-spinner = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/plymouth-theme-spinner-24.004.60-13.el10.alma.1.x86_64_v2.rpm;name=plymouth-theme-spinner;unpack=0"
SRC_URI += "${URI_plymouth-theme-spinner}"
SRC_URI[plymouth-theme-spinner.sha256sum] = "1484e644dd3a45eb4ae4fa1fca60700db47fe1a8ac517bacc61b1ebf1f99a6ea"
RDEPENDS:plymouth-theme-spinner = " \
 plymouth-plugin-two-step \
 plymouth-scripts \
 bash \
 redhat-text-vf-fonts \
 redhat-mono-vf-fonts \
"
