# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "polkit"
PE = "0"
PV = "125"
PR = "3.el10"
PACKAGES = "polkit polkit-libs polkit-devel polkit-docs"
PROVIDES = "rpm/polkit rpm/polkit-libs rpm/polkit-devel rpm/polkit-docs"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/polkit-125-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1486c85a9d252e832ca1244f5381eff796fa727ad655340c4989f97b73b3edbb"

URI_polkit = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/polkit-125-3.el10.x86_64_v2.rpm;name=polkit;unpack=0"
SRC_URI += "${URI_polkit}"
SRC_URI[polkit.sha256sum] = "7e04edaea3b5e0f7a3b4cb88ee85f86c7f9d4052575ea6896c5922decb531b58"
RDEPENDS:polkit = " \
 shadow-utils \
 systemd \
 systemd-libs \
 pam-libs \
 polkit-libs \
 bash \
 glib2 \
 dbus \
 expat \
 glibc \
 duktape \
"

URI_polkit-libs = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/polkit-libs-125-3.el10.x86_64_v2.rpm;name=polkit-libs;unpack=0"
SRC_URI += "${URI_polkit-libs}"
SRC_URI[polkit-libs.sha256sum] = "d7d078e4f13c0b7e5d8ecc45d9154baf619c2f3860510cf7a7b4123f1da74f3f"
RDEPENDS:polkit-libs = " \
 glibc \
 glib2 \
 systemd-libs \
"

URI_polkit-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/polkit-devel-125-3.el10.x86_64_v2.rpm;name=polkit-devel;unpack=0"
SRC_URI += "${URI_polkit-devel}"
SRC_URI[polkit-devel.sha256sum] = "c4d65463bd4780e29ba143bf7e41194bcfbadb9b61dd57d36f53d2614df80f92"
RDEPENDS:polkit-devel = " \
 glib2-devel \
 polkit-devel \
 polkit-docs \
 pkgconf-pkg-config \
 polkit-libs \
"

URI_polkit-docs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/polkit-docs-125-3.el10.noarch.rpm;name=polkit-docs;unpack=0"
SRC_URI += "${URI_polkit-docs}"
SRC_URI[polkit-docs.sha256sum] = "7f7dde7699542c9b2b542b7a5107ace8e9d77741552790d45faede5b46e7021e"
RDEPENDS:polkit-docs = " \
 polkit-devel \
"
