# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "postgresql-odbc"
PE = "0"
PV = "16.00.0000"
PR = "5.el10"
PACKAGES = "postgresql-odbc postgresql-odbc-tests"
PROVIDES = "rpm/postgresql-odbc rpm/postgresql-odbc-tests"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/postgresql-odbc-16.00.0000-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b00317c07e63810dfc927c72ee4340435cd0f9e083cfb8baff77790cf1a2cb9d"

URI_postgresql-odbc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/postgresql-odbc-16.00.0000-5.el10.x86_64_v2.rpm;name=postgresql-odbc;unpack=0"
SRC_URI += "${URI_postgresql-odbc}"
SRC_URI[postgresql-odbc.sha256sum] = "d1cf7cd0dd6ce1d059efe3d42e6684c1ce55a4d7113d60d95da4f20bcbb64f12"
RDEPENDS:postgresql-odbc = " \
 glibc \
 unixODBC \
 libpq \
"

URI_postgresql-odbc-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/postgresql-odbc-tests-16.00.0000-5.el10.x86_64_v2.rpm;name=postgresql-odbc-tests;unpack=0"
SRC_URI += "${URI_postgresql-odbc-tests}"
SRC_URI[postgresql-odbc-tests.sha256sum] = "6c2ba07c00062f8cdc1f897334f77adcc8db96f33ac97bbe1daa153617c777a3"
RDEPENDS:postgresql-odbc-tests = " \
 unixODBC-devel \
 postgresql-odbc \
 make \
 bash \
 postgresql-test \
 gcc \
"
