# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "procps-ng"
PE = "0"
PV = "4.0.4"
PR = "7.el10"
PACKAGES = "procps-ng procps-ng-i18n procps-ng-devel"
PROVIDES = "rpm/procps-ng rpm/procps-ng-i18n rpm/procps-ng-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/procps-ng-4.0.4-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b0ab4dc76b6ab72f056282a1de173423aa471dc4156b340c5dde423b0fb938f2"

URI_procps-ng = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/procps-ng-4.0.4-7.el10.x86_64_v2.rpm;name=procps-ng;unpack=0"
SRC_URI += "${URI_procps-ng}"
SRC_URI[procps-ng.sha256sum] = "6fbeb1138d2318ab6e495c858a18f965725544d963810a10af9edb1980296c6d"
RDEPENDS:procps-ng = " \
 glibc \
 ncurses-libs \
 systemd-libs \
"

URI_procps-ng-i18n = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/procps-ng-i18n-4.0.4-7.el10.noarch.rpm;name=procps-ng-i18n;unpack=0"
SRC_URI += "${URI_procps-ng-i18n}"
SRC_URI[procps-ng-i18n.sha256sum] = "b73acc001607a80a909922a57830b4b938dfe7d7976b604c397f9268dfde4c6f"
RDEPENDS:procps-ng-i18n = " \
 procps-ng \
"

URI_procps-ng-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/procps-ng-devel-4.0.4-7.el10.x86_64_v2.rpm;name=procps-ng-devel;unpack=0"
SRC_URI += "${URI_procps-ng-devel}"
SRC_URI[procps-ng-devel.sha256sum] = "9ec80964ed89173df8ec498336a66ec2088f1b6482f9ad8c054b5d70bc5043ec"
RDEPENDS:procps-ng-devel = " \
 procps-ng \
 pkgconf-pkg-config \
"
