# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "pybind11"
PE = "0"
PV = "2.11.1"
PR = "7.el10"
PACKAGES = "pybind11-devel python3-pybind11"
PROVIDES = "rpm/pybind11-devel rpm/python3-pybind11"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/pybind11-2.11.1-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b45eaf1ffc30dfa9f1c4f0fb0f9c223ec1d3dab8db17f9c03fa5461561619c01"

URI_pybind11-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/pybind11-devel-2.11.1-7.el10.x86_64_v2.rpm;name=pybind11-devel;unpack=0"
SRC_URI += "${URI_pybind11-devel}"
SRC_URI[pybind11-devel.sha256sum] = "c0504881cffd795d653b4a85c4f533c309e3a2a0265533773499724ff08bfdd6"
RDEPENDS:pybind11-devel = " \
 python3 \
 cmake-filesystem \
 pkgconf-pkg-config \
 cmake \
"

URI_python3-pybind11 = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/python3-pybind11-2.11.1-7.el10.x86_64_v2.rpm;name=python3-pybind11;unpack=0"
SRC_URI += "${URI_python3-pybind11}"
SRC_URI[python3-pybind11.sha256sum] = "4984fc02f2d972f31f0b06ef6da81cf7763ba7fa54660bc323f2d4ae650bdb74"
RDEPENDS:python3-pybind11 = " \
 python3 \
 pybind11-devel \
"
