# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "pykickstart"
PE = "0"
PV = "3.52.8"
PR = "1.el10"
PACKAGES = "pykickstart python3-kickstart"
PROVIDES = "rpm/pykickstart rpm/python3-kickstart"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/pykickstart-3.52.8-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "fec4868b89096c649a92b3e8900b8f4ca75e52d5dd114bc48715c01349ff5295"

URI_pykickstart = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/pykickstart-3.52.8-1.el10.noarch.rpm;name=pykickstart;unpack=0"
SRC_URI += "${URI_pykickstart}"
SRC_URI[pykickstart.sha256sum] = "770c75ab01ab8740da048b6a4c3d0b41395f2edc121e2e1443fded8bd761a6c8"
RDEPENDS:pykickstart = " \
 python3 \
 python3-kickstart \
"

URI_python3-kickstart = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/python3-kickstart-3.52.8-1.el10.noarch.rpm;name=python3-kickstart;unpack=0"
SRC_URI += "${URI_python3-kickstart}"
SRC_URI[python3-kickstart.sha256sum] = "355a06923c65e5ba52a71ee0042fc3958a5042d3146f24654bc658cdd2256f65"
RDEPENDS:python3-kickstart = " \
 python3 \
 python3-requests \
"
