# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "pyodbc"
PE = "0"
PV = "5.1.0"
PR = "3.el10"
PACKAGES = "python3-pyodbc"
PROVIDES = "rpm/python3-pyodbc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/pyodbc-5.1.0-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "495734fa396b25ab5dc4b2e7baabb271f2d2123e5078f0f6705842cd5a52bed3"

URI_python3-pyodbc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/python3-pyodbc-5.1.0-3.el10.x86_64_v2.rpm;name=python3-pyodbc;unpack=0"
SRC_URI += "${URI_python3-pyodbc}"
SRC_URI[python3-pyodbc.sha256sum] = "c43de53a5f1fecca9507c4791f96688c02917fdd7a3b9076a41a721c68025b46"
RDEPENDS:python3-pyodbc = " \
 python3 \
 libgcc \
 libstdc++ \
 unixODBC \
 glibc \
"
