# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-ptyprocess"
PE = "0"
PV = "0.7.0"
PR = "9.el10"
PACKAGES = "python3-ptyprocess"
PROVIDES = "rpm/python3-ptyprocess"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/python-ptyprocess-0.7.0-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "89eddd9ddad564877f3df2ca69df3f01183081f80920f1d6344a261e529f58b3"

URI_python3-ptyprocess = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-ptyprocess-0.7.0-9.el10.noarch.rpm;name=python3-ptyprocess;unpack=0"
SRC_URI += "${URI_python3-ptyprocess}"
SRC_URI[python3-ptyprocess.sha256sum] = "8f3bc470a29bb1393a8b6dde3fdd3483af04d6e17a617dc2591aa096105e28a9"
RDEPENDS:python3-ptyprocess = " \
 python3 \
"
