# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-asn1crypto"
PE = "0"
PV = "1.5.1"
PR = "10.el10"
PACKAGES = "python3-asn1crypto"
PROVIDES = "rpm/python3-asn1crypto"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/python-asn1crypto-1.5.1-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4e1fdb0ab306be8c6b980de218b3c52813ca13e20bf839556fde77a63b4f5097"

URI_python3-asn1crypto = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/python3-asn1crypto-1.5.1-10.el10.noarch.rpm;name=python3-asn1crypto;unpack=0"
SRC_URI += "${URI_python3-asn1crypto}"
SRC_URI[python3-asn1crypto.sha256sum] = "095a2f404536810e9ff9d356b62f1d570eba19cebb7b97922dedb4df95da84cb"
RDEPENDS:python3-asn1crypto = " \
 python3 \
"
