# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-setuptools"
PE = "0"
PV = "69.0.3"
PR = "12.el10_0"
PACKAGES = "python3-setuptools python3-setuptools-wheel"
PROVIDES = "rpm/python3-setuptools rpm/python3-setuptools-wheel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/python-setuptools-69.0.3-12.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ad5d22b7b0879b9490d22c7f5a82749511465a78d2bcd74ac94a40938c482be5"

URI_python3-setuptools = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-setuptools-69.0.3-12.el10_0.noarch.rpm;name=python3-setuptools;unpack=0"
SRC_URI += "${URI_python3-setuptools}"
SRC_URI[python3-setuptools.sha256sum] = "f093bbd794c34f4bc580126716de560820652ea11b484431b86ebdd5b1f86711"
RDEPENDS:python3-setuptools = " \
 python3 \
"

URI_python3-setuptools-wheel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/python3-setuptools-wheel-69.0.3-12.el10_0.noarch.rpm;name=python3-setuptools-wheel;unpack=0"
SRC_URI += "${URI_python3-setuptools-wheel}"
SRC_URI[python3-setuptools-wheel.sha256sum] = "9fa0b1fcb22954f7be7b46f933793550b6b18e30f2ab1b68be2ac341d6195217"
RDEPENDS:python3-setuptools-wheel = ""
