# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-libevdev"
PE = "0"
PV = "0.11"
PR = "10.el10"
PACKAGES = "python3-libevdev"
PROVIDES = "rpm/python3-libevdev"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/python-libevdev-0.11-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f0f6def5062b0eea1937ad6637ed52254ab5bc1726ceb251744ca6dd26dde09b"

URI_python3-libevdev = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/python3-libevdev-0.11-10.el10.noarch.rpm;name=python3-libevdev;unpack=0"
SRC_URI += "${URI_python3-libevdev}"
SRC_URI[python3-libevdev.sha256sum] = "5fea67a12ffe78f57e5665478f039c3bbbf96df4bb7b3fe354e45d8b085f99ef"
RDEPENDS:python3-libevdev = " \
 python3 \
 libevdev \
"
