# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-requests-ftp"
PE = "0"
PV = "0.3.1"
PR = "35.el10"
PACKAGES = "python3-requests-ftp"
PROVIDES = "rpm/python3-requests-ftp"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/python-requests-ftp-0.3.1-35.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "6a3c67a7258f5f8bb104afc65b2c52c2b66764926087f6156de9bccf5afa74ec"

URI_python3-requests-ftp = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/python3-requests-ftp-0.3.1-35.el10.noarch.rpm;name=python3-requests-ftp;unpack=0"
SRC_URI += "${URI_python3-requests-ftp}"
SRC_URI[python3-requests-ftp.sha256sum] = "bd5446aa56c0921bd46671612cc1533ebcd5a62985d326b99756752819e1cf0a"
RDEPENDS:python3-requests-ftp = " \
 python3 \
 python3-requests \
"
