# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-packaging"
PE = "0"
PV = "24.2"
PR = "2.el10"
PACKAGES = "python3-packaging"
PROVIDES = "rpm/python3-packaging"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/python-packaging-24.2-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "404e60a1f2aad480af8b74219fb6f4e1234989e3e84342126697fc542fb6c9c8"

URI_python3-packaging = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-packaging-24.2-2.el10.noarch.rpm;name=python3-packaging;unpack=0"
SRC_URI += "${URI_python3-packaging}"
SRC_URI[python3-packaging.sha256sum] = "34f09b71d61ef37a3c1aa1c59f09d68c14f9f92b36d842d408b8da7b6061b1f0"
RDEPENDS:python3-packaging = " \
 python3 \
"
