# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-pycparser"
PE = "0"
PV = "2.20"
PR = "16.el10"
PACKAGES = "python3-pycparser"
PROVIDES = "rpm/python3-pycparser"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/python-pycparser-2.20-16.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d41e1c8fd21d70f1d9df79acb5d4342de9ad964838c785e8f6ccb6528561bb92"

URI_python3-pycparser = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-pycparser-2.20-16.el10.noarch.rpm;name=python3-pycparser;unpack=0"
SRC_URI += "${URI_python3-pycparser}"
SRC_URI[python3-pycparser.sha256sum] = "f8f1d7d507602407a6b2fe002d833b3cd5fd8baf64f6ff3d12bfb7db4edb4fad"
RDEPENDS:python3-pycparser = " \
 python3 \
 python3-ply \
"
