# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-pyproject-hooks"
PE = "0"
PV = "1.0.0"
PR = "16.el10"
PACKAGES = "python3-pyproject-hooks"
PROVIDES = "rpm/python3-pyproject-hooks"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/python-pyproject-hooks-1.0.0-16.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "89b27705ef116c4cba32e3f1f8c9586d977643b6244e3b947c0776a63c2618fd"

URI_python3-pyproject-hooks = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/python3-pyproject-hooks-1.0.0-16.el10.noarch.rpm;name=python3-pyproject-hooks;unpack=0"
SRC_URI += "${URI_python3-pyproject-hooks}"
SRC_URI[python3-pyproject-hooks.sha256sum] = "a3a62f62f67a3c7f544ac91133dd19d2611d11897910818e9c95f8e5949ec26e"
RDEPENDS:python3-pyproject-hooks = " \
 python3 \
"
