# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-jsonschema"
PE = "0"
PV = "4.19.1"
PR = "7.el10"
PACKAGES = "python3-jsonschema"
PROVIDES = "rpm/python3-jsonschema"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/python-jsonschema-4.19.1-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "485ee99ba09e39cc5da6107b97659be7e4f4f34a45a1386fbbaaddabaa2767dc"

URI_python3-jsonschema = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-jsonschema-4.19.1-7.el10.noarch.rpm;name=python3-jsonschema;unpack=0"
SRC_URI += "${URI_python3-jsonschema}"
SRC_URI[python3-jsonschema.sha256sum] = "9f2aad5b31e2d8fb8eb541d41777c745ade73a766a75a89beab6ad791da0597b"
RDEPENDS:python3-jsonschema = " \
 python3 \
 python3-referencing \
 python3-attrs \
 python3-rpds-py \
 python3-jsonschema-specifications \
"
