# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-ruamel-yaml-clib"
PE = "0"
PV = "0.2.7"
PR = "8.el10"
PACKAGES = "python3-ruamel-yaml-clib"
PROVIDES = "rpm/python3-ruamel-yaml-clib"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/python-ruamel-yaml-clib-0.2.7-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "10e0554f1b44fde1efea60bd27169c4950a043cbbba5a0487d4df7c2cfd6d924"

URI_python3-ruamel-yaml-clib = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/python3-ruamel-yaml-clib-0.2.7-8.el10.x86_64_v2.rpm;name=python3-ruamel-yaml-clib;unpack=0"
SRC_URI += "${URI_python3-ruamel-yaml-clib}"
SRC_URI[python3-ruamel-yaml-clib.sha256sum] = "de8a038437e6201b4c1e32b212264d9427e62cde8b200b69faa585c39469b987"
RDEPENDS:python3-ruamel-yaml-clib = " \
 glibc \
 python3-ruamel-yaml \
 python3 \
"
