# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-pip"
PE = "0"
PV = "23.3.2"
PR = "7.el10"
PACKAGES = "python3-pip-wheel python3-pip"
PROVIDES = "rpm/python3-pip-wheel rpm/python3-pip"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/python-pip-23.3.2-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d479b92934429ffcbdb73b45c149e4acc6f61ace2200eb339b2bae0a0eca9965"

URI_python3-pip-wheel = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-pip-wheel-23.3.2-7.el10.noarch.rpm;name=python3-pip-wheel;unpack=0"
SRC_URI += "${URI_python3-pip-wheel}"
SRC_URI[python3-pip-wheel.sha256sum] = "f4dd09a08791002146ddc16612168ec5ba122c4eaebabd615e81e41315f984c6"
RDEPENDS:python3-pip-wheel = " \
 ca-certificates \
"

URI_python3-pip = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/python3-pip-23.3.2-7.el10.noarch.rpm;name=python3-pip;unpack=0"
SRC_URI += "${URI_python3-pip}"
SRC_URI[python3-pip.sha256sum] = "bfebec27f42d0cdc658d0041a047d5b810f788c788680b367f72f373db979722"
RDEPENDS:python3-pip = " \
 python3 \
 ca-certificates \
"
