# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-prettytable"
PE = "0"
PV = "3.6.0"
PR = "10.el10"
PACKAGES = "python3-prettytable"
PROVIDES = "rpm/python3-prettytable"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/python-prettytable-3.6.0-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "df8fecb4b8ac6c41a013d533e30deaca8899f95016e35ae5fe5532e6c6233d82"

URI_python3-prettytable = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/python3-prettytable-3.6.0-10.el10.noarch.rpm;name=python3-prettytable;unpack=0"
SRC_URI += "${URI_python3-prettytable}"
SRC_URI[python3-prettytable.sha256sum] = "01e517e250ae095cc1669f33c262f96c909db4c90a4e5edf2ea4584251cfa221"
RDEPENDS:python3-prettytable = " \
 python3 \
 python3-wcwidth \
"
