# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-referencing"
PE = "0"
PV = "0.31.1"
PR = "6.el10"
PACKAGES = "python3-referencing"
PROVIDES = "rpm/python3-referencing"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/python-referencing-0.31.1-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "cfb20b4a68b385c40709ffacec07fa668957728ebc7cde336b65e223487be358"

URI_python3-referencing = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-referencing-0.31.1-6.el10.noarch.rpm;name=python3-referencing;unpack=0"
SRC_URI += "${URI_python3-referencing}"
SRC_URI[python3-referencing.sha256sum] = "cc0682bf02b5d92a2caa806af0bc7c16ce22ea1c1ba6402cc92abfb383bebd47"
RDEPENDS:python3-referencing = " \
 python3 \
 python3-attrs \
 python3-rpds-py \
"
