# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-netifaces"
PE = "0"
PV = "0.11.0"
PR = "10.el10"
PACKAGES = "python3-netifaces"
PROVIDES = "rpm/python3-netifaces"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/python-netifaces-0.11.0-10.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "da9cb3e30b37e17428103975e71f886b88aa2c0c3538effbf2e2caf98e00034f"

URI_python3-netifaces = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/python3-netifaces-0.11.0-10.el10.x86_64_v2.rpm;name=python3-netifaces;unpack=0"
SRC_URI += "${URI_python3-netifaces}"
SRC_URI[python3-netifaces.sha256sum] = "4dc262c9163bae94a367d20ec51a31ebf4953e2a81c3c024022807f2d2321481"
RDEPENDS:python3-netifaces = " \
 glibc \
 python3 \
"
