# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-typing-extensions"
PE = "0"
PV = "4.9.0"
PR = "6.el10"
PACKAGES = "python3-typing-extensions"
PROVIDES = "rpm/python3-typing-extensions"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/python-typing-extensions-4.9.0-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1faecb08dfe02fd5735886cd84547d1a069cfdefe0b4e040816ac80cb654a199"

URI_python3-typing-extensions = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-typing-extensions-4.9.0-6.el10.noarch.rpm;name=python3-typing-extensions;unpack=0"
SRC_URI += "${URI_python3-typing-extensions}"
SRC_URI[python3-typing-extensions.sha256sum] = "b323e7e183cda698488c44cd91f8fafffc78a910bc313d2d0de1a6ea5e21e040"
RDEPENDS:python3-typing-extensions = " \
 python3 \
"
