# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-jsonpointer"
PE = "0"
PV = "2.3"
PR = "9.el10"
PACKAGES = "python3-jsonpointer"
PROVIDES = "rpm/python3-jsonpointer"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/python-jsonpointer-2.3-9.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d9af30aa71ccad33177f77cfb771cf2e330df255500c203633dcb4c765d29e24"

URI_python3-jsonpointer = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/python3-jsonpointer-2.3-9.el10.noarch.rpm;name=python3-jsonpointer;unpack=0"
SRC_URI += "${URI_python3-jsonpointer}"
SRC_URI[python3-jsonpointer.sha256sum] = "a6c983e7b5cf90587fcf4ba867ba49830f2ea05707350b942fca1336118b7ba3"
RDEPENDS:python3-jsonpointer = " \
 python3 \
"
