# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "python-kmod"
PE = "0"
PV = "0.9.2"
PR = "6.el10"
PACKAGES = "python3-kmod"
PROVIDES = "rpm/python3-kmod"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/python-kmod-0.9.2-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "dd28fc0b6ca6f7d0ce71ba818ac29cf9ed583b34eb767f969994a5ff837a3a22"

URI_python3-kmod = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-kmod-0.9.2-6.el10.x86_64_v2.rpm;name=python3-kmod;unpack=0"
SRC_URI += "${URI_python3-kmod}"
SRC_URI[python3-kmod.sha256sum] = "c9e2298f2f9faf06de184d76a5a02ef9c062c8650ed0d57f8d8671d75982bb60"
RDEPENDS:python3-kmod = " \
 glibc \
 kmod-libs \
 python3 \
"
