# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "qatengine"
PE = "0"
PV = "1.7.0"
PR = "1.el10"
PACKAGES = "qatengine"
PROVIDES = "rpm/qatengine"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/qatengine-1.7.0-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2d7533adddc75a7b0e117214dd9af09d2a41c522943aa14e27d58d4aa7f2e08e"

URI_qatengine = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/qatengine-1.7.0-1.el10.x86_64_v2.rpm;name=qatengine;unpack=0"
SRC_URI += "${URI_qatengine}"
SRC_URI[qatengine.sha256sum] = "3772f714d480eef6d8749e9b089d264f1fdaa6e062badd3ba4a6db3c237b535f"
RDEPENDS:qatengine = " \
 glibc \
 qatlib \
"
