# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "qatzip"
PE = "0"
PV = "1.2.0"
PR = "4.el10"
PACKAGES = "qatzip qatzip-libs qatzip-devel"
PROVIDES = "rpm/qatzip rpm/qatzip-libs rpm/qatzip-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/qatzip-1.2.0-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ca80dad6b4499f6b472233214e7ea549fb3947dbbb75baf311d364d775cfe91f"

URI_qatzip = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/qatzip-1.2.0-4.el10.x86_64_v2.rpm;name=qatzip;unpack=0"
SRC_URI += "${URI_qatzip}"
SRC_URI[qatzip.sha256sum] = "f2ea1fe51053781fcea667c510f679410f75e1db43990bbb26e7be536e2cb3d8"
RDEPENDS:qatzip = " \
 glibc \
 lz4-libs \
 qatlib \
 zlib-ng-compat \
"

URI_qatzip-libs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/qatzip-libs-1.2.0-4.el10.x86_64_v2.rpm;name=qatzip-libs;unpack=0"
SRC_URI += "${URI_qatzip-libs}"
SRC_URI[qatzip-libs.sha256sum] = "9a143cf3b758235e1f24a9a9bd99bbadef9a2f7c0207f35493cc0d9540a12881"
RDEPENDS:qatzip-libs = " \
 glibc \
 lz4-libs \
 qatlib \
 zlib-ng-compat \
"

URI_qatzip-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/qatzip-devel-1.2.0-4.el10.x86_64_v2.rpm;name=qatzip-devel;unpack=0"
SRC_URI += "${URI_qatzip-devel}"
SRC_URI[qatzip-devel.sha256sum] = "ee522b84e1f8bba324e9c2226ed3aeba44beccf604b3fa11aed6a0f932fb58e9"
RDEPENDS:qatzip-devel = " \
 zlib-ng-compat-devel \
 lz4-devel \
 pkgconf-pkg-config \
 qatzip-libs \
"
