# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "realtime-setup"
PE = "0"
PV = "2.5"
PR = "2.el10"
PACKAGES = ""
PROVIDES = ""


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/realtime-setup-2.5-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "bf9439451dabb76c3bd2b86c738046243137f94d39e2c0e59486608602f3aa4f"
