# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "rest"
PE = "0"
PV = "0.9.1"
PR = "11.el10"
PACKAGES = "rest rest-devel rest-demo"
PROVIDES = "rpm/rest rpm/rest-devel rpm/rest-demo"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/rest-0.9.1-11.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "7be74dafe2883123060ec52ef7cdeda74a83e43f511be25cb79046a33ed48ce0"

URI_rest = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rest-0.9.1-11.el10.x86_64_v2.rpm;name=rest;unpack=0"
SRC_URI += "${URI_rest}"
SRC_URI[rest.sha256sum] = "92cc24a3cccd0d3fc6c6370e2cc692c34c0d9f0a6ca3a32aa516b248c937b8ed"
RDEPENDS:rest = " \
 libsoup3 \
 libgcc \
 libxml2 \
 json-glib \
 glib2 \
 glibc \
"

URI_rest-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/rest-devel-0.9.1-11.el10.x86_64_v2.rpm;name=rest-devel;unpack=0"
SRC_URI += "${URI_rest-devel}"
SRC_URI[rest-devel.sha256sum] = "128953eccd7d7dba37b184b1e3b63425668b2740d6a4138ac8a086693c3b0a94"
RDEPENDS:rest-devel = " \
 libxml2-devel \
 rest-devel \
 json-glib-devel \
 glib2-devel \
 libsoup3-devel \
 rest \
 pkgconf-pkg-config \
"

URI_rest-demo = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/rest-demo-0.9.1-11.el10.x86_64_v2.rpm;name=rest-demo;unpack=0"
SRC_URI += "${URI_rest-demo}"
SRC_URI[rest-demo.sha256sum] = "ea054aabfd315d3be2b1c0efff4142fe59cd7d5ec58080d22aeec21af412b3e0"
RDEPENDS:rest-demo = " \
 libsoup3 \
 libgcc \
 rest \
 json-glib \
 glib2 \
 glibc \
 gtk4 \
 libadwaita \
 gtksourceview5 \
"
