# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "rng-tools"
PE = "0"
PV = "6.17"
PR = "4.el10"
PACKAGES = "rng-tools"
PROVIDES = "rpm/rng-tools"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/rng-tools-6.17-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "3a410a4771d933a29d79d2005f730c0215e29baf8edd54345c3b9b247f79d87f"

URI_rng-tools = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/rng-tools-6.17-4.el10.x86_64_v2.rpm;name=rng-tools;unpack=0"
SRC_URI += "${URI_rng-tools}"
SRC_URI[rng-tools.sha256sum] = "178b9e41ad934abb59b484d7271adfe34340774e03227f25270fe5aff7d8e2d2"
RDEPENDS:rng-tools = " \
 systemd \
 jansson \
 jitterentropy \
 openssl-libs \
 libcap \
 bash \
 libcurl \
 glibc \
 selinux-policy \
"
