# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "rpcsvc-proto"
PE = "0"
PV = "1.4"
PR = "17.el10"
PACKAGES = "rpcgen rpcsvc-proto-devel"
PROVIDES = "rpm/rpcgen rpm/rpcsvc-proto-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/rpcsvc-proto-1.4-17.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0b63396890f3320842b96facedb38a8e953c51b157e86803e10e8d72157847ff"

URI_rpcgen = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rpcgen-1.4-17.el10.x86_64_v2.rpm;name=rpcgen;unpack=0"
SRC_URI += "${URI_rpcgen}"
SRC_URI[rpcgen.sha256sum] = "b000137be7eb148e527f0640f92cbd590113dbb476080a41294cf822e041268d"
RDEPENDS:rpcgen = " \
 glibc \
"

URI_rpcsvc-proto-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/rpcsvc-proto-devel-1.4-17.el10.x86_64_v2.rpm;name=rpcsvc-proto-devel;unpack=0"
SRC_URI += "${URI_rpcsvc-proto-devel}"
SRC_URI[rpcsvc-proto-devel.sha256sum] = "f0ec4ded0855d6bdd8393b4a893839494952879631fdc3e043ac030cbc17447b"
RDEPENDS:rpcsvc-proto-devel = ""
