# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "rpm-local-generator-support"
PE = "0"
PV = "1"
PR = "4.el10"
PACKAGES = "rpm-local-generator-support"
PROVIDES = "rpm/rpm-local-generator-support"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/rpm-local-generator-support-1-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "645211c48381892ad3131955c5db63b24013c2c670fac2e26a85385292f38875"

URI_rpm-local-generator-support = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/rpm-local-generator-support-1-4.el10.noarch.rpm;name=rpm-local-generator-support;unpack=0"
SRC_URI += "${URI_rpm-local-generator-support}"
SRC_URI[rpm-local-generator-support.sha256sum] = "2f2670f67092485437db08df4dca9ad28d299ca76d546bc0454d9d4503e2d863"
RDEPENDS:rpm-local-generator-support = ""
