# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "rsyslog"
PE = "0"
PV = "8.2412.0"
PR = "1.el10"
PACKAGES = "rsyslog rsyslog-crypto rsyslog-doc rsyslog-elasticsearch rsyslog-gnutls rsyslog-gssapi rsyslog-kafka rsyslog-mmaudit rsyslog-mmfields rsyslog-mmjsonparse rsyslog-mmkubernetes rsyslog-mmnormalize rsyslog-mmsnmptrapd rsyslog-mysql rsyslog-omamqp1 rsyslog-openssl rsyslog-pgsql rsyslog-relp rsyslog-snmp rsyslog-udpspoof"
PROVIDES = "rpm/rsyslog rpm/rsyslog-crypto rpm/rsyslog-doc rpm/rsyslog-elasticsearch rpm/rsyslog-gnutls rpm/rsyslog-gssapi rpm/rsyslog-kafka rpm/rsyslog-mmaudit rpm/rsyslog-mmfields rpm/rsyslog-mmjsonparse rpm/rsyslog-mmkubernetes rpm/rsyslog-mmnormalize rpm/rsyslog-mmsnmptrapd rpm/rsyslog-mysql rpm/rsyslog-omamqp1 rpm/rsyslog-openssl rpm/rsyslog-pgsql rpm/rsyslog-relp rpm/rsyslog-snmp rpm/rsyslog-udpspoof"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/rsyslog-8.2412.0-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1c2bcb6ce82b178c5ba5633f3957863c130c444a3e4d2cb915070b4bd5d460c1"

URI_rsyslog = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog;unpack=0"
SRC_URI += "${URI_rsyslog}"
SRC_URI[rsyslog.sha256sum] = "aa0fa56452f08034a56f92d428f32331cb46331342a70f22cf1c45ba5931b9f7"
RDEPENDS:rsyslog = " \
 libuuid \
 zlib-ng-compat \
 systemd-libs \
 libgcc \
 libcap-ng \
 libestr \
 bash \
 libcurl \
 glibc \
 libfastjson \
"

URI_rsyslog-crypto = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-crypto-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-crypto;unpack=0"
SRC_URI += "${URI_rsyslog-crypto}"
SRC_URI[rsyslog-crypto.sha256sum] = "6cc699800a0d8d0bc6f940bb59a77ed66493343510c7b044d2fc5a227c4f073d"
RDEPENDS:rsyslog-crypto = " \
 glibc \
 rsyslog \
 openssl-libs \
 libcap-ng \
"

URI_rsyslog-doc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-doc-8.2412.0-1.el10.noarch.rpm;name=rsyslog-doc;unpack=0"
SRC_URI += "${URI_rsyslog-doc}"
SRC_URI[rsyslog-doc.sha256sum] = "612f89202cf3354f8c2b2adfeafeb7b7bf6021f49d42cf7af4c13658f05dfa0f"
RDEPENDS:rsyslog-doc = ""

URI_rsyslog-elasticsearch = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-elasticsearch-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-elasticsearch;unpack=0"
SRC_URI += "${URI_rsyslog-elasticsearch}"
SRC_URI[rsyslog-elasticsearch.sha256sum] = "b0777791392156d2eee596d482b0dc0cd4669e0023eba5d1b299e9a2856db901"
RDEPENDS:rsyslog-elasticsearch = " \
 glibc \
 rsyslog \
 libcap-ng \
 libcurl \
"

URI_rsyslog-gnutls = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-gnutls-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-gnutls;unpack=0"
SRC_URI += "${URI_rsyslog-gnutls}"
SRC_URI[rsyslog-gnutls.sha256sum] = "c7d8092fa496ced4267c64a56e26a4face6c8c4d48197cc6e834c36c639b1462"
RDEPENDS:rsyslog-gnutls = " \
 glibc \
 rsyslog \
 gnutls \
 libcap-ng \
"

URI_rsyslog-gssapi = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-gssapi-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-gssapi;unpack=0"
SRC_URI += "${URI_rsyslog-gssapi}"
SRC_URI[rsyslog-gssapi.sha256sum] = "c57beba4888955e298bde37b0f0afc336d53edefd66ac6459cc6ecc133b61a8c"
RDEPENDS:rsyslog-gssapi = " \
 glibc \
 krb5-libs \
 rsyslog \
 libcap-ng \
"

URI_rsyslog-kafka = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-kafka-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-kafka;unpack=0"
SRC_URI += "${URI_rsyslog-kafka}"
SRC_URI[rsyslog-kafka.sha256sum] = "c12c44459227bfcc4d4c558c133865a6aeee2c07fc0fefeba9e7d099d37092bd"
RDEPENDS:rsyslog-kafka = " \
 glibc \
 rsyslog \
 librdkafka \
 libcap-ng \
"

URI_rsyslog-mmaudit = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-mmaudit-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-mmaudit;unpack=0"
SRC_URI += "${URI_rsyslog-mmaudit}"
SRC_URI[rsyslog-mmaudit.sha256sum] = "c001bbaa70387818b309bd3492540f3462415e9ccd609b16218767d8e0453472"
RDEPENDS:rsyslog-mmaudit = " \
 glibc \
 rsyslog \
 libcap-ng \
"

URI_rsyslog-mmfields = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-mmfields-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-mmfields;unpack=0"
SRC_URI += "${URI_rsyslog-mmfields}"
SRC_URI[rsyslog-mmfields.sha256sum] = "9acdc0ce040844b7810216b4046a3f93e54cb207f1b61a880e557d3df89f5f11"
RDEPENDS:rsyslog-mmfields = " \
 glibc \
 rsyslog \
 libcap-ng \
"

URI_rsyslog-mmjsonparse = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-mmjsonparse-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-mmjsonparse;unpack=0"
SRC_URI += "${URI_rsyslog-mmjsonparse}"
SRC_URI[rsyslog-mmjsonparse.sha256sum] = "45b250a4035431092417392f89ca1ff01584e0400883ee45ae2a3d38b997ee90"
RDEPENDS:rsyslog-mmjsonparse = " \
 glibc \
 libfastjson \
 rsyslog \
 libcap-ng \
"

URI_rsyslog-mmkubernetes = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-mmkubernetes-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-mmkubernetes;unpack=0"
SRC_URI += "${URI_rsyslog-mmkubernetes}"
SRC_URI[rsyslog-mmkubernetes.sha256sum] = "abef12692ea066a6ba9926a8ba1a573a7231fc4cdc4621a3d58b3308e6003bf7"
RDEPENDS:rsyslog-mmkubernetes = " \
 rsyslog \
 liblognorm \
 libcap-ng \
 libcurl \
 glibc \
 libfastjson \
"

URI_rsyslog-mmnormalize = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-mmnormalize-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-mmnormalize;unpack=0"
SRC_URI += "${URI_rsyslog-mmnormalize}"
SRC_URI[rsyslog-mmnormalize.sha256sum] = "8454f09b1c1dc62d58507e3e961199967fb651ca7c9d8faa33e7ad2dd4d09790"
RDEPENDS:rsyslog-mmnormalize = " \
 rsyslog \
 liblognorm \
 libcap-ng \
 glibc \
 libfastjson \
"

URI_rsyslog-mmsnmptrapd = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-mmsnmptrapd-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-mmsnmptrapd;unpack=0"
SRC_URI += "${URI_rsyslog-mmsnmptrapd}"
SRC_URI[rsyslog-mmsnmptrapd.sha256sum] = "af986e80341898bdf5e9dccb25c62a9006920b2c39d6eedda00f995d75015619"
RDEPENDS:rsyslog-mmsnmptrapd = " \
 glibc \
 rsyslog \
 libcap-ng \
"

URI_rsyslog-mysql = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-mysql-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-mysql;unpack=0"
SRC_URI += "${URI_rsyslog-mysql}"
SRC_URI[rsyslog-mysql.sha256sum] = "7a817923124f8400905474e357a0b90e0d7b60143172463901dcc7cee48f41ab"
RDEPENDS:rsyslog-mysql = " \
 glibc \
 rsyslog \
 mariadb-connector-c \
"

URI_rsyslog-omamqp1 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-omamqp1-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-omamqp1;unpack=0"
SRC_URI += "${URI_rsyslog-omamqp1}"
SRC_URI[rsyslog-omamqp1.sha256sum] = "ce8381a4c50c3b0def24e8a78bf240ea3237212729ed3a1d54c2bc103c3a141e"
RDEPENDS:rsyslog-omamqp1 = " \
 rsyslog \
 openssl-libs \
 libcap-ng \
 cyrus-sasl-lib \
 glibc \
"

URI_rsyslog-openssl = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-openssl-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-openssl;unpack=0"
SRC_URI += "${URI_rsyslog-openssl}"
SRC_URI[rsyslog-openssl.sha256sum] = "cb654362bd39b8af2a885a408589f2ed2a046bb884b258e738a49b69d506b3ea"
RDEPENDS:rsyslog-openssl = " \
 glibc \
 rsyslog \
 openssl-libs \
 libcap-ng \
"

URI_rsyslog-pgsql = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-pgsql-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-pgsql;unpack=0"
SRC_URI += "${URI_rsyslog-pgsql}"
SRC_URI[rsyslog-pgsql.sha256sum] = "7e84c1e46a530e3383737e28c37f3d67afdfd754ec1ade58510c6a2bccc6b460"
RDEPENDS:rsyslog-pgsql = " \
 glibc \
 rsyslog \
 libpq \
 libcap-ng \
"

URI_rsyslog-relp = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-relp-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-relp;unpack=0"
SRC_URI += "${URI_rsyslog-relp}"
SRC_URI[rsyslog-relp.sha256sum] = "4b913872e5643744c471b046ea56601d0a0ed6ad89b7a957e8d02c48759402c2"
RDEPENDS:rsyslog-relp = " \
 glibc \
 rsyslog \
 librelp \
 libcap-ng \
"

URI_rsyslog-snmp = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-snmp-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-snmp;unpack=0"
SRC_URI += "${URI_rsyslog-snmp}"
SRC_URI[rsyslog-snmp.sha256sum] = "abd316e287fbfdd14e1ae9fc56839dd480e7eb5a48e2be5e3ad83cc2e866f87f"
RDEPENDS:rsyslog-snmp = " \
 glibc \
 rsyslog \
 net-snmp-libs \
 libcap-ng \
"

URI_rsyslog-udpspoof = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rsyslog-udpspoof-8.2412.0-1.el10.x86_64_v2.rpm;name=rsyslog-udpspoof;unpack=0"
SRC_URI += "${URI_rsyslog-udpspoof}"
SRC_URI[rsyslog-udpspoof.sha256sum] = "a93f07e43abbe28fd75b61c56304033dd6cc6d4b9115517c8d6cda5cdb5015b7"
RDEPENDS:rsyslog-udpspoof = " \
 glibc \
 rsyslog \
 libnet \
 libcap-ng \
"
