# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "rubygem-rspec"
PE = "0"
PV = "3.13.0"
PR = "3.el10"
PACKAGES = "rubygem-rspec rubygem-rspec-doc"
PROVIDES = "rpm/rubygem-rspec rpm/rubygem-rspec-doc"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/rubygem-rspec-3.13.0-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d3a673a006bee6b218ddf2b3ef696706ea31932dc3c43421ec54a611e3521301"

URI_rubygem-rspec = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/rubygem-rspec-3.13.0-3.el10.noarch.rpm;name=rubygem-rspec;unpack=0"
SRC_URI += "${URI_rubygem-rspec}"
SRC_URI[rubygem-rspec.sha256sum] = "313f9ad81fa3f270e3030a5a49be76ce700a0d1345f0fd99112aa70b05cc0db6"
RDEPENDS:rubygem-rspec = " \
 rubygems \
 rubygem-rspec-mocks \
 rubygem-rspec-core \
 rubygem-rspec-expectations \
"

URI_rubygem-rspec-doc = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/rubygem-rspec-doc-3.13.0-3.el10.noarch.rpm;name=rubygem-rspec-doc;unpack=0"
SRC_URI += "${URI_rubygem-rspec-doc}"
SRC_URI[rubygem-rspec-doc.sha256sum] = "47998e383c5c1831c4b724694639ca938e1cc09ba1800ba5e2e88a6a80485e2c"
RDEPENDS:rubygem-rspec-doc = " \
 rubygem-rspec \
"
