# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ruby"
PE = "0"
PV = "3.3.8"
PR = "10.el10_0"
PACKAGES = "ruby ruby-bundled-gems ruby-default-gems ruby-devel ruby-libs rubygem-bigdecimal rubygem-bundler rubygem-io-console rubygem-irb rubygem-json rubygem-minitest rubygem-power_assert rubygem-psych rubygem-racc rubygem-rake rubygem-rbs rubygem-rdoc rubygem-rexml rubygem-rss rubygem-test-unit rubygem-typeprof rubygems rubygems-devel ruby-doc"
PROVIDES = "rpm/ruby rpm/ruby-bundled-gems rpm/ruby-default-gems rpm/ruby-devel rpm/ruby-libs rpm/rubygem-bigdecimal rpm/rubygem-bundler rpm/rubygem-io-console rpm/rubygem-irb rpm/rubygem-json rpm/rubygem-minitest rpm/rubygem-power_assert rpm/rubygem-psych rpm/rubygem-racc rpm/rubygem-rake rpm/rubygem-rbs rpm/rubygem-rdoc rpm/rubygem-rexml rpm/rubygem-rss rpm/rubygem-test-unit rpm/rubygem-typeprof rpm/rubygems rpm/rubygems-devel rpm/ruby-doc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/ruby-3.3.8-10.el10_0.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "be2f07b7d9f0cb25488bff82239cddaa67b974cfc2b648fe8ded20bbcd365209"

URI_ruby = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ruby-3.3.8-10.el10_0.x86_64_v2.rpm;name=ruby;unpack=0"
SRC_URI += "${URI_ruby}"
SRC_URI[ruby.sha256sum] = "6a06b68f4f4744583c4414bbdcc5958a879b89d7b7b2e4d0608fd12aa860b474"
RDEPENDS:ruby = " \
 gmp \
 zlib-ng-compat \
 libxcrypt \
 ruby-libs \
 glibc \
"

URI_ruby-bundled-gems = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ruby-bundled-gems-3.3.8-10.el10_0.x86_64_v2.rpm;name=ruby-bundled-gems;unpack=0"
SRC_URI += "${URI_ruby-bundled-gems}"
SRC_URI[ruby-bundled-gems.sha256sum] = "f899ca719e928081dbbcb3a9811f100f446102fb357c600dd37b48cbe4934ea0"
RDEPENDS:ruby-bundled-gems = " \
 ruby \
 ruby-default-gems \
 rubygems \
 ruby-libs \
 glibc \
 rubygem-irb \
"

URI_ruby-default-gems = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ruby-default-gems-3.3.8-10.el10_0.noarch.rpm;name=ruby-default-gems;unpack=0"
SRC_URI += "${URI_ruby-default-gems}"
SRC_URI[ruby-default-gems.sha256sum] = "ff56292a0f5dc09dc988fbc7e487c33e1b304f3ddc47b5787a4ef845c45abfd6"
RDEPENDS:ruby-default-gems = " \
 rubygems \
 ruby-default-gems \
 rubygem-io-console \
 ruby \
"

URI_ruby-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ruby-devel-3.3.8-10.el10_0.x86_64_v2.rpm;name=ruby-devel;unpack=0"
SRC_URI += "${URI_ruby-devel}"
SRC_URI[ruby-devel.sha256sum] = "1370106e5538475176f83ca816ffdcd128a358f983ebdaaa70b5294e1f2ec66e"
RDEPENDS:ruby-devel = " \
 rubygems \
 ruby \
 ruby-libs \
 pkgconf-pkg-config \
"

URI_ruby-libs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/ruby-libs-3.3.8-10.el10_0.x86_64_v2.rpm;name=ruby-libs;unpack=0"
SRC_URI += "${URI_ruby-libs}"
SRC_URI[ruby-libs.sha256sum] = "2ab563296cecaba596f64d42700d2440f75e1ad1380b2ec6e964a2aa0355da4d"
RDEPENDS:ruby-libs = " \
 gmp \
 zlib-ng-compat \
 libffi \
 libxcrypt \
 openssl-libs \
 libgcc \
 glibc \
"

URI_rubygem-bigdecimal = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-bigdecimal-3.1.5-10.el10_0.x86_64_v2.rpm;name=rubygem-bigdecimal;unpack=0"
SRC_URI += "${URI_rubygem-bigdecimal}"
SRC_URI[rubygem-bigdecimal.sha256sum] = "cc4d80aa16fb6cd93c1af921361f0a9ba0f214cc6749512b126607bf61dcadac"
RDEPENDS:rubygem-bigdecimal = " \
 glibc \
 rubygems \
 ruby-libs \
"

URI_rubygem-bundler = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-bundler-2.5.22-10.el10_0.noarch.rpm;name=rubygem-bundler;unpack=0"
SRC_URI += "${URI_rubygem-bundler}"
SRC_URI[rubygem-bundler.sha256sum] = "7dd21d0b71684b061c77df1b5ae31220cc8ba1a7cf822b733ecaf0ef368cccd4"
RDEPENDS:rubygem-bundler = " \
 rubygems \
 rubygem-io-console \
 ruby \
"

URI_rubygem-io-console = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-io-console-0.7.1-10.el10_0.x86_64_v2.rpm;name=rubygem-io-console;unpack=0"
SRC_URI += "${URI_rubygem-io-console}"
SRC_URI[rubygem-io-console.sha256sum] = "716c6d25841b71ae149d3d7b2cbc94cef23dba3847d48b970b17a95843a46fe5"
RDEPENDS:rubygem-io-console = " \
 glibc \
 rubygems \
 ruby-libs \
"

URI_rubygem-irb = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-irb-1.13.1-10.el10_0.noarch.rpm;name=rubygem-irb;unpack=0"
SRC_URI += "${URI_rubygem-irb}"
SRC_URI[rubygem-irb.sha256sum] = "78fa8c4a557c809664e24ae265f5e4547745fada84375364357bf58a98608604"
RDEPENDS:rubygem-irb = " \
 rubygems \
 ruby-default-gems \
 ruby \
 rubygem-rdoc \
"

URI_rubygem-json = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-json-2.7.2-10.el10_0.x86_64_v2.rpm;name=rubygem-json;unpack=0"
SRC_URI += "${URI_rubygem-json}"
SRC_URI[rubygem-json.sha256sum] = "1dc68571d9fbbf72c67feeb03c06b74595fce542564c2b38f93be43753903b14"
RDEPENDS:rubygem-json = " \
 glibc \
 rubygems \
 ruby-libs \
"

URI_rubygem-minitest = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-minitest-5.20.0-10.el10_0.noarch.rpm;name=rubygem-minitest;unpack=0"
SRC_URI += "${URI_rubygem-minitest}"
SRC_URI[rubygem-minitest.sha256sum] = "9d4c545129d46b0e36a7024b0d1ea8071a20bc002b39e2438550ebe2ad5feeb2"
RDEPENDS:rubygem-minitest = " \
 rubygems \
"

URI_rubygem-power_assert = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-power_assert-2.0.3-10.el10_0.noarch.rpm;name=rubygem-power_assert;unpack=0"
SRC_URI += "${URI_rubygem-power_assert}"
SRC_URI[rubygem-power_assert.sha256sum] = "967f3ceb1f03f961ce913304ea4bc74f83a0a5e118bef43b6250d175031c063e"
RDEPENDS:rubygem-power_assert = " \
 rubygems \
"

URI_rubygem-psych = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-psych-5.1.2-10.el10_0.x86_64_v2.rpm;name=rubygem-psych;unpack=0"
SRC_URI += "${URI_rubygem-psych}"
SRC_URI[rubygem-psych.sha256sum] = "805fc401dd68667aea1ba0b3e6783c7ae91382595c5c5783f18df8a6f06ce5c8"
RDEPENDS:rubygem-psych = " \
 libyaml \
 ruby-default-gems \
 rubygems \
 ruby-libs \
 glibc \
"

URI_rubygem-racc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-racc-1.7.3-10.el10_0.x86_64_v2.rpm;name=rubygem-racc;unpack=0"
SRC_URI += "${URI_rubygem-racc}"
SRC_URI[rubygem-racc.sha256sum] = "850e30a58052a2ba9fa7db0b98a4804f72b253e213b05847b2a5786b696f3a2e"
RDEPENDS:rubygem-racc = " \
 glibc \
 ruby \
 rubygems \
 ruby-libs \
"

URI_rubygem-rake = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-rake-13.1.0-10.el10_0.noarch.rpm;name=rubygem-rake;unpack=0"
SRC_URI += "${URI_rubygem-rake}"
SRC_URI[rubygem-rake.sha256sum] = "5bc6f0eab10cc1e6d7dcf548db89906057d6bea53ea80c50c457d9b88d17e534"
RDEPENDS:rubygem-rake = " \
 rubygems \
 ruby \
"

URI_rubygem-rbs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-rbs-3.4.0-10.el10_0.x86_64_v2.rpm;name=rubygem-rbs;unpack=0"
SRC_URI += "${URI_rubygem-rbs}"
SRC_URI[rubygem-rbs.sha256sum] = "fc3c0aefab3798a13f0e4f60be78150fd9fb85ed8c897bacff4e5b0be7bccd8d"
RDEPENDS:rubygem-rbs = " \
 ruby \
 ruby-default-gems \
 rubygems \
 ruby-libs \
 glibc \
"

URI_rubygem-rdoc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-rdoc-6.6.3.1-10.el10_0.noarch.rpm;name=rubygem-rdoc;unpack=0"
SRC_URI += "${URI_rubygem-rdoc}"
SRC_URI[rubygem-rdoc.sha256sum] = "000f7ae4b812c2f8b76657ab8a2eb89bac65625b9c16fdabbb066367199be08b"
RDEPENDS:rubygem-rdoc = " \
 rubygem-psych \
 ruby \
 rubygems \
 rubygem-io-console \
 rubygem-json \
"

URI_rubygem-rexml = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-rexml-3.3.9-10.el10_0.noarch.rpm;name=rubygem-rexml;unpack=0"
SRC_URI += "${URI_rubygem-rexml}"
SRC_URI[rubygem-rexml.sha256sum] = "dada2b54032dd2b68b46e91ca4406c099a2870f48660965b5abee5dccf3a6e81"
RDEPENDS:rubygem-rexml = " \
 rubygems \
"

URI_rubygem-rss = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-rss-0.3.1-10.el10_0.noarch.rpm;name=rubygem-rss;unpack=0"
SRC_URI += "${URI_rubygem-rss}"
SRC_URI[rubygem-rss.sha256sum] = "2848b4be77f58301df888353630f1a3c9682a34832454e39630adf91d1aea9dc"
RDEPENDS:rubygem-rss = " \
 rubygems \
 rubygem-rexml \
"

URI_rubygem-test-unit = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-test-unit-3.6.1-10.el10_0.noarch.rpm;name=rubygem-test-unit;unpack=0"
SRC_URI += "${URI_rubygem-test-unit}"
SRC_URI[rubygem-test-unit.sha256sum] = "5302e1d16ea44cbb171ea758e9b5e6ae802e7a8ee31d0d7684e4685e49aefa0f"
RDEPENDS:rubygem-test-unit = " \
 rubygems \
 rubygem-power_assert \
"

URI_rubygem-typeprof = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-typeprof-0.21.9-10.el10_0.noarch.rpm;name=rubygem-typeprof;unpack=0"
SRC_URI += "${URI_rubygem-typeprof}"
SRC_URI[rubygem-typeprof.sha256sum] = "7731d655f4f2577401b92eb83b124cd72087c6b54e9d856ff37081d2181fa4a5"
RDEPENDS:rubygem-typeprof = " \
 rubygems \
 rubygem-rbs \
 ruby \
"

URI_rubygems = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygems-3.5.22-10.el10_0.noarch.rpm;name=rubygems;unpack=0"
SRC_URI += "${URI_rubygems}"
SRC_URI[rubygems.sha256sum] = "2535aadd931d6ffe6a62fa72fa20e0f7298f36a9d95f3572576eb3d4cb1b0744"
RDEPENDS:rubygems = " \
 ruby-libs \
 ruby \
 rubygem-psych \
"

URI_rubygems-devel = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygems-devel-3.5.22-10.el10_0.noarch.rpm;name=rubygems-devel;unpack=0"
SRC_URI += "${URI_rubygems-devel}"
SRC_URI[rubygems-devel.sha256sum] = "155cbfad75054d591f4af2bc0623816222795d49f8a9aa13185bae6f5724f4d5"
RDEPENDS:rubygems-devel = " \
 rubygem-rdoc \
 rubygems \
 ruby \
 rubygem-json \
"

URI_ruby-doc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/ruby-doc-3.3.8-10.el10_0.noarch.rpm;name=ruby-doc;unpack=0"
SRC_URI += "${URI_ruby-doc}"
SRC_URI[ruby-doc.sha256sum] = "1d51af9d9ce63f6f9ce5c086008e0ee96160064dff2ea7fde6da5774cdd48731"
RDEPENDS:ruby-doc = " \
 rubygem-rdoc \
"
