# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "rubygem-pg"
PE = "0"
PV = "1.5.4"
PR = "5.el10"
PACKAGES = "rubygem-pg rubygem-pg-doc"
PROVIDES = "rpm/rubygem-pg rpm/rubygem-pg-doc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/rubygem-pg-1.5.4-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ba09ee4fc72ab9c58ab04409f0500ea6fda87440f84994247a29a5e4f7fb49b9"

URI_rubygem-pg = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/rubygem-pg-1.5.4-5.el10.x86_64_v2.rpm;name=rubygem-pg;unpack=0"
SRC_URI += "${URI_rubygem-pg}"
SRC_URI[rubygem-pg.sha256sum] = "c0511dfc7f24a2a580e6881ecbc3fe54aad245edf824973b4545b251492290ac"
RDEPENDS:rubygem-pg = " \
 libpq \
 rubygems \
 ruby-libs \
 rubygem-bigdecimal \
 glibc \
 rubygem-json \
"

URI_rubygem-pg-doc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/rubygem-pg-doc-1.5.4-5.el10.noarch.rpm;name=rubygem-pg-doc;unpack=0"
SRC_URI += "${URI_rubygem-pg-doc}"
SRC_URI[rubygem-pg-doc.sha256sum] = "31f6c5a7b548a0558bfa5e9016147f118efaba8acea1ec1f67692de065bd98ac"
RDEPENDS:rubygem-pg-doc = " \
 rubygem-pg \
"
