# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "rust-rpm-sequoia"
PE = "0"
PV = "1.6.0"
PR = "6.el10"
PACKAGES = "rpm-sequoia rpm-sequoia-devel"
PROVIDES = "rpm/rpm-sequoia rpm/rpm-sequoia-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/rust-rpm-sequoia-1.6.0-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "78382b150d6d91ddb23e8bf1efe17125e4b1063836c5a90a3ce54a9d1fff81d7"

URI_rpm-sequoia = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/rpm-sequoia-1.6.0-6.el10.x86_64_v2.rpm;name=rpm-sequoia;unpack=0"
SRC_URI += "${URI_rpm-sequoia}"
SRC_URI[rpm-sequoia.sha256sum] = "c164162ae0cba140f0c7bb6bea13843deb8762e57f997d4d5db1b3eb40671b7e"
RDEPENDS:rpm-sequoia = " \
 glibc \
 openssl-libs \
 libgcc \
"

URI_rpm-sequoia-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/rpm-sequoia-devel-1.6.0-6.el10.x86_64_v2.rpm;name=rpm-sequoia-devel;unpack=0"
SRC_URI += "${URI_rpm-sequoia-devel}"
SRC_URI[rpm-sequoia-devel.sha256sum] = "3ba964ce8c84f42660788ddce05b1486a1892426fb9c8ffc727ccc5ad62006ce"
RDEPENDS:rpm-sequoia-devel = " \
 rpm-sequoia \
 openssl-devel \
 pkgconf-pkg-config \
"
