# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "rust-bootupd"
PE = "0"
PV = "0.2.27"
PR = "2.el10"
PACKAGES = "bootupd"
PROVIDES = "rpm/bootupd"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/rust-bootupd-0.2.27-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e9de96324056340f6e8c238391ff402dfe03dcc1abf8afd2579030691c6d1c75"

URI_bootupd = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/bootupd-0.2.27-2.el10.x86_64_v2.rpm;name=bootupd;unpack=0"
SRC_URI += "${URI_bootupd}"
SRC_URI[bootupd.sha256sum] = "904e9555cd3a2eb1ef6d0bb592d5838d761edf98eecfcbf6ff5a74fd50064b88"
RDEPENDS:bootupd = " \
 glibc \
 libgcc \
 systemd \
 openssl-libs \
"
