# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "s390utils"
PE = "2"
PV = "2.36.0"
PR = "2.el10"
PACKAGES = "s390utils s390utils-se-data"
PROVIDES = "rpm/s390utils rpm/s390utils-se-data"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/s390utils-2.36.0-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e6969fd2587f28e0f817287fbdf2cf2a7458c1a3a63351b808a4968ba8d99fa7"

URI_s390utils = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/s390utils-2.36.0-2.el10.x86_64_v2.rpm;name=s390utils;unpack=0"
SRC_URI += "${URI_s390utils}"
SRC_URI[s390utils.sha256sum] = "bc8f78a25fd6af6e369c9832caec9e09fbdffce83e196e6d670d5e53262dd7a5"
RDEPENDS:s390utils = " \
 s390utils-se-data \
 openssl-libs \
 libgcc \
 bash \
 libcurl \
 glibc \
"

URI_s390utils-se-data = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/s390utils-se-data-2.36.0-2.el10.noarch.rpm;name=s390utils-se-data;unpack=0"
SRC_URI += "${URI_s390utils-se-data}"
SRC_URI[s390utils-se-data.sha256sum] = "fb0809eee6d6d2a5a26f496cd913afedee7a9d8160b8d576aff6e7ea08fe9955"
RDEPENDS:s390utils-se-data = " \
 bash \
"
