# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "sanlock"
PE = "0"
PV = "3.9.5"
PR = "4.el10"
PACKAGES = "sanlock sanlock-lib sanlock-devel"
PROVIDES = "rpm/sanlock rpm/sanlock-lib rpm/sanlock-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/sanlock-3.9.5-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d14ca81bd6d794bf7aafaaf98083656f78acaf7f2584e599853de9a62e81a1f6"

URI_sanlock = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/sanlock-3.9.5-4.el10.x86_64_v2.rpm;name=sanlock;unpack=0"
SRC_URI += "${URI_sanlock}"
SRC_URI[sanlock.sha256sum] = "fa870fbbc897701c6020e8ad3f4816d5db20a649fd3a4fe76ccc7bea356b7c08"
RDEPENDS:sanlock = " \
 libuuid \
 systemd \
 libaio \
 sanlock-lib \
 libblkid \
 bash \
 glibc \
"

URI_sanlock-lib = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/sanlock-lib-3.9.5-4.el10.x86_64_v2.rpm;name=sanlock-lib;unpack=0"
SRC_URI += "${URI_sanlock-lib}"
SRC_URI[sanlock-lib.sha256sum] = "048fb32ae6a8fc16db1f09d0b02b5e6722859d2f9993472f2ebecd43db267b7f"
RDEPENDS:sanlock-lib = " \
 glibc \
 libaio \
 libblkid \
"

URI_sanlock-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/sanlock-devel-3.9.5-4.el10.x86_64_v2.rpm;name=sanlock-devel;unpack=0"
SRC_URI += "${URI_sanlock-devel}"
SRC_URI[sanlock-devel.sha256sum] = "b6c6fc1f1d5b7265b1581b99eb0f756af6091fbad2de96950bcc9d1698549129"
RDEPENDS:sanlock-devel = " \
 pkgconf-pkg-config \
 sanlock-lib \
"
