# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "sassc"
PE = "0"
PV = "3.4.1"
PR = "2.el10"
PACKAGES = "sassc"
PROVIDES = "rpm/sassc"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/sassc-3.4.1-2.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "86d10d0acab7081a639e4bdbce0e2c61b3912637f9062e85a05dc02a2c8d5f8c"

URI_sassc = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/sassc-3.4.1-2.el10.x86_64_v2.rpm;name=sassc;unpack=0"
SRC_URI += "${URI_sassc}"
SRC_URI[sassc.sha256sum] = "a6604928cf75102bf3166ef0693f290b97dd28abebe4bb110e61931756b3b0c3"
RDEPENDS:sassc = " \
 glibc \
 libstdc++ \
 libsass \
"
