# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "scap-security-guide"
PE = "0"
PV = "0.1.78"
PR = "1.el10_0.alma.1"
PACKAGES = "scap-security-guide scap-security-guide-doc"
PROVIDES = "rpm/scap-security-guide rpm/scap-security-guide-doc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/scap-security-guide-0.1.78-1.el10_0.alma.1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0ce34bbf57570157c4b6780a1e1bff8b40b9f2b58879765fe896cf5cc49bd476"

URI_scap-security-guide = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/scap-security-guide-0.1.78-1.el10_0.alma.1.noarch.rpm;name=scap-security-guide;unpack=0"
SRC_URI += "${URI_scap-security-guide}"
SRC_URI[scap-security-guide.sha256sum] = "17aee309303d08f76fd5a2a70d99a54278e2b7fb38e6e79cced490f94eefbe4d"
RDEPENDS:scap-security-guide = " \
 openscap-scanner \
 xml-common \
"

URI_scap-security-guide-doc = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/scap-security-guide-doc-0.1.78-1.el10_0.alma.1.noarch.rpm;name=scap-security-guide-doc;unpack=0"
SRC_URI += "${URI_scap-security-guide-doc}"
SRC_URI[scap-security-guide-doc.sha256sum] = "91ce9f8f18ec786e860d440d2684fbca9eeb9090339ccec5f36321a955b9a5a1"
RDEPENDS:scap-security-guide-doc = " \
 scap-security-guide \
"
