# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "sdl2-compat"
PE = "0"
PV = "2.32.50"
PR = "1.el10"
PACKAGES = "sdl2-compat sdl2-compat-devel"
PROVIDES = "rpm/sdl2-compat rpm/sdl2-compat-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/sdl2-compat-2.32.50-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "4abef5ca5551965b03d944bab6046eb580206454234e794147336bd15b9aad9c"

URI_sdl2-compat = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/sdl2-compat-2.32.50-1.el10.x86_64_v2.rpm;name=sdl2-compat;unpack=0"
SRC_URI += "${URI_sdl2-compat}"
SRC_URI[sdl2-compat.sha256sum] = "7083aafe6940e6ec249b64b15910115f2bcccc525376f20c4fda2ce5878910ae"
RDEPENDS:sdl2-compat = " \
 glibc \
 SDL3 \
"

URI_sdl2-compat-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/sdl2-compat-devel-2.32.50-1.el10.x86_64_v2.rpm;name=sdl2-compat-devel;unpack=0"
SRC_URI += "${URI_sdl2-compat-devel}"
SRC_URI[sdl2-compat-devel.sha256sum] = "36bc4fb83da410dd0ff5a9befbf381e65882afa056346a213ddda3328a208e26"
RDEPENDS:sdl2-compat-devel = " \
 cmake-filesystem \
 libglvnd-devel \
 pkgconf-pkg-config \
 libX11-devel \
 xorg-x11-proto-devel \
 bash \
 mesa-libGLU-devel \
 sdl2-compat \
 SDL2 \
"
