# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "sip6"
PE = "0"
PV = "6.9.0"
PR = "1.el10"
PACKAGES = "sip6"
PROVIDES = "rpm/sip6"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/sip6-6.9.0-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "770cb20cbe4c143d82230cfc43fefd9b35c0799748b2dc69e730a5c2403d595d"

URI_sip6 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/sip6-6.9.0-1.el10.noarch.rpm;name=sip6;unpack=0"
SRC_URI += "${URI_sip6}"
SRC_URI[sip6.sha256sum] = "7698bee06f89fe02583730f3b73e493b5acdace8bf3c2ec6257f54bd0578ed6c"
RDEPENDS:sip6 = " \
 python3 \
 python3-packaging \
 python3-setuptools \
"
