# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "sisu"
PE = "1"
PV = "0.3.5"
PR = "14.el10"
PACKAGES = "sisu sisu-javadoc"
PROVIDES = "rpm/sisu rpm/sisu-javadoc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/sisu-0.3.5-14.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "45d3cf3ea5da44be5ea64c4ffc9387ac34fb84b1cf0c56061891be4e2a3a80ca"

URI_sisu = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/sisu-0.3.5-14.el10.noarch.rpm;name=sisu;unpack=0"
SRC_URI += "${URI_sisu}"
SRC_URI[sisu.sha256sum] = "c0dc7d7d8ca946dbf3eee8f38e44766273ffe3605d54b4f0a93502888e295127"
RDEPENDS:sisu = " \
 plexus-classworlds \
 plexus-containers-component-annotations \
 plexus-utils \
 javapackages-filesystem \
 cdi-api \
"

URI_sisu-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/sisu-javadoc-0.3.5-14.el10.noarch.rpm;name=sisu-javadoc;unpack=0"
SRC_URI += "${URI_sisu-javadoc}"
SRC_URI[sisu-javadoc.sha256sum] = "911c57a8c660976cd0562fd9cd754c344bdbd61bcb58bae0e7215747ebe8cc5a"
RDEPENDS:sisu-javadoc = " \
 javapackages-filesystem \
"
