# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "slf4j"
PE = "0"
PV = "1.7.32"
PR = "13.el10"
PACKAGES = "jcl-over-slf4j slf4j slf4j-jdk14 jul-to-slf4j log4j-over-slf4j slf4j-javadoc slf4j-jcl slf4j-manual slf4j-migrator slf4j-sources"
PROVIDES = "rpm/jcl-over-slf4j rpm/slf4j rpm/slf4j-jdk14 rpm/jul-to-slf4j rpm/log4j-over-slf4j rpm/slf4j-javadoc rpm/slf4j-jcl rpm/slf4j-manual rpm/slf4j-migrator rpm/slf4j-sources"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/slf4j-1.7.32-13.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "740fbbe4fc7bb37082d14a643c463f5d5e1dd972d07a5678e94d3ef6e4d0a030"

URI_jcl-over-slf4j = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/jcl-over-slf4j-1.7.32-13.el10.noarch.rpm;name=jcl-over-slf4j;unpack=0"
SRC_URI += "${URI_jcl-over-slf4j}"
SRC_URI[jcl-over-slf4j.sha256sum] = "23f9fa02919c1aafa1843aa86848713f5cf86c1ef0dc25243f9afa6cbcf4c4dd"
RDEPENDS:jcl-over-slf4j = " \
 javapackages-filesystem \
 slf4j \
"

URI_slf4j = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/slf4j-1.7.32-13.el10.noarch.rpm;name=slf4j;unpack=0"
SRC_URI += "${URI_slf4j}"
SRC_URI[slf4j.sha256sum] = "3434ad7606c595540f2672af0dddea3d0721c8baa9cff9c04cdd56e5f4afd045"
RDEPENDS:slf4j = " \
 javapackages-filesystem \
"

URI_slf4j-jdk14 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/slf4j-jdk14-1.7.32-13.el10.noarch.rpm;name=slf4j-jdk14;unpack=0"
SRC_URI += "${URI_slf4j-jdk14}"
SRC_URI[slf4j-jdk14.sha256sum] = "3766d9726a6f4dfac5dcea1df4f6b23f11dd4ca4a4d52cf3cab1c0942e544a58"
RDEPENDS:slf4j-jdk14 = " \
 javapackages-filesystem \
 slf4j \
"

URI_jul-to-slf4j = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/jul-to-slf4j-1.7.32-13.el10.noarch.rpm;name=jul-to-slf4j;unpack=0"
SRC_URI += "${URI_jul-to-slf4j}"
SRC_URI[jul-to-slf4j.sha256sum] = "48bf40d6c0c71959e5aad492c97f2702baba75a67cb0fb8a097e11a414a89b64"
RDEPENDS:jul-to-slf4j = " \
 javapackages-filesystem \
 slf4j \
"

URI_log4j-over-slf4j = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/log4j-over-slf4j-1.7.32-13.el10.noarch.rpm;name=log4j-over-slf4j;unpack=0"
SRC_URI += "${URI_log4j-over-slf4j}"
SRC_URI[log4j-over-slf4j.sha256sum] = "3a8df0ae6ece67b78610fa002d2946f7bc01551f1f1603fe7d971d1f6e8e123a"
RDEPENDS:log4j-over-slf4j = " \
 javapackages-filesystem \
 slf4j \
"

URI_slf4j-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/slf4j-javadoc-1.7.32-13.el10.noarch.rpm;name=slf4j-javadoc;unpack=0"
SRC_URI += "${URI_slf4j-javadoc}"
SRC_URI[slf4j-javadoc.sha256sum] = "c788decf9bf6f5fb95fb81dff884b1e6a064800fcf1aa5c2538c907234772546"
RDEPENDS:slf4j-javadoc = " \
 javapackages-filesystem \
"

URI_slf4j-jcl = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/slf4j-jcl-1.7.32-13.el10.noarch.rpm;name=slf4j-jcl;unpack=0"
SRC_URI += "${URI_slf4j-jcl}"
SRC_URI[slf4j-jcl.sha256sum] = "01247777d80724afbf43519be71caa914bde9d38bf94302485df78f2a8c9e946"
RDEPENDS:slf4j-jcl = " \
 javapackages-filesystem \
 apache-commons-logging \
 slf4j \
"

URI_slf4j-manual = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/slf4j-manual-1.7.32-13.el10.noarch.rpm;name=slf4j-manual;unpack=0"
SRC_URI += "${URI_slf4j-manual}"
SRC_URI[slf4j-manual.sha256sum] = "cd8cbc958016c1c646addf9f44158033a1c1d85674147144d2600d4d8205a3c3"
RDEPENDS:slf4j-manual = ""

URI_slf4j-migrator = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/slf4j-migrator-1.7.32-13.el10.noarch.rpm;name=slf4j-migrator;unpack=0"
SRC_URI += "${URI_slf4j-migrator}"
SRC_URI[slf4j-migrator.sha256sum] = "79fa103506d6077c7aeddc4b4731f022e40091ddc7efe1284884890c97a38ef2"
RDEPENDS:slf4j-migrator = " \
 javapackages-filesystem \
"

URI_slf4j-sources = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/slf4j-sources-1.7.32-13.el10.noarch.rpm;name=slf4j-sources;unpack=0"
SRC_URI += "${URI_slf4j-sources}"
SRC_URI[slf4j-sources.sha256sum] = "d011a498b339f6dbc5537c9177a41e781b07c250376ce2a7e83877ca174e6089"
RDEPENDS:slf4j-sources = " \
 javapackages-filesystem \
 apache-commons-logging \
 slf4j \
"
