# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "spice-protocol"
PE = "0"
PV = "0.14.4"
PR = "7.el10"
PACKAGES = "spice-protocol"
PROVIDES = "rpm/spice-protocol"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/spice-protocol-0.14.4-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "dd6e1a21db640e93e3384349a1eaf244fd7fbbb01e6005b13820a20c9d25b604"

URI_spice-protocol = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/spice-protocol-0.14.4-7.el10.noarch.rpm;name=spice-protocol;unpack=0"
SRC_URI += "${URI_spice-protocol}"
SRC_URI[spice-protocol.sha256sum] = "6912c198611373c943cb272afa1d3d43e89f2ff600cec5245979198c4fdaab0a"
RDEPENDS:spice-protocol = " \
 pkgconf-pkg-config \
"
