# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "splix"
PE = "0"
PV = "2.0.1"
PR = "0.53.20130902svn.el10"
PACKAGES = "splix"
PROVIDES = "rpm/splix"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/splix-2.0.1-0.53.20130902svn.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5e2d85f1804b8f9ec27e9f829d06e0ca7ef20c91f8366f411cf02d46f07622ca"

URI_splix = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/splix-2.0.1-0.53.20130902svn.el10.x86_64_v2.rpm;name=splix;unpack=0"
SRC_URI += "${URI_splix}"
SRC_URI[splix.sha256sum] = "33f1ae092684dd14e9c632c96460d03d77db7fe49a7bb368dd521b7277be5075"
RDEPENDS:splix = " \
 libgcc \
 cups-libs \
 cups \
 libstdc++ \
 jbigkit-libs \
 glibc \
"
