# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "squid"
PE = "7"
PV = "6.10"
PR = "5.el10"
PACKAGES = "squid"
PROVIDES = "rpm/squid"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/squid-6.10-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "3a6442d372e5e448fd503ad0385a3b91529de4de45515028b6123254a63b0b9e"

URI_squid = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/squid-6.10-5.el10.x86_64_v2.rpm;name=squid;unpack=0"
SRC_URI += "${URI_squid}"
SRC_URI[squid.sha256sum] = "9a90a1e56367142a7d1d4b5a663301d7b25f408c7ca072bb9a6a2d86d607ffce"
RDEPENDS:squid = " \
 perl-libnet \
 systemd \
 perl-libs \
 systemd-libs \
 libtool-ltdl \
 perl-FileHandle \
 perl-Getopt-Long \
 perl-Getopt-Std \
 krb5-libs \
 cyrus-sasl-lib \
 libecap \
 perl-vars \
 httpd-filesystem \
 libcap \
 perl-IPC-Open3 \
 libstdc++ \
 libcom_err \
 libtdb \
 perl-DBI \
 perl-Data-Dumper \
 openldap \
 shadow-utils \
 perl-URI \
 libxcrypt \
 perl-Digest-MD5 \
 libgcc \
 openssl-libs \
 perl-Digest-SHA \
 pam-libs \
 bash \
 perl-English \
 gawk \
 perl-File-Basename \
 glibc \
 perl-interpreter \
 perl-Pod-Usage \
"
