# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "subscription-manager"
PE = "0"
PV = "1.30.6.1"
PR = "1.el10_0.alma.1"
PACKAGES = "libdnf-plugin-subscription-manager python3-cloud-what python3-subscription-manager-rhsm subscription-manager subscription-manager-plugin-ostree"
PROVIDES = "rpm/libdnf-plugin-subscription-manager rpm/python3-cloud-what rpm/python3-subscription-manager-rhsm rpm/subscription-manager rpm/subscription-manager-plugin-ostree"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/subscription-manager-1.30.6.1-1.el10_0.alma.1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "9994c6211553cb56eb04d86d1b491c68a79dafe3459447040c55a270b9218eda"

URI_libdnf-plugin-subscription-manager = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/libdnf-plugin-subscription-manager-1.30.6.1-1.el10_0.alma.1.x86_64_v2.rpm;name=libdnf-plugin-subscription-manager;unpack=0"
SRC_URI += "${URI_libdnf-plugin-subscription-manager}"
SRC_URI[libdnf-plugin-subscription-manager.sha256sum] = "bbf3c348d6250576a5ab9dec891f2417721196563b2fbde4a74848f21955cb8b"
RDEPENDS:libdnf-plugin-subscription-manager = " \
 zlib-ng-compat \
 openssl-libs \
 json-c \
 glib2 \
 librepo \
 glibc \
 libdnf \
"

URI_python3-cloud-what = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-cloud-what-1.30.6.1-1.el10_0.alma.1.x86_64_v2.rpm;name=python3-cloud-what;unpack=0"
SRC_URI += "${URI_python3-cloud-what}"
SRC_URI[python3-cloud-what.sha256sum] = "ba8e75dbfe42caf009d776cd273aea3f7b47900caf3938939b8932d300eef358"
RDEPENDS:python3-cloud-what = " \
 python3 \
 dmidecode \
 python3-requests \
"

URI_python3-subscription-manager-rhsm = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/python3-subscription-manager-rhsm-1.30.6.1-1.el10_0.alma.1.x86_64_v2.rpm;name=python3-subscription-manager-rhsm;unpack=0"
SRC_URI += "${URI_python3-subscription-manager-rhsm}"
SRC_URI[python3-subscription-manager-rhsm.sha256sum] = "144f364bbb6784275317a5a3c93885fd7d277b38288cd7ba4329abee99fd4fdf"
RDEPENDS:python3-subscription-manager-rhsm = " \
 python3 \
 python3-iniparse \
 python3-rpm \
 python3-cloud-what \
 python3-dateutil \
 openssl-libs \
 glibc \
 subscription-manager-rhsm-certificates \
"

URI_subscription-manager = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/subscription-manager-1.30.6.1-1.el10_0.alma.1.x86_64_v2.rpm;name=subscription-manager;unpack=0"
SRC_URI += "${URI_subscription-manager}"
SRC_URI[subscription-manager.sha256sum] = "704ea5f0bc2731078d323418b7f4534944c709352f629f99e8f49259b7968fe4"
RDEPENDS:subscription-manager = " \
 python3 \
 systemd \
 python3-cloud-what \
 iproute \
 python3-dateutil \
 python3-dbus \
 python3-decorator \
 python3-dnf \
 python3-dnf-plugins-core \
 python3-gobject-base \
 python3-iniparse \
 python3-inotify \
 dmidecode \
 python3-librepo \
 virt-what \
 libdnf-plugin-subscription-manager \
 bash \
 python3-subscription-manager-rhsm \
 glib2 \
 glibc \
 subscription-manager-rhsm-certificates \
"

URI_subscription-manager-plugin-ostree = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/subscription-manager-plugin-ostree-1.30.6.1-1.el10_0.alma.1.x86_64_v2.rpm;name=subscription-manager-plugin-ostree;unpack=0"
SRC_URI += "${URI_subscription-manager-plugin-ostree}"
SRC_URI[subscription-manager-plugin-ostree.sha256sum] = "60370f4d21f031652d0e5204a5d8c179b087cfd4c8df06b83ecf8b6819b8957b"
RDEPENDS:subscription-manager-plugin-ostree = " \
 python3 \
 python3-iniparse \
 subscription-manager \
 python3-gobject-base \
"
