# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "subscription-manager-rhsm-certificates"
PE = "0"
PV = "20220623"
PR = "6.el10"
PACKAGES = "subscription-manager-rhsm-certificates"
PROVIDES = "rpm/subscription-manager-rhsm-certificates"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/subscription-manager-rhsm-certificates-20220623-6.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f28091fbcaf1fad6f5cdc148c2a06e5d3490e93d6f24c058cbc3a2ab116af844"

URI_subscription-manager-rhsm-certificates = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/subscription-manager-rhsm-certificates-20220623-6.el10.noarch.rpm;name=subscription-manager-rhsm-certificates;unpack=0"
SRC_URI += "${URI_subscription-manager-rhsm-certificates}"
SRC_URI[subscription-manager-rhsm-certificates.sha256sum] = "55f946d4ad26ece36d5c23986385da4bd108bd97debfba93c98f408c86d705e6"
RDEPENDS:subscription-manager-rhsm-certificates = ""
