# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "sudo"
PE = "0"
PV = "1.9.15"
PR = "8.p5.el10_0.2"
PACKAGES = "sudo sudo-python-plugin sudo-devel"
PROVIDES = "rpm/sudo rpm/sudo-python-plugin rpm/sudo-devel"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/sudo-1.9.15-8.p5.el10_0.2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a43d262cd67f092f052ad8db1c77f3d2f4480cbf90e1cbeca7c823bf68a1c53f"

URI_sudo = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/sudo-1.9.15-8.p5.el10_0.2.x86_64_v2.rpm;name=sudo;unpack=0"
SRC_URI += "${URI_sudo}"
SRC_URI[sudo.sha256sum] = "5485c16e3d7bf3abe1e972ae6d1586e9a94b19264e93e726b9334433fed05741"
RDEPENDS:sudo = " \
 zlib-ng-compat \
 audit-libs \
 pam \
 pam-libs \
 glibc \
 libselinux \
 openldap \
"

URI_sudo-python-plugin = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/sudo-python-plugin-1.9.15-8.p5.el10_0.2.x86_64_v2.rpm;name=sudo-python-plugin;unpack=0"
SRC_URI += "${URI_sudo-python-plugin}"
SRC_URI[sudo-python-plugin.sha256sum] = "92e5b51fb7f4ffca90b75ad4cb14271d739d78c3c6f35562188d9d1bc4af3d78"
RDEPENDS:sudo-python-plugin = " \
 glibc \
 sudo \
 python3-libs \
"

URI_sudo-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/sudo-devel-1.9.15-8.p5.el10_0.2.x86_64_v2.rpm;name=sudo-devel;unpack=0"
SRC_URI += "${URI_sudo-devel}"
SRC_URI[sudo-devel.sha256sum] = "850c408baa92ad679a85ea22fa274255f4bf445944330778dfe3b65290b8837a"
RDEPENDS:sudo-devel = " \
 sudo \
"
