# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "swig"
PE = "0"
PV = "4.3.0"
PR = "3.el10"
PACKAGES = "swig swig-doc swig-gdb"
PROVIDES = "rpm/swig rpm/swig-doc rpm/swig-gdb"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/swig-4.3.0-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f9816537a9eb9ca1bd1e5f1b86daab245f3b681c87843a122f3739e6f348afba"

URI_swig = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/swig-4.3.0-3.el10.x86_64_v2.rpm;name=swig;unpack=0"
SRC_URI += "${URI_swig}"
SRC_URI[swig.sha256sum] = "5a593c5deb6c6ad8ab52f24a7feb2fdc9e55bbea0dc6142da77b627f1dcb9f61"
RDEPENDS:swig = " \
 glibc \
 libgcc \
 pcre2 \
 libstdc++ \
"

URI_swig-doc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/swig-doc-4.3.0-3.el10.noarch.rpm;name=swig-doc;unpack=0"
SRC_URI += "${URI_swig-doc}"
SRC_URI[swig-doc.sha256sum] = "bc263923523364ea726df2a397c6e16472b86ba8cb9cfe1ba41c5b09a14e6396"
RDEPENDS:swig-doc = ""

URI_swig-gdb = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/swig-gdb-4.3.0-3.el10.x86_64_v2.rpm;name=swig-gdb;unpack=0"
SRC_URI += "${URI_swig-gdb}"
SRC_URI[swig-gdb.sha256sum] = "344ed56414943c3f64aaa2252e9689bfabc57e294d6a3aee9ab2983417f6e853"
RDEPENDS:swig-gdb = " \
 swig \
"
