# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "telnet"
PE = "1"
PV = "0.17"
PR = "94.el10"
PACKAGES = "telnet telnet-server"
PROVIDES = "rpm/telnet rpm/telnet-server"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/telnet-0.17-94.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "6dfe2ea81904d6eeff8b69b4b08ffb96a6204ce75479b02ff3949c3084ee1ee6"

URI_telnet = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/telnet-0.17-94.el10.x86_64_v2.rpm;name=telnet;unpack=0"
SRC_URI += "${URI_telnet}"
SRC_URI[telnet.sha256sum] = "eb19ad3df359a98f58c082701d68d7e0dff6944265aeddabf81ea76adeaf75fe"
RDEPENDS:telnet = " \
 glibc \
 ncurses-libs \
"

URI_telnet-server = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/telnet-server-0.17-94.el10.x86_64_v2.rpm;name=telnet-server;unpack=0"
SRC_URI += "${URI_telnet-server}"
SRC_URI[telnet-server.sha256sum] = "4f75265745eee44e2af1fd39affd7be2aa92c69756121120f7d70d0004899e1c"
RDEPENDS:telnet-server = " \
 glibc \
 systemd \
 bash \
"
