# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "torque"
PE = "0"
PV = "6.1.3"
PR = "16.el10"
PACKAGES = "torque-libs torque torque-client torque-devel torque-docs torque-drmaa torque-drmaa-devel torque-gui torque-mom torque-pam torque-scheduler torque-server"
PROVIDES = "rpm/torque-libs rpm/torque rpm/torque-client rpm/torque-devel rpm/torque-docs rpm/torque-drmaa rpm/torque-drmaa-devel rpm/torque-gui rpm/torque-mom rpm/torque-pam rpm/torque-scheduler rpm/torque-server"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/torque-6.1.3-16.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "ab332fe0b1cabef6fe08bd6d19afb28df313bfc62190640d042101d9e4ebfe93"

URI_torque-libs = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/torque-libs-6.1.3-16.el10.x86_64_v2.rpm;name=torque-libs;unpack=0"
SRC_URI += "${URI_torque-libs}"
SRC_URI[torque-libs.sha256sum] = "c800bda1d7e714c1702788e329c847429fbea09feb15cf4da90a0995700f0863"
RDEPENDS:torque-libs = " \
 jsoncpp \
 zlib-ng-compat \
 libgcc \
 munge-libs \
 libxml2 \
 munge \
 hwloc-libs \
 libstdc++ \
 glibc \
"

URI_torque = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/torque-6.1.3-16.el10.x86_64_v2.rpm;name=torque;unpack=0"
SRC_URI += "${URI_torque}"
SRC_URI[torque.sha256sum] = "b25138b2e4ee5c9d5d13c259078fbd5de21ff32cc1e63cd70cc4b41891bb4584"
RDEPENDS:torque = " \
 setup \
 systemd \
 munge \
 grep \
 libstdc++ \
 bash \
 torque-libs \
 glibc \
 coreutils \
"

URI_torque-client = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/torque-client-6.1.3-16.el10.x86_64_v2.rpm;name=torque-client;unpack=0"
SRC_URI += "${URI_torque-client}"
SRC_URI[torque-client.sha256sum] = "c2c1572918cd7c0c5effa21799deb7823a2936bacb3ad1604a57c3a4b7724b23"
RDEPENDS:torque-client = " \
 zlib-ng-compat \
 libgcc \
 readline \
 tcl \
 libstdc++ \
 bash \
 torque-libs \
 glibc \
 alternatives \
"

URI_torque-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/torque-devel-6.1.3-16.el10.x86_64_v2.rpm;name=torque-devel;unpack=0"
SRC_URI += "${URI_torque-devel}"
SRC_URI[torque-devel.sha256sum] = "61c6ad13b158071ef75261168bc62187728c7be28bfad16ed2985c8bb1915cd7"
RDEPENDS:torque-devel = " \
 bash \
 torque-libs \
"

URI_torque-docs = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/torque-docs-6.1.3-16.el10.noarch.rpm;name=torque-docs;unpack=0"
SRC_URI += "${URI_torque-docs}"
SRC_URI[torque-docs.sha256sum] = "fc4ece4c5b7590f38fa95c774defbd4a778e4173e46c67a15ceebade18c5035f"
RDEPENDS:torque-docs = " \
 torque \
"

URI_torque-drmaa = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/torque-drmaa-6.1.3-16.el10.x86_64_v2.rpm;name=torque-drmaa;unpack=0"
SRC_URI += "${URI_torque-drmaa}"
SRC_URI[torque-drmaa.sha256sum] = "21bb149f2431870da0f3068579aba33f3badef57dfd9b4b7db90b5bdf44cb913"
RDEPENDS:torque-drmaa = " \
 jsoncpp \
 zlib-ng-compat \
 libgcc \
 munge-libs \
 libxml2 \
 hwloc-libs \
 libstdc++ \
 torque-libs \
 glibc \
"

URI_torque-drmaa-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/torque-drmaa-devel-6.1.3-16.el10.x86_64_v2.rpm;name=torque-drmaa-devel;unpack=0"
SRC_URI += "${URI_torque-drmaa-devel}"
SRC_URI[torque-drmaa-devel.sha256sum] = "405f76b3f7f2503b783f9f62723f791db80e4f5f5d8d4dfbf0ecee1b40444952"
RDEPENDS:torque-drmaa-devel = " \
 torque-devel \
 torque-drmaa \
"

URI_torque-gui = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/torque-gui-6.1.3-16.el10.x86_64_v2.rpm;name=torque-gui;unpack=0"
SRC_URI += "${URI_torque-gui}"
SRC_URI[torque-gui.sha256sum] = "8faeedb0a2f04ae102fabce2f7bf9396a44d1d4d8d207ea2d311e73249ded403"
RDEPENDS:torque-gui = " \
 torque-client \
 libgcc \
 tcl \
 tk \
 libstdc++ \
 torque-libs \
 glibc \
"

URI_torque-mom = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/torque-mom-6.1.3-16.el10.x86_64_v2.rpm;name=torque-mom;unpack=0"
SRC_URI += "${URI_torque-mom}"
SRC_URI[torque-mom.sha256sum] = "0221f9843c0e937b175a50831f506f2508a302ef2946d8e1713b8522865f96a6"
RDEPENDS:torque-mom = " \
 jsoncpp \
 systemd \
 openssh-clients \
 libgcc \
 munge \
 libxml2 \
 hwloc-libs \
 libstdc++ \
 bash \
 torque-libs \
 glibc \
"

URI_torque-pam = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/torque-pam-6.1.3-16.el10.x86_64_v2.rpm;name=torque-pam;unpack=0"
SRC_URI += "${URI_torque-pam}"
SRC_URI[torque-pam.sha256sum] = "807fe6a0c2b4083089673fbfee7894eac62822c3e76c5d1166f40550cb78dfd3"
RDEPENDS:torque-pam = " \
 jsoncpp \
 zlib-ng-compat \
 libgcc \
 munge-libs \
 libxml2 \
 pam-libs \
 hwloc-libs \
 libstdc++ \
 glibc \
"

URI_torque-scheduler = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/torque-scheduler-6.1.3-16.el10.x86_64_v2.rpm;name=torque-scheduler;unpack=0"
SRC_URI += "${URI_torque-scheduler}"
SRC_URI[torque-scheduler.sha256sum] = "b97ba235d1d5b8aecd86d4457e7a1de023f0d6860dbcd7238c7931e7715a4ff8"
RDEPENDS:torque-scheduler = " \
 glibc \
 systemd \
 bash \
 torque-libs \
"

URI_torque-server = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/torque-server-6.1.3-16.el10.x86_64_v2.rpm;name=torque-server;unpack=0"
SRC_URI += "${URI_torque-server}"
SRC_URI[torque-server.sha256sum] = "5ec8646de376d635354b61b5c868a426b2d1cc13402d41da1f509c1e930c25b1"
RDEPENDS:torque-server = " \
 jsoncpp \
 systemd \
 openssh-server \
 libgcc \
 munge-libs \
 libxml2 \
 munge \
 libstdc++ \
 bash \
 torque-libs \
 glibc \
"
