# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "traceroute"
PE = "3"
PV = "2.1.6"
PR = "3.el10"
PACKAGES = "traceroute"
PROVIDES = "rpm/traceroute"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/traceroute-2.1.6-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "744eecdb6f47df5731213194decff03e1eb2f22a533ccde82432584a4d5f23eb"

URI_traceroute = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/traceroute-2.1.6-3.el10.x86_64_v2.rpm;name=traceroute;unpack=0"
SRC_URI += "${URI_traceroute}"
SRC_URI[traceroute.sha256sum] = "5a8235941be33ac7dc1734bdcef4095ad5a6483d6e3eff91c5a532fda679b7e8"
RDEPENDS:traceroute = " \
 glibc \
 bash \
"
