# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "ucs-miscfixed-fonts"
PE = "0"
PV = "0.3"
PR = "34.el10"
PACKAGES = "ucs-miscfixed-fonts ucs-miscfixed-opentype-fonts"
PROVIDES = "rpm/ucs-miscfixed-fonts rpm/ucs-miscfixed-opentype-fonts"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/ucs-miscfixed-fonts-0.3-34.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "254569149228d9760cc64ce6463dbe26b61e44b6c064f3de095ebab66298354f"

URI_ucs-miscfixed-fonts = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ucs-miscfixed-fonts-0.3-34.el10.noarch.rpm;name=ucs-miscfixed-fonts;unpack=0"
SRC_URI += "${URI_ucs-miscfixed-fonts}"
SRC_URI[ucs-miscfixed-fonts.sha256sum] = "c01261991299ed0ba78bd301cc2a817e696922dd93d61bab47e3595723e03b50"
RDEPENDS:ucs-miscfixed-fonts = ""

URI_ucs-miscfixed-opentype-fonts = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ucs-miscfixed-opentype-fonts-0.3-34.el10.noarch.rpm;name=ucs-miscfixed-opentype-fonts;unpack=0"
SRC_URI += "${URI_ucs-miscfixed-opentype-fonts}"
SRC_URI[ucs-miscfixed-opentype-fonts.sha256sum] = "1b71b2a07aba349a940a71a88ef9c1c00f435a04649a625ebb0c74fae730a662"
RDEPENDS:ucs-miscfixed-opentype-fonts = ""
