# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "virt-viewer"
PE = "0"
PV = "11.0"
PR = "10.el10.alma.1"
PACKAGES = "virt-viewer"
PROVIDES = "rpm/virt-viewer"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/virt-viewer-11.0-10.el10.alma.1.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "692b91303cff9cc4f8840289a2bf979f1b49a0e13f73e598ed2e8b89eaa3bfc1"

URI_virt-viewer = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/virt-viewer-11.0-10.el10.alma.1.x86_64_v2.rpm;name=virt-viewer;unpack=0"
SRC_URI += "${URI_virt-viewer}"
SRC_URI[virt-viewer.sha256sum] = "7a0cba2930ba963220be2a570791c26db1b98ee075a4a05bc379b879117d2efb"
RDEPENDS:virt-viewer = " \
 openssh-clients \
 vte291 \
 spice-glib \
 libxml2 \
 pango \
 gdk-pixbuf2 \
 gvnc \
 spice-gtk3 \
 glib2 \
 gtk3 \
 gtk-vnc2 \
 glibc \
 libvirt-glib \
 libvirt-libs \
 libvirt-client \
"
