# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "vte291"
PE = "0"
PV = "0.78.1"
PR = "1.el10"
PACKAGES = "vte-profile vte291 vte291-gtk4 vte291-devel vte291-gtk4-devel"
PROVIDES = "rpm/vte-profile rpm/vte291 rpm/vte291-gtk4 rpm/vte291-devel rpm/vte291-gtk4-devel"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/vte291-0.78.1-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "2c03102cb63aec5a7017abd05f2f5aa0c23eadbac52ed9aa38e2677d91d254e0"

URI_vte-profile = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/vte-profile-0.78.1-1.el10.x86_64_v2.rpm;name=vte-profile;unpack=0"
SRC_URI += "${URI_vte-profile}"
SRC_URI[vte-profile.sha256sum] = "04104a9aec97fc67f6808696b6ee73815aee253c6267cfe5f00744dfb4e82c96"
RDEPENDS:vte-profile = " \
 glibc \
"

URI_vte291 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/vte291-0.78.1-1.el10.x86_64_v2.rpm;name=vte291;unpack=0"
SRC_URI += "${URI_vte291}"
SRC_URI[vte291.sha256sum] = "2d74e2f1abc91f961dc5cbfd8845007d20e0bc6403da550046b7b6db2e9603c0"
RDEPENDS:vte291 = " \
 atk \
 systemd-libs \
 gnutls \
 cairo-gobject \
 lz4-libs \
 libgcc \
 fribidi \
 pango \
 libstdc++ \
 pcre2 \
 glib2 \
 cairo \
 gtk3 \
 glibc \
 libicu \
 vte-profile \
"

URI_vte291-gtk4 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/vte291-gtk4-0.78.1-1.el10.x86_64_v2.rpm;name=vte291-gtk4;unpack=0"
SRC_URI += "${URI_vte291-gtk4}"
SRC_URI[vte291-gtk4.sha256sum] = "9bc28412c2a5640a8eb7509cfe6bbe8f59d003b142217db50ada557055c3678c"
RDEPENDS:vte291-gtk4 = " \
 systemd-libs \
 gnutls \
 lz4-libs \
 vte291 \
 libgcc \
 fribidi \
 pango \
 libstdc++ \
 pcre2 \
 glib2 \
 cairo \
 cairo-gobject \
 glibc \
 libicu \
 gtk4 \
 graphene \
"

URI_vte291-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/vte291-devel-0.78.1-1.el10.x86_64_v2.rpm;name=vte291-devel;unpack=0"
SRC_URI += "${URI_vte291-devel}"
SRC_URI[vte291-devel.sha256sum] = "a3673c374816e1cecfb637b64b02f60504bee73afa16ff32b1bd6ede2e165060"
RDEPENDS:vte291-devel = " \
 glib2-devel \
 cairo-gobject \
 vte291 \
 libgcc \
 gtk3-devel \
 pkgconf-pkg-config \
 pango \
 gdk-pixbuf2 \
 pango-devel \
 libstdc++ \
 glib2 \
 cairo \
 gtk3 \
 glibc \
 cairo-devel \
"

URI_vte291-gtk4-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/vte291-gtk4-devel-0.78.1-1.el10.x86_64_v2.rpm;name=vte291-gtk4-devel;unpack=0"
SRC_URI += "${URI_vte291-gtk4-devel}"
SRC_URI[vte291-gtk4-devel.sha256sum] = "b57e6b5d56ac684fb97aaa41597592f8ed77ffe37914359977d59caceb481b79"
RDEPENDS:vte291-gtk4-devel = " \
 glib2-devel \
 libgcc \
 pkgconf-pkg-config \
 pango \
 gdk-pixbuf2 \
 vte291-gtk4 \
 pango-devel \
 libstdc++ \
 glib2 \
 cairo \
 cairo-gobject \
 glibc \
 vte291-devel \
 gtk4 \
 cairo-devel \
 gtk4-devel \
"
