# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "vulkan-utility-libraries"
PE = "0"
PV = "1.4.304.0"
PR = "1.el10"
PACKAGES = "vulkan-utility-libraries-devel"
PROVIDES = "rpm/vulkan-utility-libraries-devel"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/vulkan-utility-libraries-1.4.304.0-1.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "01ee72f5b42a9953835b3443fd1199265078f1a0ab2fbb205139ac7c06eba42e"

URI_vulkan-utility-libraries-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/vulkan-utility-libraries-devel-1.4.304.0-1.el10.x86_64_v2.rpm;name=vulkan-utility-libraries-devel;unpack=0"
SRC_URI += "${URI_vulkan-utility-libraries-devel}"
SRC_URI[vulkan-utility-libraries-devel.sha256sum] = "9e257957c3b4d3b9fd80417c6e2aed29b7758ffbbeb326b3644ca88146adab8b"
RDEPENDS:vulkan-utility-libraries-devel = " \
 vulkan-headers \
 cmake-filesystem \
"
