# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "wireless-regdb"
PE = "0"
PV = "2024.01.23"
PR = "3.el10"
PACKAGES = "wireless-regdb"
PROVIDES = "rpm/wireless-regdb"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/wireless-regdb-2024.01.23-3.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "d9c27aa0971ca30940d054d4fa9f70da5348ee7c1b601f84efea50a05939ef50"

URI_wireless-regdb = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/wireless-regdb-2024.01.23-3.el10.noarch.rpm;name=wireless-regdb;unpack=0"
SRC_URI += "${URI_wireless-regdb}"
SRC_URI[wireless-regdb.sha256sum] = "f80e67246587560bcc793c036992d49d964dd4c461acd0cb129e97ab1ad69099"
RDEPENDS:wireless-regdb = " \
 systemd-udev \
 systemd \
 bash \
 iw \
"
