# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "woff2"
PE = "0"
PV = "1.0.2"
PR = "21.el10"
PACKAGES = "woff2 woff2-devel woff2-tools"
PROVIDES = "rpm/woff2 rpm/woff2-devel rpm/woff2-tools"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/woff2-1.0.2-21.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "b2459bffeff1c7beadfc53af7253ee142472b8502cde12057285171cd6fc6ebf"

URI_woff2 = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/woff2-1.0.2-21.el10.x86_64_v2.rpm;name=woff2;unpack=0"
SRC_URI += "${URI_woff2}"
SRC_URI[woff2.sha256sum] = "ad24cea60e3faa6ec1fac7c18ed7cf75bce0fc1abcb7281ca654e5629e931e41"
RDEPENDS:woff2 = " \
 glibc \
 libbrotli \
 libgcc \
 libstdc++ \
"

URI_woff2-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/woff2-devel-1.0.2-21.el10.x86_64_v2.rpm;name=woff2-devel;unpack=0"
SRC_URI += "${URI_woff2-devel}"
SRC_URI[woff2-devel.sha256sum] = "ff2854945a84f74cc1754ddeec4dbfe49d387d9c7619307cb87b5650e4763638"
RDEPENDS:woff2-devel = " \
 woff2 \
 brotli-devel \
 woff2-devel \
 pkgconf-pkg-config \
"

URI_woff2-tools = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/woff2-tools-1.0.2-21.el10.x86_64_v2.rpm;name=woff2-tools;unpack=0"
SRC_URI += "${URI_woff2-tools}"
SRC_URI[woff2-tools.sha256sum] = "7703eca2ede3dd1f83e23d72ca416de05432c4cf68efe9286853620086c66a81"
RDEPENDS:woff2-tools = " \
 glibc \
 woff2 \
 libgcc \
 libstdc++ \
"
