# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "xisxwayland"
PE = "0"
PV = "2"
PR = "4.el10"
PACKAGES = "xisxwayland"
PROVIDES = "rpm/xisxwayland"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/xisxwayland-2-4.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "0dda4d1d23b415bff12c82b58c5d0ec6989cd88673b13ed7faed99734c966c53"

URI_xisxwayland = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/xisxwayland-2-4.el10.x86_64_v2.rpm;name=xisxwayland;unpack=0"
SRC_URI += "${URI_xisxwayland}"
SRC_URI[xisxwayland.sha256sum] = "9881a09bd15974d946596c49e81be5a26b6c85c8893a426b9c809e824f718485"
RDEPENDS:xisxwayland = " \
 glibc \
 libX11 \
 libXrandr \
"
