# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "xmodmap"
PE = "0"
PV = "1.0.11"
PR = "7.el10"
PACKAGES = "xmodmap"
PROVIDES = "rpm/xmodmap"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/xmodmap-1.0.11-7.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "63b9718fefd09dca091d815be71ff8fe0b00699abedcfb5acf95211bf57a30d7"

URI_xmodmap = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/xmodmap-1.0.11-7.el10.x86_64_v2.rpm;name=xmodmap;unpack=0"
SRC_URI += "${URI_xmodmap}"
SRC_URI[xmodmap.sha256sum] = "b29896f867589c27a35bf6f4aede77d40c39606fb5b80c7ed9bea1ba25632dcf"
RDEPENDS:xmodmap = " \
 glibc \
 libX11 \
"
