# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "xmvn-generator"
PE = "0"
PV = "1.2.2"
PR = "8.el10"
PACKAGES = "xmvn-generator xmvn-generator-javadoc"
PROVIDES = "rpm/xmvn-generator rpm/xmvn-generator-javadoc"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/xmvn-generator-1.2.2-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e2562b25b98fac5d48d04f2ef26811dc3c9725d92f3578be35d929462df9b8fa"

URI_xmvn-generator = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/xmvn-generator-1.2.2-8.el10.x86_64_v2.rpm;name=xmvn-generator;unpack=0"
SRC_URI += "${URI_xmvn-generator}"
SRC_URI[xmvn-generator.sha256sum] = "d98fea92efd247955f25631cf3c33e937cc9c54e432923933d9332b790d29614"
RDEPENDS:xmvn-generator = " \
 objectweb-asm \
 apache-commons-compress \
 javapackages-filesystem \
 rpm-build \
 java-21-openjdk-headless \
 lujavrite \
"

URI_xmvn-generator-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/xmvn-generator-javadoc-1.2.2-8.el10.noarch.rpm;name=xmvn-generator-javadoc;unpack=0"
SRC_URI += "${URI_xmvn-generator-javadoc}"
SRC_URI[xmvn-generator-javadoc.sha256sum] = "68bdce3350892884b83cf8e5abf5ca081c6ef5e5f3b69f36428b0de7723ae48d"
RDEPENDS:xmvn-generator-javadoc = " \
 javapackages-filesystem \
"
