# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "xorg-x11-xtrans-devel"
PE = "0"
PV = "1.4.0"
PR = "15.el10"
PACKAGES = "xorg-x11-xtrans-devel"
PROVIDES = "rpm/xorg-x11-xtrans-devel"


URI_src = "https://vault.almalinux.org/10.0/CRB/Source/Packages/xorg-x11-xtrans-devel-1.4.0-15.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "5f55a7cab437bf353ee0f62d011c54749858b1c6a65c430072fc279d01b159b7"

URI_xorg-x11-xtrans-devel = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/xorg-x11-xtrans-devel-1.4.0-15.el10.noarch.rpm;name=xorg-x11-xtrans-devel;unpack=0"
SRC_URI += "${URI_xorg-x11-xtrans-devel}"
SRC_URI[xorg-x11-xtrans-devel.sha256sum] = "d9f3d159bb5bc707af6144cd0efd92253794dc343fb00fbcf9182e89ca527047"
RDEPENDS:xorg-x11-xtrans-devel = " \
 pkgconf-pkg-config \
"
