# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "xorg-x11-font-utils"
PE = "1"
PV = "7.5"
PR = "61.el10"
PACKAGES = "xorg-x11-font-utils"
PROVIDES = "rpm/xorg-x11-font-utils"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/xorg-x11-font-utils-7.5-61.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "24a68aeac4c9472b3ec6342c32d8014d44319c52cd4aabd39c1245d3e98586af"

URI_xorg-x11-font-utils = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/xorg-x11-font-utils-7.5-61.el10.x86_64_v2.rpm;name=xorg-x11-font-utils;unpack=0"
SRC_URI += "${URI_xorg-x11-font-utils}"
SRC_URI[xorg-x11-font-utils.sha256sum] = "47a495a01a2df47362fa6d00f634e14679cc12ebb4cd438e879113355fdce68b"
RDEPENDS:xorg-x11-font-utils = " \
 glibc \
 bash \
 pkgconf-pkg-config \
"
