# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "xorg-x11-server"
PE = "0"
PV = "1.20.14"
PR = "36.el10"
PACKAGES = "xorg-x11-server-Xdmx xorg-x11-server-Xephyr xorg-x11-server-Xnest xorg-x11-server-Xorg xorg-x11-server-Xvfb xorg-x11-server-common xorg-x11-server-devel xorg-x11-server-source"
PROVIDES = "rpm/xorg-x11-server-Xdmx rpm/xorg-x11-server-Xephyr rpm/xorg-x11-server-Xnest rpm/xorg-x11-server-Xorg rpm/xorg-x11-server-Xvfb rpm/xorg-x11-server-common rpm/xorg-x11-server-devel rpm/xorg-x11-server-source"


URI_src = "https://vault.almalinux.org/10.0/devel/Source/Packages/xorg-x11-server-1.20.14-36.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "1308139b95f9edfc732ff4f130461268ce0c69cc2f6a6f08fec1c2c0783fa626"

URI_xorg-x11-server-Xdmx = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/xorg-x11-server-Xdmx-1.20.14-36.el10.x86_64_v2.rpm;name=xorg-x11-server-Xdmx;unpack=0"
SRC_URI += "${URI_xorg-x11-server-Xdmx}"
SRC_URI[xorg-x11-server-Xdmx.sha256sum] = "3486baabf6f496a580802ef6f5db04771409b461140ef66d97ed98ec4926e4cb"
RDEPENDS:xorg-x11-server-Xdmx = " \
 systemd-libs \
 libX11 \
 libXau \
 libXaw \
 libselinux \
 libXdmcp \
 libXext \
 libXfixes \
 libXfont2 \
 libXi \
 libXmu \
 libXrender \
 libXt \
 libdmx \
 xorg-x11-server-common \
 audit-libs \
 openssl-libs \
 pixman \
 glibc \
"

URI_xorg-x11-server-Xephyr = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/xorg-x11-server-Xephyr-1.20.14-36.el10.x86_64_v2.rpm;name=xorg-x11-server-Xephyr;unpack=0"
SRC_URI += "${URI_xorg-x11-server-Xephyr}"
SRC_URI[xorg-x11-server-Xephyr.sha256sum] = "75786d2a49a972552bc5741221a1d3f45d3a3c6eb8b4287aa0011836ac596329"
RDEPENDS:xorg-x11-server-Xephyr = " \
 xcb-util-wm \
 systemd-libs \
 libX11 \
 libX11-xcb \
 libXau \
 libselinux \
 libXdmcp \
 libXfont2 \
 libepoxy \
 xorg-x11-server-common \
 libglvnd-glx \
 audit-libs \
 openssl-libs \
 libxcb \
 pixman \
 libxshmfence \
 glibc \
 xcb-util \
 xcb-util-image \
 xcb-util-keysyms \
 xcb-util-renderutil \
"

URI_xorg-x11-server-Xnest = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/xorg-x11-server-Xnest-1.20.14-36.el10.x86_64_v2.rpm;name=xorg-x11-server-Xnest;unpack=0"
SRC_URI += "${URI_xorg-x11-server-Xnest}"
SRC_URI[xorg-x11-server-Xnest.sha256sum] = "f366f23e353a0e6c3bfde8785709bc9d64970c0910ba4585660c7435f567a380"
RDEPENDS:xorg-x11-server-Xnest = " \
 libXfont2 \
 systemd-libs \
 xorg-x11-server-common \
 audit-libs \
 openssl-libs \
 libXdmcp \
 libX11 \
 libXau \
 glibc \
 libselinux \
 pixman \
 libXext \
"

URI_xorg-x11-server-Xorg = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/xorg-x11-server-Xorg-1.20.14-36.el10.x86_64_v2.rpm;name=xorg-x11-server-Xorg;unpack=0"
SRC_URI += "${URI_xorg-x11-server-Xorg}"
SRC_URI[xorg-x11-server-Xorg.sha256sum] = "dd53ab319c2415f7442d4712acc10cb34195c8b3e2ce595d39333c5706398101"
RDEPENDS:xorg-x11-server-Xorg = " \
 libpciaccess \
 systemd \
 systemd-libs \
 libXau \
 dbus-libs \
 libselinux \
 libXdmcp \
 libdrm \
 libXfont2 \
 libepoxy \
 xorg-x11-drv-libinput \
 xorg-x11-server-common \
 libglvnd-egl \
 libglvnd-glx \
 audit-libs \
 openssl-libs \
 bash \
 mesa-libgbm \
 pixman \
 libxshmfence \
 glibc \
"

URI_xorg-x11-server-Xvfb = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/xorg-x11-server-Xvfb-1.20.14-36.el10.x86_64_v2.rpm;name=xorg-x11-server-Xvfb;unpack=0"
SRC_URI += "${URI_xorg-x11-server-Xvfb}"
SRC_URI[xorg-x11-server-Xvfb.sha256sum] = "d77ba51ad78d5f8ab5f97cb83efd241869f76b4825e5b7a6ef2bbfdd6f770b71"
RDEPENDS:xorg-x11-server-Xvfb = " \
 libXfont2 \
 systemd-libs \
 xorg-x11-server-common \
 util-linux \
 libglvnd-glx \
 audit-libs \
 openssl-libs \
 libXdmcp \
 bash \
 libXau \
 xorg-x11-xauth \
 glibc \
 libselinux \
 pixman \
"

URI_xorg-x11-server-common = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/xorg-x11-server-common-1.20.14-36.el10.x86_64_v2.rpm;name=xorg-x11-server-common;unpack=0"
SRC_URI += "${URI_xorg-x11-server-common}"
SRC_URI[xorg-x11-server-common.sha256sum] = "fb2d2f92026dc0491826136083cadf833aeaf98970c907dc8fd00bfa0eaf7eee"
RDEPENDS:xorg-x11-server-common = " \
 xkbcomp \
 xkeyboard-config \
 pixman \
"

URI_xorg-x11-server-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/xorg-x11-server-devel-1.20.14-36.el10.x86_64_v2.rpm;name=xorg-x11-server-devel;unpack=0"
SRC_URI += "${URI_xorg-x11-server-devel}"
SRC_URI[xorg-x11-server-devel.sha256sum] = "56cb28b912c471aa316ee5286c1622574558a3570812a00f6db7c55421574ab0"
RDEPENDS:xorg-x11-server-devel = " \
 xorg-x11-util-macros \
 libpciaccess-devel \
 pkgconf-pkg-config \
 libXfont2-devel \
 xorg-x11-proto-devel \
 bash \
 pixman-devel \
"

URI_xorg-x11-server-source = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/xorg-x11-server-source-1.20.14-36.el10.noarch.rpm;name=xorg-x11-server-source;unpack=0"
SRC_URI += "${URI_xorg-x11-server-source}"
SRC_URI[xorg-x11-server-source.sha256sum] = "44482392faada71f3a6e3cd65067426092b1be320c8c9e8fb73b426b0d1a7849"
RDEPENDS:xorg-x11-server-source = ""
