# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "xwayland-run"
PE = "0"
PV = "0.0.4"
PR = "5.el10"
PACKAGES = "xwayland-run"
PROVIDES = "rpm/xwayland-run"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/xwayland-run-0.0.4-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "a6985c94259e5acdce947462eb6b63c799964e5ff3357316b8da4f24587810d5"

URI_xwayland-run = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/xwayland-run-0.0.4-5.el10.noarch.rpm;name=xwayland-run;unpack=0"
SRC_URI += "${URI_xwayland-run}"
SRC_URI[xwayland-run.sha256sum] = "45bed949ae9bbf0857f7ba98a12c1b31b0df4a321892853feeef31a11c8780f0"
RDEPENDS:xwayland-run = " \
 python3 \
 dbus-daemon \
 gnome-kiosk \
 xorg-x11-server-Xwayland \
 xorg-x11-xauth \
"
