# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "xz-java"
PE = "0"
PV = "1.9"
PR = "11.el10"
PACKAGES = "xz-java xz-java-javadoc"
PROVIDES = "rpm/xz-java rpm/xz-java-javadoc"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/xz-java-1.9-11.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "9805a0a48043937665d00211f480983b75d69da4b87e9120d68885dffeb6a967"

URI_xz-java = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/xz-java-1.9-11.el10.noarch.rpm;name=xz-java;unpack=0"
SRC_URI += "${URI_xz-java}"
SRC_URI[xz-java.sha256sum] = "4eadd47efd97684d445006a96dfaf34ec59496a09c61fe033dfd1c38164313be"
RDEPENDS:xz-java = " \
 javapackages-filesystem \
"

URI_xz-java-javadoc = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/xz-java-javadoc-1.9-11.el10.noarch.rpm;name=xz-java-javadoc;unpack=0"
SRC_URI += "${URI_xz-java-javadoc}"
SRC_URI[xz-java-javadoc.sha256sum] = "0e00d1fffb8273ccd9c0d6d8694045d83b16029f87f18eb81bf9f5b643c8b9c9"
RDEPENDS:xz-java-javadoc = " \
 javapackages-filesystem \
"
