# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "yelp-tools"
PE = "0"
PV = "42.1"
PR = "8.el10"
PACKAGES = "yelp-tools"
PROVIDES = "rpm/yelp-tools"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/yelp-tools-42.1-8.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "e034169247dc0ea7921753b260589a4847aeb03e702dffed4c03a9dc5b672a67"

URI_yelp-tools = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/yelp-tools-42.1-8.el10.noarch.rpm;name=yelp-tools;unpack=0"
SRC_URI += "${URI_yelp-tools}"
SRC_URI[yelp-tools.sha256sum] = "9b287fb96b0ed67e7a4679224facaa816060fceeab7e473230a50b3ac67f163f"
RDEPENDS:yelp-tools = " \
 python3 \
 itstool \
 mallard-rng \
 libxslt \
 yelp-xsl \
 libxml2 \
 python3-lxml \
"
