# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "zenity"
PE = "0"
PV = "4.0.1"
PR = "5.el10"
PACKAGES = "zenity"
PROVIDES = "rpm/zenity"


URI_src = "https://vault.almalinux.org/10.0/AppStream/Source/Packages/zenity-4.0.1-5.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "013e6d33aebe01ad69722c08153a6512752586a2204dd8e056a656eb965c71e4"

URI_zenity = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/zenity-4.0.1-5.el10.x86_64_v2.rpm;name=zenity;unpack=0"
SRC_URI += "${URI_zenity}"
SRC_URI[zenity.sha256sum] = "eb1ce3b4df7da4d09a0e2a0589fc51ee2ef07548f21c09f2ee946f55c22ff66b"
RDEPENDS:zenity = " \
 libgcc \
 pango \
 glib2 \
 glibc \
 gtk4 \
 libadwaita \
"
