# File generated by gen-dnf-proxy, do not modify

inherit dnf-bridge

PN = "zip"
PE = "0"
PV = "3.0"
PR = "44.el10"
PACKAGES = "zip"
PROVIDES = "rpm/zip"


URI_src = "https://vault.almalinux.org/10.0/BaseOS/Source/Packages/zip-3.0-44.el10.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "f01b88116f312e0da03ae38bc7cf104456a92eea727a95a39268900fa667dc73"

URI_zip = "https://vault.almalinux.org/10.0/BaseOS/x86_64_v2/os/Packages/zip-3.0-44.el10.x86_64_v2.rpm;name=zip;unpack=0"
SRC_URI += "${URI_zip}"
SRC_URI[zip.sha256sum] = "43cf9aa11f8915560368ed371776c6017695f7985c64c8ce66a595f4c1bfdc34"
RDEPENDS:zip = " \
 glibc \
 unzip \
 bzip2-libs \
"
