#!/usr/bin/env python3

from __future__ import annotations

import logging
import tempfile

import dnf

logging.basicConfig(format='[%(levelname)s] %(message)s', level=logging.DEBUG)

conf = dnf.conf.Conf()

with (tempfile.TemporaryDirectory() as persistdir,
      tempfile.TemporaryDirectory() as reposdir,
      tempfile.TemporaryDirectory() as system_cachedir,
      tempfile.TemporaryDirectory() as varsdir):
    # avoid any system configuration
    conf_config_file_path = conf._config.config_file_path()
    conf_config_file_path.set(value='/dev/null', priority=conf_config_file_path.getPriority())
    conf_reposdir = conf._config.reposdir()
    conf_reposdir.set(conf_reposdir.getPriority(), reposdir)
    conf_persistdir = conf._config.persistdir()
    conf_persistdir.set(conf_persistdir.getPriority(), persistdir)
    conf_system_cachedir = conf._config.system_cachedir()
    conf_system_cachedir.set(conf_system_cachedir.getPriority(), system_cachedir)
    conf_varsdir = conf._config.varsdir()
    conf_varsdir.set(conf_varsdir.getPriority(), varsdir)

    # necessary to solve deps against concrete files
    conf._config.optional_metadata_types().getValue().push_back('load_filelists')

    #print(conf.dump())

    db_src = dnf.Base(conf=conf)
    db_bin = dnf.Base(conf=conf)

    V = '10.0'
    for section in ['BaseOS', 'AppStream', 'CRB', 'devel']:
        db_bin.repos.add_new_repo(section, conf, [f"https://vault.almalinux.org/{V}/{section}/x86_64_v2/os/"])
        db_src.repos.add_new_repo(f"{section}", conf, [f"https://vault.almalinux.org/{V}/{section}/Source/"])
    db_bin.fill_sack(load_system_repo=False)
    db_src.fill_sack(load_system_repo=False)

    rpms_src: list[dnf.package.Package] = list(db_src.sack.query().filter(latest=1).available())
    print(f"#src={len(rpms_src)}")

    pkg = rpms_src[0]
    print(f"# src: {pkg}")
    print(f'PN = "{pkg.name}"')
    print(f'PE = "{pkg.epoch}"')
    print(f'PV = "{pkg.version}"')
    print(f'PR = "{pkg.release}"')
    
    rpms: list[dnf.package.Package] = list(db_bin.sack.query().filter(sourcerpm=f"{pkg}.rpm").available())
    print(f'PACKAGES = "{' '.join(p.name for p in rpms)}"')
    for p in rpms:
        print(f'URI_{p.name} = "{p.remote_location(schemes=["https", "http", "file"])};unpack=0"')
        rel: hawkey.Reldep
        for rel in p.requires:
            print(f"# {rel.name} {rel.relation} {rel.version}")
            g = dnf.goal.Goal(db_bin.sack)
            sel = dnf.selector.Selector(db_bin.sack).set(rel)
            g.install(select=sel)
            assert g.run()
            print(g.list_installs())
        #print(f'RDEPENDS_{p.name} = "{p.requires};unpack=0"')
